<title>loan System | Module List</title>
<form name="frmlist" action="" dojoType="dijit.form.Form" method="post">
	<form name="frmsearch" action="" method="post">
				<table cellspacing="2" style="width: 350px" >
					<tr>
						<td><select name="fmod" id="fmod" class='fullside' required="true" missingMessage="Invalid Parent Name!" dojoType="dijit.form.FilteringSelect"><?php echo $this->optoin_mod;?></select></td>	
						<td class="btn" align="center">
							<input type="submit" class="fullside" value="Search" name="btsave" label="ស្វែងរក/Search" title="Search" dojoType="dijit.form.Button"/>
						</td>
					</tr>		
				</table>
				</form>
	<table class="fullside">
		  <tr>
		  	<td>	  		
		  		<?php echo $this->list;?>
		  	</td>
		  	
		  </tr>		  
	</table>
</form>
<?php 
$df=$this->data;
?>
<script>
$(function(){		
	$('#fmod').val('<?php echo $df['fmod']?>');
});
</script>