  <?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();
  // report
  
  $rpt_client = $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-client'));
  $rpt_callteral = $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-calleteral'));
  $rpt_change_call = $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-calleteral-change'));
  $rpt_return_call = $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-returncollteral'));
  $rpt_property = $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-properties'));
  $rpt_cancel = $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-cancel-sale'));
  $rpt_expense = $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-expense'));
  $rpt_income = $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-income'));
  $rpt_daily_cash = $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-daily-cash'));
  $rpt_sale_history = $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-sale-history'));
  
  
  $rpt_loanrelease=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-sold'), null, true);
  $rpt_loanoustading=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-outstanding'), null, true);
  $rpt_collectfromco=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-collectionco'), null, true);
  $rpt_loancollect=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loancollect'), null, true);
  $rpt_dailypayment=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-payment'), null, true);
  $rpt_loanincome=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-income'), null, true);
  $rpt_loan_late=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-late'), null, true);
  $rpt_total_collect=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-total-collect'), null, true);
  $rpt_writoff=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-writoff'), null, true);
  $rpt_paymenthistory=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-payment-history'), null, true);
  $rpt_reschedule=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-reschedule-loan'), null, true);
  $rpt_payoff=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-payoff'), null, true);
  $rpt_expectincome=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-expect-income'), null, true);
  $rpt_exchangemoney=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-xchange'), null, true);
  
  $rpt_loandisburseco=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-disburse-co'), null, true);
  $rpt_npl=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-npl'), null, true);
  $rpt_transferloan=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-trasfer'), null, true);
  $rpt_clientco=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-clientco'), null, true);
  $rpt_expense  =$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-expense'), null, true);
  
  
  
  ?>
  <style>
  ul.link-rpt li a {
	color: #3A3939;
    height: 50px;
  	width:180px;
    display: block;
    padding: 10px;
    background: #D6D6D6;
  	font-family: 'Kh Battambang','Khmer Battambang' !important;
  	text-align: center;
  	word-wrap: break-word;
  } 
    ul.link-rpt li {
	float:left; margin:10px;
    list-style: none;
    border:1px solid #B1B0AF;
    word-wrap: break-word;
    
  } 
  .dijitReset, .dijitInline  ,.dijitButton {
	width: 200px !important;
  }
  </style>
  <div style="background:#ccc; width: 100%;">
  	<ul class="link-rpt">
   	    <!-- <li><a href="<?php //echo $this->url(array('module'=>'report','controller'=>'Paramater','action'=>'rpt-holiday')); ?>"><?php echo $tr->translate('LIST_HOLIDAY');?></a></li>
  		 <li><a href="<?php //echo $this->url(array('module'=>'report','controller'=>'Paramater','action'=>'rpt-village')); ?>"><?php echo $tr->translate('LIST_VILLAGE');?></a></li>
  		-->
  		<li><a href="<?php echo $this->url(array('module'=>'report','controller'=>'Paramater','action'=>'rpt-staff')); ?>"><?php echo $tr->translate('LIST_STAFF');?></a></li>
  		<li><a href="<?php echo $rpt_client;?>"><?php echo $tr->translate('LIST_OF_CLIENT');?></a></li>
  		<li><a href="<?php echo $rpt_property;?>"><?php echo $tr->translate('LIST_PROPERTY');?></a></li>
  		<li><a href="<?php echo $rpt_cancel;?>"><?php echo $tr->translate('CANCEL_REPORT');?></a></li>
  		<li><a href="<?php echo $rpt_income;?>"><?php echo $tr->translate('REPORT_INCOME');?></a></li>
  		<li><a href="<?php echo $rpt_expense;?>"><?php echo $tr->translate('REPORT_EXPENSE');?></a></li>
  		<li><a href="<?php echo $rpt_daily_cash;?>"><?php echo $tr->translate('REPORT_DAILY_CASH');?></a></li>
  		<li><a href="<?php echo $rpt_sale_history;?>"><?php echo $tr->translate('REPORT_SALE_HISTORY');?></a></li>
  	
  		<li><a href="<?php echo $rpt_loanrelease;?>"><?php echo $tr->translate('LOAN_DISBURSE');?></a></li>
  		<li><a href="<?php echo $rpt_loancollect;?>"><?php echo $tr->translate('REPORT_LOAN_COLLECT');?></a></li>
  		<li><a href="<?php echo $rpt_dailypayment;?>"><?php echo $tr->translate('RPT_CLIENT_PAYMENT');?></a></li>
  		<li><a href="<?php echo $rpt_loan_late;?>"><?php echo $tr->translate('LOAN_LATE');?></a></li>
  		<li><a href="<?php echo $rpt_paymenthistory;?>"><?php echo $tr->translate('REPORT_LOAN_PAYMENT');?></a></li>
  		<li><a href="<?php echo $rpt_expectincome;?>"><?php echo $tr->translate('REPORT_EXPECT_INCOME');?></a></li>
  		<li><a href="<?php echo $rpt_loanoustading;?>"><?php echo $tr->translate('LOAN_OUTSTADING');?></a></li>
  		<!-- <li><a href="<?php echo $rpt_payoff;?>"><?php echo $tr->translate('REPORT_LOAN_PAYOFF');?></a></li>
  		<li><a href="<?php echo $rpt_expense;?>"><?php echo $tr->translate('REPORT_EXPENSE');?></a></li>
  		<li><a href="<?php echo $rpt_writoff;?>"><?php echo $tr->translate('REPORT_LOAN_WRITE_OFF');?></a></li>
  		<li><a href="<?php echo $rpt_loanincome;?>"><?php echo $tr->translate('PROFIT');?></a></li> -->
  		
  	</ul>
  </div>
  <div style="clear: both;"></div>