<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_BRANCH')); 
?>
<?php  $frm = $this->frm_term;?>
<script>
dojo.require("dijit.form.Textarea");
</script>
<form action="<?php echo $this->url(array('module'=>'other','controller'=>'term','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
	</script>
	<table cellspacing="10" style="margin: 0 auto; width:100%">
		<tr>
			<td>
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("TERMCONDICTION");?></strong></legend>
					<table cellspacing="20" width="100%" >
						<tr>
							<td align="center" valign="top">
								<table width="100%" cellspacing="10"  > 
									<tr>
										<td style="white-space: nowrap;"><?php echo $tr->translate("CONDICTION_STEP")?></td>
										<td><textarea class="fullside"  dojoType="dijit.form.Textarea" class="fullside" style="width:100%;min-height:60px;max-height:300px; font-size:14px; font-family:'Kh Battambang'"   tabindex="" class="fullside" id="con_step" name="con_step"><?php echo $this->term['con_step'];?></textarea>
										</td>
									</tr>
									<tr>
										<td width="12%" style="white-space: nowrap;"><?php echo $tr->translate("CONDICTION_INSTALLMENT")?></td>
										<td width="90%"><textarea dojoType="dijit.form.Textarea" class="fullside" style="width:100%;min-height:60px;max-height:300px; font-size:14px; font-family:'Kh Battambang'" tabindex="" class="fullside" id="con_khmer" name="con_khmer"><?php echo $this->term['con_khmer'];?></textarea>
										</td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("CONDICTION_PAYOFF")?></td>
										<td>
											<textarea class="fullside"  dojoType="dijit.form.Textarea" class="fullside" style="width:100%;min-height:60px;max-height:300px; font-size:14px; font-family:'Kh Battambang'"   tabindex="" class="fullside" id="con_payoff" name="con_payoff"><?php echo $this->term['con_payoff'];?></textarea>
										</td>
									</tr>
									<tr>
										<td colspan="6" align="center">
											<input type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" iconClass="dijitIconClear" />
											<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button" 
												iconClass="dijitEditorIcon dijitEditorIconSave" />
										</td>
									</tr>					
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		
	</table>	
</form>