<?php
$this->headTitle('Sale Realty Management System | log in page'); 
echo $this->headTitle();
$base_url = Application_Form_FrmMessage::getUrl("/");
?>
<!DOCTYPE HTML> 
<html>
<head>
<style type="text/css">
		*{ padding:0;margin:0;}
        html, body { width: 100%; height: 100%; margin: 0; }
		.btn{
			height: 40px;
			min-width: 100px;	
		}
.soria .dijitButtonText {
    line-height: 30px;
}
		.add-link{  
				    background-color: rgb(90, 138, 237);
			  width: 90px;
			  margin-top: 2px;
			  color: #fff;
			  text-align: center;
			  font-size: 13px;
			  font-weight: 600;}
		.fullside{ width:100% !important; height: 30px;}
		.full{ width:100%;}
		body, html {font-size:98%; 
		font-family: Helvetica,sans-serif,'Kh Battambang','Khmer Battambang';
		/*font-family:Arial,serif !important;*/ /*font-family:'Khmer OS Battambang'*/}
		.normal,.alternate{ font-size:90% !important;}
        /*body, html { font-family:helvetica,arial,sans-serif; font-size:95%; }*/
		*{ padding: 0; margin: 0;}
		fieldset{ font-family: inherit;}
		.border{ border: 1px solid #ccc; height: 100%; margin: 5px; padding: 5px;}
        .border1{ border: 1px solid #ccc; height: 100%; margin: 5px; margin-left:0px; padding: 5px;}
		.hover:hover{background: #eee;}
		.odd{background-color: #f9f9f9;}
		
	</style>	
<?php /*
*/?>
<script src="<?php echo $base_url;?>js/dojo-1.6.1/dojo/dojo.js"  djConfig="isDebug: true,parseOnLoad: true"></script>
<script>dojoConfig = {parseOnLoad: true}</script>
<link rel="stylesheet" type="text/css" href="<?php echo $base_url;?>js/dojo-1.6.1/dijit/themes/soria/soria.css"/>
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.7.2.min.js"></script>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<style type="text/css">
	.btn{
		height: 40px;
		min-width: 100px;	
	}
	.f_style{
		font-family:'NiDA Khmer Empire';
	    font-size:14px;
		text-shadow: 1px 1px 1px #0B404A;
	}
.t_shadow{ text-shadow: 1px 1px 1px #0B404A;}
	#footer table tr td dl {
    line-height: 28px ;
    color: #ffffff;
}
.soria .dijitTextBoxReadOnly{
	background: #fff;
    opacity: 0.80;
}
</style>
<link rel="stylesheet" href="<?php echo $base_url;?>css/stylelogin.css"/>
<link rel="shortcut icon" href="images/icon.ico" type="image/x-icon"/>
<script>	
	require(["dojo/parser", "dijit/form/Form", "dijit/form/FilteringSelect","dijit/form/Button", "dijit/form/ValidationTextBox"]);
</script>
</head>
<body class="soria" style="background:#d2e9f7;" id="body" >
<div id="header" style="position:absolute;left: 0;top: 0;">
	<table width="100%">
		<tr align="center">
			<td class="title" style="padding-left: 7px; text-align: center;font-size:20px;text-align:center; font-family:'Khmer MEF2'">តារាងគណនា រំលស់របស់អតិថិជន<?php //echo $this->data["system_name"];?></td>
		</tr>
		<tr>
			<td class="textblue" align="center"></td>
		</tr>
	</table>
</div>
<div style="height:60px;">
</div>
<div style="width:100%">
	<?php	
	$this->headTitle('Add Sell'); 
	echo $this->headTitle();
	$frm = $this->frm_loan;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>

<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>	
	<script src="<?php echo $baseurl;?>/js/help.js"></script>
   <script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog"]);
   </script>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
            branch_id = dijit.byId('branch_id').get('value');
            if (branch_id=='' || branch_id==-1){
				alert('Please Select Branch!');
				dijit.byId('branch_id').focus();
				return false;
			}
			client = dijit.byId('member').get('value');
			if (client=='' || client==-1){
				alert('Please Select Client Name !');
				dijit.byId('member').focus();
				return false;
			}
			rs = checkValidateDate();
			if(rs==false){
              return false;			
            }
              payment_id =dijit.byId("schedule_opt").get("value");
              paid_amount =dijit.byId("deposit").get("value");
              if(payment_id==1 && paid_amount<=0){ alert("សូមបញ្ចូលចំនួនទឹកប្រាក់ត្រូវបង់");dijit.byId("deposit").focus();return false;}
				return true;
			}else {
				return false;
			}
</script>
<table style="margin-top:8px; background: #d2e9f7;" width="100%" >
	<tr>
		<td>
					<table width="100%" cellspacing="5" style="margin-top: -10px;" >
						<tr>
							<td width="13%"><?php echo $tr->translate("BRANCH_NAME")?></td>
							<td width="20%"><?php echo $frm->getElement('branch_id');?></td>
							<td width="13%"><?php echo $tr->translate("DATE_BUY")?></td>
							<td width="20%"><?php echo $frm->getElement('date_buy');?></td>
							<td width="13%"></td>
							<td width="20%"></td>
						</tr>
						<tr height="40px">
							<td><?php echo $tr->translate("PROPERY_CODE")?></td>
							<td><input id="land_code" />
								<input dojoType="dijit.form.TextBox"  id="propertype" name="propertype" type="hidden">
							</td>
							<td><?php echo $tr->translate("LAND_PRICE")?></td>
							<td><?php echo $frm->getElement('land_price');?></td>
							<td><?php echo $tr->translate("HOUSE_PRICE")?></td>
							<td><?php echo $frm->getElement('house_price');?>
								<input dojoType="dijit.form.TextBox" class="fullside" id="joint_with" name="joint_with"  type="hidden">
							</td>
						</tr>
						<tr style="background: #edf7f8;">
							<td colspan="6" style="border-bottom:1px solid #aac4e6;"><strong style="color:#284db7;"><?php echo $tr->translate("PROPERTY_INFORMATION")?></strong></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("TOTAL_SOLD")?></td>
							<td><?php echo $frm->getElement('total_sold');?></td>
							<td><?php echo $tr->translate("Discount")?></td>
							<td><?php echo $frm->getElement('discount_percent');?></td>
							<td><?php echo $tr->translate("Discount")?></td>
							<td><?php echo $frm->getElement('discount');?></td>
						</tr>
						<tr style="background: #edf7f8;">
							<td colspan="6" style="border-bottom:1px solid #aac4e6;"><strong style="color:#284db7;"><?php echo $tr->translate("PAYMENT_INFORMATION")?></strong></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("TOTAL_PAYMENT")?></td>
							<td><?php echo $frm->getElement('sold_price');?></td>
							<td><?php echo $tr->translate("PAYMENT_TYPE")?></td>
							<td><?php echo $frm->getElement('schedule_opt');?></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Paid")?></td>
							<td><?php echo $frm->getElement('deposit');?></td>
							<td><?php echo $tr->translate("Balance")?></td>
							<td><?php echo $frm->getElement('balance');?></td>
							<td style="color:red;">ប្រាក់រំលស់</td>
							<td>
									<input readonly type="text" class="fullside" dojoType="dijit.form.TextBox" name="for_installamount" id="for_installamount"  value="" >
									<input type="hidden" class="fullside" dojoType="dijit.form.TextBox" name="total_installamount" id="total_installamount"  value="" ></td>
						</tr>
						<tr>
						    <td style="white-space: nowrap;"><lable id='lbl_period'><?php echo $tr->translate("TERM_BORROW")?></lable><lable id='lbl_year'><?php echo $tr->translate("YEAR")?></lable></td>
							<td><?php echo $frm->getElement('period');?></td>
							<td><?php echo $tr->translate("INTEREST_RATE")?></td>
							<td><?php echo $frm->getElement('interest_rate');?></td>
							<td style="white-space: nowrap;"><label id="lbl_payment"><?php echo $tr->translate("AMOUNT_FUND_GRAICE_PARIOD")?></label></td>
							<td><?php echo $frm->getElement('fixed_payment');?></td>
						</tr>
						<tr>
							<td><label id="lbl_release"><?php echo $tr->translate("LOAN_RELEASE")?></label></td>
							<td><?php echo $frm->getElement('release_date');?>
							<!--<input type="text" dojoType="dijit.form.TextBox" required="true" class="fullside" constraints="{datePattern:'dd/MM/yyyy'}" id="release_date" name="release_date" value="<?php //echo date("Y-m-d")?>" /> -->
							</td>
							<td><?php echo $tr->translate("FIRST_PAYMENT")?></td>
							<td><?php echo $frm->getElement('first_payment');?></td>
							<td><?php echo $tr->translate("LIFE_LOAN")?></td>
							<td><?php echo $frm->getElement('date_line');?>
							<input type="hidden" name="identity" id="identity"  value="" >
							</td>
						</tr>
						<tr>
							<td colspan="6" style="border-bottom:1px solid #ccc;"><strong style="color:#284db7;"><?php echo $tr->translate("AGENT_INFORMATION")?></strong></td>
						</tr>
						<tr style="max-height: 300px;">
								<td colspan="6">
									<div  id="showrecord"></div>
									<input type="button" label="<?php echo $tr->translate('ADD_INSTALLMENT');?>" dojoType="dijit.form.Button" 
								 		iconClass="dijitIconEditProperty" onclick="addRow();" />
								</td>
						</tr>
					</table>
		</td>
	</tr>		
	<tr>
		<td align="center">
			<a href="<?php echo $this->url(array('module'=>'index','controller'=>'index','action'=>'index'), null, true);?>"><button class="f_styles" style="color: #1C90C3; font: 13px 'Khmer MEF2';" type="button" value="ទៅទំព័រដើម" label="ទៅទំព័រដើម" data-dojo-type="dijit/form/Button" >
								ទៅទំព័រដើម
								</button>		</a>
			<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
			<input type="button" onclick="addPreviewLoan();displayNone();" label="<?php echo $tr->translate("PREVIEW")?>" name='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask" />
		</td>
	</tr>	
</table>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'កាលវិភាគត្រូវបង់ប្រាក់'" id="lbl_schedule" style="width: 28cm !important;">
		<div align="center">
			<input style="text-align: center;" type="button" onclick="doPrint();" label="<?php echo $tr->translate("បោះពុម្ភបង្កាន់ដៃ")?>" name='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask" />
		</div>
		<div id="rpt_print" class="print" style="width:100%;text-align: center;">
		    <div id="t_amountmoneytype" name="t_amountmoneytype" style="font-family:'Khmer OS Battambang'; font-size:14px;">
			<div style="width:100%;text-align:center;font-size:18px;margin:0 auto;text-align:center; font-size:16px; font-family:'Khmer OS Muol';background:red;"></div>
			</div>
		</div>
	</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
</form>
<script type="text/javascript">	

dojo.require("dojo.data.ItemFileWriteStore");  
						           
var staff_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->co_name));?> );
new dijit.form.FilteringSelect({
	store: staff_store,
	autoComplete: true,                        
    id: "staff_id",
    name: "staff_id",  
   // tabindex: "17",    
    class: 'fullside',  
    required:false,
    placeHolder:"Selected Agent", 
    onChange: function() {        
    	branch_id = dijit.byId('branch_id').get('value');
    	staff_id = dijit.byId('staff_id').get('value');
    	if(branch_id==0){
    		if(staff_id==-1){
    			alert('Please select branch');
    			dijit.byId('branch_id').focus();
    			return false;
        	}
    	}else{
		    if(staff_id==-1){
		    	dijit.byId('branch_id_pop').attr('value',branch_id);
		   		dijit.byId("popup_staff").show();
		    }
    	}
    } 
}, "staff_id");
function displayNone(){
	//alert(1);
	document.getElementById('divPrint1').style.display="none";
	//document.getElementById('id_stu').style.display="none";
	
}

function checkScheduleOption(){
	dijit.byId('first_payment').set("readOnly",false);
	dijit.byId('period').set("readOnly",false);
	dijit.byId('interest_rate').set("readOnly",false);
	dijit.byId('release_date').set("readOnly",false);
	dijit.byId('date_line').set("readOnly",true);
	method_id = dijit.byId('schedule_opt').get('value');

	amount_principal = dijit.byId('balance').get('value');	
	debt_amount = dijit.byId('period').get('value')*12;
	if(method_id==3 || method_id==6){
		debt_amount = dijit.byId('period').get('value');
	}
	dojo.byId('lbl_period').innerHTML="<?php echo $tr->translate("TERM_BORROW")?>";
	dojo.byId('lbl_year').innerHTML="<?php echo $tr->translate("YEAR")?>";

	dojo.query("#table_row").append('');
	$('#identity').val('');
	dojo.query("#showrecord").append('');
	title=0;
	no=0;
	
	if(method_id==4){
		calCulateFixedPeriod();	
		}else {
			dijit.byId('fixed_payment').attr('value',0);
			dijit.byId('fixed_payment').set("readOnly",true);
		if(method_id==1){//booking
			dijit.byId('date_line').attr('value','<?php echo date("Y-m-d");?>');
			dijit.byId('release_date').set("readOnly",true);
			dijit.byId('first_payment').set("readOnly",true);
			dijit.byId('date_line').set("readOnly",false);
			dijit.byId('period').set("readOnly",true);
			dijit.byId('period').attr("value",0);
			dijit.byId('interest_rate').attr("value",0);
			dijit.byId('interest_rate').set("readOnly",true);
		}else if(method_id==2){//payoff
			dijit.byId('release_date').set("readOnly",true);
			dijit.byId('first_payment').set("readOnly",true);
			dijit.byId('interest_rate').set("readOnly",true);
			dijit.byId('interest_rate').attr("value",0);
			dijit.byId('period').set("readOnly",true);
			amount_principal = dijit.byId("sold_price").get("value");
			dijit.byId('deposit').attr("value",amount_principal);
			dijit.byId('first_payment').attr("value",'<?php echo date("Y-m-d");?>');
			dijit.byId('date_line').attr("value",'<?php echo date("Y-m-d");?>');
		}else if(method_id==3){//times
			dojo.byId('lbl_period').innerHTML="<?php echo $tr->translate("TOTAL_INSTALLMENT")?>";
			dojo.byId('lbl_release').innerHTML="<?php echo $tr->translate("START_DATE")?>";
			dojo.byId('lbl_year').innerHTML='<?php echo $tr->translate("MONTH")?>';
			if(isNaN(amount_principal)){amount_principal=0;}if(isNaN(debt_amount)){debt_amount=0;}
			amount_principal=dijit.byId('sold_price').get('value');
			total_collect = amount_principal/debt_amount;
			total_collect = total_collect.toFixed(0);
			if(debt_amount!=0){
				dijit.byId('fixed_payment').attr("value",total_collect);
			}
			dijit.byId('first_payment').attr("value",'<?php echo date("Y-m-d");?>');
			if(dijit.byId('interest_rate').get('value')==0){
				dijit.byId('interest_rate').attr("value",0);}
			dijit.byId('interest_rate').set("readOnly",false);
			
		}else if(method_id==5){//times
			dijit.byId('release_date').set("readOnly",true);
			dijit.byId('first_payment').set("readOnly",true);
			if(dijit.byId('interest_rate').get('value')==0 ){
				dijit.byId('interest_rate').attr("value",0);
			}
			dijit.byId('interest_rate').set("readOnly",true);
			dijit.byId('period').set("readOnly",true);
		}
		else if(method_id==6){//times			
			if(dijit.byId('period').get('value')==12){
				dijit.byId('period').attr('value',12);
			}
			$('#identity').val('');
			dijit.byId('first_payment').attr("value",'<?php echo date("Y-m-d");?>');
			dojo.byId('lbl_period').innerHTML="<?php echo $tr->translate("TOTAL_INSTALLMENT")?>";
			dojo.byId('lbl_year').innerHTML='<?php echo $tr->translate("MONTH")?>';
			dojo.byId('lbl_release').innerHTML="<?php echo $tr->translate("START_DATE")?>";
			if(isNaN(amount_principal)){amount_principal=0;}if(isNaN(debt_amount)){debt_amount=0;}
			
			total_collect = amount_principal/debt_amount;
			total_collect = total_collect.toFixed(2);
			if(isNaN(total_collect)){
				total_collect=0;
			}
			dijit.byId('fixed_payment').attr("value",total_collect);
			if(dijit.byId('interest_rate').get('value')==0){
			dijit.byId('interest_rate').attr("value",0);}
			dijit.byId('interest_rate').set("readOnly",false);
		}
	}
}
function calCulateFixedPeriod(){
	var total_paid_install = dijit.byId('total_installamount').get('value');
	if(total_paid_install == 0){
		amount_principal = dijit.byId('sold_price').get('value');
	}else{
		amount_principal = dijit.byId('sold_price').get('value')-dijit.byId('total_installamount').get('value');
	}	
	
	dijit.byId('fixed_payment').set('readOnly',false);
	dojo.byId('lbl_payment').innerHTML="<?php echo $tr->translate("AMOUNT_GRAICE_PARIOD")?>";
	debt_term=30;
	collect_term = 1;
	collect_amount = 1;
	collect_term=30;
	debt_amount = dijit.byId('period').get('value')*12;
	
	term = (debt_term*debt_amount)/(collect_term*collect_amount);
	interest_rate=dijit.byId('interest_rate').get('value')/12/(100);//(100/30day)
	if(interest_rate==0){
		amount_payment = parseFloat(amount_principal/debt_amount);
		amount_payment = amount_payment.toFixed(0);
		if(amount_payment=='Infinity' || amount_payment=='NaN'){amount_payment=0;}
	}else{
		top_pow = Math.pow((1+interest_rate),term);
		bellow = Math.pow((1+interest_rate),(term))-1;
		amount_payment = (amount_principal*interest_rate*top_pow)/(bellow);
		
		amount_payment = amount_payment.toFixed(0);
		if(isNaN(amount_payment)){amount_payment=0;
		}
	}	
	
	dijit.byId('fixed_payment').attr('value',amount_payment);
	dijit.byId('for_installamount').attr('value',amount_principal);
	
}
function calculateDiscount(){
	total_sold = dijit.byId('total_sold').get('value');
	discount = dijit.byId('discount').get('value');
	discount_percent = dijit.byId('discount_percent').get('value');
	other_fee = 0;//dijit.byId('other_fee').get('value');
	if(isNaN(other_fee)){
		other_fee=0;
	}if(isNaN(discount)){
		discount=0;
	}
	if(isNaN(discount_percent)){
		discount_percent=0;
	}
	discount_percent = total_sold*discount_percent/100;
	total_sold = total_sold-discount_percent-discount+other_fee;
	dijit.byId('sold_price').attr('value',total_sold);
	Balance();
}
function Balance(){
	price = dijit.byId('sold_price').get('value');
	deposit =dijit.byId('deposit').get('value');
	if(isNaN(deposit)){
		deposit=0;
	}
	if(deposit>price){
		alert("Deposit can not biger than price ");
		dijit.byId('deposit').focus();
		dijit.byId('deposit').attr('value',price)
		dijit.byId('balance').attr('value',0)
	}else{ 
		schedule_opt = dijit.byId('schedule_opt').get('value');
		if(schedule_opt==2){
			dijit.byId('balance').attr('value',0);
		}else{
			if(schedule_opt==3){
				dijit.byId('for_installamount').attr('value',price-deposit);
			}
			dijit.byId('balance').attr('value',price-deposit);
		}
		checkScheduleOption();
	}
}
function filterClient(){
	branch_id = dijit.byId('branch_id').get('value');
	
	dijit.byId('client_branch_id').attr('value',branch_id); // set branch id to popup client
	
	getAllPropertyBranch(branch_id);
	getLoanByBranch('');
	//getReceiptByBranch('');
	getAllClientByBranch(branch_id);
	getAllClientNumberByBranch(branch_id);
}
var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
function getAllPropertyBranch(branch_id){
	dojo.xhrPost({
		url:url_getland,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			property_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('land_code').set('store', property_store);
		},
		error: function(err) {
		}
	});
} 
var url_getclient = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientbybranch')); ?>';
function getAllClientByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclient,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('member').set('store', client_store);
		},
		error: function(err) {
		}
	});
}
var url_getclientnum = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientnumberbybranch')); ?>';
function getAllClientNumberByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclientnum,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_number_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('customer_code').set('store', client_number_store);
		},
		error: function(err) {
		}
	});
}
var url_getloan = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getloannumber')); ?>';
function getLoanByBranch(condition){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_getloan,	
		content:{ 
		    'branch_id':branch_id,
		    'is_group':0
		},		    
		handleAs:"json",
		load: function(data) {
			//dijit.byId('sale_code').attr('value',data);
			
			if(condition==1){
				getReceiptByBranch(data);
			}
			
		},
		error: function(err) {
			//alert(err);
		}
	});
}

var url_getreceipt = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'get-receipt-number')); ?>';
function getReceiptByBranch(new_sale_id){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_getreceipt,	
		content:{ 
		    'branch_id':branch_id,
		    'is_group':0
		},		    
		handleAs:"json",
		load: function(data) {
			//dijit.byId('receipt').attr('value',data);
			if(new_sale_id!=''){
			//	printSave(new_sale_id,data);
			}
		},
		error: function(err) {
			//alert(err);
		}
	});
}
    function calCulatorBalance(){
    	price = dijit.byId('land_price').get('value');
    	deposit =dijit.byId('deposit').get('value');
    	if(isNaN(deposit)){
    		deposit=0;
    	}
    	if(deposit>price){
    		alert("Deposit can not biger than price ");
    		dijit.byId('deposit').focus();
    		dijit.byId('deposit').attr('value',price)
    	}
        dijit.byId('balance').attr('value',price-deposit);
        checkScheduleOption();
    }
    
    function checkValidateDate(){
		return true;
     }
    function setDefaultPaymentAmount(){
    	amount_principal = dijit.byId('land_price').get('value');
    	debt_term = dijit.byId('pay_every').get('value');
    	debt_amount = dijit.byId('period').get('value')*12;
    	if(debt_term==1){
    		debt_term=1;
    	}else if(debt_term==2){
    		debt_term=7;
    	}
    	else{
    		debt_term=30;
    	}
    	//collect_term = dijit.byId('collect_termtype').get('value');
		collect_amount = 1;
		if(collect_term==1){
			collect_term=1;
    	}else if(collect_term==2){
    		collect_term=7;
    	}
    	else{
    		collect_term=30;
    	}
		
    	term = (debt_term*debt_amount)/(collect_term*collect_amount);

		interest_rate=dijit.byId('interest_rate').get('value')/100;

		top_pow = Math.pow((1+interest_rate),term);
		bellow = Math.pow((1+interest_rate),(term))-1;
		
		amount_payment = (amount_principal*interest_rate*top_pow)/(bellow);
		}
	function hideDialog() {		
		dijit.byId("recript_dialog").hide();
		saveTrans(); 
	}
	function doPrint() {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('rpt_print').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
		hideDialog();
		
	}
	function printSubmit(){
		$('#frm_add_tran').submit();
	}
</script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");

var client_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->client_name));?> );
var client_number_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->client_code));?> );
var co_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->co_name));?> );
var property_store  = getDataStorefromJSON('id','name', null );

require(["dojo/ready"], function(ready){
	 ready(function(){
		setFirstPaymentAndDateLine(3,<?php echo date('d-m-Y');?>,1);
		checkScheduleOption();
	  });
	 
	new dijit.form.FilteringSelect({
			store: property_store,//dojo.data.ObjectStore({objectStore: client_data}),
			autoComplete: true,
			required: false,		           
			name: "land_code",
			id: "land_code",
			searchAttr: "name",
			class: 'fullside',
			onChange: function() {
				land_code = dijit.byId('land_code').get('value');
				if(land_code==-1){
				}else{
					getlandinfo();
				}
		}
			}, "land_code");
	 
	new dijit.form.FilteringSelect({
	store: client_store,//dojo.data.ObjectStore({objectStore: client_data}),
	autoComplete: true,
	required: false,		           
	name: "member",
	id: "member",
	searchAttr: "name",
	required:true,
	class: 'fullside',
	onChange: function() {
		member = dijit.byId('member').get('value');
		if(member==-1){
			showPopupclient();
		}else{
			dijit.byId('customer_code').attr('value',member);
			getcustomerinfo(member);
		}
}
	}, "member");
	
	new dijit.form.FilteringSelect({
	store: client_number_store,//dojo.data.ObjectStore({objectStore: client_number}),
	autoComplete: true,
	           
	required: false,		           
	name: "customer_code",
	id: "customer_code",
	searchAttr: "name",
	class: 'fullside',
	onChange: function() {
		customer_code = dijit.byId('customer_code').get('value');
		if(customer_code==-1){
			showPopupclient();
		}else{
			dijit.byId('member').attr('value',customer_code);
		}
    }
	}, "customer_code");

	new dijit.form.FilteringSelect({
		store: co_store,//dojo.data.ObjectStore({objectStore: client_number}),
		autoComplete: true,            
		required: false,		           
		name: "co_id",
		id: "co_id",
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			co_id = dijit.byId('co_id').get('value');
			if(co_id==-1){
				popupcreditofficer();
			}else{
			}
	    }
		}, "co_id");
	 
	});
</script>
<script type="text/javascript">

function showPopupclient(){
	dijit.byId("popup_client").show();
}
var url_getcustomer = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclient')); ?>';
function getcustomerinfo(client_id){
	dojo.xhrPost({
		url:url_getcustomer,	
		content:{ 
		    'client_id':client_id
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('joint_with').attr('value',data.hname_kh);
		},
		error: function(err) {
			alert(err);
		}
	});
}

var url_getlandinfodetail = '<?php echo $this->url(array('module'=>'group','controller'=>'land','action'=>'getlandinfo')); ?>';
function getlandinfo(){
	dijit.byId('land_price').attr('value',0);
	dijit.byId('house_price').attr('value',0);
	dijit.byId('total_sold').attr('value',0);
	dijit.byId('sold_price').attr('value',0);
	dojo.xhrPost({
		url:url_getlandinfodetail,	
		content:{ 
		    'land_id':dijit.byId('land_code').get('value')
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('land_price').attr('value',data.land_price);
			dijit.byId('house_price').attr('value',data.house_price);
			dijit.byId('total_sold').attr('value',data.price);
			dijit.byId('sold_price').attr('value',data.price);
			dijit.byId('propertype').attr('value',data.house_type);
		},
		error: function(err) {
			alert(err);
		}
	});
}
function clearTextBox(){
	dijit.byId('member').set('value','');
	dijit.byId('total_amount').set('value',0);
}
function getClientInfo(type){
	if(type==1){
		customer_code= dijit.byId('customer_code').get('value');
		dijit.byId('member').attr('value',customer_code);
	}else{
		customer_code= dijit.byId('member').get('value');
		dijit.byId('customer_code').attr('value',customer_code);
	}
}
var url_submitdistrict = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'add-newdistrict')); ?>';
function addNewDistrict(){
		dojo.xhrPost({
	    url: url_submitdistrict,	
		form: dojo.byId("form_district"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_district').reset(); 
			dijit.byId('frm_district').hide();
		},
		error: function(err) {
			alert("Your message could not be sent, please try again!.");
		}
	});
}
var url_submitcommune = '<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'add-newcommune')); ?>';
function addNewCommune(){
		dojo.xhrPost({
	    url: url_submitcommune,	
		form: dojo.byId("form_commune"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_commune').reset(); 
			dijit.byId('frm_commune').hide();
		},
		error: function(err) {
			alert("Your message could not be sent, please try again!.");
		}
	});
}
var url_submitvillage = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'add-newvillage')); ?>';
function addNewVillage(){
		dojo.xhrPost({
	    url: url_submitvillage,	
		form: dojo.byId("form_village"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_village').reset(); 
			dijit.byId('frm_village').hide();
		},
		error: function(err) {
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
</script>

<script>
function checkFirstRecord(){
	return true;
	var rowId = $('#identity').val();
	if(rowId!=''){
		var rowIDArray = rowId.split(',');
		for(var n = 0; n < rowIDArray.length; n++) {
			total_amountpayment = (dijit.byId('total_payment'+rowIDArray[n]).get('value'));
			if(n==0){ 
				paid = dijit.byId('deposit').get('value');
				if(total_amountpayment<paid){alert("សូមបញ្ជូលប្រាក់ត្រូវបង់ ធំជាងប្រាក់ដែលទទួលបាន! ");dijit.byId('percent'+rowIDArray[n]).focus();return false;}
			}
		}
  }
}
col=0;no=0;title=0;temp='';
function addRow(){
	result = checkFirstRecord();
	if(result==false){return false;}
	payment_method = dijit.byId('schedule_opt').get('value');
	if(payment_method==4){addInstallment();}
	if(payment_method!=6){return false;}
	period = dijit.byId('period').get('value');
	//deposit = dijit.byId("deposit").get("value");
	//if(isNaN(deposit)){
		//deposit = 0;
	//}
	//if(deposit>0){ period = period-1;}
	if(period==0){alert("សូមបញ្ជូលចំនួនដង ត្រូវបង់!");dijit.byId('period').focus();return false;}

	no=0;title=0;temp='';$('#identity').val('');
	dojo.byId("showrecord").innerHTML = '';
	tmp='<table id="table_row" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
	tmp+='<tr id="head-title" class="head-td" style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
	tmp+='</table>';
	dojo.query("#showrecord").append(tmp);
	
	for(i=1;i<=period;i++){
		if(payment_method==6){
			col++;no++;
			template='';
			if(title!=1){    
				temp+='<th><?php echo $tr->translate("DEL");?></th>';
				temp+='<th><?php echo $tr->translate("NUM");?></th>';
				temp+='<th><?php echo $tr->translate("DATE_PAYMENT");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("PERCENT_PAID");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("OS_AMOUNT");?></th>';
				temp+='<th><?php echo $tr->translate("NOTE");?></th>';
				dojo.query("#head-title").append(temp);
				title=1;
				epx_date = '<?php echo date('Y-m-d');?>';
			}else{
				indexs = col-1;
				epx_date = dijit.byId("date_payment"+indexs).get("value");
				var a = new Date(epx_date);
				mm = a.getMonth()+2;
				var dd = a.getDate();
				 if(dd<10){
					 dd = "0"+dd;
				}
				if(mm<10){
					 mm = "0"+mm;
				}
				var y = a.getFullYear();
				var epx_date = y+'-'+ mm + '-'+dd ;
			}
				template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
				template+='<td width="2%" align="center">'+no+'</td>';
				template+="<td><input class='fullside' type='text' constraints="+"{datePattern:'dd/MM/yyyy'}"+" dojoType='dijit.form.DateTextBox' value='"+epx_date+"' id='date_payment"+col+"' name='date_payment"+col+"' /></td>";
				template+='<td><input type="text" onkeyup="calCulateAmount('+col+')" class="fullside" required="true" data-dojo-type="dijit.form.NumberTextBox"  id="percent'+col+'" name="percent'+col+'" /></td>';			
				template+='<td><input class="fullside" onkeyup="calCulateAmount('+col+',2)" type="text" required="true"  dojoType="dijit.form.NumberTextBox" id="total_payment'+col+'" name="total_payment'+col+'" /></td>';			
				template+='<td <input class="fullside" type="text"  name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ"/><label id="subsub"></label></td>';
			tmp='<tr class="hover" style="border-bottom:1px solid #ccc;" id="row'+col+'">';
			tmp+="</tr>";
			dojo.query("#table_row").append(tmp);
		
			if($("#identity").val()!="") {
				var identity = $("#identity").val();
				$("#identity").val(identity+','+col);
			} else {$("#identity").val(col);}
			dojo.html.set(dojo.byId("row"+col),template , {
			     parseContent: true,
			});
		}
	}
	dijit.byId("date_line").attr('value',epx_date);
}
function addInstallment(){
	result = checkFirstRecord();
	if(result==false){return false;}
	payment_method = dijit.byId('schedule_opt').get('value');
	
	period = dijit.byId('period').get('value')*12;
	if(period==0){alert("សូមបញ្ជូលចំនួនដង ត្រូវបង់!");dijit.byId('period').focus();return false;}
	temp='';

	result = checkFirstRecord();
	if(result==false){return false;}
	
		if(payment_method==4){
			col++;no++;
			template='';
			if(title!=1){    
				tmp='<table id="table_row" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
				tmp+='<tr id="head-title" class="head-td" style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
				tmp+='</table>';
				dojo.query("#showrecord").append(tmp);
				
				temp+='<th><?php echo $tr->translate("DEL");?></th>';
				temp+='<th><?php echo $tr->translate("NUM");?></th>';
				temp+='<th><?php echo $tr->translate("DATE_PAYMENT");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("PERCENT_PAID");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("OS_AMOUNT");?></th>';
				temp+='<th><?php echo $tr->translate("NOTE");?></th>';
				dojo.query("#head-title").append(temp);
				title=1;
				epx_date ='<?php echo date('Y-m-d');?>';
			}else{
				indexs = col-1;
				epx_date = dijit.byId("date_payment"+indexs).get("value");
				var a = new Date(epx_date);
				mm = a.getMonth()+2;
				var dd = a.getDate();
				 if(dd<10){
					 dd = "0"+dd;
				}
				if(mm<10){
					 mm = "0"+mm;
				}
				var y = a.getFullYear();
				var epx_date = y+'-'+ mm + '-'+dd ;

				mm_nextmonth = a.getMonth()+3;
				if(mm_nextmonth<10){
					mm_nextmonth = "0"+mm_nextmonth;
				}
				
				var start_date = y + '-'+ mm_nextmonth + '-'+dd ;
				dijit.byId("first_payment").attr('value',start_date);
			}
			    dijit.byId("release_date").attr('value',epx_date);
				template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
				template+='<td width="2%" align="center">'+no+'</td>';
				template+="<td><input class='fullside' type='text' constraints="+"{datePattern:'dd/MM/yyyy'}"+" dojoType='dijit.form.DateTextBox' value='"+epx_date+"' id='date_payment"+col+"' name='date_payment"+col+"' /></td>";
				template+='<td><input onkeyup="calCulateAmount('+col+')" class="fullside" type="text" required="true" data-dojo-type="dijit.form.NumberTextBox" id="percent'+col+'" name="percent'+col+'" /></td>';	//data-dojo-props='+'regExp:"[0-9]{1,2}"'+'		
				template+='<td><input class="fullside" type="text" onkeyup="calCulateAmount('+col+',2)" required="true"  dojoType="dijit.form.NumberTextBox" id="total_payment'+col+'" name="total_payment'+col+'" /></td>';			
				template+='<td <input class="fullside" type="text"  name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ"/><label id="subsub"></label></td>';
			tmp='<tr class="hover" style="border-bottom:1px solid #ccc;" id="row'+col+'">';
			tmp+="</tr>";
			dojo.query("#table_row").append(tmp);
		
			if($("#identity").val()!="") {
				var identity = $("#identity").val();
				$("#identity").val(identity+','+col);
			} else {$("#identity").val(col);}
			dojo.html.set(dojo.byId("row"+col),template , {
			     parseContent: true,
			});
		}
}

function calCulateAmount(index,revers=1){
	balance = dijit.byId('sold_price').get('value');
	if(revers==1){//% to value
	    percent = dijit.byId('percent'+index).get('value');
	    amount_payment = balance*percent/100;
	    dijit.byId('total_payment'+index).attr('value',amount_payment);
   }else{//value to %
	   amount_payment =  dijit.byId('total_payment'+index).get('value');
	   percent = amount_payment*100/balance;
	   dijit.byId('percent'+index).attr('value',percent);
     }
	calCulateSchedulePayment();
	 if(dijit.byId('percent'+index).get('value')>100){
		 alert("តម្លៃត្រូវបង់មិនអាចធំជាង ១០០ ភាគរយបានទេ !");
		 dijit.byId('percent'+index).focus();
     }
}
function InputSoldPrice(){
	total_sold =dijit.byId("total_sold").get('value');
	//alert(total_sold);
	dijit.byId('sold_price').attr('value',total_sold);
}
function calCulateSchedulePayment(){
	var total_amount=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	if(rowId!=''){
	for(var n = 0; n < rowIDArray.length; n++) {
			total_amountpayment = (dijit.byId('total_payment'+rowIDArray[n]).get('value'));
			if(n==0){ 
			}
			if(isNaN(total_amountpayment)){
				total_amountpayment = 0;
			}
			total_amount = total_amount+ total_amountpayment;
		}
	}
	dijit.byId('total_installamount').attr('value',total_amount);
	calCulateFixedPeriod();
}
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
	if(arrays.length==0){ dijit.byId('total_installamount').attr('value','');}
	calCulateSchedulePayment();
}

function setFirstPaymentAndDateLine(pay_term,date_release,amount_date){
	var a = new Date(date_release);
	mm = a.getMonth()+amount_date+1;
	 var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	 if(mm<10){
		 mm = "0"+mm;
	}
	var y = a.getFullYear()+1;

	var epx_date = y + '-'+ mm + '-'+dd ;
	calCulateEndDate();
	calCulateFirstPayment();
}
function calCulateEndDate(){
	amount_period = 1;
	if(dijit.byId("schedule_opt").get('value')==4){amount_period=12;}
	amount_date = dijit.byId('period').get('value')*amount_period;
	release_date = dijit.byId("first_payment").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
	}else{
		var a = new Date(release_date);
		month = a.getMonth()+amount_date;
		mm = month%12;
		year = parseInt(month/12);
		 var dd = a.getDate();
		 if(dd<10){
			 dd = "0"+dd;
		}
		 if(mm<10){
			 mm = "0"+mm;
		}
		var y = a.getFullYear()+year;
		var epx_date = y + '-'+ mm + '-'+dd ;
        payment_option = dijit.byId('schedule_opt').attr('value');
		if(payment_option==2){
			dijit.byId('date_line').attr('value','<?php echo date("Y-m-d");?>');
		}else{
			dijit.byId('date_line').attr('value',epx_date);	
		}
    }
}
function CalculateDate(){
	pay_term = 1;
	amount_period = 1;
	if(dijit.byId("schedule_opt").get('value')==4){amount_period=12;}
	amount_date = dijit.byId('period').get('value')*amount_period;
	
	release_date = dijit.byId("first_payment").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
	}else{
		setFirstPaymentAndDateLine(pay_term,release_date,amount_date);		
    }
}
function checkReleaseDate(){
	CalculateDate();
}
function getFirstPayment(){
	calCulateFirstPayment();
}
function calCulateFirstPayment(){
	pay_term = 1;
	amount_date = 1;
	method_id = dijit.byId('schedule_opt').get('value');
	addamount=1;
	if(method_id==3 || method_id==4 || schedule_opt==6){
		addamount=0;
	}
	release_date = dijit.byId("release_date").get('value');
	var a = new Date(release_date);
		mm = a.getMonth()+amount_date+addamount;
	var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	 if(mm<10){
		 mm = "0"+mm;
	}
	var y = a.getFullYear();
	var epx_date = y + '-'+ mm + '-'+dd ;
	dijit.byId('first_payment').attr('value',epx_date);
}

function printSave(new_stu_id,new_receipt_no){
	 dijit.byId("terms").show();	
}
var url_previewloan = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'demoschedule')); ?>';
function addPreviewLoan(){
	r=0;
	if(dijit.byId('frm_add_tran').validate()){
		schedule_opt = dijit.byId("schedule_opt").get("value");
		if(schedule_opt==6){ 
			identity = $("#identity").val(); if(identity==''){ alert("Please Add Record First!");addRow(); return false;}}
		result = checkFirstRecord();
		if(result==false){return false;}
		loading();
		dojo.xhrPost({
		    url: url_previewloan,	
			form: dojo.byId("frm_add_tran"),		    
			handleAs:"json", 
			load: function(data) {
				 document.getElementsByClassName("overlay")[0].style.display="none";
				if(data.row_id=='row_id'){//return 1;
					printSave('','');
					}else{
						  temp='';	
						  fund_title=0;thead='';fund_title=0;
						  temp="<table border='1' class='collape tablesorter' style='border-collapse: collapse;border:1px solid #000;font-size:14px; width:1000px !important;' id='table'>";
						  temp+='<tr ><th colspan="7" style="border:1px solid #fff;border-bottom:1px solid #000;font-size:18px;font-family:Helvetica,sans-serif,Khmer OS Muol";><?php echo $tr->translate("តារាងគណនារំលស់");?></th></tr>';
						  temp+='<tr style="background:#ccc;font-family:Helvetica,sans-serif,"Kh Battambang","Khmer Battambang";"><th><?php echo $tr->translate("NUM");?></th>';
						  temp+='<th><?php echo $tr->translate("ថ្ងៃបង់ប្រាក់");?></th>';
						  temp+='<th><?php echo $tr->translate("ប្រាក់ដើមមុនបង់");?></th>';
						  temp+='<th><?php echo $tr->translate("ប្រាក់ដើមត្រូវបង់");?></th>';
						  temp+='<th><?php echo $tr->translate("ប្រាក់ការត្រូវបង់");?></th>';
						  temp+='<th><?php echo $tr->translate("ត្រូវបង់សរុប");?></th>';
						  temp+='<th><?php echo $tr->translate("ប្រាក់ដើមនៅសល់");?></th>';
						  principal_permonth=0;total_interest=0;total_payment_after=0;
						for(i=0;i<data.length;i++){
							principal_permonth=principal_permonth+parseFloat(data[i].principal_permonth);
							total_interest=total_interest+parseFloat(data[i].total_interest);
							total_payment_after=total_payment_after+parseFloat(data[i].total_payment_after);
					      r++;
						  temp+='<tr style="border:1px solid #000;"><td align="center">'+r+'</td>';
						  var myDate = new Date(data[i].date_payment);
						  d = new Date(data[i].date_name);
						  temp+='<td>&nbsp;'+getDayName(d.getDay())+'-'+data[i].date_payments+'</td>';
						  temp+='<td align="center">'+dojo.number.format(data[i].begining_balance,2)+'</td>';
						  temp+='<td align="center">'+dojo.number.format(data[i].principal_permonth,2)+'</td>';
						  temp+='<td align="center">'+dojo.number.format(data[i].total_interest,2)+'</td>';
						  temp+='<td align="center"><b>'+dojo.number.format(data[i].total_payment_after,2)+'<b></td>';
						  temp+='<td align="center"><b>'+dojo.number.format((data[i].ending_balance),2)+'<b></td>';
						 }
						  temp+='<tr><td align="right" colspan="3" style="border-left:1px solid #fff;border-bottom:1px solid #fff;">&nbsp;សរុប -Total</td>';
						  temp+='<td>'+dojo.number.format(principal_permonth,2)+'</td>';
						  temp+='<td>'+dojo.number.format(total_interest,2)+'</td>';
						  temp+='<td><b>'+dojo.number.format(total_payment_after,2)+'<b></td>';
						  temp+='<td></td>';
						temp+='</table>';
						dojo.byId('t_amountmoneytype').innerHTML = temp;
						dijit.byId("lbl_schedule").show();
					}
				
			},
			error: function(response, ioArgs) {
				 document.getElementsByClassName("overlay")[0].style.display="none";
				alert("Failed while doing the operation: " + ioArgs.xhr.response);
			}
	   });
	}
}
function getDayName(day){
	 var weekday = new Array(7);
	    weekday[0] = "អាទិត្យ";
	    weekday[1] = "ច័ន្ទ";
	    weekday[2] = "អង្គារ";
	    weekday[3] = "ពុធ";
	    weekday[4] = "ព្រហ";
	    weekday[5] = "សុក្រ";
	    weekday[6] = "សៅរ៍";
	    return weekday[day];
}
function hideDialog() {		
	dijit.byId("lbl_schedule").hide();
}
function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}

var url_add_staff = '<?php echo $this->url(array("module"=>"loan","controller"=>"index","action"=>"add-staff")); ?>';
function addStaff(){
	dojo.xhrPost({
		url:url_add_staff,
		form: dojo.byId("frm_staff"),
		handleAs:"json",
		load: function(data) {
			var Itemmake = { 
	    	  	id: data,
		        name: dijit.byId('kh_name').get('value')
		    };
	 		addDataToSelectbox(dijit.byId('staff_id'), staff_store, Itemmake, data);
		    dijit.byId('frm_staff').reset();
		    dijit.byId("popup_staff").hide();
		},
		error: function(err) {
			alert(err);
		}
	});
}
function hideDialog1(){
	 dijit.byId("popup_staff").hide();
}
function hideDialog2(){
	 dijit.byId("popup_client").hide();
}
var url_add_client = "<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'add-client'));?>";
function addNewClient(){
	//alert(1);
	dojo.xhrPost({
		url:url_add_client,	
		form:dojo.byId('frmpop_client'),
		handleAs:"json",
		load: function(response) {
			
			var myNewItem = {					
				id: response.id,
				name: dijit.byId('client_name').get('value'),
			};			
			addDataToSelectbox(dijit.byId('member'), client_store, myNewItem, response.id);
			
			var myNewItem1 = {					
				 id: response.id,
		         name: response.customer_code,
			 };			
			addDataToSelectbox(dijit.byId('customer_code'), client_number_store, myNewItem1, response.id);	

			pop_client_branch_id = dijit.byId('client_branch_id').get('value');  // get value to set it back for pop up 2 time
			
			dijit.byId('frmpop_client').reset();
			dijit.byId("popup_client").hide();
			
			dijit.byId('client_branch_id').attr('value',pop_client_branch_id);
			
		},
		error: function(err) {
		}
	});
}


</script>
<style>
						           .hover:hover{background: #eee;}
.overlay {display: none;position: absolute;width: 100%;height: 100%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .95;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           border: solid 1px #060522;text-align: center;
           background: #fff url("<?php echo $this->baseUrl()?>/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>


<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:30%;" id="popup_staff" >
		<form style="background-color: buttonface; width:100%;" id='frm_staff' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
				<tr>
					<td>
						<fieldset style="background-color: buttonface;">
						<legend align="center" ><?php echo $tr->translate('ADD_STAFF');?></legend>
							<table style="margin: 0 auto; width: 100%;  padding:10px;" cellspacing="7" >
								<tr>
									<td><?php echo $tr->translate('NAME_KH');?></td>
									<td>
										<input dojoType="dijit.form.ValidationTextBox"   class="fullside" id="kh_name" name="kh_name" value="" type="text">
									</td>
								</tr>
								<tr>
									<td><?php echo $tr->translate('SEX');?></td>
									<td>
										<select dojoType="dijit.form.FilteringSelect"  class="fullside" id="sex" name="sex" value="" type="text">
											<option value="1">Male</option>
											<option value="2">Female</option>
										</select>
									</td>
								</tr>
								<input type="hidden" name="branch_id_pop" id="branch_id_pop" dojoType="dijit.form.TextBox" />
								<tr>
									<td><?php echo $tr->translate('PHONE');?></td>
									<td>
										<input type="text" name="phone" id="phone" class="fullside" dojoType="dijit.form.TextBox" />
									</td>
									
								</tr>
								
								<tr>
									<td><?php echo $tr->translate('NOTE');?></td>
									<td>
										<input type="text" name="note_pop" id="note_pop" class="fullside" dojoType="dijit.form.TextBox" />
									</td>
									
								</tr>
								
								<tr>
									<td colspan="4" align="center">
										<input type="button" value="ចាកចេញ" label="Close" id="close" name="close" dojoType="dijit.form.Button" 
										​ ​​iconClass="dijitIconUndo" onclick="hideDialog1();"/>
										<input type="button" value="save" label="SAVE" id="save" name="save" dojoType="dijit.form.Button" 
										 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addStaff();"/>
									</td>
								</tr>
								
							</table>
					</fieldset>
					</td>
				</tr>
			</table>

		</form>
	</div>
</div>



<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:35%;" id="popup_client" >
		<form style="background-color: buttonface; width:100%;" id='frmpop_client' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
				<tr>
					<td>
						<fieldset style="background-color: buttonface;">
						<legend align="center" ><?php echo $tr->translate('ADD_CLIENT');?></legend>
							<table style="margin: 0 auto; width: 100%;  padding:10px;" cellspacing="7" >
								<tr>
									<td><?php echo $tr->translate('CUSTOMER_NAME');?></td>
									<td>
										<input dojoType="dijit.form.ValidationTextBox"  class="fullside" id="client_name" name="client_name" value="" type="text">
									</td>
								</tr>
								<tr>
									<td><?php echo $tr->translate('SEX');?></td>
									<td>
										<select dojoType="dijit.form.FilteringSelect"  class="fullside" id="client_sex" name="client_sex" value="1" type="text">
											<option value="1">Male</option>
											<option value="2">Female</option>
										</select>
									</td>
								</tr>
								
								<tr>
									<td><?php echo $tr->translate('DOCUMENT_TYPE');?></td>
									<td>
										<select dojoType="dijit.form.FilteringSelect"  class="fullside" id="client_doc_type" name="client_doc_type" value="2" type="text">
											<?php if(!empty($this->client_doc_type)){foreach($this->client_doc_type as $row){?>
												<option value="<?php echo $row['id']?>"><?php echo $row['name']?></option>
											<?php }}?>
										</select>
									</td>
								</tr>
								<tr>
									<td><?php echo $tr->translate('NATIONAL_ID');?></td>
									<td>
										<input type="text" name="national_id" id="national_id" class="fullside" dojoType="dijit.form.TextBox" />
									</td>
									
								</tr>
								<input type="hidden" name="client_branch_id" id="client_branch_id" dojoType="dijit.form.TextBox" />
								<tr>
									<td><?php echo $tr->translate('PHONE');?></td>
									<td>
										<input type="text" name="client_phone" id="client_phone" class="fullside" dojoType="dijit.form.TextBox" />
									</td>
									
								</tr>
								
								<tr>
									<td><?php echo $tr->translate('NOTE');?></td>
									<td>
										<input type="text" name="client_note" id="client_note" class="fullside" dojoType="dijit.form.TextBox" />
									</td>
									
								</tr>
								
								<tr>
									<td colspan="4" align="center">
										<input type="button" value="ចាកចេញ" label="Close" dojoType="dijit.form.Button" 
										​ ​​iconClass="dijitIconUndo" onclick="hideDialog2();"/>
										<input type="button" value="save" label="SAVE"  dojoType="dijit.form.Button" 
										 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addNewClient();"/>
									</td>
								</tr>
								
							</table>
					</fieldset>
					</td>
				</tr>
			</table>

		</form>
	</div>
</div>
<script>
function returnMOnth(monthnum){
	var month = new Array();
	month[1] = "Jan";
	month[2] = "Feb";
	month[3] = "Mar";
	month[4] = "Apr";
	month[5] = "May";
	month[6] = "Jun";
	month[7] = "Jul";
	month[8] = "Aug";
	month[8] = "Sep";
	month[10] = "Oct";
	month[11] = "Nov";
	month[12] = "Dec";
	return month[monthnum];
}
function calculateDuration(type=null){
	if(type==1){
		var total_paid_install = dijit.byId('total_installamount').get('value');
		if(total_paid_install == 0){
			sold_price = dijit.byId('sold_price').get('value');
		}else{
			sold_price = dijit.byId('sold_price').get('value')-dijit.byId('total_installamount').get('value');
		}
		
		interest_rate= dijit.byId('interest_rate').get('value')/12/(100);//(100/30day)
		fixed_payment = dijit.byId('fixed_payment').get('value');
		if(isNaN(interest_rate)){interest_rate=0;}
		pi = (parseFloat(fixed_payment)-(parseFloat(sold_price)*parseFloat(interest_rate)));
		s = parseFloat(fixed_payment);
		top_ii = Math.log(s/pi);
		var duration =  Math.ceil(top_ii / Math.log(1+ parseFloat(interest_rate)));// ROUND UP
		duration = duration/12;
		dijit.byId('period').attr('value',duration);
	}
}
</script>
</div>
<div style="clear: both;"></div>
</body>
</html>