<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_STAFF'));
?>	
<?php  $techer= $this->frm_co;?>
<script>
	dojo.require("dijit/form/DateTextBox");
	dojo.require("dijit/form/NumberTextBox");
	dojo.ready(function(){
		//getStaffCode();
		});
</script>
<form  id='add_techer' action="<?php echo $this->url(array('module'=>'group','controller'=>'co','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				/*if(dijit.byId('province').get('value')==''){
					alert('Province required');
					return false;
			    }*/
				return true;
			} else {
				return false;
			}
</script>
<table width="100%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset style="margin-top: -10px;">
					<legend><strong><?php echo $tr->translate("INFO_STAFF");?></strong></legend>
					
					<table style="margin: 0 auto; width: 100%;" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("BRANCH_NAME")?></td>
							<td><?php  echo $techer->getElement('branch_id');?></td>
							<td><?php echo $tr->translate("STAFF_CODE")?></td>
							<td><?php  echo $techer->getElement('co_id'); echo $techer->getElement('id');?></td>
							<td><?php echo $tr->translate("NAME_KH")?></td>
							<td><?php  echo $techer->getElement('name_kh');?></td>
						</tr>
						
						<tr>
							<td><?php echo $tr->translate("SEX")?></td>
							<td><?php  echo $techer->getElement('co_sex');?></td>
							<td><?php echo $tr->translate("PHONE")?></td>
							<td><?php  echo $techer->getElement('tel');?></td>
							<td><?php echo $tr->translate("NATIONALITY_NO")?></td>
							<td><?php  echo $techer->getElement('national_id');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("EMAIL")?></td>
							<td><?php  echo $techer->getElement('email');?></td>
							<td><?php echo $tr->translate("POB")?></td>
							<td><?php  echo $techer->getElement('pob');?></td>
							<td><?php echo $tr->translate("CURRENT_ADDRESS")?></td>
							<td><?php  echo $techer->getElement('address');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NOTE")?></td>
							<td><?php echo $techer->getElement('note');?></td>
							<td><?php echo $tr->translate("STATUS")?></td>
							<td><?php  echo $techer->getElement('status');?></td>
							<td><?php echo $tr->translate("PICTURE")?></td>
							<td><?php  echo $techer->getElement('photo');?></td>
						</tr>
						<tr>
							<td><?php //echo $tr->translate("DISPLAY_BY")?></td>
							<td><?php  //echo $techer->getElement('display');?></td>
							<td><?php //echo $tr->translate("POSITION")?></td>
							<td><?php  //echo $techer->getElement('position');?></td>
							<td><?php //echo $tr->translate("NAME_EN")?></td>
							<td><?php  //echo $techer->getElement('name_en');?></td>
						</tr>
						<tr>
					        <td><?php //echo $tr->translate("DEGREE")?></td>
							<td><?php // echo $techer->getElement('degree');?></td>
							<td><?php //echo $tr->translate("DEPARTMENT")?></td>
							<td><?php  //echo $techer->getElement('department_id');?></td>
							<td><?php //echo $tr->translate("FINGER_PRINT")?></td>
							<td><?php  //echo $techer->getElement('figer_print_id');?></td>
						</tr>
						
					</table>
					<fieldset>
						<legend ><strong><?php //echo $tr->translate("SALARY_INFO");?></strong></legend>
							<table style="margin: 0 auto; width: 95%; display: none;" cellspacing="10">
								<tr>
									<td><?php //echo $tr->translate("BASIC_SALARY")?></td>
									<td><?php  //echo $techer->getElement('basic_salary');?></td>
									<td><?php //echo $tr->translate("DATE_START_WORK")?></td>
									<td><?php  //echo $techer->getElement('start_date');?></td>
									<td><?php //echo $tr->translate("DATE_END_CONTRACT")?></td>
									<td><?php  //echo $techer->getElement('end_date');?></td>
								</tr>
								<tr>
									<td><?php //echo $tr->translate("CONTRACT_NO")?></td>
									<td><?php  //echo $techer->getElement('contract_no');?></td>
									<td><?php //echo $tr->translate("SHIFT")?></td>
									<td><?php  //echo $techer->getElement('shift');?></td>
								</tr>
								<tr>
									<td><?php //echo $tr->translate("WORKING_TIME")?></td>
									<td><?php // echo $techer->getElement('workingtime');?></td>
									<td><?php //echo $tr->translate("ANNUAL_LIVES")?></td>
									<td><?php // echo $techer->getElement('annual_lives');?></td>
									<td><?php //echo $tr->translate("")?></td>
									<td><?php // echo $techer->getElement('');?></td>
								</tr>
								
							</table>
							<div style="text-align: center; margin: 10px 0px;">
									<input type="hidden" name="exchangefrom" value="2" />
									<input type="hidden" name="inv_no" value="<?php echo $this->inv_no;?>">
									<input type="reset" value="សំអាត" label="សំអាត"dojoType="dijit.form.Button"/>
									<input type="submit" value="save_close" name="save_close" label="រក្សាទុក+បិត" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
									<input type="submit" value="save_new" name="save_new" label="រក្សាទុក+ថ្មី" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
							</div>
					</fieldset>	
		</fieldset>		
		
		</td>
	</tr>
</table>	
</form>
<?php  echo $this->frmpopupdepartment;?>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dojo.date.locale");

dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");

	function calculateDay(){
		start_date = dijit.byId("start_date").get('value');
		var a=new Date(start_date);
		m=a.getMonth()+1;
		d=a.getDate();
		if(d<15){
			m=m-1;
		}
		t_day=18*(12-m)/12;
		dijit.byId('annual_lives').attr('value',t_day);
	}
	function Checktime(type){
		workingtime_id=dijit.byId("workingtime").get("value");
		shift_id=dijit.byId("shift").get("value");
		if(type==1){
			if(workingtime_id==1){
				dijit.byId("shift").attr('value',1);
				dijit.byId("workingtime").set('readOnly',true);
			}
			else if(workingtime_id==2){
				dijit.byId("shift").attr('value',2);
			}
			else if(workingtime_id==3){
				dijit.byId("shift").attr('value',2);
			}
		}else{
			if(shift_id==1){
				dijit.byId("workingtime").attr('value',1);
				dijit.byId("workingtime").set('readOnly',true);
			}
			else if(shift_id==2){
				dijit.byId("workingtime").attr('value',2);
				dijit.byId("workingtime").set('readOnly',false);
			}
			else if(shift_id==2){
				dijit.byId("workingtime").attr('value',3);
				dijit.byId("workingtime").set('readOnly',false);
			}
		}
	}

	function popupDepartment(){
		var department_id = dijit.byId('department_id').get('value');
		if(department_id==-1){
			dijit.byId('department').show();
		}
	}
	function addNewDepartment(){
		var url_submit = '<?php echo $this->url(array('module'=>'payroll','controller'=>'co','action'=>'addnewdepartment')); ?>';
				dojo.xhrPost({
			    url: url_submit,	
				form: dojo.byId("frm_department"),		    
				handleAs:"json", 
				load: function(data) {	
					labelen = dijit.byId('department_en').get('value');
					labelkh = dijit.byId('department_kh').get('value');
					$('#department_id').val(labelen);
					$('input[name="department_id"]').val(data);
					dojo.byId('frm_department').reset(); 
					dijit.byId('department').hide();
				},
				error: function(e) {
				alert("Your message could not be sent, please try again!.");
				}
			});
	}
var url_staffcode = '<?php echo $this->url(array('module'=>'group','controller'=>'co','action'=>'getstaffcode')); ?>';
	function getStaffCode(){
		branch_id = dijit.byId('branch_id').get('value');
		dijit.byId('co_id').attr('value','');
		if(branch_id==''){
			alert('Please Select Branch');
			dijit.byId('branch_id').focus();
			return false;
		}
		dojo.xhrPost({
			url:url_staffcode,	
			content:{ 
			    'branch_id':branch_id,
			},		    
			handleAs:"json",
			load: function(data) {
				dijit.byId('co_id').attr('value',data);
			},
			error: function(err) {
			}
		});
	}
</script>