<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('WORK_PROCESS'));
	$user_id = Application_Model_DbTable_DbGlobal::GlobalgetUserId();	
?>
<?php  $dailywork= $this->frm_dailywork;?>
<script>
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.Textarea");
</script>
<form id="add_province" action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
	</script>
	<table cellspacing="20" style="margin: 0 auto; width: 600px">
		<tr>
			<td>
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("WORK_PROCESS");?></strong></legend>
					<table cellspacing="20" width="100%" >
						<tr>
							<td align="center" valign="top">
								<table style="margin: 0 auto; width:100%;" cellspacing="10">
									<tr>
										<td><?php echo $tr->translate("TODO_TASK")?></td>
										<td><?php echo $dailywork->getElement("work");?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("TODO_TYPE")?></td>
										<td><?php echo $dailywork->getElement("projectname");?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("CUSTOME_NANE")?></td>
										<td><?php echo $dailywork->getElement("customer_id");?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("User")?></td>
										<td><?php echo $dailywork->getElement("user");?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("DATE")?></td>
										<td><?php echo $dailywork->getElement("start_date");?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("STATUS")?></td>
										<td><?php echo $dailywork->getElement("work_status");?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("Description")?></td>
										<td><?php echo $dailywork->getElement("description");?></td>
									</tr>
									<tr>
										<td colspan="2" align="center">
											<input type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>"dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
											<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button" 
												iconClass="dijitEditorIcon dijitEditorIconSave" />
											<input type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVENEW');?>" dojoType="dijit.form.Button" 
												iconClass="dijitEditorIcon dijitEditorIconSave" />
										</td>
									</tr>					
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
	</table>	
</form>

 <script>
 jQuery(document).ready(function(){
});

<?php $url_getwork =  $this->url(array('module'=>'dailywork','controller'=>'workprocess','action'=>'getworkdetail')); ?>
function getWorkDetail(){
	var work_id= $("#work").val();
	$.ajax({
        url: "<?php echo $url_getwork;?>",
        type: "post",
        data: {'work_id':work_id},
        success: function(data){
            rs = $.parseJSON(data);
          
            $("#customer_id").val(rs.customer_id);
            $("#user").val(rs.user);
            $("#projectname").attr("value",rs.projectname).attr('selected',true);
			$("#projectname").select2();
			$("#user").select2();
			//$("#projectname").val(rs.projectname);
           
        },
        error:function(response, ioArgs){
        	//alert("Failed while doing the operation: " + ioArgs.xhr.response);  
        }
    });
}
</script>	