<?php
$row_rs = $this->row_rs;
?>
<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage(); ?>
<?php $formFilter =  $this->frm_search;?>
<meta charset="utf-8" />
<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
   <table>
   		<tr>
		   	<td><input class="form-control" id="adv_search" name="adv_search" value="<?php echo $this->row['adv_search']?>" type="text" ></td>
		   	<td><?php echo $formFilter->getElement("user");?></td>
		   	<td><?php echo $formFilter->getElement("projectname");?></td>
		    <td><input class="form-control form-control-inline date-picker" id="start_date" name="start_date" value="<?php echo date("m/d/Y",strtotime($this->row['start_date']));?>" type="text" ></td>
		    <td><input class="form-control form-control-inline date-picker" id="end_date" name="end_date" value="<?php echo date("m/d/Y",strtotime($this->row['end_date']));?>" type="text" ></td>
		    <td><select name="status" class="form-control" >
					<option <?php if($this->row["status"]==2){echo "selected='selected'";} ?> value="2">In Progress</option>
					<option <?php if($this->row["status"]==3){echo "selected='selected'";} ?> value="3">Cancel</option>
					<option <?php if($this->row["status"]==""){echo "selected='selected'";} ?> value="">All</option>
				</select>
		    </td>
		    <td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
   	   </tr>
   </table>
</form>
<?php echo $this->list; ?>