<?php	
	$this->headTitle('Add Sell'); 
	echo $this->headTitle();
	$frm = $this->frm_loan;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<style>
.fullside50{ width:48%;}
</style>
<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>	
	<script src="<?php echo $baseurl;?>/js/help.js"></script>
	<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.7.2.min.js"></script>
   <script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog"]);
   </script>
<form id='frm_add_tran' action="" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else {
				return false;
			}
</script>
<table width="100%" style="margin-top:-10px;">
	<tr width='50%'>
		<td>
			<fieldset>
				<legend><strong style="color:#284db7;"><?php echo $tr->translate("INFO_INDILOAN")?></strong></legend>
				<table cellspacing="5"  style="margin-top: -10px;">
					<tr>
						<td style="width: 200px;"><?php echo $frm->getElement('commission');?></td>
						
						<td style="width: 200px;"><?php echo $frm->getElement('village_1_ed')?></td>
						<td width="100">ជ្រើសរើសភូមិ</td>
						<td><input type="text" style="width:200px"  name="date_input_system"  required="required" dojoType="dijit.form.DateTextBox"/>
						ថ្ងៃបញ្ចូលក្នុងប្រព័ន្ធ
						</td>

						
						<td>
							<input type="hidden" class="fullside" id="record_row" name="record_row" value="0"  dojoType="dijit.form.TextBox" />

						</td>
					
					</tr>
					
					<tr style="max-height: 300px;">
							<td colspan="6">
								<div  id="showrecord"></div>
								<input type="button" label="<?php echo $tr->translate('ADD_INSTALLMENT');?>" dojoType="dijit.form.Button" 
							 		iconClass="dijitIconEditProperty" onclick="addRow();" />
							</td>
					</tr>
				</table>
			</fieldset>
		</td>
	</tr>		
	<tr>
		<td>
			<div  id="showrecord"></div>
		</td>
	</tr>
	<tr>
		<td align="center">
			<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
			<input type="submit" label="<?php echo $tr->translate("SAVECLOSE");?>" name='saveclose' value='saveclose' dojoType="dijit.form.Button" iconClass="dijitIconDelete"/>
			<input type="submit" label="<?php echo $tr->translate("SAVENEW")?>" name='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask"/>
			<input type="button" onclick="addPreviewLoan();displayNone();" label="<?php echo $tr->translate("PREVIEW")?>" name='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask" />
		</td>
	</tr>	
	
</table>

<script>
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");

url_getvillagecode = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'get-info-custom'));?>';
r=0;
function getAllcustomer(){
	vllage = dijit.byId('village_1_ed').get('value');
	fund_title=0;
	 dojo.query("#showrecord").append('');
	 tmp='<table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
	 tmp+='<tr style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
	 tmp+='</table>';
	 dojo.query("#showrecord").append(tmp);
		  dojo.xhrPost({
		     url: url_getvillagecode, 
		  content:{ 
		   'vllage':vllage,
		   },      
		  handleAs:"json",
		  load: function(data) {
			  //alert(data);
			  dijit.byId('record_row').attr('value','');
			  if(data==''){
				  thead='<th><?php echo $tr->translate("DEL");?></th>';
				    thead+='<th><?php echo $tr->translate("No");?></th>';
				    thead+='<th><?php echo $tr->translate("Client_id");?></th>';
				    thead+='<th><?php echo $tr->translate("Old_use");?></th>';
				    thead+='<th><?php echo $tr->translate("New_Use");?></th>';
				    thead+='<th><?php echo $tr->translate("Total");?></th>';
				    thead+='<th><?php echo $tr->translate("Price");?> </th>';
	  				thead+='<th><?php echo $tr->translate("Date_input");?> </th>';
				    fund_title=1;
				    dojo.query("#head_title").append(thead);
			  				   }
			  				   for(i=0;i<data.length;i++){
			  				   r++;
			  				   if(fund_title!=1){
			  				    thead='<th><?php echo $tr->translate("DEL");?></th>';
			  				    thead+='<th><?php echo $tr->translate("No");?></th>';
			  				    thead+='<th><?php echo $tr->translate("Client_id");?></th>';
				  				  thead+='<th><?php echo $tr->translate("Customer");?></th>';
			  				    thead+='<th><?php echo $tr->translate("Old_use");?></th>';
			  				    thead+='<th><?php echo $tr->translate("New_Use");?></th>';
			  				    thead+='<th><?php echo $tr->translate("Total");?></th>';
								thead+='<th><?php echo $tr->translate("តម្លៃកត្តា");?> </th>';
			  				    thead+='<th><?php echo $tr->translate("Price");?> </th>';
				  				thead+='<th><?php echo $tr->translate("Start_Date");?> </th>';
				  				thead+='<th><?php echo $tr->translate("Date_input");?> </th>';

					  						  				    
			  				    fund_title=1;
			  				    dojo.query("#head_title").append(thead);
			  				         }
			  				   temp='<td style="width:30px !important;text-align:center;" ><img style="cursor:pointer" onclick="deleteRecord('+r+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			  				   temp+='<td>'+r+'</td>';
			  				   temp+='<td><input style=" width:100px" value="'+data[i].id+'"  name="id'+r+'" type="hidden" required="true" readonly="true"  dojoType="dijit.form.ValidationTextBox"/>' +
								   '<input style=" width:100px" value="'+data[i].client_number+'"  name="client_num'+r+'" type="text" required="true" readonly="true"  dojoType="dijit.form.ValidationTextBox"/><input type="hidden" name="client_id'+r+'" style="width: 30px;" value="'+data[i].client_id+'" dojoType="dijit.form.TextBox" /></td>';
			  				   temp+='<td><input style=" width:90%; readonly="true" readonly="true" font-size:12px;" type="text" value="'+data[i].name_kh+'"   name="name_kh'+r+'" required="true"  id="toowner_name'+r+'" dojoType="dijit.form.ValidationTextBox"/></td>';
			  				   temp+='<td><input type="text" readonly="true" style="width:110px" required="true" value="'+data[i].end_use+'"  name="start_use'+r+'" id="start_use'+r+'" dojoType="dijit.form.ValidationTextBox"/></td>';
			  				   temp+='<td><input type="text" style="width:110px"   onkeyup="calculate('+r+')"  name="new_num'+r+'" id="new_num'+r+'" dojoType="dijit.form.ValidationTextBox"/></td>';
				  			   temp+='<td><input style="  width:110px" type="text" name="toatal_water'+r+'" readonly="true" id="toatal_water'+r+'" dojoType="dijit.form.TextBox" /><input type="hidden" name="coid'+r+'" id="coid'+r+'" dojoType="dijit.form.TextBox" /> </td>';
					  		//temp+='<td><input style=" width:110px" type="text" name="tonote'+r+'"  id="1tonote'+r+'" dojoType="dijit.form.TextBox" /><input type="hidden" name="coid'+r+'" id="coid'+r+'" dojoType="dijit.form.TextBox" /> </td>';	 
								   temp+='<td><input type="text" style="width: 30px;color:red;font-weight: bold;border: none;"  readonly="true" name="price_setting'+r+'" id="price_setting'+r+'" value="'+data[i].price+'" dojoType="dijit.form.TextBox" /><input type="hidden" name="price_setting_id'+r+'"  value="'+data[i].price_set_id+'" dojoType="dijit.form.TextBox" /></td>'

								   temp+='<td><input style=" width:110px; color:red;" readonly="true" type="text" name="total_price'+r+'"  id="total_price_id'+r+'" dojoType="dijit.form.TextBox" /><input type="hidden" name="coid'+r+'" id="1coid'+r+'" dojoType="dijit.form.TextBox" /> </td>'

								temp+='<td><input type="text" style="width:110px"  name="1issue_date'+r+'" readonly="true" value="'+data[i].date_cus_start+'" id="1issue_date'+r+'" dojoType="dijit.form.DateTextBox"/></td>';
					  			temp+='<td><input type="text" style="width:110px"  name="issue_date'+r+'"  id="0issue_date'+r+'" dojoType="dijit.form.DateTextBox"/></td>';   
						  			 
				  			   tmp='<tr style="border:1px solid #eee; font-size:14px; !important" id="row_capital'+r+'">'

			  				   tmp+="</tr>";
			  				    dojo.query("#t_amountmoneytype").append(tmp);
			  				    
			  				   dojo.html.set(dojo.byId("row_capital"+r),temp, {
			  				       parseContent: true,
			  				   });
			  				   
			  				   if(dijit.byId("record_row").get('value')!="") {
			  				    var ids = dijit.byId("record_row").value;
			  				    dijit.byId("record_row").attr('value',ids+','+r);
			  				   } 
			  				   else { dijit.byId("record_row").attr('value',r);
			  				   }
			  				   
			  				    /*dijit.byId('collect_type'+r).attr('value',data[i].collecteral_type);
			  				    dijit.byId('owner_type'+r).attr('value',data[i].owner_type);
			  				    dijit.byId('owner_name'+r).attr('value',data[i].owner_name);
			  				    dijit.byId('toowner_name'+r).attr('value',data[i].owner_name);
			  				    
			  				    dijit.byId('number_collteral'+r).attr('value',data[i].number_collecteral);
			  				    dijit.byId('coid'+r).attr('value',data[i].id);
			  				    dijit.byId('client_coll').attr('value',data[i].client_coll);*/
			  				   }
		  },
		  error: function(err) {
		  }
		 });
}


function calculate(r){
	old_num=parseFloat(dijit.byId('start_use'+r).get('value'));
	new_num=parseFloat(dijit.byId('new_num'+r).get('value'));
	price_stting=parseFloat(dijit.byId('price_setting'+r).get('value'));

	total=new_num-old_num;
	total_price=total*price_stting;
	if(new_num > old_num){
		
		dijit.byId("toatal_water"+r).attr('value',total);
		dijit.byId("total_price_id"+r).attr('value',total_price+'៛');
	}else{
		dijit.byId("total_price_id"+r).attr('value','0៛');
		dijit.byId("toatal_water"+r).attr('value',total);
	}
	
}

 </script>
 </form>