<?php	
	$this->headTitle('Add Sell'); 
	echo $this->headTitle();
	$frm = $this->frm_loan;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<style>
.fullside50{ width:48%;}
</style>
<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>	
	<script src="<?php echo $baseurl;?>/js/help.js"></script>
   <script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog"]);
   </script>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'edit')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
            branch_id = dijit.byId('branch_id').get('value');
            if (branch_id=='' || branch_id==-1){
				alert('Please Select Branch!');
				dijit.byId('branch_id').focus();
				return false;
			}
			client = dijit.byId('member').get('value');
			if (client=='' || client==-1){
				alert('Please Select Client Name !');
				dijit.byId('member').focus();
				return false;
			}
			rs = checkValidateDate();
			if(rs==false){
              return false;			
            }
              payment_id =dijit.byId("schedule_opt").get("value");
              paid_amount =dijit.byId("deposit").get("value");
              if(payment_id==1 && paid_amount<=0){ alert("សូមបញ្ចូលចំនួនទឹកប្រាក់ត្រូវបង់");dijit.byId("deposit").focus();return false;}
				return true;
			}else {
				return false;
			}
</script>
<table width="100%" style="margin-top:-10px;">
	<tr>
		<td>
				<fieldset>
					<legend><strong style="color:#284db7;"><?php echo $tr->translate("INFO_INDILOAN")?></strong></legend>
					<table cellspacing="5"  width="100%" style="margin-top: -10px;">
						<tr>
							<td width="13%"><?php echo $tr->translate("BRANCH_NAME")?></td>
							<td width="25%"><?php echo $frm->getElement('branch_id');?></td>
							<td><?php echo $tr->translate("SALE_NO")?></td>
							<td  width="22%">
								<table width="100%">
									<tr>
										<td width="33%"><?php echo $frm->getElement('sale_code');?></td>
										<td width="33%" style="white-space: nowrap;"><?php echo $tr->translate("បង្កាន់ដៃបង់")?></td>
										<td width="33%"><?php echo $frm->getElement('receipt');?></td>
									</tr>
								</table>
							</td>
							<td><?php echo $tr->translate("CUSTOMER_CODE")?></td>
							<td><input id="customer_code" /><input type="hidden" name="identity" id="identity"  value="" ></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DATE_BUY")?></td>
							<td><?php echo $frm->getElement('date_buy');?></td>
							<td style="white-space: nowrap;">ថ្ងៃចេញកិច្ចសន្យា</td>
							<td><?php echo $frm->getElement('agreement_date');?></td>
							<td style="white-space: nowrap;"><?php echo $tr->translate("CUSTOMER_NAME")?></td>
							<td><input id="member" /> <?php //echo $frm->getElement('member');?>
								<input dojoType="dijit.form.TextBox" class="fullside" id="joint_with" name="joint_with"  type="hidden">
							</td>
						</tr>
						<tr style="background: #edf7f8;">
							<td colspan="6" style="border-bottom:1px solid #aac4e6;"><strong style="color:#284db7;"><?php echo $tr->translate("PROPERTY_INFORMATION")?></strong></td>
						</tr>
						<tr height="40px">
							<td><?php echo $tr->translate("PROPERY_CODE")?></td>
							<td><input id="land_code" /><?php //echo $frm->getElement('');?>
								<input dojoType="dijit.form.TextBox"  id="propertype" name="propertype" type="hidden">
							</td>
							<td><?php echo $tr->translate("DESCRIPTION")?></td>
							<td style="height: 50px; border:1px solid #aac4e6; widht:100%; font-size: 13px; color:#284db7;padding:5px;" colspan="4"><label id="land_information" style="max-width:100%;"></label><?php //echo $tr->translate("Address")?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("LAND_PRICE")?></td>
							<td><?php echo $frm->getElement('land_price');?></td>
							<td><?php echo $tr->translate("HOUSE_PRICE")?></td>
							<td><?php echo $frm->getElement('house_price');?></td>
							<td><?php echo $tr->translate("TOTAL_SOLD")?></td>
							<td><?php echo $frm->getElement('total_sold');?></td>
						</tr>
						<tr style="background: #edf7f8;">
							<td colspan="6" style="border-bottom:1px solid #aac4e6;"><strong style="color:#284db7;"><?php echo $tr->translate("PAYMENT_INFORMATION")?></strong></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Discount")?></td>
							<td><?php echo $frm->getElement('discount_percent');?><?php echo $frm->getElement('discount');?></td>
							<td><?php echo $tr->translate("TOTAL_PAYMENT")?></td>
							<td><?php echo $frm->getElement('sold_price');?></td>
							<td><?php echo $tr->translate("OTHER_FEE")?></td>
							<td><?php echo $frm->getElement('other_fee');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("PAYMENT_TYPE")?></td>
							<td><?php echo $frm->getElement('schedule_opt');?></td>
							<td><?php echo $tr->translate("Paid")?></td>
							<td><?php echo $frm->getElement('deposit');?></td>
							<td><?php echo $tr->translate("Balance")?></td>
							<td width="250px">
								<table width="100%" >	
									<tr>
									<td width="35%"><?php echo $frm->getElement('balance');?></td>
									<td width="30%" style="color:red; white-space: nowrap;">ប្រាក់រំលស់</td>
									<td width="35%">
									<input readonly type="text" class="fullside" dojoType="dijit.form.TextBox" name="for_installamount" id="for_installamount"  value="" >
									<input type="hidden" class="fullside" dojoType="dijit.form.TextBox" name="total_installamount" id="total_installamount"  value="" ></td>
								   </tr>
								</table>
							</td>
						</tr>
						<tr>
						    <td style="white-space: nowrap;"><lable id='lbl_period'><?php echo $tr->translate("TERM_BORROW")?></lable><lable id='lbl_year'><?php echo $tr->translate("YEAR")?></lable></td>
							<td><?php echo $frm->getElement('period');?></td>
							<td><?php echo $tr->translate("INTEREST_RATE")?></td>
							<td><?php echo $frm->getElement('interest_rate');?></td>
							<td style="white-space: nowrap;"><label id="lbl_payment"><?php echo $tr->translate("AMOUNT_FUND_GRAICE_PARIOD")?></label></td>
							<td><?php echo $frm->getElement('fixed_payment');?></td>
						</tr>
						<tr>
							<td><label id="lbl_release"><?php echo $tr->translate("LOAN_RELEASE")?></label></td>
							<td><?php echo $frm->getElement('release_date');?>
							<!--<input type="text" dojoType="dijit.form.TextBox" required="true" class="fullside" constraints="{datePattern:'dd/MM/yyyy'}" id="release_date" name="release_date" value="<?php //echo date("Y-m-d")?>" /> -->
							</td>
							<td><?php echo $tr->translate("FIRST_PAYMENT")?></td>
							<td><?php echo $frm->getElement('first_payment');?></td>
							<td><?php echo $tr->translate("LIFE_LOAN")?></td>
							<td><?php echo $frm->getElement('date_line');?>
							<?php echo $frm->getElement('id');?><input type="hidden" name="old_landid" id="old_landid" dojoType="dijit.form.TextBox" value="<?php echo $this->datarow['house_id']; ?>" />
							</td>
						</tr>
						<tr>
							<td colspan="6" style="border-bottom:1px solid #ccc;"><strong style="color:#284db7;"><?php echo $tr->translate("AGENT_INFORMATION")?></strong></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("CO_NAME")?></td>
							<td><input id="staff_id" /> </td>
							<td><?php echo $tr->translate("COMISSION")?></td>
							<td><?php echo $frm->getElement('commission');?></td>
							<td><?php echo $tr->translate("paid_receivehouse")?></td>
							<td><?php echo $frm->getElement('paid_receivehouse')?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NOTE")?></td>
							<td><?php echo $frm->getElement('note')?></td>
							<td><?php echo $tr->translate("STATUS")?></td>
							<td><?php echo $frm->getElement('status_using')?></td>
							<td colspan="2"></td>
						</tr>
						<tr style="max-height: 300px;">
								<td colspan="6">
									<div  id="showrecord"></div>
									<input type="button" label="<?php echo $tr->translate('ADD_INSTALLMENT');?>" dojoType="dijit.form.Button" 
								 		iconClass="dijitIconEditProperty" onclick="addRow();" />
								</td>
						</tr>
					</table>
				</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
			<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
			<input type="submit" label="<?php echo $tr->translate("SAVECLOSE");?>" name='saveclose' value='saveclose' dojoType="dijit.form.Button" iconClass="dijitIconDelete"/>
			<input type="submit" label="<?php echo $tr->translate("SAVENEW")?>" name='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask"/>
			<input type="button" onclick="addPreviewLoan();displayNone();" label="<?php echo $tr->translate("PREVIEW")?>" name='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask" />
		</td>
	</tr>	
</table>
<div class="dijitHidden">
	<style>
	.print tr td{
		padding:5px 2px; 
	}
	</style>
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'កាលវិភាគត្រូវបង់ប្រាក់'" id="lbl_schedule" style="width: 25cm !important;">
		<div id="rpt_print" class="print" style="text-align: center;">
			<input style="text-align: center;" type="button" onclick="printSave('','');" label="<?php echo $tr->translate("បោះពុម្ភបង្កាន់ដៃ")?>" name='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask" />
			<div id="t_amountmoneytype" name="t_amountmoneytype">
			</div>
		</div>
	</div>
</div>
<div class="dijitHidden" style="width:25cm !important; height: 11cm ; padding: 0px; margin: 0px;">
	<div data-dojo-type="dijit.Dialog" style="width:24cm !important;" align="center" data-dojo-props="title:'<?php echo $tr->translate("PAYMENT_RECEIPT");?>'" id="terms" >
		<div id="divPrint" style="height: 13cm ; padding: 0px; margin: 0px;font-family:'Khmer OS Battambang';">
			<style>
				.fontbig{
					font-size: 15px;	
				}
				.fonttel{
					font-size: 18px;	
				}
				.pleft{
					width: 110px;	
				}

				.label{ font-size: 22px;}
				.value{ font:16px 'Khmer OS Battambang';border: 1px solid #000; height: 30px; padding: 0 2px;width: 100%;margin-right:5px; display: block;
						line-height: 30px;
					    text-align: center;
						}
				.values{ border: 1px solid #000; height: 30px; padding: 0 10px;display: block;
						line-height: 30px;}
				.h{}
				.print tr td{
					padding:2px 2px; 
				}
			   .khmerbold{font:14px 'Khmer OS Battambang';}
			   .khmer{font:14px 'Khmer OS Battambang';}
			   .one{white-space:nowrap;}
			   .h{ margin-top: -10px;}
			</style>	
			<table style="width:21cm !important; white-space: nowrap;font-size:14px;  padding:-5px 10px 0px 5px;margin-top: -10px;" class="print" cellspacing="0"  cellpadding="0" >
				<tr>
					<td colspan="6">
						<table width="100%" style="font-family:'Khmer MEF2';white-space:nowrap;">
							<tr>
								<td width="25%">
									<img style="width:100%;height:61px;" src="<?php echo $this->baseUrl().'/images/bppt_logo.png'?>">
								</td>					
								<td width="50%" style="font:18px 'Kh Muol';" valign="top" align="center"><u><strong style=" font-family: Arial Black;font-family:'Khmer MEF2';">បង្កាន់ដៃទទួលប្រាក់</strong></u>
									<div style="line-height:35px;"><strong style="font-size: 18px;font-weight:bold">OFFICIAL RECEIPT</strong></div>
								</td>
								<td width="25%">
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<table style="width:22cm !important;white-space: nowrap;margin-top: -30px;font-family:'Khmer OS Battambang';font-size: 16px;" class="print" cellspacing="3px"  cellpadding="0">
				<tr>
					<td width="10%" ></td>
					<td width="30%" ></td>
					<td width="15%" ></td>
					<td width="17%" ></td>
					<td width="10%" ></td>
					<td width="18%" ></td>
				</tr>
				<tr style="white-space: nowrap;">
				    <td colspan="5"></td>
					<td align="right"><strong><label id="lb_receipt" ></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
				    <td>លេខកូដលក់</td>
				    <td><strong><label id="lb_student_id" class="value">3</label></strong></td>
				  
					<td>&nbsp;&nbsp;&nbsp;តម្លៃលក់</td>
                    <td colspan="3" ><strong><label id="lb_price" class="value"></label></strong></td>
				</tr>
				
				<tr style="white-space: nowrap;">
				    <td>ឈ្មោះ​អតិថិជន </td>
				    <td><strong><label id="lb_customer" class="value"></label></strong></td>
					<td>​&nbsp;&nbsp;&nbsp;បញ្ចុះតម្លៃ</td>
				    <td><strong><label id="lb_discount" class="value"></label></strong></td>
					<td>&nbsp;&nbsp;តម្លៃផ្សេងៗ</td>
				    <td><strong><label id="lb_otherfee" class="value"></label></strong></td>
                </tr>
				<tr style="white-space: nowrap;">
					<td>លេខផ្ទះ</td>
                    <td><strong><label id="lb_hourseno" class="value"></label></strong></td>
				    <td>&nbsp;&nbsp;&nbsp;ប្រាក់ត្រូវបង់</td>
                    <td colspan="3"><strong><label id="lb_amount" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td width="10%">ប្រភេទបង់</td>
				    <td width="40%"><strong><label id="lb_paymentid" class="value"></label></strong></td>
					<td>&nbsp;&nbsp;&nbsp;ប្រាក់បានបង់</td>
				    <td colspan="3"><strong><label id="lb_paid" class="value" style="font-weight: bold; font-family:Arial;"></label></strong></td>
				</tr>
				<tr>
					<td>សែក</td>
					<td><strong><label id="lb_moneynote" class="value"></label></strong></td>
					<td>&nbsp;&nbsp;&nbsp;ប្រាក់នៅសល់</td>
					<td colspan="3"><strong><label id="lb_balance" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td>សម្គាល់</td>
				    <td><strong style="white-space: nowrap;"><label style="white-space: nowrap;" id="lb_noted" class="value"></label></strong></td>
					<td>&nbsp;&nbsp;&nbsp;ថ្ងៃលក់</td>
				    <td colspan="3"><strong><label id="lb_buydate" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;" height="60px;">
					<td colspan="6">
						<table width="100%" border="0" style="font-size:14px;line-height: 18px;">
							<tr>
								<td width="30%">
									&nbsp;
								</td>
								<td align="center" width="40%">
									ស្នាមមេដៃអ្នកប្រគល់
								</td>
								<td align="center" width="30%">
									ស្នាមមេដៃអ្នកទទួល
								</td>
							</tr>
							<tr>
								<td colspan="3">
									&nbsp;
								</td>
							</tr>
							<tr>
								<td colspan="3">
									&nbsp;
								</td>
							</tr>
							<tr>
								<td width="30%">
									&nbsp;
								</td>
								<td align="center" width="40%">
									<strong><label id="lbl_customer" ></label></strong>
								</td>
								<td align="center" width="30%">
									<strong>
										<?php 
										   $session_user=new Zend_Session_Namespace('auth');
										   $last_name=$session_user->last_name;
										   $username = $session_user->first_name;
										   echo $last_name." ".$username;
										?>
									</strong>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr style="line-height: 20px;font-size: 11px;">
					<td valign="top" >
						<span style="text-decoration:underline;font-size: 14px;">សំគាល់ ៖</span>
					</td>
					<td colspan="5">
						<span style="font-size: 13px;"><?php echo $this->data['comment'];?></span><br />
						<span style="white-space: pre-line;font-size: 13px;"><?php echo $this->data['comment1'];?></span><br />
					</td>
				</tr>
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="6" style="border-top: 2px solid rgba(255, 235, 59, 0.88)">
					</td>
				</tr>
				<tr style="line-height: 15px;">
					<td colspan="6" >
						<table width="100%" style="font-family: 'Khmer OS Battambang'; font-size:13px;line-height: 15px;margin-top: -5px;margin-bottom:15px;white-space:nowrap;"> 
							<tr>
								<td width="22%">
									<img style="width:70%;height: 25px;" src="<?php echo $this->baseUrl().'/images/bppt_letter.png'?>">
								</td>
								<td width="40%">
									<span style=""><?php echo $this->data['website'];?></span>
								</td>
								<td width="40%" align="right">
									<span style="font-family: 'Khmer OS Battambang'; "><?php echo $this->data['email_client'];?></span>
								</td>
							</tr>
							<tr style="white-space:nowrap;">
								<td colspan="2">
									<?php echo $this->data['footer_branch'];?>
								</td>
								<td width="40%" align="right">
									<span style=""><?php echo $this->data['tel-client'];?> </span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="6" style="border-top:2px dashed #000;" >
						
					</td>
				</tr>
			</table>
		</div>
		<table>
			<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
			<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
				type="button" onclick="doPrint();">បោះពុម្ភ/Print</button>
		</table>
		<div id="divPrint1" style="width: 21cm !important; height: 13cm ; padding: 0px; margin: 0px;">
			<table width="100%" style="white-space: nowrap;font-size:14px;  padding:15px 10px 0px 5px;margin-top: 15px;" class="print" cellspacing="0"  cellpadding="0" >
				<tr>
					<td colspan="6">
						<table width="100%" style="font-family:'Khmer MEF2';white-space:nowrap;">
							<tr>
								<td width="25%">
									<img style="width:100%;height:61px;" src="<?php echo $this->baseUrl().'/images/bppt_logo.png'?>">
								</td>					
								<td width="50%" style="font:18px 'Kh Muol';" valign="top" align="center"><u><strong style=" font-family: Arial Black;font-family:'Khmer MEF2';">បង្កាន់ដៃទទួលប្រាក់</strong></u>
									<div style="line-height:35px;"><strong style="font-size: 18px;">OFFICIAL RECEIPT</strong></div>
								</td>
								<td width="25%">
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<table width="100%" style="white-space: nowrap;font-size:16px;margin-top:-30px;font-family: 'Khmer OS Battambang';" class="print" cellspacing="3px"  cellpadding="0">
				<tr>
					<td width="10%" ></td>
					<td width="30%" ></td>
					<td width="15%" ></td>
					<td width="17%" ></td>
					<td width="10%" ></td>
					<td width="18%" ></td>
				</tr>
				
				<tr style="white-space: nowrap;">
				    <td colspan="5"></td>
					<td align="right"><strong><label id="lb_receipt1" ></label></strong></td>
				</tr>
				
				<tr style="white-space: nowrap;">
				    <td   >លេខកូដលក់</td>
				    <td  ><strong><label id="lb_student_id1" class="value">3</label></strong></td>
				  
					<td   >&nbsp;&nbsp;&nbsp;តម្លៃលក់</td>
                    <td colspan="3" ><strong><label id="lb_price1" class="value"></label></strong></td>
				</tr>
				
				<tr style="white-space: nowrap;">
				
				    <td  >ឈ្មោះ​អតិថិជន </td>
				    <td ><strong><label id="lb_customer1" class="value"></label></strong></td>
					
					<td  >​&nbsp;&nbsp;&nbsp;បញ្ចុះតម្លៃ</td>
				    <td><strong><label id="lb_discount1" class="value"></label></strong></td>
				    
					<td  >&nbsp;&nbsp;តម្លៃផ្សេងៗ</td>
				    <td><strong><label id="lb_otherfee1" class="value"></label></strong></td>
                    
                </tr>
				<tr style="white-space: nowrap;">
				
					<td  >លេខផ្ទះ</td>
                    <td><strong><label id="lb_hourseno1" class="value"></label></strong></td>
					
					
				    <td  >&nbsp;&nbsp;&nbsp;ប្រាក់ត្រូវបង់</td>
                    <td colspan="3"><strong><label id="lb_amount1" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
				
					<td   width="10%">ប្រភេទបង់</td>
				    <td width="40%"><strong><label id="lb_paymentid1" class="value"></label></strong></td>
					
					<td  >&nbsp;&nbsp;&nbsp;ប្រាក់បានបង់</td>
				    <td colspan="3"><strong><label id="lb_paid1" class="value" style="font-weight: bold; font-family:Arial;"></label></strong></td>
				</tr>

				<tr>
					<td  >សែក</td>
					<td ><strong><label id="lb_moneynote1" class="value"></label></strong></td>
					
					
					<td  >&nbsp;&nbsp;&nbsp;ប្រាក់នៅសល់</td>
					<td colspan="3"><strong><label id="lb_balance1" class="value"></label></strong></td>
					
				</tr>
				<tr style="white-space: nowrap;">
				
					<td  >សម្គាល់</td>
				    <td ><strong style="white-space: nowrap;"><label style="white-space: nowrap;" id="lb_noted1" class="value"></label></strong></td>
					
					<td  >&nbsp;&nbsp;&nbsp;ថ្ងៃលក់</td>
				    <td colspan="3"><strong><label id="lb_buydate1" class="value"></label></strong></td>
				</tr>
				
				
				<tr style="white-space: nowrap;" height="60px;">
					<td colspan="6">
						<table width="100%" border="0" style="font-size:14px;line-height: 18px;">
							<tr>
								<td width="30%">
									&nbsp;
								</td>
								
								<td align="center" width="40%">
									ស្នាមមេដៃអ្នកប្រគល់
								</td>
									
								<td align="center" width="30%">
									ស្នាមមេដៃអ្នកទទួល
								</td>
							</tr>
							<tr>
								<td colspan="3">
									&nbsp;
								</td>
							</tr>
							<tr>
								<td colspan="3">
									&nbsp;
								</td>
							</tr>
							<tr>
								<td width="30%">
									&nbsp;
								</td>
								
								<td align="center" width="40%">
									<strong><label id="lbl_customer1"></label></strong>
								</td>
									
								<td align="center" width="30%">
									<strong>
										<?php 
										   $session_user=new Zend_Session_Namespace('auth');
										   $last_name=$session_user->last_name;
										   $username = $session_user->first_name;
										   echo $last_name." ".$username;
										?>
									</strong>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				
				<tr style="line-height: 20px;font-size: 11px;">
					<td valign="top" >
						<span style="text-decoration:underline;font-size: 14px;">សំគាល់ ៖</span>
					</td>
					<td colspan="5">
						<span style="font-size: 13px;"><?php echo $this->data['comment'];?></span><br />
						<span style="white-space: pre-line;font-size: 13px;"><?php echo $this->data['comment1'];?></span><br />
					</td>
				</tr>
				
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="6" style="border-top: 2px solid rgba(255, 235, 59, 0.88)">
						
					</td>
				</tr>
				
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="6" >
						<table width="100%" style="font-family: 'Khmer OS Battambang'; font-size:13px;line-height: 15px;margin-top: -5px;margin-bottom:15px;white-space:nowrap;"> 
							<tr>
								<td width="22%">
									<img style="width:70%;height: 25px;" src="<?php echo $this->baseUrl().'/images/bppt_letter.png'?>">
								</td>
								<td width="40%">
									<span style=""><?php echo $this->data['website'];?></span>
								</td>
								<td width="40%" align="right">
									<span style="font-family: 'Khmer OS Battambang';"><?php echo $this->data['email_client'];?></span>
								</td>
							</tr>
							<tr style="white-space:nowrap;">
								<td colspan="2">
									<?php echo $this->data['footer_branch'];?>
								</td>
								<td width="40%" align="right">
									<span style=""><?php echo $this->data['tel-client'];?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div>
	</div>
</div>
</form>
<script type="text/javascript">	

dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.Textarea");	
var staff_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->co_name));?> );
new dijit.form.FilteringSelect({
	store: staff_store,
	autoComplete: true,                        
    id: "staff_id",
    name: "staff_id",  
   // tabindex: "17",    
    class: 'fullside',  
    required:false,
    placeHolder:"Selected Agent", 
    onChange: function() {        
    	branch_id = dijit.byId('branch_id').get('value');
    	staff_id = dijit.byId('staff_id').get('value');
    	if(branch_id==0){
    		if(staff_id==-1){
    			alert('Please select branch');
    			dijit.byId('branch_id').focus();
    			return false;
        	}
    	}else{
		    if(staff_id==-1){
		    	dijit.byId('branch_id_pop').attr('value',branch_id);
		   		dijit.byId("popup_staff").show();
		    }
    	}
    } 
}, "staff_id");
function displayNone(){
	//alert(1);
	document.getElementById('divPrint1').style.display="none";
	//document.getElementById('id_stu').style.display="none";
	
}

function checkScheduleOption(){
	dijit.byId('first_payment').set("readOnly",false);
	dijit.byId('period').set("readOnly",false);
	dijit.byId('interest_rate').set("readOnly",false);
	dijit.byId('release_date').set("readOnly",false);
	dijit.byId('date_line').set("readOnly",true);
	method_id = dijit.byId('schedule_opt').get('value');

	amount_principal = dijit.byId('balance').get('value');	
	debt_amount = dijit.byId('period').get('value')*12;
	if(method_id==3 || method_id==6){
		debt_amount = dijit.byId('period').get('value');
	}
	dojo.byId('lbl_period').innerHTML="<?php echo $tr->translate("TERM_BORROW")?>";
	dojo.byId('lbl_year').innerHTML="<?php echo $tr->translate("YEAR")?>";

	dojo.query("#table_row").append('');
	$('#identity').val('');
	dojo.query("#showrecord").append('');
	title=0;
	no=0;
	
	if(method_id==4){
		calCulateFixedPeriod();	
		}else {
			dijit.byId('fixed_payment').attr('value',0);
			dijit.byId('fixed_payment').set("readOnly",true);
		if(method_id==1){//booking
			dijit.byId('date_line').attr('value','<?php echo date("Y-m-d");?>');
			dijit.byId('release_date').set("readOnly",true);
			dijit.byId('first_payment').set("readOnly",true);
			dijit.byId('date_line').set("readOnly",false);
			dijit.byId('period').set("readOnly",true);
			dijit.byId('period').attr("value",0);
			dijit.byId('interest_rate').attr("value",0);
			dijit.byId('interest_rate').set("readOnly",true);
		}else if(method_id==2){//payoff
			dijit.byId('release_date').set("readOnly",true);
			dijit.byId('first_payment').set("readOnly",true);
			dijit.byId('interest_rate').set("readOnly",true);
			dijit.byId('interest_rate').attr("value",0);
			dijit.byId('period').set("readOnly",true);
			amount_principal = dijit.byId("sold_price").get("value");
			dijit.byId('deposit').attr("value",amount_principal);
			dijit.byId('first_payment').attr("value",'<?php echo date("Y-m-d");?>');
			dijit.byId('date_line').attr("value",'<?php echo date("Y-m-d");?>');
		}else if(method_id==3){//times
			dojo.byId('lbl_period').innerHTML="<?php echo $tr->translate("TOTAL_INSTALLMENT")?>";
			dojo.byId('lbl_release').innerHTML="<?php echo $tr->translate("START_DATE")?>";
			dojo.byId('lbl_year').innerHTML='<?php echo $tr->translate("MONTH")?>';
			if(isNaN(amount_principal)){amount_principal=0;}if(isNaN(debt_amount)){debt_amount=0;}
			amount_principal=dijit.byId('sold_price').get('value');
			total_collect = amount_principal/debt_amount;
			total_collect = total_collect.toFixed(0);
			if(debt_amount!=0){
				dijit.byId('fixed_payment').attr("value",total_collect);
			}
			dijit.byId('first_payment').attr("value",'<?php echo date("Y-m-d");?>');
			if(dijit.byId('interest_rate').get('value')==0){
				dijit.byId('interest_rate').attr("value",0);}
			dijit.byId('interest_rate').set("readOnly",false);
			
		}else if(method_id==5){//times
			dijit.byId('release_date').set("readOnly",true);
			dijit.byId('first_payment').set("readOnly",true);
			if(dijit.byId('interest_rate').get('value')==0 ){
				dijit.byId('interest_rate').attr("value",0);
			}
			dijit.byId('interest_rate').set("readOnly",true);
			dijit.byId('period').set("readOnly",true);
		}
		else if(method_id==6){//times			
			if(dijit.byId('period').get('value')==12){
				dijit.byId('period').attr('value',12);
			}
			$('#identity').val('');
			dijit.byId('first_payment').attr("value",'<?php echo date("Y-m-d");?>');
			dojo.byId('lbl_period').innerHTML="<?php echo $tr->translate("TOTAL_INSTALLMENT")?>";
			dojo.byId('lbl_year').innerHTML='<?php echo $tr->translate("MONTH")?>';
			dojo.byId('lbl_release').innerHTML="<?php echo $tr->translate("START_DATE")?>";
			if(isNaN(amount_principal)){amount_principal=0;}if(isNaN(debt_amount)){debt_amount=0;}
			
			total_collect = amount_principal/debt_amount;
			total_collect = total_collect.toFixed(2);
			if(isNaN(total_collect)){
				total_collect=0;
			}
			dijit.byId('fixed_payment').attr("value",total_collect);
			if(dijit.byId('interest_rate').get('value')==0){
			dijit.byId('interest_rate').attr("value",0);}
			dijit.byId('interest_rate').set("readOnly",false);
		}
	}
}
function calCulateFixedPeriod(){
	var total_paid_install = dijit.byId('total_installamount').get('value');
	if(total_paid_install == 0){
		amount_principal = dijit.byId('sold_price').get('value');
	}else{
		amount_principal = dijit.byId('sold_price').get('value')-dijit.byId('total_installamount').get('value');
	}	
	
	dijit.byId('fixed_payment').set('readOnly',false);
	dojo.byId('lbl_payment').innerHTML="<?php echo $tr->translate("AMOUNT_GRAICE_PARIOD")?>";
	debt_term=30;
	collect_term = 1;
	collect_amount = 1;
	collect_term=30;
	debt_amount = dijit.byId('period').get('value')*12;
	
	term = (debt_term*debt_amount)/(collect_term*collect_amount);
	interest_rate=dijit.byId('interest_rate').get('value')/12/(100);//(100/30day)
	if(interest_rate==0){
		amount_payment = parseFloat(amount_principal/debt_amount);
		amount_payment = amount_payment.toFixed(0);
		if(amount_payment=='Infinity' || amount_payment=='NaN'){amount_payment=0;}
	}else{
		top_pow = Math.pow((1+interest_rate),term);
		bellow = Math.pow((1+interest_rate),(term))-1;
		amount_payment = (amount_principal*interest_rate*top_pow)/(bellow);
		
		amount_payment = amount_payment.toFixed(0);
		if(isNaN(amount_payment)){amount_payment=0;
		}
	}	
	dijit.byId('fixed_payment').attr('value',amount_payment);
	dijit.byId('for_installamount').attr('value',amount_principal);
}
function calculateDiscount(){
	total_sold = dijit.byId('total_sold').get('value');
	discount = dijit.byId('discount').get('value');
	discount_percent = dijit.byId('discount_percent').get('value');
	other_fee = dijit.byId('other_fee').get('value');
	if(isNaN(other_fee)){
		other_fee=0;
	}if(isNaN(discount)){
		discount=0;
	}
	if(isNaN(discount_percent)){
		discount_percent=0;
	}
	discount_percent = total_sold*discount_percent/100;
	total_sold = total_sold-discount_percent-discount+other_fee;
	dijit.byId('sold_price').attr('value',total_sold);
	Balance();
}
function Balance(){
	price = dijit.byId('sold_price').get('value');
	deposit =dijit.byId('deposit').get('value');
	if(isNaN(deposit)){
		deposit=0;
	}
	if(deposit>price){
		alert("Deposit can not biger than price ");
		dijit.byId('deposit').focus();
		dijit.byId('deposit').attr('value',price)
		dijit.byId('balance').attr('value',0)
	}else{ 
		schedule_opt = dijit.byId('schedule_opt').get('value');
		if(schedule_opt==2){
			dijit.byId('balance').attr('value',0);
		}else{
			if(schedule_opt==3){
				dijit.byId('for_installamount').attr('value',price-deposit);
			}
			dijit.byId('balance').attr('value',price-deposit);
		}
		checkScheduleOption();
	}
}
function filterClient(){
	branch_id = dijit.byId('branch_id').get('value');
	dijit.byId('client_branch_id').attr('value',branch_id); // set branch id to popup client
	
	getAllPropertyBranch(branch_id);
	//getLoanByBranch('');
	//getReceiptByBranch('');
	oldbranch_id = '<?php echo $this->datarow['branch_id'];?>';
	if(branch_id==oldbranch_id){
	}else{
		getLoanByBranch();
	}
	getAllClientByBranch(branch_id);
	getAllClientNumberByBranch(branch_id);
}
house_id = '<?php echo $this->datarow['house_id'];?>';
var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
function getAllPropertyBranch(branch_id){
	dojo.xhrPost({
		url:url_getland,	
		content:{ 
		    'branch_id':branch_id,
		    'action':1
		},		    
		handleAs:"json",
		load: function(data) {
			property_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('land_code').set('store', property_store);
		   // alert(house_id);
		    dijit.byId('land_code').attr('value',house_id);
		},
		error: function(err) {
		}
	});
} 
customer_id = '<?php echo $this->datarow['client_id'];?>';
var url_getclient = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientbybranch')); ?>';
function getAllClientByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclient,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('member').set('store', client_store);
		    dijit.byId('member').attr("value",customer_id)	 
		},
		error: function(err) {
		}
	});
}
var url_getclientnum = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientnumberbybranch')); ?>';
function getAllClientNumberByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclientnum,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_number_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('customer_code').set('store', client_number_store);
		    dijit.byId('customer_code').set('store', client_number_store);
		},
		error: function(err) {
		}
	});
}
var url_getloan = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getloannumber')); ?>';
function getLoanByBranch(condition){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_getloan,	
		content:{ 
		    'branch_id':branch_id,
		    'is_group':0
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('sale_code').attr('value',data);
			
			if(condition==1){
				getReceiptByBranch(data);
			}
			
		},
		error: function(err) {
			//alert(err);
		}
	});
}

var url_getreceipt = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'get-receipt-number')); ?>';
function getReceiptByBranch(new_sale_id){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_getreceipt,	
		content:{ 
		    'branch_id':branch_id,
		    'is_group':0
		},		    
		handleAs:"json",
		load: function(data) {
			//dijit.byId('receipt').attr('value',data);
			data = dijit.byId('receipt').get('value');
			if(new_sale_id!=''){
				printSave(new_sale_id,data);
			}
		},
		error: function(err) {
			//alert(err);
		}
	});
}
    function calCulatorBalance(){
    	price = dijit.byId('land_price').get('value');
    	deposit =dijit.byId('deposit').get('value');
    	if(isNaN(deposit)){
    		deposit=0;
    	}
    	if(deposit>price){
    		alert("Deposit can not biger than price ");
    		dijit.byId('deposit').focus();
    		dijit.byId('deposit').attr('value',price)
    	}
        dijit.byId('balance').attr('value',price-deposit);
        checkScheduleOption();
    }
    
    function checkValidateDate(){
		return true;
     }
    function setDefaultPaymentAmount(){
    	amount_principal = dijit.byId('land_price').get('value');
    	debt_term = dijit.byId('pay_every').get('value');
    	debt_amount = dijit.byId('period').get('value')*12;
    	if(debt_term==1){
    		debt_term=1;
    	}else if(debt_term==2){
    		debt_term=7;
    	}
    	else{
    		debt_term=30;
    	}
    	//collect_term = dijit.byId('collect_termtype').get('value');
		collect_amount = 1;
		if(collect_term==1){
			collect_term=1;
    	}else if(collect_term==2){
    		collect_term=7;
    	}
    	else{
    		collect_term=30;
    	}
		
    	term = (debt_term*debt_amount)/(collect_term*collect_amount);

		interest_rate=dijit.byId('interest_rate').get('value')/100;

		top_pow = Math.pow((1+interest_rate),term);
		bellow = Math.pow((1+interest_rate),(term))-1;
		
		amount_payment = (amount_principal*interest_rate*top_pow)/(bellow);
		}
	function hideDialog() {		
		dijit.byId("recript_dialog").hide();
		saveTrans(); 
	}
	function doPrint() {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML + dojo.byId('divPrint1').innerHTML;;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    printSubmit();
		hideDialog();
		
	}
	function printSubmit(){
		$('#frm_add_tran').submit();
	}
</script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");

var client_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->client_name));?> );
var client_number_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->client_code));?> );
var co_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->co_name));?> );
var property_store  = getDataStorefromJSON('id','name', null );

require(["dojo/ready"], function(ready){
	 ready(function(){
		setFirstPaymentAndDateLine(3,<?php echo $this->datarow['startcal_date'];?>,<?php echo $this->datarow['total_duration'];?>);
		checkScheduleOption();
		filterClient();
		<?php if($this->datarow['payment_id']==6 OR $this->datarow['payment_id']==4){?>
		 	initailize();
		 	initailizeinstallment();
		 <?php }?>
	  });
	 
	new dijit.form.FilteringSelect({
			store: property_store,//dojo.data.ObjectStore({objectStore: client_data}),
			autoComplete: true,
			required: false,		           
			name: "land_code",
			id: "land_code",
			searchAttr: "name",
			class: 'fullside',
			required:true,
			onChange: function() {
				land_code = dijit.byId('land_code').get('value');
				if(land_code==-1){
				}else{
					getlandinfo();
				}
		}
			}, "land_code");
	 
	new dijit.form.FilteringSelect({
	store: client_store,//dojo.data.ObjectStore({objectStore: client_data}),
	autoComplete: true,
	required: false,		           
	name: "member",
	id: "member",
	searchAttr: "name",
	required:true,
	class: 'fullside',
	onChange: function() {
		member = dijit.byId('member').get('value');
		if(member==-1){
			showPopupclient();
		}else{
			dijit.byId('customer_code').attr('value',member);
			getcustomerinfo(member);
		}
}
	}, "member");
	
	new dijit.form.FilteringSelect({
	store: client_number_store,//dojo.data.ObjectStore({objectStore: client_number}),
	autoComplete: true,
	           
	required: false,		           
	name: "customer_code",
	id: "customer_code",
	searchAttr: "name",
	class: 'fullside',
	onChange: function() {
		customer_code = dijit.byId('customer_code').get('value');
		if(customer_code==-1){
			showPopupclient();
		}else{
			dijit.byId('member').attr('value',customer_code);
		}
    }
	}, "customer_code");

	new dijit.form.FilteringSelect({
		store: co_store,//dojo.data.ObjectStore({objectStore: client_number}),
		autoComplete: true,            
		required: false,		           
		name: "co_id",
		id: "co_id",
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			co_id = dijit.byId('co_id').get('value');
			if(co_id==-1){
				popupcreditofficer();
			}else{
			}
	    }
		}, "co_id");
	 
	});
function initailize(){
	if(dijit.byId('schedule_opt').get('value')!=6){return false;}
	period = dijit.byId('period').get('value');
	payment_method = dijit.byId('schedule_opt').get('value');
	no=0;title=0;temp='';i=0; $('#identity').val('');
	dojo.byId("showrecord").innerHTML = '';
	tmp='<table id="table_row" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
	tmp+='<tr id="head-title" class="head-td" style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
	tmp+='</table>';
	dojo.query("#showrecord").append(tmp);
	<?php if(!empty($this->rs)){
		foreach($this->rs as  $row){
	?>
		if(payment_method==6){
			col++;no++;i++;
			template='';
			if(title!=1){    
				temp+='<th><?php echo $tr->translate("DEL");?></th>';
				temp+='<th><?php echo $tr->translate("NUM");?></th>';
				temp+='<th><?php echo $tr->translate("DATE_PAYMENT");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("PERCENT_PAID");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("OS_AMOUNT");?></th>';
				temp+='<th><?php echo $tr->translate("REMARK");?></th>';
				dojo.query("#head-title").append(temp);
				title=1;
			}
			prev_date = dijit.byId("first_payment").get('value');
			amount_date = 1;
			var a = new Date(prev_date);
				mm = a.getMonth()+amount_date+i-1;
			var dd = a.getDate();
			 if(dd<10){
				 dd = "0"+dd;
			}
			 if(mm<10){
				 mm = "0"+mm;
			}
			var y = a.getFullYear();
			var epx_date = y + '-'+ mm + '-'+dd ;
				template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
				template+='<td width="2%" align="center">'+no+'</td>';
				template+="<td><input class='fullside' type='text' constraints="+"{datePattern:'dd/MM/yyyy'}"+" dojoType='dijit.form.DateTextBox' value='"+epx_date+"' id='date_payment"+col+"' name='date_payment"+col+"' /></td>";
				template+='<td><input onkeyup="calCulateAmount('+col+')" class="fullside" type="text" required="true" dojoType="dijit.form.NumberTextBox" id="percent'+col+'" name="percent'+col+'" /></td>';			
				template+='<td><input readonly class="fullside" type="text" required="true" dojoType="dijit.form.NumberTextBox" id="total_payment'+col+'" name="total_payment'+col+'" /></td>';			
				template+='<td <input class="fullside" type="text"  name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ"/><label id="subsub"></label></td>';
			tmp='<tr class="hover" style="border-bottom:1px solid #ccc;" id="row'+col+'">';
			tmp+="</tr>";
			dojo.query("#table_row").append(tmp);
		
			if($("#identity").val()!="") {
				var identity = $("#identity").val();
				$("#identity").val(identity+','+col);
			} else {$("#identity").val(col);}
			dojo.html.set(dojo.byId("row"+col),template , {
			     parseContent: true,
			});
		}
		dijit.byId('total_payment'+col).attr('value',<?php echo $row['total_payment']?>);
		dijit.byId('date_payment'+col).attr('value','<?php echo $row['date_payment'];?>');
		dijit.byId('percent'+col).attr('value','<?php echo $row['percent']?>');
		dijit.byId('remark'+col).attr('value','<?php echo $row['note']?>');
		<?php } }?>
}
function initailizeinstallment(){
	if(dijit.byId('schedule_opt').get('value')!=4){return false;}
	period = dijit.byId('period').get('value');
	payment_method = dijit.byId('schedule_opt').get('value');
	no=0;title=0;temp='';i=0; $('#identity').val('');
	dojo.byId("showrecord").innerHTML = '';
	tmp='<table id="table_row" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
	tmp+='<tr id="head-title" class="head-td" style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
	tmp+='</table>';
	dojo.query("#showrecord").append(tmp);
	<?php if(!empty($this->rs)){
		foreach($this->rs as $key=> $row){
	?>
		//if(payment_method==6){
			col++;no++;i++;
			template='';
			if(title!=1){    
				temp+='<th><?php echo $tr->translate("DEL");?></th>';
				temp+='<th><?php echo $tr->translate("NUM");?></th>';
				temp+='<th><?php echo $tr->translate("DATE_PAYMENT");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("PERCENT_PAID");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("OS_AMOUNT");?></th>';
				temp+='<th><?php echo $tr->translate("REMARK");?></th>';
				dojo.query("#head-title").append(temp);
				title=1;
				first_amount = parseFloat(dijit.byId('deposit').get('value'))+parseFloat('<?php echo $row['total_payment']?>');
			}else{
				first_amount =parseFloat('<?php echo $row['total_payment']?>');
				}
			prev_date = dijit.byId("first_payment").get('value');
			amount_date = 1;
			var a = new Date(prev_date);
				mm = a.getMonth()+amount_date+i-1;
			var dd = a.getDate();
			 if(dd<10){
				 dd = "0"+dd;
			}
			 if(mm<10){
				 mm = "0"+mm;
			}
			var y = a.getFullYear();
			var epx_date = y + '-'+ mm + '-'+dd ;
				template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
				template+='<td width="2%" align="center">'+no+'</td>';
				template+="<td><input class='fullside' type='text' constraints="+"{datePattern:'dd/MM/yyyy'}"+" dojoType='dijit.form.DateTextBox' value='"+epx_date+"' id='date_payment"+col+"' name='date_payment"+col+"' /></td>";
				template+='<td><input onkeyup="calCulateAmount('+col+')" class="fullside" type="text" required="true" dojoType="dijit.form.NumberTextBox" id="percent'+col+'" name="percent'+col+'" /></td>';			
				template+='<td><input readonly class="fullside" type="text" required="true" dojoType="dijit.form.NumberTextBox" id="total_payment'+col+'" name="total_payment'+col+'" /></td>';			
				template+='<td <input class="fullside" type="text"  name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ"/><label id="subsub"></label></td>';
			tmp='<tr class="hover" style="border-bottom:1px solid #ccc;" id="row'+col+'">';
			tmp+="</tr>";
			dojo.query("#table_row").append(tmp);
		
			if($("#identity").val()!="") {
				var identity = $("#identity").val();
				$("#identity").val(identity+','+col);
			} else {$("#identity").val(col);}
			dojo.html.set(dojo.byId("row"+col),template , {
			     parseContent: true,
			});
		//}
		//alert('<?php //echo $row['total_payment']?>');
			
		dijit.byId('total_payment'+col).attr('value',<?php echo $row['total_payment']?>);
		dijit.byId('date_payment'+col).attr('value','<?php echo $row['date_payment'];?>');
		dijit.byId('percent'+col).attr('value','<?php echo $row['percent']?>');
		dijit.byId('remark'+col).attr('value','<?php echo $row['note']?>');
		<?php } }?>
		calCulateSchedulePayment();
}
</script>
<script type="text/javascript">

function showPopupclient(){
	dijit.byId("popup_client").show();
}
var url_getcustomer = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclient')); ?>';
function getcustomerinfo(client_id){
	dojo.xhrPost({
		url:url_getcustomer,	
		content:{ 
		    'client_id':client_id
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('joint_with').attr('value',data.hname_kh);
		},
		error: function(err) {
			alert(err);
		}
	});
}
var url_getlandinfodetail = '<?php echo $this->url(array('module'=>'group','controller'=>'land','action'=>'getlandinfo')); ?>';
function getlandinfo(){
	dijit.byId('land_price').attr('value',0);
	dijit.byId('house_price').attr('value',0);
	dijit.byId('total_sold').attr('value',0);
	dijit.byId('sold_price').attr('value',0);
	dojo.xhrPost({
		url:url_getlandinfodetail,	
		content:{ 
		    'land_id':dijit.byId('land_code').get('value')
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('land_price').attr('value',data.land_price);
			dijit.byId('house_price').attr('value',data.house_price);
			dijit.byId('total_sold').attr('value',data.price);
			dijit.byId('sold_price').attr('value',data.price);
			dojo.byId('land_information').innerHTML ="លេខសម្គាល់ "+data.land_code+", លេខផ្ទះ/ឡូតិ៏  "+data.land_address+", លេខផ្លូវ  "+data.street+", ប្រភេទ  "+data.property_type+", ទំហំ "+data.land_size+" ម៉ែត្រការ៉េ, បណ្តោយ "+data.height+" ម៉ែត្រ, ទទឹង  "+data.width+" ម៉ែត្រ";
			dijit.byId('propertype').attr('value',data.house_type);
			
			old_house =<?php echo $this->datarow['house_id'];?>;
			if(old_house==dijit.byId('land_code').get('value')){
				dijit.byId('sold_price').attr('value',<?php echo $this->amount_price;?>);
			}else{
				dijit.byId('sold_price').attr('value',data.price);
			}
		},
		error: function(err) {
			alert(err);
		}
	});
}
function clearTextBox(){
	dijit.byId('member').set('value','');
	dijit.byId('total_amount').set('value',0);
}
function getClientInfo(type){
	if(type==1){
		customer_code= dijit.byId('customer_code').get('value');
		dijit.byId('member').attr('value',customer_code);
	}else{
		customer_code= dijit.byId('member').get('value');
		dijit.byId('customer_code').attr('value',customer_code);
	}
}
var url_submitdistrict = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'add-newdistrict')); ?>';
function addNewDistrict(){
		dojo.xhrPost({
	    url: url_submitdistrict,	
		form: dojo.byId("form_district"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_district').reset(); 
			dijit.byId('frm_district').hide();
		},
		error: function(err) {
			alert("Your message could not be sent, please try again!.");
		}
	});
}
var url_submitcommune = '<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'add-newcommune')); ?>';
function addNewCommune(){
		dojo.xhrPost({
	    url: url_submitcommune,	
		form: dojo.byId("form_commune"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_commune').reset(); 
			dijit.byId('frm_commune').hide();
		},
		error: function(err) {
			alert("Your message could not be sent, please try again!.");
		}
	});
}
var url_submitvillage = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'add-newvillage')); ?>';
function addNewVillage(){
		dojo.xhrPost({
	    url: url_submitvillage,	
		form: dojo.byId("form_village"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_village').reset(); 
			dijit.byId('frm_village').hide();
		},
		error: function(err) {
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
</script>

<script>
function checkFirstRecord(){
	var rowId = $('#identity').val();
	if(rowId!=''){
		var rowIDArray = rowId.split(',');
		for(var n = 0; n < rowIDArray.length; n++) {
			total_amountpayment = (dijit.byId('total_payment'+rowIDArray[n]).get('value'));
			if(n==0){ 
				paid = dijit.byId('deposit').get('value');
				if(total_amountpayment<paid){alert("សូមបញ្ជូលប្រាក់ត្រូវបង់ ធំជាងប្រាក់ដែលទទួលបាន! ");dijit.byId('percent'+rowIDArray[n]).focus();return false;}
			}
		}
  }
}
col=0;no=0;title=0;temp='';
function addRow(){
	result = checkFirstRecord();
	if(result==false){return false;}
	payment_method = dijit.byId('schedule_opt').get('value');
	if(payment_method==4){addInstallment();}
	if(payment_method!=6){return false;}
	period = dijit.byId('period').get('value');
	//deposit = dijit.byId("deposit").get("value");
	//if(isNaN(deposit)){
		//deposit = 0;
	//}
	//if(deposit>0){ period = period-1;}
	if(period==0){alert("សូមបញ្ជូលចំនួនដង ត្រូវបង់!");dijit.byId('period').focus();return false;}

	no=0;title=0;temp='';$('#identity').val('');
	dojo.byId("showrecord").innerHTML = '';
	tmp='<table id="table_row" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
	tmp+='<tr id="head-title" class="head-td" style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
	tmp+='</table>';
	dojo.query("#showrecord").append(tmp);
	
	for(i=1;i<=period;i++){
		if(payment_method==6){
			col++;no++;
			template='';
			if(title!=1){    
				temp+='<th><?php echo $tr->translate("DEL");?></th>';
				temp+='<th><?php echo $tr->translate("NUM");?></th>';
				temp+='<th><?php echo $tr->translate("DATE_PAYMENT");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("PERCENT_PAID");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("OS_AMOUNT");?></th>';
				temp+='<th><?php echo $tr->translate("NOTE");?></th>';
				dojo.query("#head-title").append(temp);
				title=1;
				epx_date = '<?php echo date('Y-m-d');?>';
			}else{
				indexs = col-1;
				epx_date = dijit.byId("date_payment"+indexs).get("value");
				var a = new Date(epx_date);
				mm = a.getMonth()+2;
				var dd = a.getDate();
				 if(dd<10){
					 dd = "0"+dd;
				}
				if(mm<10){
					 mm = "0"+mm;
				}
				var y = a.getFullYear();
				var epx_date = y+'-'+ mm + '-'+dd ;
			}
				template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
				template+='<td width="2%" align="center">'+no+'</td>';
				template+="<td><input class='fullside' type='text' constraints="+"{datePattern:'dd/MM/yyyy'}"+" dojoType='dijit.form.DateTextBox' value='"+epx_date+"' id='date_payment"+col+"' name='date_payment"+col+"' /></td>";
				template+='<td><input type="text" onkeyup="calCulateAmount('+col+')" class="fullside" required="true" data-dojo-type="dijit.form.NumberTextBox"  id="percent'+col+'" name="percent'+col+'" /></td>';			
				template+='<td><input class="fullside" onkeyup="calCulateAmount('+col+',2)" type="text" required="true"  dojoType="dijit.form.NumberTextBox" id="total_payment'+col+'" name="total_payment'+col+'" /></td>';			
				template+='<td <input class="fullside" type="text"  name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ"/><label id="subsub"></label></td>';
			tmp='<tr class="hover" style="border-bottom:1px solid #ccc;" id="row'+col+'">';
			tmp+="</tr>";
			dojo.query("#table_row").append(tmp);
		
			if($("#identity").val()!="") {
				var identity = $("#identity").val();
				$("#identity").val(identity+','+col);
			} else {$("#identity").val(col);}
			dojo.html.set(dojo.byId("row"+col),template , {
			     parseContent: true,
			});
		}
	}
	dijit.byId("date_line").attr('value',epx_date);
}
function addInstallment(){
	result = checkFirstRecord();
	if(result==false){return false;}
	payment_method = dijit.byId('schedule_opt').get('value');
	
	period = dijit.byId('period').get('value')*12;
	if(period==0){alert("សូមបញ្ជូលចំនួនដង ត្រូវបង់!");dijit.byId('period').focus();return false;}
	temp='';

	result = checkFirstRecord();
	if(result==false){return false;}
	
		if(payment_method==4){
			col++;no++;
			template='';
			if(title!=1){    
				tmp='<table id="table_row" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
				tmp+='<tr id="head-title" class="head-td" style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
				tmp+='</table>';
				dojo.query("#showrecord").append(tmp);
				
				temp+='<th><?php echo $tr->translate("DEL");?></th>';
				temp+='<th><?php echo $tr->translate("NUM");?></th>';
				temp+='<th><?php echo $tr->translate("DATE_PAYMENT");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("PERCENT_PAID");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("OS_AMOUNT");?></th>';
				temp+='<th><?php echo $tr->translate("NOTE");?></th>';
				dojo.query("#head-title").append(temp);
				title=1;
				epx_date ='<?php echo date('Y-m-d');?>';
			}else{
				indexs = col-1;
				epx_date = dijit.byId("date_payment"+indexs).get("value");
				var a = new Date(epx_date);
				mm = a.getMonth()+2;
				var dd = a.getDate();
				 if(dd<10){
					 dd = "0"+dd;
				}
				if(mm<10){
					 mm = "0"+mm;
				}
				var y = a.getFullYear();
				var epx_date = y+'-'+ mm + '-'+dd ;

				mm_nextmonth = a.getMonth()+3;
				if(mm_nextmonth<10){
					mm_nextmonth = "0"+mm_nextmonth;
				}
				
				var start_date = y + '-'+ mm_nextmonth + '-'+dd ;
				dijit.byId("first_payment").attr('value',start_date);
			}
			    dijit.byId("release_date").attr('value',epx_date);
				template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
				template+='<td width="2%" align="center">'+no+'</td>';
				template+="<td><input class='fullside' type='text' constraints="+"{datePattern:'dd/MM/yyyy'}"+" dojoType='dijit.form.DateTextBox' value='"+epx_date+"' id='date_payment"+col+"' name='date_payment"+col+"' /></td>";
				template+='<td><input onkeyup="calCulateAmount('+col+')" class="fullside" type="text" required="true" data-dojo-type="dijit.form.NumberTextBox" id="percent'+col+'" name="percent'+col+'" /></td>';	//data-dojo-props='+'regExp:"[0-9]{1,2}"'+'		
				template+='<td><input class="fullside" type="text" onkeyup="calCulateAmount('+col+',2)" required="true"  dojoType="dijit.form.NumberTextBox" id="total_payment'+col+'" name="total_payment'+col+'" /></td>';			
				template+='<td <input class="fullside" type="text"  name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ"/><label id="subsub"></label></td>';
			tmp='<tr class="hover" style="border-bottom:1px solid #ccc;" id="row'+col+'">';
			tmp+="</tr>";
			dojo.query("#table_row").append(tmp);
		
			if($("#identity").val()!="") {
				var identity = $("#identity").val();
				$("#identity").val(identity+','+col);
			} else {$("#identity").val(col);}
			dojo.html.set(dojo.byId("row"+col),template , {
			     parseContent: true,
			});
		}
}
function initailize(){
	if(dijit.byId('schedule_opt').get('value')!=6){return false;}
	period = dijit.byId('period').get('value');
	payment_method = dijit.byId('schedule_opt').get('value');
	no=0;title=0;temp='';i=0; $('#identity').val('');
	dojo.byId("showrecord").innerHTML = '';
	tmp='<table id="table_row" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
	tmp+='<tr id="head-title" class="head-td" style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
	tmp+='</table>';
	dojo.query("#showrecord").append(tmp);
	<?php if(!empty($this->rs)){
		foreach($this->rs as  $row){
	?>
		if(payment_method==6){
			col++;no++;i++;
			template='';
			if(title!=1){    
				temp+='<th><?php echo $tr->translate("DEL");?></th>';
				temp+='<th><?php echo $tr->translate("NUM");?></th>';
				temp+='<th><?php echo $tr->translate("DATE_PAYMENT");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("PERCENT_PAID");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("OS_AMOUNT");?></th>';
				temp+='<th><?php echo $tr->translate("REMARK");?></th>';
				dojo.query("#head-title").append(temp);
				title=1;
			}
			prev_date = dijit.byId("first_payment").get('value');
			amount_date = 1;
			var a = new Date(prev_date);
				mm = a.getMonth()+amount_date+i-1;
			var dd = a.getDate();
			 if(dd<10){
				 dd = "0"+dd;
			}
			 if(mm<10){
				 mm = "0"+mm;
			}
			var y = a.getFullYear();
			var epx_date = y + '-'+ mm + '-'+dd ;
				template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
				template+='<td width="2%" align="center">'+no+'</td>';
				template+="<td><input class='fullside' type='text' constraints="+"{datePattern:'dd/MM/yyyy'}"+" dojoType='dijit.form.DateTextBox' value='"+epx_date+"' id='date_payment"+col+"' name='date_payment"+col+"' /></td>";
				template+='<td><input onkeyup="calCulateAmount('+col+')" class="fullside" type="text" required="true" dojoType="dijit.form.NumberTextBox" id="percent'+col+'" name="percent'+col+'" /></td>';			
				template+='<td><input class="fullside" onkeyup="calCulateAmount('+col+',2)" type="text" required="true" dojoType="dijit.form.NumberTextBox" id="total_payment'+col+'" name="total_payment'+col+'" /></td>';			
				template+='<td <input class="fullside" type="text"  name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ"/><label id="subsub"></label></td>';
			tmp='<tr class="hover" style="border-bottom:1px solid #ccc;" id="row'+col+'">';
			tmp+="</tr>";
			dojo.query("#table_row").append(tmp);
		
			if($("#identity").val()!="") {
				var identity = $("#identity").val();
				$("#identity").val(identity+','+col);
			} else {$("#identity").val(col);}
			dojo.html.set(dojo.byId("row"+col),template , {
			     parseContent: true,
			});
		}
		dijit.byId('total_payment'+col).attr('value',<?php echo $row['total_payment']?>);
		dijit.byId('date_payment'+col).attr('value','<?php echo $row['date_payment'];?>');
		dijit.byId('percent'+col).attr('value','<?php echo $row['percent']?>');
		dijit.byId('remark'+col).attr('value','<?php echo $row['note']?>');
		<?php } }?>
}
function initailizeinstallment(){
	
	if(dijit.byId('schedule_opt').get('value')!=4){return false;}
	period = dijit.byId('period').get('value');
	payment_method = dijit.byId('schedule_opt').get('value');
	no=0;title=0;temp='';i=0; $('#identity').val('');
	dojo.byId("showrecord").innerHTML = '';
	tmp='<table id="table_row" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
	tmp+='<tr id="head-title" class="head-td" style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
	tmp+='</table>';
	dojo.query("#showrecord").append(tmp);
	<?php if(!empty($this->rs)){
		foreach($this->rs as $key=> $row){
	?>
			col++;no++;i++;
			template='';
			if(title!=1){    
				temp+='<th><?php echo $tr->translate("DEL");?></th>';
				temp+='<th><?php echo $tr->translate("NUM");?></th>';
				temp+='<th><?php echo $tr->translate("DATE_PAYMENT");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("PERCENT_PAID");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("OS_AMOUNT");?></th>';
				temp+='<th><?php echo $tr->translate("REMARK");?></th>';
				dojo.query("#head-title").append(temp);
				title=1;
				first_amount = parseFloat(dijit.byId('deposit').get('value'))+parseFloat('<?php echo $row['total_payment']?>');
			}else{
				first_amount =parseFloat('<?php echo $row['total_payment']?>');
				}
			prev_date = dijit.byId("first_payment").get('value');
			amount_date = 1;
			var a = new Date(prev_date);
				mm = a.getMonth()+amount_date+i-1;
			var dd = a.getDate();
			 if(dd<10){
				 dd = "0"+dd;
			}
			 if(mm<10){
				 mm = "0"+mm;
			}
			var y = a.getFullYear();
			var epx_date = y + '-'+ mm + '-'+dd ;
				template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
				template+='<td width="2%" align="center">'+no+'</td>';
				template+="<td><input class='fullside' type='text' constraints="+"{datePattern:'dd/MM/yyyy'}"+" dojoType='dijit.form.DateTextBox' value='"+epx_date+"' id='date_payment"+col+"' name='date_payment"+col+"' /></td>";
				template+='<td><input onkeyup="calCulateAmount('+col+')" class="fullside" type="text" required="true" dojoType="dijit.form.NumberTextBox" id="percent'+col+'" name="percent'+col+'" /></td>';			
				template+='<td><input onkeyup="calCulateAmount('+col+',2)" class="fullside" type="text" required="true" dojoType="dijit.form.NumberTextBox" id="total_payment'+col+'" name="total_payment'+col+'" /></td>';			
				template+='<td <input class="fullside" type="text"  name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ"/><label id="subsub"></label></td>';
			tmp='<tr class="hover" style="border-bottom:1px solid #ccc;" id="row'+col+'">';
			tmp+="</tr>";
			dojo.query("#table_row").append(tmp);
		
			if($("#identity").val()!="") {
				var identity = $("#identity").val();
				$("#identity").val(identity+','+col);
			} else {$("#identity").val(col);}
			dojo.html.set(dojo.byId("row"+col),template , {
			     parseContent: true,
			});
		//}
		
		dijit.byId('total_payment'+col).attr('value',<?php echo $row['total_payment']?>);
		dijit.byId('date_payment'+col).attr('value','<?php echo $row['date_payment'];?>');
		dijit.byId('percent'+col).attr('value','<?php echo $row['percent']?>');
		dijit.byId('remark'+col).attr('value','<?php echo $row['note']?>');
		<?php } }?>
		calCulateSchedulePayment();
}
function calCulateAmount(index,revers=1){
	balance = dijit.byId('sold_price').get('value');
	if(revers==1){//% to value
	    percent = dijit.byId('percent'+index).get('value');
	    amount_payment = balance*percent/100;
	    dijit.byId('total_payment'+index).attr('value',amount_payment);
   }else{//value to %
	   amount_payment =  dijit.byId('total_payment'+index).get('value');
	   percent = amount_payment*100/balance;
	   dijit.byId('percent'+index).attr('value',percent);
     }
	calCulateSchedulePayment();
	 if(dijit.byId('percent'+index).get('value')>100){
		 alert("តម្លៃត្រូវបង់មិនអាចធំជាង ១០០ ភាគរយបានទេ !");
		 dijit.byId('percent'+index).focus();
     }
}
function calCulateSchedulePayment(){
	var total_amount=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	if(rowId!=''){
	for(var n = 0; n < rowIDArray.length; n++) {
			total_amountpayment = (dijit.byId('total_payment'+rowIDArray[n]).get('value'));
			if(n==0){ 
			}
			if(isNaN(total_amountpayment)){
				total_amountpayment = 0;
			}
			total_amount = total_amount+ total_amountpayment;
		}
	}
	dijit.byId('total_installamount').attr('value',total_amount);
	calCulateFixedPeriod();
}
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
	if(arrays.length==0){ dijit.byId('total_installamount').attr('value','');}
	calCulateSchedulePayment();
}

function setFirstPaymentAndDateLine(pay_term,date_release,amount_date){
	var a = new Date(date_release);
	mm = a.getMonth()+amount_date+1;
	 var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	 if(mm<10){
		 mm = "0"+mm;
	}
	var y = a.getFullYear()+1;

	var epx_date = y + '-'+ mm + '-'+dd ;
	calCulateEndDate();
	calCulateFirstPayment();
}
function calCulateEndDate(){
	amount_period = 1;
	if(dijit.byId("schedule_opt").get('value')==4){amount_period=12;}
	amount_date = dijit.byId('period').get('value')*amount_period;
	release_date = dijit.byId("first_payment").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
	}else{
		var a = new Date(release_date);
		month = a.getMonth()+amount_date;
		mm = month%12;
		year = parseInt(month/12);
		 var dd = a.getDate();
		 if(dd<10){
			 dd = "0"+dd;
		}
		 if(mm<10){
			 mm = "0"+mm;
		}
		var y = a.getFullYear()+year;
		var epx_date = y + '-'+ mm + '-'+dd ;
        payment_option = dijit.byId('schedule_opt').attr('value');
		if(payment_option==2){
			dijit.byId('date_line').attr('value','<?php echo date("Y-m-d");?>');
		}else{
			dijit.byId('date_line').attr('value',epx_date);	
		}
    }
}
function CalculateDate(){
	pay_term = 1;
	amount_date = dijit.byId('period').get('value')*12;
	release_date = dijit.byId("first_payment").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
	}else{
		setFirstPaymentAndDateLine(pay_term,release_date,amount_date);		
    }
}
function checkReleaseDate(){
	CalculateDate();
}
function getFirstPayment(){
	calCulateFirstPayment();
}
function calCulateFirstPayment(){
	pay_term = 1;
	amount_date = 1;
	method_id = dijit.byId('schedule_opt').get('value');
	addamount=1;
	if(method_id==3 || method_id==4 || schedule_opt==6){
		addamount=0;
	}
	release_date = dijit.byId("release_date").get('value');
	var a = new Date(release_date);
		mm = a.getMonth()+amount_date+addamount;
	var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	 if(mm<10){
		 mm = "0"+mm;
	}
	var y = a.getFullYear();
	var epx_date = y + '-'+ mm + '-'+dd ;
	dijit.byId('first_payment').attr('value',epx_date);
}

function printSave(new_stu_id,new_receipt_no){
	symbal=" $";
	if(new_stu_id=='' && new_receipt_no==''){
		getLoanByBranch(1);
	}else{
		dojo.byId("lb_student_id").innerHTML = new_stu_id;
		dojo.byId("lb_receipt").innerHTML = new_receipt_no;
		
		dojo.byId("lb_student_id1").innerHTML = new_stu_id;
		dojo.byId("lb_receipt1").innerHTML = new_receipt_no;
	}
	dijit.byId("lbl_schedule").hide();
	dojo.byId("lb_paymentid").innerHTML = dijit.byId("schedule_opt").attr('displayedValue');

	date_payment = dijit.byId("date_buy").get('value');
	var a = new Date(date_payment);
	mm = a.getMonth()+1;
	var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	month = returnMOnth(mm);
	var y = a.getFullYear();
	var date_payment = dd +'-'+month+'-'+y ;
	
	dojo.byId("lb_buydate").innerHTML = date_payment; //dijit.byId("date_buy").attr('displayedValue');
	dojo.byId("lb_hourseno").innerHTML = dijit.byId("land_code").attr('displayedValue')+dijit.byId("propertype").attr('displayedValue');
	dojo.byId("lb_price").innerHTML = "$ "+dojo.number.format(dijit.byId("total_sold").get('value'),{places:2});

	/*dis_percent = dijit.byId("discount_percent").get('value');
	if(isNaN(dis_percent)){dis_percent='';}else{dis_percent=dis_percent+" %+";}
	discount = dijit.byId("discount").get('value');
	if(isNaN(discount)){discount=' $ 0';}else{discount = "$ "+dojo.number.format(discount,{places:2});};
	*/
	total_sold = dijit.byId('total_sold').get('value');
	discount_percent = dijit.byId('discount_percent').get('value');
	if(isNaN(discount_percent)){
		discount_percent=0;
	}
	discount = dijit.byId('discount').get('value');
	if(isNaN(discount)){
		discount=0;
	}
	
	discount_percent = total_sold*discount_percent/100;
	total_discount = parseFloat(discount_percent)+parseFloat(discount);
	
	dojo.byId("lb_discount").innerHTML = symbal+" "+dojo.number.format(total_discount,2);
	//dojo.byId("lb_discount").innerHTML = dis_percent+discount;
	other_fee = dijit.byId("other_fee").get('value');
	if(isNaN(other_fee)){other_fee=0;}
	dojo.byId("lb_otherfee").innerHTML = "$ "+dojo.number.format(other_fee,{places:2});
	dojo.byId("lb_amount").innerHTML = "$ "+dojo.number.format(dijit.byId("sold_price").get('value'),{places:2});
	dojo.byId("lb_paid").innerHTML = "$ "+dojo.number.format(dijit.byId("deposit").get('value'),{places:2});
	
	balance = dijit.byId("balance").get('value');
	if(isNaN(balance)){balance=0;}
	dojo.byId("lb_balance").innerHTML = "$ "+dojo.number.format(balance,{places:2});
	
	dojo.byId("lb_noted").innerHTML =dijit.byId("note").get('value');
	
	dojo.byId("lb_paymentid1").innerHTML = dijit.byId("schedule_opt").attr('displayedValue');
	dojo.byId("lb_buydate1").innerHTML = date_payment;//dijit.byId("date_buy").attr('displayedValue');
	
	dojo.byId("lb_hourseno1").innerHTML = dijit.byId("land_code").attr('displayedValue')+dijit.byId("propertype").attr('displayedValue');
	dojo.byId("lb_price1").innerHTML = "$ "+dojo.number.format(dijit.byId("total_sold").get('value'),{places:2});
	dojo.byId("lb_discount1").innerHTML = symbal+" "+dojo.number.format(total_discount,2);//dis_percent+discount;//dijit.byId("discount").get('value');
	other_fee = dijit.byId("other_fee").get('value');
	if(isNaN(other_fee)){other_fee=0;}
	dojo.byId("lb_otherfee1").innerHTML = "$ "+dojo.number.format(other_fee,{places:2});
	dojo.byId("lb_amount1").innerHTML = "$ "+dojo.number.format(dijit.byId("sold_price").get('value'),{places:2});
	dojo.byId("lb_paid1").innerHTML = "$ "+dojo.number.format(dijit.byId("deposit").get('value'),{places:2});
	dojo.byId("lb_balance1").innerHTML = "$ "+dojo.number.format(balance,{places:2});
	dojo.byId("lb_noted1").innerHTML =dijit.byId("note").get('value');
	joint_with = dijit.byId("joint_with").attr('displayedValue');
	if(joint_with!=''){joint_with = "/"+joint_with}
	dojo.byId("lbl_customer1").innerHTML = dijit.byId("member").attr('displayedValue')+joint_with;
	dojo.byId("lb_customer1").innerHTML = dijit.byId("member").attr('displayedValue');
	dojo.byId("lb_customer").innerHTML = dijit.byId("member").attr('displayedValue');
	dojo.byId("lbl_customer").innerHTML = dijit.byId("member").attr('displayedValue')+joint_with;
	
	schedule_opt = dijit.byId("schedule_opt").get("value");
	if(schedule_opt==1){
		//EXPIRED_DATE
	}
	 dijit.byId("terms").show();	
}
var url_previewloan = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'addschedultest')); ?>';
function addPreviewLoan(){
	r=0;
	if(dijit.byId('frm_add_tran').validate()){
		client = dijit.byId('member').get('value');
		if (client=='' || client==-1){
			alert('Please Select Client Name !');
			dijit.byId('customer_code').focus();
			return false;
		}
		schedule_opt = dijit.byId("schedule_opt").get("value");
		if(schedule_opt==6){ 
			identity = $("#identity").val(); if(identity==''){ alert("Please Add Record First!");addRow(); return false;}}
		result = checkFirstRecord();
		if(result==false){return false;}
		loading();
		dojo.xhrPost({
		    url: url_previewloan,	
			form: dojo.byId("frm_add_tran"),		    
			handleAs:"json", 
			load: function(data) {
				 document.getElementsByClassName("overlay")[0].style.display="none";
				if(data.row_id=='row_id'){//return 1;
					printSave('','');
					}else{
						  temp='';	
						  fund_title=0;thead='';fund_title=0;
						  temp='<table class="collape tablesorter" style="font-size:13px; width:1000px !important; " id="table">'
						  temp+='<tr style="background:#ccc;"><th><?php echo $tr->translate("NUM");?></th>';
						  temp+='<th><?php echo $tr->translate("ថ្ងៃបង់ប្រាក់");?></th>';
						  temp+='<th><?php echo $tr->translate("ប្រាក់ដើមគ្រា");?></th>';
						  temp+='<th><?php echo $tr->translate("ប្រាក់ដើម");?></th>';
						  temp+='<th><?php echo $tr->translate("ប្រាក់ការ");?></th>';
						  temp+='<th><?php echo $tr->translate("សរុប");?></th>';
						  temp+='<th><?php echo $tr->translate("ប្រាក់ដើមនៅសល់");?></th>';
						  principal_permonth=0;total_interest=0;total_payment_after=0;
						for(i=0;i<data.length;i++){
							principal_permonth=principal_permonth+parseFloat(data[i].principal_permonth);
							total_interest=total_interest+parseFloat(data[i].total_interest);
							total_payment_after=total_payment_after+parseFloat(data[i].total_payment_after);
					      r++;
						  temp+='<tr><td align="center">'+r+'</td>';
						  var myDate = new Date(data[i].date_payment);
						  d = new Date(data[i].date_name);
						  temp+='<td>'+getDayName(d.getDay())+'-'+data[i].date_payments+'</td>';
						  temp+='<td>'+dojo.number.format(data[i].begining_balance,2)+'</td>';
						  temp+='<td>'+dojo.number.format(data[i].principal_permonth,2)+'</td>';
						  temp+='<td>'+dojo.number.format(data[i].total_interest,2)+'</td>';
						  temp+='<td><b>'+dojo.number.format(data[i].total_payment_after,2)+'<b></td>';
						  temp+='<td><b>'+dojo.number.format((data[i].ending_balance),2)+'<b></td>';
						 }
						  temp+='<tr><td align="right" colspan="3" style="border-left:1px solid #fff;border-bottom:1px solid #fff;">&nbsp;សរុប -Total</td>';
						  temp+='<td>'+dojo.number.format(principal_permonth,2)+'</td>';
						  temp+='<td>'+dojo.number.format(total_interest,2)+'</td>';
						  temp+='<td><b>'+dojo.number.format(total_payment_after,2)+'<b></td>';
						  temp+='<td></td>';
						temp+='</table>';
						dojo.byId('t_amountmoneytype').innerHTML = temp;
						dijit.byId("lbl_schedule").show();
					}
				
			},
			error: function(response, ioArgs) {
				 document.getElementsByClassName("overlay")[0].style.display="none";
				alert("Failed while doing the operation: " + ioArgs.xhr.response);
			}
	   });
	}
}
function getDayName(day){
	 var weekday = new Array(7);
	    weekday[0] = "អាទិត្យ";
	    weekday[1] = "ច័ន្ទ";
	    weekday[2] = "អង្គារ";
	    weekday[3] = "ពុធ";
	    weekday[4] = "ព្រហ";
	    weekday[5] = "សុក្រ";
	    weekday[6] = "សៅរ៍";
	    return weekday[day];
}
function hideDialog() {		
	dijit.byId("lbl_schedule").hide();
}
function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}

var url_add_staff = '<?php echo $this->url(array("module"=>"loan","controller"=>"index","action"=>"add-staff")); ?>';
function addStaff(){
	dojo.xhrPost({
		url:url_add_staff,
		form: dojo.byId("frm_staff"),
		handleAs:"json",
		load: function(data) {
			var Itemmake = { 
	    	  	id: data,
		        name: dijit.byId('kh_name').get('value')
		    };
	 		addDataToSelectbox(dijit.byId('staff_id'), staff_store, Itemmake, data);
		    dijit.byId('frm_staff').reset();
		    dijit.byId("popup_staff").hide();
		},
		error: function(err) {
			alert(err);
		}
	});
}
function hideDialog1(){
	 dijit.byId("popup_staff").hide();
}
function hideDialog2(){
	 dijit.byId("popup_client").hide();
}
var url_add_client = "<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'add-client'));?>";
function addNewClient(){
	//alert(1);
	dojo.xhrPost({
		url:url_add_client,	
		form:dojo.byId('frmpop_client'),
		handleAs:"json",
		load: function(response) {
			
			var myNewItem = {					
				id: response.id,
				name: dijit.byId('client_name').get('value'),
			};			
			addDataToSelectbox(dijit.byId('member'), client_store, myNewItem, response.id);
			
			var myNewItem1 = {					
				 id: response.id,
		         name: response.customer_code,
			 };			
			addDataToSelectbox(dijit.byId('customer_code'), client_number_store, myNewItem1, response.id);	

			pop_client_branch_id = dijit.byId('client_branch_id').get('value');  // get value to set it back for pop up 2 time
			
			dijit.byId('frmpop_client').reset();
			dijit.byId("popup_client").hide();
			
			dijit.byId('client_branch_id').attr('value',pop_client_branch_id);
			
		},
		error: function(err) {
		}
	});
}


</script>
<style>
						           .hover:hover{background: #eee;}
.overlay {display: none;position: absolute;width: 100%;height: 100%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .95;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           border: solid 1px #060522;text-align: center;
           background: #fff url("<?php echo $this->baseUrl()?>/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>


<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:30%;" id="popup_staff" >
		<form style="background-color: buttonface; width:100%;" id='frm_staff' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
				<tr>
					<td>
						<fieldset style="background-color: buttonface;">
						<legend align="center" ><?php echo $tr->translate('ADD_STAFF');?></legend>
							<table style="margin: 0 auto; width: 100%;  padding:10px;" cellspacing="7" >
								<tr>
									<td><?php echo $tr->translate('NAME_KH');?></td>
									<td>
										<input dojoType="dijit.form.ValidationTextBox"   class="fullside" id="kh_name" name="kh_name" value="" type="text">
									</td>
								</tr>
								<tr>
									<td><?php echo $tr->translate('SEX');?></td>
									<td>
										<select dojoType="dijit.form.FilteringSelect"  class="fullside" id="sex" name="sex" value="" type="text">
											<option value="1">Male</option>
											<option value="2">Female</option>
										</select>
									</td>
								</tr>
								<input type="hidden" name="branch_id_pop" id="branch_id_pop" dojoType="dijit.form.TextBox" />
								<tr>
									<td><?php echo $tr->translate('PHONE');?></td>
									<td>
										<input type="text" name="phone" id="phone" class="fullside" dojoType="dijit.form.TextBox" />
									</td>
									
								</tr>
								
								<tr>
									<td><?php echo $tr->translate('NOTE');?></td>
									<td>
										<input type="text" name="note_pop" id="note_pop" class="fullside" dojoType="dijit.form.TextBox" />
									</td>
									
								</tr>
								
								<tr>
									<td colspan="4" align="center">
										<input type="button" value="ចាកចេញ" label="Close" id="close" name="close" dojoType="dijit.form.Button" 
										​ ​​iconClass="dijitIconUndo" onclick="hideDialog1();"/>
										<input type="button" value="save" label="SAVE" id="save" name="save" dojoType="dijit.form.Button" 
										 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addStaff();"/>
									</td>
								</tr>
								
							</table>
					</fieldset>
					</td>
				</tr>
			</table>

		</form>
	</div>
</div>



<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:35%;" id="popup_client" >
		<form style="background-color: buttonface; width:100%;" id='frmpop_client' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
				<tr>
					<td>
						<fieldset style="background-color: buttonface;">
						<legend align="center" ><?php echo $tr->translate('ADD_CLIENT');?></legend>
							<table style="margin: 0 auto; width: 100%;  padding:10px;" cellspacing="7" >
								<tr>
									<td><?php echo $tr->translate('CUSTOMER_NAME');?></td>
									<td>
										<input dojoType="dijit.form.ValidationTextBox"  class="fullside" id="client_name" name="client_name" value="" type="text">
									</td>
								</tr>
								<tr>
									<td><?php echo $tr->translate('SEX');?></td>
									<td>
										<select dojoType="dijit.form.FilteringSelect"  class="fullside" id="client_sex" name="client_sex" value="1" type="text">
											<option value="1">Male</option>
											<option value="2">Female</option>
										</select>
									</td>
								</tr>
								
								<tr>
									<td><?php echo $tr->translate('DOCUMENT_TYPE');?></td>
									<td>
										<select dojoType="dijit.form.FilteringSelect"  class="fullside" id="client_doc_type" name="client_doc_type" value="2" type="text">
											<?php if(!empty($this->client_doc_type)){foreach($this->client_doc_type as $row){?>
												<option value="<?php echo $row['id']?>"><?php echo $row['name']?></option>
											<?php }}?>
										</select>
									</td>
								</tr>
								<tr>
									<td><?php echo $tr->translate('NATIONAL_ID');?></td>
									<td>
										<input type="text" name="national_id" id="national_id" class="fullside" dojoType="dijit.form.TextBox" />
									</td>
									
								</tr>
								<input type="hidden" name="client_branch_id" id="client_branch_id" dojoType="dijit.form.TextBox" />
								<tr>
									<td><?php echo $tr->translate('PHONE');?></td>
									<td>
										<input type="text" name="client_phone" id="client_phone" class="fullside" dojoType="dijit.form.TextBox" />
									</td>
									
								</tr>
								
								<tr>
									<td><?php echo $tr->translate('NOTE');?></td>
									<td>
										<input type="text" name="client_note" id="client_note" class="fullside" dojoType="dijit.form.TextBox" />
									</td>
									
								</tr>
								
								<tr>
									<td colspan="4" align="center">
										<input type="button" value="ចាកចេញ" label="Close" dojoType="dijit.form.Button" 
										​ ​​iconClass="dijitIconUndo" onclick="hideDialog2();"/>
										<input type="button" value="save" label="SAVE"  dojoType="dijit.form.Button" 
										 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addNewClient();"/>
									</td>
								</tr>
								
							</table>
					</fieldset>
					</td>
				</tr>
			</table>

		</form>
	</div>
</div>
<script>
function returnMOnth(monthnum){
	var month = new Array();
	month[1] = "Jan";
	month[2] = "Feb";
	month[3] = "Mar";
	month[4] = "Apr";
	month[5] = "May";
	month[6] = "Jun";
	month[7] = "Jul";
	month[8] = "Aug";
	month[8] = "Sep";
	month[10] = "Oct";
	month[11] = "Nov";
	month[12] = "Dec";
	return month[monthnum];
}
</script>