<?php
$url_edit = $this->url(array('module'=>'dailywork','controller'=>'index','action'=>'edit'));
?>
<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage(); ?>
<?php $formFilter =  $this->frm_search;?>
<meta charset="utf-8" />
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
   <table width="100%" >
   		<tr>
		   	<td><input class="form-control" dojoType="dijit.form.TextBox" id="adv_search" name="adv_search" value="<?php echo $this->row['adv_search']?>" type="text" ></td>
		   	<td><?php echo $formFilter->getElement("user");?></td>
		   	<td><?php echo $formFilter->getElement("projectname");?></td>
		    <td><input dojoType="dijit.form.DateTextBox" class="" id="start_date" name="start_date" value="<?php echo $this->row['end_date'];?>" type="text"></td>
		    <td><input dojoType="dijit.form.DateTextBox" class="" id="end_date" name="end_date" value="<?php echo $this->row['end_date'];?>" type="text"></td>
		    <td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
   	   </tr>
   </table>
</form>
<?php echo $this->list; ?>