<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate('SALE_CANCEL'));
$frm = $this->frm_loan;
?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.CheckBox");
dojo.require("dijit.Dialog");
</script>
<form id="add_cancel" action="<?php echo $this->url(array('module'=>'loan','controller'=>'cancel','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	 <script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
    	return true;
   		}else {
    	return false;
   	}
	</script>
<table cellspacing="10" class='fullside' >
	<tr>
		<td>
				<fieldset>
					<legend><strong><?php echo $tr->translate('SALE_CANCEL');?></strong></legend>
					<table cellspacing="10"  width="100%">
					   <tr>
							<td><?php echo $tr->translate("BRANCH_NAME")?></td>
							<td><?php echo $frm->getElement('branch_id');?></td>
							<td><?php echo $tr->translate("CLIENT_NAME")?></td>
							<td><input id="sale_client" /></td>
							<td><?php echo $tr->translate("SALE_NO")?></td>
							<td><input id="sale_no" ><?php echo $frm->getElement('property_id')?></td>
						</tr>
						<tr>
							<td colspan="3"><?php echo $tr->translate("CUSTOMER_INFO")?></td>
							<td colspan="3"><?php echo $tr->translate("LAND_INFO")?></td>
						</tr>
						<tr>
							<td style="height: 70px; border:1px solid #aac4e6; widht:100%;" colspan="3"><label id="cus_information"></label></td>	
							<td style="height: 70px; border:1px solid #aac4e6; widht:100%;" colspan="3"><label id="land_information"></label></td>					
						</tr>
						<tr>
							<td colspan="6" style="border-bottom:1px solid #aac4e6;"><strong><?php echo $tr->translate("PAYMENT_INFO")?></strong></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("PRICE_SOLD")?></td>
							<td width="25%"><?php echo $frm->getElement('price_sold');?></td>
							<td><?php echo $tr->translate("DISCOUNT")?></td>
							<td><?php echo $frm->getElement('discount');?></td>
							<td><?php echo $tr->translate("OTHER_FEE")?></td>
							<td><?php echo $frm->getElement('other_fee');?></td>
						</tr>
						<tr>
							<td style="white-space: nowrap;"><?php echo $tr->translate("PAYMENT_TYPE")?></td>
							<td><?php  echo $frm->getElement('schedule_opt');?></td>	
							<td><?php echo $tr->translate("DURATION")?></td>
							<td><?php echo $frm->getElement('period');?></td>
							<td><?php echo $tr->translate("BUY_DATE")?></td>
							<td><?php echo $frm->getElement('buy_date');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("END_DATE")?></td>
							<td><?php  echo $frm->getElement('end_date');?></td>
							<td><?php echo $tr->translate("BUY_DATE")?></td>
							<td><?php  echo $frm->getElement('sold_date');?></td>
							<td><?php echo $tr->translate("COMMISION")?></td>
							<td><?php  echo $frm->getElement('commision');?></td>	
						</tr>
						<tr>
							<td style="white-space: nowrap;"><?php echo $tr->translate("INSTALLMENT_PAID")?></td>
							<td><?php  echo $frm->getElement('installment_paid');?></td>	
							<td><?php echo $tr->translate("PAID_AMOUNT")?></td>
							<td><?php  echo $frm->getElement('paid_amount');?></td>	
							<td><?php echo $tr->translate("BALANCE")?></td>
							<td><?php echo $frm->getElement('balance')?></td>	
						</tr>
						<tr>
							<td><?php echo $tr->translate("RETURN_MONEY_BACK")?></td>
							<td><?php echo $frm->getElement('return_back')?></td>	
							<td><?php echo $tr->translate("CATEGORY")?></td>
							<td><input id="income_category" /></td>
						</tr>
						<tr>
							<td colspan="3"><?php echo $tr->translate("NOTE")?></td>
							<td colspan="3"><?php echo $tr->translate("REASON")?></td>
						</tr>
						<tr>
							<td style="height: 70px; border:1px solid #aac4e6; widht:100%;" colspan="3"><label id="sale_note"></label></td>	
							<td colspan="3"><textarea class="fullside" style="height: 60px;font-family:'Khmer OS Battambang';font-size: 17px" id="reason" name="reason"></textarea></td>
						</tr>
						<tr>
							<td align="center" colspan="6">
								<input type="submit" name="save" value="រក្សាទុក  + បន្ថែមថ្មី​​ " label="<?php echo $tr->translate('SAVENEW')?>" id="submitButton" dojoType="dijit.form.Button"
				 					iconClass="dijitEditorIcon dijitEditorIconSave"/>
				 				<input type="submit" name="save_close"​​ value="រក្សាទុក​  + ចាកចេញ" label="<?php echo $tr->translate('SAVECLOSE')?>" id="submitBtn" dojoType="dijit.form.Button"
				 					iconClass="dijitEditorIcon dijitEditorIconSave"/>
				 						<input type="button" label="<?php echo $tr->translate("PREVIEW")?>" name='print' value=''print'' dojoType="dijit.form.Button"
				 iconClass="dijitIconNewTask" onClick="printSave('');displayNone();" />
							</td>
						</tr>
					</table>
				</fieldset>
		</td>
	</tr>		
	<tr>
	</tr>	
</table>
</form>
<table>
<tr>
</tr>
</table>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:30%;" id="popup_category" >
		<form style="background-color: buttonface; width:100%;" id='frm_category' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
				<tr>
					<td>
						<fieldset style="background-color: buttonface;">
						<legend align="center" ><?php echo $tr->translate('ADD_CATEGORY');?></legend>
							<table style="margin: 0 auto; width: 100%;  padding:10px;" cellspacing="7" >
								<tr>
									<td><?php echo $tr->translate('NAME_KH');?></td>
									<td>
										<input dojoType="dijit.form.ValidationTextBox"   class="fullside" id="cate_name" name="cate_name" value="" type="text">
									</td>
								</tr>
								<tr>
									<td><?php echo $tr->translate('STATUS');?></td>
									<td>
										<select name="status_j" id="status_j" dojoType="dijit.form.FilteringSelect"   class="fullside">
		    								<option value="1" label="active">Active</option>
		    								<option value="0" label="deactive">Deactive</option>
										</select>
									</td>
									
								</tr>
								<tr>
									<td colspan="4" align="center">
										<input type="button" value="ចាកចេញ" label="Close" id="close" name="close" dojoType="dijit.form.Button" 
										​ ​​iconClass="dijitIconUndo" onclick="hideDialog1();"/>
										<input type="button" value="save" label="SAVE" id="save" name="save" dojoType="dijit.form.Button" 
										 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addCategory();"/>
									</td>
								</tr>
								
							</table>
					</fieldset>
					</td>
				</tr>
			</table>

		</form>
	</div>
</div>
<div class="dijitHidden" style="width: 22cm !important; height: 11cm ; padding: 0px; margin: 0px;">
	<div data-dojo-type="dijit.Dialog" style="width:22cm; font-family:Khmer OS Battambang;" align="center" data-dojo-props="title:'<?php echo $tr->translate("PAYMENT_RECEIPT");?>'" id="print_expense" >
		<div id="divPrint" style="width: 21cm !important; height: 13cm ; padding: 0px; margin: 0px;">
			<style>
				.fontbig{
					font-size: 15px;	
				}
				.fonttel{
					font-size: 18px;	
				}
				.pleft{
					width: 110px;	
				}

				.label{ font-weight: bold;font-size: 22px;}
				.value{ font:14px 'Khmer OS Battambang';border: 1px solid #000; height: 28px; width: 100%;margin-right:5px; display: block;
						line-height: 28px;
					    text-align: center;
						}
				.print tr td{
					padding:2px 2px; 
				}
			   .khmerbold{font:16px 'Khmer OS Battambang';}
			   .khmer{font:16px 'Khmer OS Battambang';}
			   .one{white-space:nowrap;}
			   .h{ margin-top: -10px;/*margin-left:4px;*/}
			</style>	
			<table width="100%" style="white-space: nowrap;font-size:16px;margin-top: 10px;" class="print" cellspacing="0"  cellpadding="0" >
				<tr>
					<td colspan="6">
						<table width="100%" style="font-family:'Khmer MEF2';white-space:nowrap;">
							<tr>
								<td width="25%">
									<img style="width:100%;height:61px;" src="<?php echo $this->baseUrl().'/images/bppt_logo.png'?>">
								</td>					
								<td width="50%" style="font:bold 18px 'Kh Muol';" valign="top" align="center"><u><b><strong style=" font-family: Arial Black;font-family:'Khmer MEF2';">បង្កាន់ដៃចំណាយ</strong></b></u>
									<div style="line-height:10px;"><strong style="font-size: 18px;font-weight:bold">OFFICIAL RECEIPT</strong></div>
								</td>
								<td width="25%">
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<table width="100%" style="white-space: nowrap;font-size:14px;margin-top: 0px;" class="print" cellspacing="3px"  cellpadding="0">
				<tr>
					<td width="10%" ></td>
					<td width="37%" ></td>
					<td width="15%" ></td>
					<td width="13%" ></td>
					<td width="10%" ></td>
					<td width="20%" ></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold">គម្រោង</td>
                    <td><strong><label id="lb_branch" class="value"></label></strong></td>
				    <td class="one khmerbold">&nbsp;&nbsp;&nbsp;វិក័យប័ត្រលេខ</td>
                    <td colspan="3"><strong><label id="lb_invoice" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold">ប្រភេទចំណាយ</td>
					<td ><strong><label id="lb_income_category" class="value"></label></strong></td>
					<td class="one khmerbold">&nbsp;&nbsp;&nbsp;ពណ៌នាចំនាយ</td>
				    <td colspan="3"><strong><label id="lb_income_title" class="value"></label></strong></td>
				</tr>
				<tr>
					<td class="one khmerbold">សែក</td>
				    <td ><strong style="white-space: nowrap;"><label style="white-space: nowrap;" id="lb_cheque" class="value"></label></strong></td>
					
					<td class="one khmerbold">&nbsp;&nbsp;&nbsp;ចំណាយសរុប</td>
					<td colspan="3"><strong><label id="lb_total_amount" class="value"></label></strong></td>
					
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold">សម្គាល់</td>
				    <td colspan="1" align="center"><strong style="white-space: nowrap;"><label style="white-space: nowrap;text-align: center; " id="lb_description" class="value"></label></strong></td>
				
					
					<td class="one khmerbold">&nbsp;&nbsp;&nbsp;ថ្ងៃចំណាយ</td>
				    <td colspan="3"><strong><label id="lb_date" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
				    <td class="khmerbold" style="line-height: 14px;"colspan="4"  align="center" >&nbsp;&nbsp;<strong style=" font-family: Arial Black;font-family:'Khmer MEF2';"></strong></td>
				    <td colspan="2" class="khmerbold" style="line-height: 14px;" align="center" ><strong style=" font-family: Arial Black;font-family:'Khmer MEF2';">ស្នាមមេដៃអ្នកទទួល</strong></td>
				</tr>
				<tr style="white-space: nowrap;" height="60px;">
					<td class="one khmerbold" colspan="4" align="center" valign="bottom">
					</td>
				    <td class="one khmerbold" colspan="2" align="center" valign="bottom">&nbsp;
				  			<h4 style="padding-right: 5px ! important;margin-bottom: -10px  !important;">
				              <?php $session_user=new Zend_Session_Namespace('auth');
						           $last_name=$session_user->last_name;
						           $username = $session_user->first_name;
						           echo $last_name." ".$username;?></h4>  
					</td>
				</tr>
				<tr style="line-height: 20px;font-size: 11px;">
					<td valign="top" >
						<span style="text-decoration:underline;font-size: 14px;">សំគាល់ ៖</span>
					</td>
					<td colspan="5" style="font-family:'Khmer OS Battambang';">
						<span style="font-size: 13px;"><?php echo $this->data['comment'];?></span><br />
						<span style="white-space: pre-line;font-size: 13px;"><?php echo $this->data['comment1'];?></span><br />
					</td>
				</tr>
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="6" style="border-top: 2px solid rgba(255, 235, 59, 0.88)">
					</td>
				</tr>
				<tr style="line-height: 15px;">
					<td colspan="6" >
						<table width="100%" style="font-family: 'Khmer OS Battambang'; font-size:13px;line-height: 15px;margin-top: -5px;margin-bottom:15px;white-space:nowrap;"> 
							<tr>
								<td width="22%">
									<img style="width:70%;height: 25px;" src="<?php echo $this->baseUrl().'/images/bppt_letter.png'?>">
								</td>
								<td width="40%">
									<span style=""><?php echo $this->data['website'];?></span>
								</td>
								<td width="40%" align="right">
									<span style="font-family: 'Khmer OS Battambang'; "><?php echo $this->data['email_client'];?></span>
								</td>
							</tr>
							<tr style="white-space:nowrap;">
								<td colspan="2">
									<?php echo $this->data['footer_branch'];?>
								</td>
								<td width="40%" align="right">
									<span style=""><?php echo $this->data['tel-client'];?> </span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="6">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="6" style="border-top:1px dashed #000;" >
					</td>
				</tr>
			</table>
		</div>
		<table>
			<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
			<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
				type="button" onclick="doPrint();">បោះពុម្ភ/Print</button>
		</table>
		<div id="divPrint1" style="width: 21cm !important; height: 13cm ; padding: 0px; margin: 0px;">
			<table width="100%" style="white-space: nowrap;font-size:14px;margin-top: 10px;" class="print" cellspacing="0"  cellpadding="0" >
				<tr>
					<td colspan="6">
						<table width="100%" style="font-family:'Khmer MEF2';white-space:nowrap;">
							<tr>
								<td width="25%">
									<img style="width:100%;height:61px;" src="<?php echo $this->baseUrl().'/images/bppt_logo.png'?>">
								</td>					
								<td width="50%" style="font:bold 18px 'Kh Muol';" valign="top" align="center"><u><b><strong style=" font-family: Arial Black;font-family:'Khmer MEF2';">បង្កាន់ដៃចំណាយ</strong></b></u>
									<div style="line-height:10px;"><strong style="font-size: 18px;font-weight:bold">OFFICIAL RECEIPT</strong></div>
								</td>
								<td width="25%">
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<table width="100%" style="white-space: nowrap;font-size:14px;margin-top: 0px;" class="print" cellspacing="3px"  cellpadding="0">
				<tr>
					<td width="10%" ></td>
					<td width="37%" ></td>
					<td width="15%" ></td>
					<td width="13%" ></td>
					<td width="10%" ></td>
					<td width="20%" ></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold">សាខា</td>
                    <td><strong><label id="lb_branch1" class="value"></label></strong></td>
				    <td class="one khmerbold">&nbsp;&nbsp;&nbsp;វិក័យប័ត្រលេខ</td>
                    <td colspan="3"><strong><label id="lb_invoice1" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold">ប្រភេទចំណាយ</td>
					<td ><strong><label id="lb_income_category1" class="value"></label></strong></td>
					<td class="one khmerbold">&nbsp;&nbsp;&nbsp;ពណ៌នាចំនាយ</td>
				    <td colspan="3"><strong><label id="lb_income_title1" class="value"></label></strong></td>
				</tr>
				<tr>
					<td class="one khmerbold">សែក</td>
				    <td ><strong style="white-space: nowrap;"><label style="white-space: nowrap;" id="lb_cheque1" class="value"></label></strong></td>
					<td class="one khmerbold">&nbsp;&nbsp;ចំណាយសរុប</td>
					<td colspan="3"><strong><label id="lb_total_amount1" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold">សម្គាល់</td>
				    <td colspan="1" align="center"><strong style="white-space: nowrap;"><label style="white-space: nowrap;text-align: center; " id="lb_description1" class="value"></label></strong></td>
					<td class="one khmerbold">&nbsp;&nbsp;ថ្ងៃចំណាយ</td>
				    <td colspan="3"><strong><label id="lb_date1" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
				    <td class="khmerbold" style="line-height: 14px;"colspan="4"  align="center" >&nbsp;&nbsp;<strong style=" font-family: Arial Black;font-family:'Khmer MEF2';"></strong></td>
				    <td colspan="2" class="khmerbold" style="line-height: 14px;" align="center" ><strong style=" font-family: Arial Black;font-family:'Khmer MEF2';">ស្នាមមេដៃអ្នកទទួល</strong></td>
				</tr>
				<tr style="white-space: nowrap;" height="60px;">
					<td class="one khmerbold" colspan="4" align="center" valign="bottom">
					</td>
				    <td class="one khmerbold" colspan="2" align="center" valign="bottom">&nbsp;
				  			<h4 style="padding-right: 5px ! important;margin-bottom: -10px  !important;">
				              <?php $session_user=new Zend_Session_Namespace('auth');
						           $last_name=$session_user->last_name;
						           $username = $session_user->first_name;
						           echo $last_name." ".$username;?></h4>  
					</td>
				</tr>
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="6" valign="top" >
					</td>
				</tr>
				<tr style="line-height: 20px;font-size: 11px;">
					<td valign="top" >
						<span style="text-decoration:underline;font-size: 14px;">សំគាល់ ៖</span>
					</td>
					<td colspan="5" style="font-family:'Khmer OS Battambang';">
						<span style="font-size: 13px;"><?php echo $this->data['comment'];?></span><br />
						<span style="white-space: pre-line;font-size: 13px;"><?php echo $this->data['comment1'];?></span><br />
					</td>
				</tr>
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="6" style="border-top: 2px solid rgba(255, 235, 59, 0.88)">
					</td>
				</tr>
				<tr style="line-height: 15px;">
					<td colspan="6" >
						<table width="100%" style="font-family: 'Khmer OS Battambang'; font-size:13px;line-height: 15px;margin-top: -5px;margin-bottom:15px;white-space:nowrap;"> 
							<tr>
								<td width="22%">
									<img style="width:70%;height: 25px;" src="<?php echo $this->baseUrl().'/images/bppt_letter.png'?>">
								</td>
								<td width="40%">
									<span style=""><?php echo $this->data['website'];?></span>
								</td>
								<td width="40%" align="right">
									<span style="font-family: 'Khmer OS Battambang'; "><?php echo $this->data['email_client'];?></span>
								</td>
							</tr>
							<tr style="white-space:nowrap;">
								<td colspan="2">
									<?php echo $this->data['footer_branch'];?>
								</td>
								<td width="40%" align="right">
									<span style=""><?php echo $this->data['tel-client'];?> </span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="6">&nbsp;</td>
				</tr>
			</table>
		</div>
		
	</div>
</div>
<script type="text/javascript">

function printSubmit(){
	 $('#frm_add_tran').submit();
}

function hideDialog1(){
	dijit.byId('popup_category').hide();
}

var income_category_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->all_category));?> );
new dijit.form.FilteringSelect({
	store: income_category_store,
	autoComplete: true,                        
    id: "income_category",
    name: "income_category",  
    class: 'fullside',  
    placeHolder:"Selected Category", 
    onChange: function() {          
	   	fa_job = dijit.byId('income_category').get('value');
	    if(fa_job==-1){
	   	 dijit.byId("popup_category").show();
	    }
    } 
}, "income_category");

var url_add_category = '<?php echo $this->url(array("module"=>"loan","controller"=>"expense","action"=>"add-category")); ?>';
function addCategory(){
	dojo.xhrPost({
		url:url_add_category,
		form: dojo.byId("frm_category"),
		handleAs:"json",
		load: function(data) {
			var Itemmake = { 
	    		id: data,
		        name: dijit.byId('cate_name').get('value')
		    };
	 		addDataToSelectbox(dijit.byId('income_category'), income_category_store, Itemmake, data);
		    dijit.byId('frm_category').reset();
		    dijit.byId("popup_category").hide();
		},
		error: function(err) {
			alert(err);
		}
	});
}

var sale_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var sale_client_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	try{
		
		new dijit.form.FilteringSelect({
		store: sale_store,
		autoComplete: true,
		required: false,		           
		name: "sale_no",
		id: "sale_no",
		searchAttr: "name",
		class: 'fullside',
		//missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ ស្រុក/ខ័ណ្ឌ!",	
			onChange: function() {
				getLandAndClientDetail("1");
			}
		}, "sale_no");

		new dijit.form.FilteringSelect({
			store: sale_client_store,
			autoComplete: true,
			required: false,		           
			name: "sale_client",
			id: "sale_client",
			searchAttr: "name",
			class: 'fullside',
			//missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ ស្រុក/ខ័ណ្ឌ!",	
				onChange: function() {
					getLandAndClientDetail("2");
				}
			}, "sale_client");
		getSaleClie();
		getSaleNo();

		}catch(e){
			alert(e);
		}
});

var	url_getSaleNo = '<?php echo $this->url(array('module'=>'loan','controller'=>'cancel','action'=>'get-sale'));?>';
	function getSaleNo(){
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id==0){
			return false;}
		dojo.xhrPost({
			url:url_getSaleNo,	
			content:{ 
				'branch_id': branch_id
			},
			handleAs:"json",
			load: function(data) {	
				sale_store  = getDataStorefromJSON('id','name', data);		
			    dijit.byId('sale_no').set('store', sale_store);
			},
			error: function(err) {
				alert(err);
			}
		});
	}
	var	url_getSaleClien = '<?php echo $this->url(array('module'=>'loan','controller'=>'cancel','action'=>'get-saleclie'));?>';
	function getSaleClie(){
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id==0){
			return false;}
		dojo.xhrPost({
			url:url_getSaleClien,	
			content:{ 
				'branch_id': branch_id, 'sale_id':'',
			},
			handleAs:"json",
			load: function(data) {	
				sale_client_store  = getDataStorefromJSON('id','name', data);		
			    dijit.byId('sale_client').set('store', sale_client_store);
			},
			error: function(err) {
				alert(err);
			}
		});
	}
	var url_land= '<?php echo $this->url(array('module'=>'loan','controller'=>'cancel','action'=>'get-info'));?>';
	function getLandAndClientDetail(inds){
		if(inds == "2"){
			sale_id = dijit.byId('sale_client').get('value');
			dijit.byId('sale_no').set("value",sale_id)
		}else{
			sale_id = dijit.byId('sale_no').get('value');
			dijit.byId('sale_client').set("value",sale_id);
		}
		dojo.xhrPost({
			url:url_land,	
			content:{ 
			    'sale_id':sale_id
			},		    
			handleAs:"json",
			load: function(data) {
				dijit.byId('price_sold').attr('value',data.price_sold);
				dijit.byId('installment_paid').attr('value',data.installment_paid);
				
				total_principal= data.total_principal;
				if(isNaN(total_principal) || total_principal==null){total_principal=0;}
			    paid_amount = data.paid_amount;
				if(isNaN(paid_amount) || paid_amount==null){paid_amount=0;}
				total_principal = parseFloat(total_principal);
				
				//dijit.byId('paid_before').attr('value',total_principal);
				
				dijit.byId('paid_amount').attr('value',total_principal);
				balance = data.price_sold-total_principal;
				dijit.byId('balance').attr('value',balance);
				dijit.byId('period').attr('value',data.total_duration);
				dijit.byId('buy_date').attr('value',data.buy_date);
				dijit.byId('end_date').attr('value',data.end_line);
				dijit.byId('discount').attr('value',data.discount_amount);
				dijit.byId('other_fee').attr('value',data.other_fee);
				dijit.byId('schedule_opt').attr('value',data.payment_id);
				dojo.byId("property_id").value = data.property_id;
				dijit.byId('sold_date').attr('value',data.create_date);
				dijit.byId('commision').attr('value',data.comission);
				
				dojo.byId('cus_information').innerHTML ="លេខកូដអតិថិជន  : "+data.client_number+", ឈ្មោះជាភាសាខ្មែរ : "+data.name_kh;
				dojo.byId('land_information').innerHTML ="លេខសម្គាល់  : "+data.land_code+", ឈ្មោះ  :  "+data.land_address+", ផ្លូវ : "+data.street+", ប្រភេទ   : "+data.pro_type+", ទំហំ  : "+data.land_size+", បណ្តោយ :  "+data.height+",ទទឹង  :  "+data.width;
				dojo.byId('sale_note').innerHTML = data.sale_note;
			},
			error: function(err) {
				alert(err);
			}
		});
	}
	function checkreturnAmount(){
		paid_amount = dijit.byId('paid_amount').get('value');
		return_back = dijit.byId('return_back').get('value');
		sale_id = dijit.byId('sale_client').get('value');
		if(sale_id==''){
			alert('សូមេជ្រើសរើសអតិថិជនជាមុនសិន!');
			dijit.byId('sale_client').focus();
			dijit.byId('return_back').attr('value',0);
			return false;
		}
		if(return_back>paid_amount){
			alert('ប្រាក់ដែលប្រគល់ត្រឡប់់មិនអាចធំជាងប្រាក់ដែលបានបង់នោះទេ!');
			dijit.byId('return_back').attr('value',paid_amount);
		}
	}
	function printSave(new_invoice_no){
	/////////////////// check Validate /////////////////////////////////////////
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id==0){
		alert('Select branch');
		dijit.byId('branch_id').focus();
		return false;
		}
		
		total_amount = dijit.byId('return_back').get('value');
		if(isNaN(total_amount)){
		alert('Income can not be null');
		dijit.byId('return_back').focus();
		return false;
		}
		//////////////////////////////////////////////////////////////////
		
		
		if(new_invoice_no==''){
			getInvoiceNo(1);
		}else{
			dojo.byId("lb_invoice").innerHTML = new_invoice_no;
			dojo.byId("lb_invoice1").innerHTML = new_invoice_no;
		}
		
		dojo.byId("lb_branch").innerHTML = dijit.byId("branch_id").attr('displayedValue');
		//dojo.byId("lb_customer").innerHTML = dijit.byId("customer").attr('displayedValue');
		dojo.byId("lb_income_category").innerHTML = dijit.byId("income_category").attr('displayedValue');
		dojo.byId("lb_income_title").innerHTML = dijit.byId("sale_client").attr('displayedValue');
		dojo.byId("lb_total_amount").innerHTML = currencyFormat(dijit.byId("return_back").get('value'));
		
		date_payment = '<?php echo date("Y-m-d");?>';
		var a = new Date(date_payment);
		mm = a.getMonth()+1;
		var dd = a.getDate();
		if(dd<10){
		dd = "0"+dd;
		}
		month = returnMOnth(mm);
		var y = a.getFullYear();
		var date_payment = dd +'-'+month+'-'+y ;
		
		dojo.byId("lb_date").innerHTML = date_payment;
		dojo.byId("lb_description").innerHTML = $("#reason").val();
		dojo.byId("lb_cheque").innerHTML = '';
		
		
		dojo.byId("lb_branch1").innerHTML = dijit.byId("branch_id").attr('displayedValue');
		dojo.byId("lb_income_category1").innerHTML =dijit.byId("income_category").attr('displayedValue');
		dojo.byId("lb_income_title1").innerHTML = dijit.byId("sale_client").attr('displayedValue');
		dojo.byId("lb_total_amount1").innerHTML = currencyFormat(dijit.byId("return_back").get('value'));
		dojo.byId("lb_date1").innerHTML = date_payment;
		dojo.byId("lb_description1").innerHTML = $("#reason").val();
		dojo.byId("lb_cheque1").innerHTML = '';
		
		dijit.byId("print_expense").show();
	}
	function currencyFormat(num) {
	    return "$ " + num.toFixed(2).replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1,")
	}
	function displayNone(){
		document.getElementById('divPrint1').style.display="none";
	}
	var url_get_invoice = '<?php echo $this->url(array('module'=>'loan','controller'=>'expense','action'=>'get-invoice-no')); ?>';
	function getInvoiceNo(condition){
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id==0){
			branch_id=1;
		}
		dojo.xhrPost({
			url:url_get_invoice,
			content:{
				'branch_id':branch_id
				},
			handleAs:"json",
			load: function(data) {
				//alert(data);
			    //dijit.byId('invoice').attr('value',data);   
				if(condition==1){
					printSave(data);
				}
			},
			error: function(err) {
				alert(err);
			}
		});
	}
	function returnMOnth(monthnum){
		var month = new Array();
		month[1] = "Jan";
		month[2] = "Feb";
		month[3] = "Mar";
		month[4] = "Apr";
		month[5] = "May";
		month[6] = "Jun";
		month[7] = "Jul";
		month[8] = "Aug";
		month[8] = "Sep";
		month[10] = "Oct";
		month[11] = "Nov";
		month[12] = "Dec";
		return month[monthnum];
	}
	function doPrint() {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML + dojo.byId('divPrint1').innerHTML;;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    printSubmit();
	    hideDialog();
	}
	function printSubmit(){
		 $('#add_cancel').submit();
	}
</script>