<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate('BAD_LOAN'));
 $frm = $this->frm_cancel;
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'loan','controller'=>'cancel','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">	<table>
	<table>	
		<tr>
			<td><?php echo $frm->getElement('adv_search');?></td>
			<td><?php echo $frm->getElement('branch_id_search');?></td>
			<td><?php echo $frm->getElement('from_date_search');?></td>
			<td><?php echo $frm->getElement('to_date_search');?></td>
			<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
		</tr>
	</table>
</form>
<?php echo $this->list;?>
