<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate('SETTINGPRICE'));
$frm = $this->frm_setting_price;
//$frm = $this->frm_search;
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'group','controller'=>'settingprice','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   <table width="70%">
   	<tr>
	   <td ><?php echo $frm->getElement("adv_search");?></td>
	   <td ><?php echo $frm->getElement('status_search');?></td>
	   <td><?php  //echo $frm->getElement("Datesearch_start");?></td>
	   <td ><?php //echo $frm->getElement('Datesearch_stop');?></td>
	   <td><input type="submit" value="search" name="search" label="Search" dojoType="dijit.form.Button" 					  
				  iconClass="dijitIconSearch" /></td>
	</tr>
   </table>
    <?php echo $this->list;?>
</form>
