<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
   <meta charset="utf-8" />
   <title>Sale Properties Management System</title>
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <meta content="" name="description" />
   <meta content="" name="author" />
   <link href="<?php echo $this->baseUrl()?>/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/assets/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/assets/bootstrap/css/bootstrap-fileupload.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/css/style.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/css/style-responsive.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/css/style-default.css" rel="stylesheet" id="style_color" />
   <link rel="shortcut icon" href="<?php echo $this->baseUrl()?>/images/icon.ico" type="image/x-icon"/>
<style>
.tundra .dijitBorderContainer-child{
	 overflow: hidden;
}
</style>
<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$client=$this->url(array('module'=>'group','controller'=>'index','action'=>'index'), null, true);
$collecteral=$this->url(array('module'=>'group','controller'=>'callteral','action'=>'index'), null, true);
$chagen_coll=$this->url(array('module'=>'group','controller'=>'changecollteral','action'=>'index'), null, true);
$indi_loan=$this->url(array('module'=>'loan','controller'=>'index','action'=>'index'), null, true);
$disburse_loan=$this->url(array('module'=>'loan','controller'=>'groupdisburse','action'=>'index'), null, true);
$indi_payment=$this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'index'), null, true);
$group_payment=$this->url(array('module'=>'loan','controller'=>'grouppayment','action'=>'index'), null, true);
$repay_schedule=$this->url(array('module'=>'loan','controller'=>'repaymentschedule','action'=>'index'), null, true);
$quickpayment=$this->url(array('module'=>'loan','controller'=>'ilquickpayment','action'=>'index'), null, true);
$co=$this->url(array('module'=>'group','controller'=>'co','action'=>'index'), null, true);
$bad_loan=$this->url(array('module'=>'loan','controller'=>'cancel','action'=>'index'), null, true);
// report
$rpt_loanrelease=$this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-properties'), null, true);
$rpt_loanoustading=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-outstanding'), null, true);
$rpt_collectfromco=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-collectionco'), null, true);
$rpt_loancollect=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-payment'), null, true);
$rpt_dailypayment=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-payment'), null, true);
$rpt_loanincome=$this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-daily-cash'), null, true);
$rpt_loan_late=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-late'), null, true);
$rpt_total_collect=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-total-collect'), null, true);
$rpt_writoff=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-writoff'), null, true);
$rpt_paymenthistory=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-payment-history'), null, true);
$rpt_reschedule=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-reschedule-loan'), null, true);
$rpt_writeoff=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-payoff'), null, true);
$rpt_expectincome=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-expect-income'), null, true);
$rpt_exchangemoney=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-xchange'), null, true);
?>
<style type="text/css">
.metro-nav {
    font-family: 'Kh Battambang','Khmer Battambang' !important;
}
</style>
</head>
<body class="fixed-top" style="font-family:'Kh Battambang','Khmer Battambang' !important;">
   <div id="container" class="row-fluid" style="margin: 0 auto;">
      <!-- BEGIN PAGE -->  
      <div id="main-content">
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
            <!-- BEGIN PAGE CONTENT-->
            <div class="row-fluid">
                <!--BEGIN METRO STATES-->
                <div class="metro-nav metro-fix-view">
                    <div class="metro-nav-block nav-block-green long">
                        <a href="<?php echo $client;?>" style="text-align: center;" class="text-center" data-original-title="">
                            <span class="value">
                                <i class="icon-user"></i>
                            </span>
                        </a>
                         <div class="status" align="center"><?php echo $tr->translate('CLIENT_INFO');?></div>
                    </div>
                    <div class="metro-nav-block nav-block-red double">
                        <a href="<?php echo $co;?>" data-original-title="">
                            <i class="icon-shopping-cart"></i>
                            <div class="info"></div>
                            <div class="status"><?php echo $tr->translate('STAFF_NAME');?></div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-blue double">
                        <a href="<?php echo $indi_loan;?>" data-original-title="">
                            <i class="icon-tasks"></i>
                            <div class="info">$37624</div>
                            <div class="status"><?php echo $tr->translate('LOAN_IL');?></div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-purple double">
                        <a href="<?php echo $rpt_expectincome;?>" class="text-center" data-original-title="">
                            <i class="icon-signout"></i>
                            <div class="status"><?php echo $tr->translate('REPORT_COMISSION_STAFF');?></div>
                        </a>
                    </div>
                    
                   
                    <div class="metro-nav-block nav-block-orange double">
                        <a href="<?php echo $repay_schedule;?>" data-original-title="" class="text-center">
                            <i class="icon-star-empty"></i>
                            <div class="status"><?php echo $tr->translate('LOAN_RESCHEDULE');?></div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-blue double">
                        <a href="<?php echo $indi_payment;?>" class="text-center" data-original-title="">
                            <i class="icon-bar-chart"></i>
                            <div class="status"><?php echo $tr->translate('IL_PAYMENT');?></div>
                        </a>
                    </div>
                    <!-- 
	                    <div class="metro-nav-block nav-block-purple double">
	                        <a href="<?php //echo $quickpayment;?>" data-original-title="">
	                            <i class="icon-eye-open"></i>
	                            <div class="info"></div>
	                            <div class="status"><?php //echo $tr->translate('QUICK_PAYMENT');?> </div>
	                        </a>
	                    </div> -->
                    <div class="metro-nav-block nav-block-grey double">
                        <a href="<?php echo $bad_loan;?>" data-original-title="">
                            <i class="icon-remove-sign"></i>
                            <div class="info"></div>
                            <div class="status"><?php echo $tr->translate('BAD_LOAN');?></div>
                        </a>
                    </div>
                   
                     <div class="metro-nav-block nav-block-blue double">
                        <a href="<?php echo $rpt_loanrelease;?>" data-original-title="">
                            <i class="icon-external-link"></i>
                            <div class="info">$53412</div>
                            <div class="status"><?php echo $tr->translate('LOAN_DISBURSE');?></div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-purple double">
                        <a href="<?php echo $rpt_loancollect;?>" data-original-title="" class="text-center">
                            <i class="icon-cogs"></i>
                            <div class="status"><?php echo $tr->translate('RPT_CLIENT_PAYMENT');?></div>
                        </a>
                    </div>

                    <div class="metro-nav-block nav-block-blue double">
                        <a href="<?php echo $rpt_dailypayment;?>" data-original-title="">
                            <i class="icon-shopping-cart"></i>
                            <div class="info"></div>
                            <div class="status"><?php echo $tr->translate('LOAN_PAYMENT_COLLECTTION');?></div>
                        </a>
                    </div>
                    <!-- 
                    <div class="metro-nav-block nav-block-green double">
                        <a href="<?php //echo $rpt_collectfromco;?>" data-original-title="">
                            <i class="icon-external-link"></i>
                            <div class="info">$53412</div>
                            <div class="status"><?php //echo $tr->translate('REPORT_COLLECT_BY_CO');?></div>
                        </a>
                    </div> -->
                   
                    <div class="metro-nav-block nav-block-grey double">
                        <a href="<?php echo $rpt_loan_late;?>" class="text-center" data-original-title="">
                            <i class="icon-dashboard"></i>
                            <div class="status"><?php echo $tr->translate('LOAN_LATE');?></div>
                        </a>
                    </div>
                     <div class="metro-nav-block nav-block-yellow double">
                        <a href="<?php echo $rpt_paymenthistory?>" class="text-center" data-original-title="">
                            <i class=" icon-puzzle-piece"></i>
                           <div class="status"><?php echo $tr->translate('REPORT_LOAN_PAYMENT');?></div>
                        </a>
                    </div>
                     <div class="metro-nav-block nav-block-orange double">
                        <a href="<?php echo $rpt_expectincome;?>" class="text-center" data-original-title="">
                            <i class="icon-signout"></i>
                            <div class="status"><?php echo $tr->translate('REPORT_EXPECT_INCOME');?></div>
                        </a>
                    </div>
                     <div class="metro-nav-block nav-block-red double">
                        <a href="<?php echo $rpt_expectincome;?>" class="text-center" data-original-title="">
                            <i class="icon-signout"></i>
                            <div class="status"><?php echo $tr->translate('REPORT_COMISSION');?></div>
                        </a>
                    </div>
                    
                     <div class="metro-nav-block nav-block-orange double">
                        <a href="<?php echo $rpt_writoff;?>" data-original-title="">
                            <i class="icon-external-link"></i>
                            <div class="info">$53412</div>
                            <div class="status"><?php echo $tr->translate('PAY_OFF');?></div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-purple double">
                        <a href="<?php echo $rpt_loanoustading;?>" data-original-title="" class="text-center">
                            <i class="icon-cogs"></i>
                            <div class="status"><?php echo $tr->translate('LOAN_OUTSTADING');?></div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-blue double">
                        <a href="<?php echo $rpt_loanincome;?>" data-original-title="">
                            <i class="icon-shopping-cart"></i>
                            <div class="info"></div>
                            <div class="status"><?php echo $tr->translate('PROFIT');?></div>
                        </a>
                    </div>  
                </div>

                <div class="space10"></div>
                <!--END METRO STATES-->
            </div>
            <!-- END PAGE CONTENT-->
         </div>
         <!-- END PAGE CONTAINER-->
      </div>
      <!-- END PAGE -->  
   </div>
   <!-- END CONTAINER -->

   <!-- BEGIN FOOTER -->
   <div id="footer">
      &copy;CopyRight by Cam App Technology.
   </div>
   <!-- END FOOTER -->

   <!-- BEGIN JAVASCRIPTS -->
   <!-- Load javascripts at bottom, this will reduce page load time -->
   <script src="<?php echo $this->baseUrl()?>/js/jquery-1.8.3.min.js"></script>
   <script src="<?php echo $this->baseUrl()?>/js/jquery.nicescroll.js" type="text/javascript"></script>
   <script src="<?php echo $this->baseUrl()?>/assets/bootstrap/js/bootstrap.min.js"></script>

   <!-- ie8 fixes -->
   <!--[if lt IE 9]>
   <script src="js/excanvas.js"></script>
   <script src="js/respond.js"></script>
   <![endif]-->

   <!--common script for all pages-->
   <script src="<?php echo $this->baseUrl()?>/js/common-scripts.js"></script>
   <!-- END JAVASCRIPTS -->   
</body>
<!-- END BODY -->
</html>