<?php 
	$tr= Application_Form_FrmLanguages::getCurrentlanguage();
	$rpt_client = $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-client'));
	$rpt_callteral = $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-calleteral'));
	$rpt_change_call = $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-calleteral-change'));
	$rpt_client_blacklist = $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-clientblacklist'));
	$rpt_return_call = $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-returncollteral'));
?>
  <style>
  ul.link-rpt li a {
	color: #3A3939;
    height: 50px;
  	width:180px;
    display: block;
    padding: 10px;
    background: #D6D6D6;
  	font-family: 'Kh Battambang','Khmer Battambang' !important;
  	text-align: center;
  	word-wrap: break-word;
  } 
    ul.link-rpt li {
	float:left; margin:10px;
    list-style: none;
    border:1px solid #B1B0AF;
    word-wrap: break-word;
    
  } 
  </style>
 <div style="background:#ccc; width: 100%;">
  	<ul class="link-rpt">
  		<li><a href="<?php echo $rpt_client;?>"><?php echo $tr->translate('LIST_OF_CLIENT');?></a></li>
  	</ul>
</div>