<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("Chartaccount"));
$frms = $this->frm_chartaccount;
?>
<script>
dojo.require("dijit/form/DateTextBox");
</script>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'accounting','controller'=>'generaljurnal','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
    <table>
    <tr width="20%">
     <td><?php echo $frms->getElement("adv_search");?></td>
     <td><?php echo $frms->getElement('status');?></td>
     <td><?php echo $frms->getElement("btn_search");?></td>
   </tr>
   </table>
   <?php echo $this->list;?>
</form>
