<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_CLIENT'));
?>
<?php  $frm = $this->frm_index;?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.CheckBox");
dojo.require("dijit.Dialog");
dojo.require("dijit.layout.TabContainer");
</script>
<form id='add_client' action="<?php echo $this->url(array('module'=>'mygroup','controller'=>'index','action'=>'add')); ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">
			if(this.validate()) {
				if(dijit.byId('province').get('value')==0){
					alert('Province required');
					dijit.byId('province').focus();
					return false;
			    }
				return true;
			} else {
				return false;
			}
</script>
<table  width="50%" style="margin: 0 auto">
	<tr>
		<td style="/* overflow: scroll;max-width:300px;overflow-y:hidden; */">
				<style>
				.dojoxGridSortNode{
						text-align: center;
						height: 30px;
					}
					.dijitTabPaneWrapper , .dijitContentPane,.dijitTabListContainer-top{max-width: 99% !important;}
				</style>
					<div style="width:100%;overflow-x:hidden;overflow-y:hidden;" dojoType="dijit.layout.ContentPane" title="<?php echo $tr->translate('ADD_CLIENT');?>" selected="true">
						<fieldset>
							<legend><strong><?php echo $tr->translate("ADD_CLIENT");?></strong></legend>
							<table style="margin: 0 auto; width:20%;" cellspacing="10">
								<tr>
									<td><?php echo $tr->translate("catagory")?></td>
									<td><?php echo $frm->getElement('catagory');?></td>
											
								</tr>
								<tr>
									<td><?php echo $tr->translate("decription")?></td>
									<td><?php echo $frm->getElement('decription');?></td>
										
								</tr>
						    </table>
					</fieldset>
				</div>

				<div style="text-align: center;">
				<input type="reset" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"
								 iconClass="dijitIconClear" />
				<input type="submit" value="SAVE_CLOSE" tabindex="2" label="<?php echo $tr->translate('SAVECLOSE');?>" id="save_close" dojoType="dijit.form.Button" name="save_close"
								 iconClass="dijitEditorIcon dijitEditorIconSave" />
			    <input type="submit" value="SAVE_NEW" tabindex="1" label="<?php echo $tr->translate('SAVENEW');?>" id="save_new" dojoType="dijit.form.Button" name="save_new"
								 iconClass="dijitEditorIcon dijitEditorIconSave"/>
			</div>
		</td>
	</tr>
</table>
</form>
<table>
<tr>
</tr>
</table>
<?php
echo $this->frm_popup_district;
echo $this->frm_popup_village;
echo $this->frm_popup_comm;
?>

<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:30%;" id="popup_doc_type" >
		<form style="background-color: buttonface; width:100%;" id='frm_client_doc_type' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
				<tr>
					<td>
						<fieldset style="background-color: buttonface;">
						<legend align="center" ><?php echo $tr->translate('ADD_DOC_TYPE');?></legend>
							<table style="margin: 0 auto; width: 100%;  padding:10px;" cellspacing="7" >
								<tr>
									<td><?php echo $tr->translate('NAME');?></td>
									<td>
										<input dojoType="dijit.form.ValidationTextBox"   class="fullside" id="doc_name" name="doc_name" value="" type="text">
									</td>
								</tr>

								<input type="hidden" name="type"	id="type" dojoType="dijit.form.TextBox" />

								<tr>
									<td colspan="4" align="center">
										<input type="button" value="ចាកចេញ" label="Close" id="close" name="close" dojoType="dijit.form.Button"
										​ ​​iconClass="dijitIconUndo" onclick="hideDialog1();"/>
										<input type="button" value="save" label="SAVE" id="save" name="save" dojoType="dijit.form.Button"
										 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addNewDocumentType();"/>
									</td>
								</tr>

							</table>
					</fieldset>
					</td>
				</tr>
			</table>

		</form>
	</div>
</div>






