<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("Client List"));
//$frm = $this->frm_search;
$frms=$this->frm_index;
?>
<script>
dojo.require("dojo.data.ItemFileWriteStore");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.CheckBox");
dojo.require("dijit.Dialog");
dojo.require("dijit.layout.TabContainer");
</script>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'mygroup','controller'=>'index','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
<table>
   <tr>
   <td>
   	<input type="text"  name="adv_search" placeholder=""><td>

      <td><?php  //echo $frm->getElement('search_village');?></td>
      <td><?php //echo $frm->getElement('status');?></td>
      <td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
	  </td>
   </tr>

</table>
<?php 
    print_r ($this->myview);
?>
</form>


