<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_COM')); 
?>
<?php  $dailywork= $this->frm_dailywork;?>
<script>
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.Textarea");
	
</script>
<form id="add_province" action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
	</script>
	<table cellspacing="20" style="margin: 0 auto; width: 600px">
		<tr>
			<td>
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("CONTACT_LIST");?></strong></legend>
					<table cellspacing="20" width="100%" >
						<tr>
							<td align="center" valign="top">
								<table style="margin: 0 auto; width:100%;" cellspacing="10">
									<tr>
										<td><?php echo $tr->translate("Contact_Name")?></td>
										<td><?php echo $dailywork->getElement("name");?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("Phone")?></td>
										<td><?php echo $dailywork->getElement("phone");?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("CATEGORY_PRODUCT")?></td>
										<td><?php echo $dailywork->getElement("category");?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("DATE")?></td>
										<td><?php echo $dailywork->getElement("start_date");?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("NOTE")?></td>
										<td><?php echo $dailywork->getElement("note");?></td>
									</tr>
									<tr>
										<td colspan="2" align="center">
											<input type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>"dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
											<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button" 
												iconClass="dijitEditorIcon dijitEditorIconSave" />
											<input type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVENEW');?>" dojoType="dijit.form.Button" 
												iconClass="dijitEditorIcon dijitEditorIconSave" />
										</td>
									</tr>					
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
	</table>	
</form>