<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_search;
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPORT_INCOME");?></title>
<form name="frm_rptstaff" action="<?php echo $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-income')); ?>" dojoType="dijit.form.Form" method="post">
	<table style="width:30cm; margin: 0 auto;">
		<tr>  
	        <td><?php echo $frm->getElement("adv_search");?></td>
	        <td><?php echo $frm->getElement('branch_id');?></td>
	        <td><?php echo $frm->getElement('category_id');?></td>
	   		<td><?php echo $frm->getElement('currency_type');?></td>
	   		<td><?php echo $frm->getElement('start_date');?></td>
	   		<td><?php echo $frm->getElement('end_date');?></td>
	   		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
	   </tr>
	</table>
 </form> 
<div style=" width:29cm;min-height:22cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
    	 <div id="divPrint">
    	 	<style>
					.style{
						line-height: 20px;font-size: 14px !important;
						font-family: 'Khmer OS Battambang';
						}
						th{padding: 5px;}
					</style>
        	<table width="100%" style="font-family:'Khmer OS Battambang';" style="margin:0; padding:0;border:none;" >
        	<tr>
                <td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                <td width="60%" valign="top">
                <h2 style="text-align:center; font-size:18px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("BRAND_TITLE");?></label></h2>
                <h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("REPORT_INCOME");?></label></h2>
                <p style="text-align:center; font-size:14px; font-family:'Khmer MEF2'"><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("d-M-Y",strtotime($this->list_end_date['end_date']));?></p>
                </td>
                <td width="20%"></td>
             </tr> 
            <tr>
            	<td colspan="3" id="exportExcel">
            		<table  border="1" width="100%" style="border-collapse:collapse; line-height: 24px; font-size: 14px; border:solid 1px #000;" >  
				    	<tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 14px; line-height: 24px; font-size:14px; padding:5px 0px; " >
							<td ><?php echo $tr->translate("NUM");?></td>
						    <td><?php echo $tr->translate("BRANCH_NAME");?></td>
						    <td><?php echo $tr->translate("INCOME_TITLE");?></td>
						    <td><?php echo $tr->translate("RECEIPT_NO");?></td>
						    <td><?php echo $tr->translate("CLIENT_NAME");?></td>
						    <td><?php echo $tr->translate("CATEGORY");?></td>
						    <td><?php echo $tr->translate("TOTAL_INCOME");?></td>
						    <td><?php echo $tr->translate("CHEQUE");?></td>
						    <td><?php echo $tr->translate("NOTE");?></td>
						    <td><?php echo $tr->translate("DATE");?></td>
						</tr>
				       <?php $branch_id=''; $i=0; $total=0; if(!empty($this->row))foreach($this->row as $key =>$row){ $i++;?>
						<tr style="font-size: 14px; line-height:25px;" align="left">
						   <td align="center">&nbsp;<?php echo $i; ?></td>
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $row['branch_name'];?></td>
						   <td align="center" style="min-width: 120px;max-width: 150px;">&nbsp;<?php echo $row['title'];?></td>
						   <td align="center">&nbsp;<?php echo $row['invoice'];?></td>
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $row['client_name'];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $row['category_name'];?></td>
						   <td align="center">&nbsp;<?php echo number_format($row['total_amount'],2);?></td>
						   <td align="center">&nbsp;<?php echo $row['cheque'];?></td>
						   <td align="center">&nbsp;<?php echo $row['description'];?></td>
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo date("d-M-Y",strtotime($row['date']));?></td>
						</tr>
							<?php $total = $total +$row['total_amount'];?>
						<?php }?>
				    </table>
            	</td>
            </tr>
            <tr style=" border-bottom: solid 1px #fff; border-left: solid 1px #fff;  border-right: solid 1px #fff;">
				<td colspan="11">
					<table align="left" style="margin-right: 6px;">
						  <tr style="font-size:10px; color:#000; height: 18px;"​ align="center">
							<td style="width:146px; font-weight:bold; font-size: 16px;">&nbsp;<?php echo $tr->translate('TOTAL_INCOME');?>&nbsp;</td>
							<td style="background: rgba(249, 225, 11, 0.7);  color:#000; font-weight:bold; width:112px; font-size: 14px;"><?php echo $i;?></td>
							<td style="background: rgba(249, 225, 11, 0.7); color:#000; font-weight:bold; width:112px; font-size: 14px;">$ <?php echo number_format($total,2);?></td>
						  </tr>
					</table>
				</td>
			</tr>
            </table>
			
    	</td>
    </tr>
</table>
		<br />
		   <table align="center" width="100%">
				   <tr style="font-size: 14px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>
</div>
