<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_search;
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<style>
.hover:hover{background: #ccc;}
</style>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPORT_DAILY_CASH");?></title>
<form name="frm_rptstaff" action="<?php echo $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-daily-cash')); ?>" dojoType="dijit.form.Form" method="post">
	<table style="width:28cm; margin: 0 auto;">
		<tr>  
	        <td><?php echo $frm->getElement("adv_search");?></td>
	        <td><?php echo $frm->getElement('branch_id');?></td>
	   		<td><?php echo $frm->getElement('client_name');?></td>
	   		<td><?php echo $frm->getElement('start_date');?></td>
	   		<td><?php echo $frm->getElement('end_date');?></td>
	   		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
	   </tr>
	</table>
 </form> 
<div style=" width:28cm;min-height:22cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
	<table style="font-family: 'Khmer OS Content'; width:100%;"  >
		<tr>
    		<td align="center">
    	 		<div id="divPrint">
    	 			<style>
						.style{
							line-height: 20px;font-size: 12px !important;
							font-family: 'Khmer OS Battambang';
						}
						th{padding: 5px;}
					</style>
        			<table width="100%" style="font-family:'Khmer OS Battambang';" style="margin:0; padding:0;border:none;" >
			        	<tr>
			                <td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
			                <td width="60%" valign="top">
			                 <h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("ស្ថានីយ៏ទឹកស្អាតព្រៃផ្តៅ");?></label></h2>
			                </td>
			                <td width="20%"></td>
			             </tr>
			             <tr>
			             	<td width="20%">&nbsp;</td>
			                <td width="60%" valign="top">
			                <h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("ទូរស័ព្ទលេខ : 016 885 866/ 015 777 262");?></label></h2>
			                <p style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("វិក្កយបត្រ");?></p>
			                </td>
			                <td width="20%"></td>
			             </tr>
             
			             <tr>
			             	<td  colspan="3">
			             		<table width="100%">
			             			<tr>
			             				<td width="25%"><?php echo $tr->translate("ឈ្មោះអតិថិជន:");?></td>
			             				<td width="25%">&nbsp;</td>
			             				<td width="25%"><?php echo $tr->translate("លេខកូដ:");?></td>
			             				<td width="25%">&nbsp;</td>
			             			</tr>
			             			<tr>
			             				<td width="25%"><?php echo $tr->translate("គិតចាប់ពីថ្ងៃទី:");?></td>
			             				<td width="25%">&nbsp;</td>
			             				<td width="25%"><?php echo $tr->translate("លេខទូរស័ព្ទ:");?></td>
			             				<td width="25%">&nbsp;</td>
			             			</tr>
			             			<tr>
			             				<td width="25%"><?php echo $tr->translate("រហូតដល់:");?></td>
			             				<td width="25%">&nbsp;</td>
			             				<td width="25%"><?php echo $tr->translate("អាស័យដ្ឌាន:");?></td>
			             				<td width="25%">&nbsp;</td>
			             			</tr>
			             		</table>
			             	</td>
			                
			             </tr>
            
			           	<tr>
			            	<td colspan="3" id="exportExcel">
			            			<table width="100%" border="1" style="border-collapse:collapse; border:1px solid #000; " cellspacing="0">
						                <tr bgcolor="#c1d0f3" class="style" align="center" style="padding:0px 2px;white-space: nowrap;">
						                    <td  width="15%"><?php echo $tr->translate("លេខចាស់");?></td>
						                    <td width="15%"><?php echo $tr->translate("លេខថ្មី");?></td>
						                    <td width="15%"><?php echo $tr->translate("សរុប(M3)");?></td>	       
						                    <td width="25%"><?php echo $tr->translate("តម្លៃឯកតា(KHR)");?></td>
						                    <td width="30%"><?php echo $tr->translate("សរុប(KHR)");?></td>	
						                   
						                </tr>
						                <tr class="style" align="center" style="padding:0px 2px;white-space: nowrap;">
						                    <td  width="15%"><?php echo $tr->translate("&nbsp;");?></td>
						                    <td  width="15%"> <?php echo $tr->translate("&nbsp;");?></td>
						                    <td  width="15%"><?php echo $tr->translate("&nbsp;");?></td>	       
						                    <td  width="25%"><?php echo $tr->translate("2,500 ៛");?></td>
						                    <td  width="30%"><?php echo $tr->translate("&nbsp;");?></td>	
						                   
						                </tr>
						                <tr class="style" align="center" style="padding:0px 2px;white-space: nowrap;">
						                    <td  width="15%"​​​​ colspan="3"><?php echo $tr->translate("&nbsp;");?></td>
						                          
						                    <td  width="25%" colspan="2">
						                    	<table width="100%" border="1" style="border-collapse:collapse; border:1px solid #000; " cellspacing="0">
						                    		<tr class="style" align="center" style="padding:0px 2px;white-space: nowrap;">
						                    			<td  width="45%"><?php echo $tr->translate("2,500 ៛");?></td>
						                    			<td  width="54%"><?php echo $tr->translate("&nbsp;");?></td>	
						                    			
						                    		</tr>
						                    		
						                    		<tr class="style" align="center" style="padding:0px 2px;white-space: nowrap;">
						                    			<td  width="43%"><?php echo $tr->translate("2,500 ៛");?></td>
						                    			<td  width="57%"><?php echo $tr->translate("&nbsp;");?></td>	
						                    		</tr>
						                    		
						                    		<tr class="style" align="center" style="padding:0px 2px;white-space: nowrap;">
						                    			<td  width="40%"><?php echo $tr->translate("2,500 ៛");?></td>
						                    			<td  width="60%"><?php echo $tr->translate("&nbsp;");?></td>	
						                    		</tr >
						                    		
						                    		<tr class="style" align="center" style="padding:0px 2px;white-space: nowrap;">
						                    			<td  width="40%"><?php echo $tr->translate("2,500 ៛");?></td>
						                    			<td  width="60%"><?php echo $tr->translate("&nbsp;");?></td>		
						                    		</tr>
						                    		<tr class="style" align="center" style="padding:0px 2px;white-space: nowrap;">
						                    			<td  width="40%"><?php echo $tr->translate("2,500 ៛");?></td>
						                    			<td  width="60%"><?php echo $tr->translate("&nbsp;");?></td>	
						                    		</tr>
						                    	</table>
						                    </td>
						                 
						                   
						                </tr>
						                
					            </table>
			            	</td>
			            	
			            </tr>
            			
            	</table>
           		 </div>
    		</td>
    	</tr>
	</table>

		<br />
		   <table align="center" width="100%">
			   <tr style="font-size: 16px;">
			        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
			        <th></th>
			        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
			        <th></th>
			        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
			   </tr>
			</table>
</div>

