<?php	
	$this->headTitle('Add Sell'); 
	echo $this->headTitle();
	$frm = $this->frm_loan;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	
	//print_r($this->rs);
?>
<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>	
	<script src="<?php echo $baseurl;?>/js/help.js"></script>
   <script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog"]);
   </script>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'transferproject','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				branch_id = dijit.byId('branch_id').get('value');
				if (branch_id=='' || branch_id==-1){
					alert('Please Select Branch!');
					dijit.byId('branch_id').focus();
					return false;
				}
				client = dijit.byId('member').get('value');
				if (client=='' || client==-1){
					alert('Please Select Client Name !');
					dijit.byId('member').focus();
					return false;
				}
				
				old_paid = dijit.byId('paid_before').get('value');
				new_paid = dijit.byId('deposit').get('value');
				if(old_paid > new_paid){
					alert('You can not pay less than old paid amount');
					dijit.byId('deposit').focus();
					return false;
				}
				return true;
			}else {
				return false;
			}
</script>
<table width="100%" style="margin-top:-10px;">
	<tr>
		<td>
				<fieldset>
					<legend><strong><?php echo $tr->translate("INFO_INDILOAN")?></strong></legend>
					<table cellspacing="10"  width="100%" style="margin-top: -10px;">
						<tr>
							<td><?php echo $tr->translate("BRANCH_NAME")?></td>
							<td><?php echo $frm->getElement('branch_id');?></td>
							<td><?php echo $tr->translate("LOAN_NO")?></td>
							<td><input id='loan_number' /></td>
							<td><?php echo $tr->translate("CUSTOMER_CODE")?></td>
							<td><input id="customer_code" /></td>
							</tr>
						<tr>
							<td><?php echo $tr->translate("DATE_BUY")?></td>
							<td><?php echo $frm->getElement('date_buy');?></td>
							<td><?php echo $tr->translate("RECEIPT_NO")?></td>
							<td><?php echo $frm->getElement('receipt');?></td>
							<td><?php echo $tr->translate("CUSTOMER_NAME")?></td>
							<td><input id="member" /> <?php //echo $frm->getElement('member');?></td>
						</tr>
						<tr style="background: #edf7f8;">
							<td colspan="6" style="border-bottom:1px solid #aac4e6;"><strong><?php echo $tr->translate("PROPERTY_INFORMATION")?></strong></td>
						</tr>
						<tr height="40px">
							<td><?php echo $tr->translate("LAND_CODE")?></td>
							<td><input id="land_code" /><?php //echo $frm->getElement('');?></td>
							<td><?php echo $tr->translate("DESCRIPTION")?></td>
							<td style="height: 50px; border:1px solid #aac4e6; widht:100%;" colspan="4"><label id="land_information"></label><?php //echo $tr->translate("Address")?></td>
						</tr>
						<tr>
						    <td><?php echo $tr->translate("TOTAL_SOLD")?></td>
							<td><?php echo $frm->getElement('total_sold');?></td>
							<td><?php echo $tr->translate("PAID")?></td>
							<td><?php echo $frm->getElement('paid_before');?></td>
							<td><?php echo $tr->translate("Balance")?></td>
							<td><?php echo $frm->getElement('balance_before');?></td>
						</tr>
						<tr>
							<td colspan="6" style="border-bottom:1px solid #aac4e6;"><strong><?php echo $tr->translate("TRANSFER_PROPERTY_INFORMATION")?></strong></td>
						</tr>
						<tr height="40px">
							<td><?php echo $tr->translate("BRANCH_NAME")?></td>
							<td><?php echo $frm->getElement('to_branch_id');?></td>
							<td><?php echo $tr->translate("TO_LAND_CODE")?></td>
							<td><input id="to_land_code" /><?php //echo $frm->getElement('');?></td>
							<td><?php echo $tr->translate("DESCRIPTION")?></td>
							<td style="height: 50px; border:1px solid #aac4e6; widht:200px; font-size: 12px;" colspan="2"><label id="to_land_information"></label><?php //echo $tr->translate("Address")?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("LAND_PRICE")?></td>
							<td><?php echo $frm->getElement('land_price');?></td>
							<td><?php echo $tr->translate("HOUSE_PRICE")?></td>
							<td><?php echo $frm->getElement('house_price');?></td>
							<td><?php echo $tr->translate("TOTAL_SOLD")?></td>
							<td><?php echo $frm->getElement('to_total_sold');?></td>
						</tr>
						<tr style="background: #edf7f8;">
							<td colspan="6" style="border-bottom:1px solid #aac4e6;"><strong><?php echo $tr->translate("PAYMENT_INFORMATION")?></strong></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Discount")?></td>
							<td><?php echo $frm->getElement('discount');?></td>
							<td><?php echo $tr->translate("TOTAL_PAYMENT")?></td>
							<td><?php echo $frm->getElement('sold_price');?></td>
							<td><?php echo $tr->translate("OTHER_FEE")?></td>
							<td><?php echo $frm->getElement('other_fee');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("PAYMENT_TYPE")?></td>
							<td><?php echo $frm->getElement('schedule_opt');?></td>
							<td><?php echo $tr->translate("Paid")?></td>
							<td><?php echo $frm->getElement('deposit');?></td>
							<td><?php echo $tr->translate("Balance")?></td>
							<td><?php echo $frm->getElement('balance');?></td>
						</tr>
						<tr>
						    <td><lable id='lbl_period'><?php echo $tr->translate("TERM_BORROW")?></lable>(Months)</td>
							<td><?php echo $frm->getElement('period');?></td>
							<td><?php echo $tr->translate("INTEREST_RATE")?></td>
							<td><?php echo $frm->getElement('interest_rate');?></td>
							<td><label id="lbl_payment"><?php echo $tr->translate("AMOUNT_FUND_GRAICE_PARIOD")?></label></td>
							<td><?php echo $frm->getElement('fixed_payment');?></td>
						</tr>
						<tr>
							<td><label id="lbl_release"><?php echo $tr->translate("LOAN_RELEASE")?></label></td>
							<td><?php echo $frm->getElement('release_date');?></td>
							<td><?php echo $tr->translate("FIRST_PAYMENT")?></td>
							<td><?php echo $frm->getElement('first_payment');?></td>
							<td><?php echo $tr->translate("LIFE_LOAN")?></td>
							<td><?php echo $frm->getElement('date_line');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NOTE")?></td>
							<td><?php echo $frm->getElement('note')?></td>
						</tr>
					</table>
				</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
			<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
			<input type="submit" label="<?php echo $tr->translate("SAVECLOSE");?>" name='saveclose' value='saveclose' dojoType="dijit.form.Button" iconClass="dijitIconDelete"/>
			<input type="submit" label="<?php echo $tr->translate("SAVENEW")?>" name='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask"/>
			<input type="button" onclick="addPreviewLoan();" label="<?php echo $tr->translate("PREVIEW")?>" name='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask" />
		</td>
	</tr>	
</table>
<div class="dijitHidden">
<style>
.print tr td{
	padding:5px 2px; 
}
</style>
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'កាលវិភាគត្រូវបង់ប្រាក់'" id="lbl_schedule" style="width:1000px">
	<div id="rpt_print" class="print" style="text-align: center;">
		<div id="t_amountmoneytype" name="t_amountmoneytype">
		</div>
		<input style="text-align: center;" type="button" onclick="printSave();" label="<?php echo $tr->translate("បោះពុម្ភបង្កាន់ដៃ")?>" name='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask" />
	</div>
</div>
</div>
<div class="dijitHidden" style="width: 22cm !important; height: 11cm ; padding: 0px; margin: 0px;">
	<div data-dojo-type="dijit.Dialog" style="width:22cm;" align="center" data-dojo-props="title:'<?php echo $tr->translate("PAYMENT_RECEIPT");?>'" id="terms" >
		 <div class="header">
		     <table cellspacing="0"  cellpadding="0" style="width: 21cm;  font-size:14px; color:rgba(14, 0, 107, 1); padding: 0px; margin: 0px;">
		          <tr>
		              <td colspan="8"  align="center"><strong style="font-family:'Khmer OS Muol';font-size: 20px;color: rgb(47, 70, 149);"> បុរី &nbsp;<font style="color: rgb(246, 86, 74);">ភ្នំពេញថ្មី </font>&nbsp;</strong>
		              </td>
		          </tr>
		     </table>
		</div>
		<div id="divPrint" style="width: 21cm !important; height: 14.4cm ; padding: 0px; margin: 0px;">
			<style>
				.fontbig{
					font-size: 15px;	
				}
				.fonttel{
					font-size: 18px;	
				}
				.pleft{
					width: 110px;	
				}

				.label{ font-weight: bold;font-size: 22px;}
				.value{ font:bold 12px 'Khmer OS Battambang';border: 1px solid rgba(14, 0, 107, 1); height: 25px; padding: 0 2px;width: 100%;margin-right:5px; display: block;
						line-height: 25px;
					    text-align: center;
						}
				.values{ border: 1px solid rgba(14, 0, 107, 1);; height: 25px; padding: 0 10px;display: block;
						line-height: 25px;}
				.h{}
.print tr td{
	padding:2px 2px; 
}
			   .khmerbold{font:bold 12px 'Khmer OS Battambang';}
			   .khmer{font:12px 'Khmer OS Battambang';}
			   .one{white-space:nowrap;}
			   .h{ margin-top: -10px;/*margin-left:4px;*/}
			</style>
			<div id="lbl_mainform">	
			<table  style="white-space: nowrap;font-size:12px; color:rgba(14, 0, 107, 1); padding:-10px 10px 0px 5px; margin: 0px;" class="print" cellspacing="0"  cellpadding="5" >
				<tr>
				    <td colspan="7"  style="font:bold 18px 'Kh Muol';" align="center"><u><b><strong style=" font-family: Arial Black;font-family:'Khmer MEF2';">បង្កាន់ដៃទទួលប្រាក់</strong></b></u>
				        <div style="line-height:10px;"><strong style="font-size: 18px;font-weight:bold">OFFICIAL RECEIPT</strong></div>
				    </td>
				</tr>
				<tr> <td colspan="7" height="5px"></td></tr>
				<tr style="white-space: nowrap;">
				    <td colspan="5"></td>
				    <td class="one khmerbold" style="width:10%;">&nbsp;លេខបង្កាន់ដៃ</td>
				    <td style="width:35%;"><strong><label id="lb_receipt" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
				    <td style="width:10%;" class="one khmerbold" >លេខកូដលក់</td>
				    <td style="width:35%;"><strong><label id="lb_student_id" class="value"></label></strong></td>
				    <td style="width:5px;"></td>
				    <td style="width:10%;" class="one khmerbold" >ប្រភេទបង់</td>
				    <td style="width:35%;"><strong><label id="lb_paymentid" class="value"></label></strong></td>
				 	<td class="one khmerbold" style="width:10%;">&nbsp;ថ្ងៃលក់</td>
				    <td style="width:35%;"><strong><label id="lb_buydate" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
				    <td class="one khmerbold">ឈ្មោះ​អតិថិជន </td>
				    <td ><strong><label id="lb_customer" class="value"></label></strong></td>
				    <td ></td>
				    <td class="one khmerbold">លេខផ្ទះ</td>
                    <td><strong><label id="lb_hourseno" class="value"></label></strong></td>
                    <td class="one khmerbold">&nbsp;តម្លៃលក់</td>
                    <td><strong><label id="lb_price" class="value"></label></strong></td>
                </tr>
				<tr style="white-space: nowrap;">
				    <td class="one khmerbold">​បញ្ចុះតម្លៃ</td>
				    <td><strong><label id="lb_discount" class="value"></label></strong></td>
				    <td ></td>
				    <td class="one khmerbold">តម្លៃផ្សេងៗ</td>
				    <td><strong><label id="lb_otherfee" class="value"></label></strong></td>
				     <td class="one khmerbold">&nbsp;ប្រាក់ត្រូវបង់សរុប</td>
                    <td><strong><label id="lb_amount" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold">ប្រាក់បានបង់</td>
				    <td><strong><label id="lb_paid" class="value"></label></strong></td>
				    <td ></td>
					<td class="one khmerbold">ប្រាក់នៅសល់</td>
					<td><strong><label id="lb_balance" class="value"></label></strong></td>
					<td class="one khmerbold">&nbsp;បញ្ចុះតម្លៃ</td>
					<td><strong><label id="lb_discount" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold">សែក</td>
					<td colspan="4"><strong><label id="lb_moneynote" class="value"></label></strong></td>
				    <td class="one khmerbold" >&nbsp;ថ្ងៃបានបង់ប្រាក់</td>
				    <td class="one khmerbold" style="white-space: nowrap;"><label style="white-space: nowrap;" class="value"> &nbsp;&nbsp;
				    	<?php  $today = date("F j, Y, g:i a");echo $today; ?></label>
				    </td>
				    <td></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold">សម្គាល់</td>
				    <td colspan="6"><strong style="white-space: nowrap;"><label style="white-space: nowrap;" id="lb_noted" class="value"></label></strong></td>
				</tr>
				
				<tr style="white-space: nowrap;">
				    <td class="khmerbold" style="line-height: 14px;"colspan="5"  align="center" >&nbsp;&nbsp;<strong style=" font-family: Arial Black;font-family:'Khmer MEF2';">ស្នាមមេដៃអ្នកប្រគល់</strong></td>
				    <td colspan="2" class="khmerbold" style="line-height: 14px;" align="center" ><strong style=" font-family: Arial Black;font-family:'Khmer MEF2';">ស្នាមមេដៃអ្នកទទួល</strong></td>
				</tr>
				<tr style="white-space: nowrap;" height="65px;">
					<td class="one khmerbold" colspan="5" align="center" valign="bottom">
						<h4 style="padding-right: 5px ! important;margin-bottom: -10px  !important;">
							<lable id="lbl_customer"></lable>
						</h4>
					</td>
				    <td class="one khmerbold" colspan="2" align="center" valign="bottom">&nbsp;
				  			<h4 style="padding-right: 5px ! important;margin-bottom: -10px  !important;">
				              <?php $session_user=new Zend_Session_Namespace('auth');
						           $last_name=$session_user->last_name;
						           $username = $session_user->first_name;
						           echo $last_name." ".$username;?></h4>  
				  </td>
				    <td></td>
				</tr>
				<tr style="line-height: 15px;font-size: 10px;font-family:'Khmer OS Battambang';">
			         <td valign="top">
			          <span style="text-decoration:underline;font-size: 11px;">សំគាល់ ៖</span>
			         </td>
			         <td colspan="6">
			          <span>*</span>&nbsp;&nbsp;<span> ក្នុងករណីបង់ប្រាក់ពុំទៀងទាត់នឺងត្រូវផាកពិន័យដូចចែងក្នុងកិច្ចសន្យា</span><br>
			          <span>*</span>&nbsp;&nbsp;<span> រាល់ការបង់ប្រាក់ជាមូលប្បទានប័ត្រ នឺងអាចមានសុពលភាពលុះត្រាតែទឺកប្រាក់នៅក្នុងមូលប្បទានប័ត្រ</span><br>
			          <span> &nbsp;&nbsp;&nbsp;&nbsp;ត្រូវបានដាក់បញ្ចូលក្នុងគណនេយ្យរបស់ក្រុមហ៊ុនរួចរាល់។ </span><br>
		            </td>
            </tr>
	         <tr style="line-height: 15px;font-size: 10px;">
		         <td colspan="7" style="border-bottom: 2px solid rgba(255, 235, 59, 0.88)">
		         </td>
	        </tr>
	        <tr style="line-height: 15px;font-size: 10px;">
         		<td colspan="7" style="border-bottom: 2px dotted #000;    padding-bottom: 6px;">
		          <table width="100%" style="font-family:'Khmer OS Battambang';font-size:11px;line-height: 12px;margin-top: -5px;"> 
		           <tbody><tr>
		            <td width="22%">
		             <img style="width:70%;height: 25px;" src="<?php echo $this->baseUrl();?>/images/bppt_letter.png">
		            </td>
		            <td width="40%">
		             វេបសាយ :  <span style="font-size:13px;">www.boreyphnompenhthmey.com</span>
		            </td>
		            <td width="40%" align="right">
		             អ៊ីម៉ែល : <span style="font-size:13px;">info@boreyphnompenhthmey.com</span>
		            </td>
		           </tr>
		           <tr height="5px">
		            <td colspan="2">
		             ការិយាល័យ :  បុរី ភ្នំពេញថ្មី  ,  ផ្លូវលេខ 1986  ,   សង្កាត់  ភ្នំពេញថ្មី  ,  ខ័ណ្ឌ  សែនសុខ  ,   រាជធានីភ្នំពេញ
		            </td>
		            <td width="40%" align="right">
		             <span style="font-weight:bold;">ទូរស័ព្ទ : 012 933 666 , 097 815 7777 </span>
		            </td>
		           </tr>
		          </tbody></table>
		          
		         </td>
        </tr>
			</table>
			</div>
			<lable id="lbl_subform"></lable>
		</div>
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
			type="button" onclick="doPrint();printSubmit();">បោះពុម្ភ/Print</button>
	</div>
</div>
</form>
<script type="text/javascript">	
var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'get-il-loan-Detail')); ?>';
function getLaonPayment(){
	loan_number = dijit.byId("loan_number").get('value');
		dojo.xhrPost({
		    url: url_submit,
		    content : { 
			    'loan_number':loan_number,
			},	
			handleAs:"json",
			load: function(respone) {
					/*dijit.byId('identity').attr('value',"");
					dijit.byId('priciple_amount').attr('value',0);
					dijit.byId('os_amount').attr('value',0);
					dijit.byId('total_payment').attr('value',0);
					dijit.byId('amount_receive').attr('value',0);
					dijit.byId('discount').attr('value',0);
					dijit.byId('service_charge').attr('value',0);
					dijit.byId('penalize_amount').attr('value',0);
					dijit.byId('total_interest').attr('value',"");
					dijit.byId('amount_return').attr('value',0);
					dijit.byId('payment_term').attr('value',"");
					dijit.byId('currency_type').attr('value',"");*/
				
			},
			error: function(e) {
				//alert(e);
			}
		});
}

function setBranchID(){
	dijit.byId('to_branch_id').attr('value',dijit.byId('branch_id').get('value'));
}

function checkScheduleOption(){
	dijit.byId('first_payment').set("readOnly",false);
	dijit.byId('period').set("readOnly",false);
	dijit.byId('interest_rate').set("readOnly",false);
	dijit.byId('release_date').set("readOnly",false);
	dijit.byId('date_line').set("readOnly",true);
	method_id = dijit.byId('schedule_opt').get('value');

	amount_principal = dijit.byId('balance').get('value');	
	debt_amount = dijit.byId('period').get('value');
	
	if(method_id==4){
		dijit.byId('fixed_payment').set('readOnly',false);
		dojo.byId('lbl_payment').innerHTML="<?php echo $tr->translate("AMOUNT_GRAICE_PARIOD")?>";
		debt_term=30;
		collect_term = 1;//dijit.byId('collect_termtype').get('value');
		collect_amount = 1;//dijit.byId('amount_collect').get('value');
		collect_term=30;
		
		term = (debt_term*debt_amount)/(collect_term*collect_amount);
		
		interest_rate=dijit.byId('interest_rate').get('value')/12/(100);//(100/30day)
	
		top_pow = Math.pow((1+interest_rate),term);
		bellow = Math.pow((1+interest_rate),(term))-1;
		
		amount_payment = (amount_principal*interest_rate*top_pow)/(bellow);
		amount_payment = amount_payment.toFixed(2);
		dijit.byId('fixed_payment').attr('value',amount_payment);
	}else {
		dijit.byId('fixed_payment').attr('value',0);
		dijit.byId('fixed_payment').set("readOnly",true);
		if(method_id==1){//booking
			dijit.byId('release_date').set("readOnly",true);
			dijit.byId('first_payment').set("readOnly",true);
			dijit.byId('date_line').set("readOnly",false);
			dijit.byId('period').set("readOnly",true);
			dijit.byId('interest_rate').set("readOnly",true);
		}else if(method_id==2){//payoff
			dijit.byId('release_date').set("readOnly",true);
			dijit.byId('first_payment').set("readOnly",true);
			dijit.byId('interest_rate').set("readOnly",true);
			dijit.byId('period').set("readOnly",true);
			amount_principal = dijit.byId("sold_price").get("value");
			dijit.byId('deposit').attr("value",amount_principal);
			
		}else if(method_id==3){//times
			dojo.byId('lbl_period').innerHTML="<?php echo $tr->translate("TOTAL_INSTALLMENT")?>";
			dojo.byId('lbl_release').innerHTML="<?php echo $tr->translate("START_DATE")?>";
			total_collect = amount_principal/debt_amount;
			total_collect = total_collect.toFixed(2);
			dijit.byId('fixed_payment').attr("value",total_collect);
			dijit.byId('interest_rate').attr("value",1.5);
			dijit.byId('interest_rate').set("readOnly",true);
		}else if(method_id==5){//times
			dijit.byId('release_date').set("readOnly",true);
			dijit.byId('first_payment').set("readOnly",true);
			dijit.byId('interest_rate').set("readOnly",true);
			dijit.byId('period').set("readOnly",true);
		}
	}
}
function calculateDiscount(){
	total_sold = dijit.byId('to_total_sold').get('value');
	discount = dijit.byId('discount').get('value');
	other_fee = dijit.byId('other_fee').get('value');
	if(isNaN(other_fee)){
		other_fee=0;
	}if(isNaN(discount)){
		discount=0;
	}
	total_sold = total_sold-discount+other_fee;
	dijit.byId('sold_price').attr('value',total_sold);
	Balance();
}
function Balance(){
	price = dijit.byId('sold_price').get('value');
	deposit =dijit.byId('deposit').get('value');
	if(isNaN(deposit)){
		deposit=0;
	}
	if(deposit>price){
		alert("Deposit can not biger than price ");
		dijit.byId('deposit').focus();
		dijit.byId('deposit').attr('value',price)
		dijit.byId('balance').attr('value',0)
	}else{
	   dijit.byId('balance').attr('value',price-deposit);
	   checkScheduleOption();
	   }
}
function filterClient(){
	branch_id = dijit.byId('branch_id').get('value');
	getAllPropertyBranch(branch_id);
	getAllClientByBranch(branch_id);
	getAllClientNumberByBranch(branch_id);
	getAllSaleNumber(branch_id);
}
var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'transferproject','action'=>'getallland')); ?>';
function getAllPropertyBranch(branch_id){//used
	dojo.xhrPost({
		url:url_getland,	
		content:{ 
		    'branch_id':branch_id,
		    'action':1
		},		    
		handleAs:"json",
		load: function(data) {
			property_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('land_code').set('store', property_store);
		},
		error: function(err) {
		}
	});
} 

var url_getland_transfer = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
function getAllPropertyBranchTransfer(){//used
	to_branch_id = dijit.byId('to_branch_id').get('value');
	dojo.xhrPost({
		url:url_getland_transfer,	
		content:{ 
		    'branch_id':to_branch_id,
		},		    
		handleAs:"json",
		load: function(data) {
			property_store_transfer  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('to_land_code').set('store', property_store_transfer);
		    dijit.byId('to_land_code').attr('value','<?php echo $this->rs['to_houseid']?>');
		},
		error: function(err) {
		}
	});
} 

var url_getclient = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientbybranch')); ?>';
function getAllClientByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclient,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('member').set('store', client_store);
		},
		error: function(err) {
		}
	});
}
var url_getclientnum = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientnumberbybranch')); ?>';
function getAllClientNumberByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclientnum,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_number_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('customer_code').set('store', client_number_store);
		},
		error: function(err) {
		}
	});
}
var url_getloan = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getloannumber')); ?>';
function getLoanByBranch(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_getloan,	
		content:{ 
		    'branch_id':branch_id,
		    'is_group':0
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('sale_code').attr('value',data);
		},
		error: function(err) {
			//alert(err);
		}
	});
}

var url_getreceipt = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'get-receipt-number')); ?>';
function getReceiptByBranch(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_getreceipt,	
		content:{ 
		    'branch_id':branch_id,
		    'is_group':0
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('receipt').attr('value',data);
		},
		error: function(err) {
			//alert(err);
		}
	});
}
    function calCulatorBalance(){
    	//price = dijit.byId('land_price').get('value');
    	deposit =dijit.byId('deposit').get('value');
    	if(isNaN(deposit)){
    		deposit=0;
    	}
    	if(deposit>price){
    		alert("Deposit can not biger than price ");
    		dijit.byId('deposit').focus();
    		dijit.byId('deposit').attr('value',price)
    	}
        dijit.byId('balance').attr('value',price-deposit);
        checkScheduleOption();
    	
    }
    
    function checkValidateDate(){
		return true;
     }
    function setDefaultPaymentAmount(){
    	//amount_principal = dijit.byId('land_price').get('value');
    	debt_term = dijit.byId('pay_every').get('value');
    	debt_amount = dijit.byId('period').get('value');
    	if(debt_term==1){
    		debt_term=1;
    	}else if(debt_term==2){
    		debt_term=7;
    	}
    	else{
    		debt_term=30;
    	}
    	//collect_term = dijit.byId('collect_termtype').get('value');
		collect_amount = 1;
		if(collect_term==1){
			collect_term=1;
    	}else if(collect_term==2){
    		collect_term=7;
    	}
    	else{
    		collect_term=30;
    	}
		
    	term = (debt_term*debt_amount)/(collect_term*collect_amount);

		interest_rate=dijit.byId('interest_rate').get('value')/100;

		top_pow = Math.pow((1+interest_rate),term);
		bellow = Math.pow((1+interest_rate),(term))-1;
		
		amount_payment = (amount_principal*interest_rate*top_pow)/(bellow);
		}
	function hideDialog() {		
		dijit.byId("recript_dialog").hide();
		saveTrans(); 
	}
	function doPrint() {
		//alert(document.getElementById('lbl_mainform'));
		dojo.byId("lbl_subform").innerHTML= document.getElementById('lbl_mainform');//dojo.byId('lbl_mainform').HTML;//document.getElementById('lbl_mainform');
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    hideDialog();
	}
</script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");

var client_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->client_name));?> );
var client_number_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->client_code));?> );
var co_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->co_name));?> );
var property_store  = getDataStorefromJSON('id','name', null );
var property_store_transfer  = getDataStorefromJSON('id','name', null );

require(["dojo/ready"], function(ready){
	
	 ready(function(){
		filterClient();
		setBranchID();
		//getlandinfotransfer();//get to branch
		setFirstPaymentAndDateLine(3,<?php echo date('d-m-Y');?>,1);
		checkScheduleOption();
	  });
	 
	new dijit.form.FilteringSelect({
			store: property_store,//dojo.data.ObjectStore({objectStore: client_data}),
			autoComplete: true,
			required: false,		           
			name: "land_code",
			id: "land_code",
			searchAttr: "name",
			class: 'fullside',
			required:true,
			onChange: function() {
				land_code = dijit.byId('land_code').get('value');
				if(land_code==-1){
				}else{
					getlandinfo();
				}
		}
	}, "land_code");

	new dijit.form.FilteringSelect({
		store: property_store_transfer,//dojo.data.ObjectStore({objectStore: client_data}),
		autoComplete: true,
		required: false,		           
		name: "to_land_code",
		id: "to_land_code",
		searchAttr: "name",
		class: 'fullside',
		required:true,
		onChange: function() {
			land_code = dijit.byId('to_land_code').get('value');
			if(land_code==-1){
			}else{
				getlandinfotransfer();
			}
	}
}, "to_land_code");
	 
	new dijit.form.FilteringSelect({
	store: client_store,//dojo.data.ObjectStore({objectStore: client_data}),
	autoComplete: true,
	required: false,		           
	name: "member",
	id: "member",
	searchAttr: "name",
	required:true,
	class: 'fullside',
	onChange: function() {
		member = dijit.byId('member').get('value');
		if(member==-1){
			showPopupclient();
		}else{
			dijit.byId('customer_code').attr('value',member);
		}
}
	}, "member");
	
	new dijit.form.FilteringSelect({
	store: client_number_store,//dojo.data.ObjectStore({objectStore: client_number}),
	autoComplete: true,
	           
	required: false,		           
	name: "customer_code",
	id: "customer_code",
	searchAttr: "name",
	class: 'fullside',
	onChange: function() {
		customer_code = dijit.byId('customer_code').get('value');
		if(customer_code==-1){
			showPopupclient();
		}else{
			dijit.byId('member').attr('value',customer_code);
		}
    }
	}, "customer_code");

	new dijit.form.FilteringSelect({
		store: co_store,//dojo.data.ObjectStore({objectStore: client_number}),
		autoComplete: true,            
		required: false,		           
		name: "co_id",
		id: "co_id",
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			co_id = dijit.byId('co_id').get('value');
			if(co_id==-1){
				popupcreditofficer();
			}else{
			}
	    }
		}, "co_id");

	new dijit.form.FilteringSelect({
		store: co_store,//dojo.data.ObjectStore({objectStore: client_number}),
		autoComplete: true,            
		required: false,		           
		name: "loan_number",
		id: "loan_number",
		searchAttr: "name",
		class: 'fullside',
		onChange: function(){
			getInfoByLoanNumber();
	    }
		}, "loan_number");
	 
	});
</script>
<script type="text/javascript">
var url_submiinfo = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getloan-bymemberid')); ?>';
function getInfoByLoanNumber(){
	loan_id = dijit.byId('loan_number').get('value');
	dojo.xhrPost({
	    url: url_submiinfo,	
	    content : { 
		    'sale_id':loan_id ,
		},	
		handleAs:"json",
		load: function(data) {

			total_principal= data.total_principal;
			if(isNaN(total_principal) || total_principal==null){total_principal=0;}
		    paid_amount = data.paid_amount;
			if(isNaN(paid_amount) || paid_amount==null){paid_amount=0;}
			total_principal = parseFloat(paid_amount)+parseFloat(total_principal);
			
			dijit.byId('paid_before').attr('value',total_principal);
			
			dijit.byId("member").attr('value',data.client_id);
			dijit.byId('customer_code').set('readOnly',true);
			dijit.byId('land_code').attr('value',data.house_id)
			dijit.byId('member').set('readOnly',true);
			//dijit.byId('loan_number').attr('value','<?php //echo $this->rs['sale_id']?>');
			
		},
		error: function(err) {
			alert(err);
		}
	});
}
var sale_number_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_getsalenumber = "<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'get-sale-number')); ?>";
function getAllSaleNumber(branch_id){//used
	dojo.xhrPost({
		url:url_getsalenumber,	
		content:{ 
		    'branch_id':dijit.byId('branch_id').get('value')
		},		    
		handleAs:"json",
		load: function(data) {
			sale_number_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('loan_number').set('store',sale_number_store); 
		    dijit.byId('loan_number').attr('value','<?php echo $this->rs['sale_id']?>');
		},
		error: function(err) {
			
		}
	});
}
var url_getlandinfodetail = '<?php echo $this->url(array('module'=>'group','controller'=>'land','action'=>'getlandinfo')); ?>';
function getlandinfo(){
	dijit.byId('total_sold').attr('value',0);
	dijit.byId('sold_price').attr('value',0);
	dojo.xhrPost({
		url:url_getlandinfodetail,	
		content:{ 
		    'land_id':dijit.byId('land_code').get('value')
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('land_code').set('readOnly',true);
			dijit.byId('paid_before').set('readOnly',true);
			dijit.byId('balance_before').set('readOnly',true);

			dijit.byId('total_sold').attr('value',data.price);
			dojo.byId('land_information').innerHTML ="លេខសម្គាល់ "+data.land_code+", ឈ្មោះ  "+data.land_address+", ប្រភេទ  "+data.property_type+", ទំហំ "+data.land_size+", បណ្តោយ "+data.height+",ទទឹង  "+data.width;
			paid_before = dijit.byId('paid_before').get('value');
			dijit.byId('balance_before').attr('value',data.price-paid_before);
			
			//dijit.byId('deposit').attr('value',paid_before);
			
			checkScheduleOption();
			Balance();
			
		},
		error: function(err) {
			alert(err);
		}
	});
}

var url_getlandinfotransferdetail = '<?php echo $this->url(array('module'=>'group','controller'=>'land','action'=>'getlandinfo')); ?>';
function getlandinfotransfer(){
	dojo.xhrPost({
		url:url_getlandinfotransferdetail,	
		content:{ 
		    'land_id':dijit.byId('to_land_code').get('value')
		},		    
		handleAs:"json",
		load: function(data) {
			
			dojo.byId('to_land_information').innerHTML ="លេខ "+data.land_code+", ឈ្មោះ  "+data.land_address+", ទំហំ "+data.land_size+", បណ្តោយ "+data.height+",ទទឹង  "+data.width;
			
			dijit.byId('land_price').attr('value',data.land_price);
			dijit.byId('house_price').attr('value',data.house_price);
			dijit.byId('to_total_sold').attr('value',data.price);
            tohouseprice = dijit.byId('to_total_sold').get('value');
            if(isNaN(tohouseprice)){tohouseprice=0;}
                
            paid_before = dijit.byId('paid_before').get('value');
            if(isNaN(tohouseprice)){paid_before=0;}
            balance_price = parseFloat(tohouseprice)-parseFloat(paid_before);
			dijit.byId('sold_price').attr('value',balance_price);
			dijit.byId('deposit').attr('value',0);
			
			Balance();
			
		},
		error: function(err) {
			alert(err);
		}
	});
}


function clearTextBox(){
	dijit.byId('member').set('value','');
	dijit.byId('total_amount').set('value',0);
}
function getClientInfo(type){
	if(type==1){
		customer_code= dijit.byId('customer_code').get('value');
		dijit.byId('member').attr('value',customer_code);
	}else{
		customer_code= dijit.byId('member').get('value');
		dijit.byId('customer_code').attr('value',customer_code);
	}
}
var url_submitdistrict = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'add-newdistrict')); ?>';
function addNewDistrict(){
		dojo.xhrPost({
	    url: url_submitdistrict,	
		form: dojo.byId("form_district"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_district').reset(); 
			dijit.byId('frm_district').hide();
		},
		error: function(err) {
			alert("Your message could not be sent, please try again!.");
		}
	});
}
var url_submitcommune = '<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'add-newcommune')); ?>';
function addNewCommune(){
		dojo.xhrPost({
	    url: url_submitcommune,	
		form: dojo.byId("form_commune"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_commune').reset(); 
			dijit.byId('frm_commune').hide();
		},
		error: function(err) {
			alert("Your message could not be sent, please try again!.");
		}
	});
}
var url_submitvillage = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'add-newvillage')); ?>';
function addNewVillage(){
		dojo.xhrPost({
	    url: url_submitvillage,	
		form: dojo.byId("form_village"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_village').reset(); 
			dijit.byId('frm_village').hide();
		},
		error: function(err) {
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
</script>
<script>
function setFirstPaymentAndDateLine(pay_term,date_release,amount_date){
	var a = new Date(date_release);
		mm = a.getMonth()+amount_date+1;
	 var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	 if(mm<10){
		 mm = "0"+mm;
	}
	
	var y = a.getFullYear();
	var epx_date = y + '-'+ mm + '-'+dd ;
	
	dijit.byId('date_line').attr('value',epx_date);
	calCulateFirstPayment();
}
function calCulateEndDate(){
	amount_date = dijit.byId('period').get('value');
	release_date = dijit.byId("first_payment").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
	}else{
		var a = new Date(release_date);
		mm = a.getMonth()+amount_date+1;
		 var dd = a.getDate();
		 if(dd<10){
			 dd = "0"+dd;
		}
		 if(mm<10){
			 mm = "0"+mm;
		}
		var y = a.getFullYear();
		var epx_date = y + '-'+ mm + '-'+dd ;
		dijit.byId('date_line').attr('value',epx_date);	
    }
}
function CalculateDate(){
	pay_term = 1;
	amount_date = dijit.byId('period').get('value');
	release_date = dijit.byId("first_payment").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
	}else{
		setFirstPaymentAndDateLine(pay_term,release_date,amount_date);		
    }
}
function checkReleaseDate(){
	CalculateDate();
}
/*function calCulatePeriod(){
	CalculateDate();
}*/
function getFirstPayment(){
	calCulateFirstPayment();
}
function calCulateFirstPayment(){
	pay_term = 1;
	amount_date = 1;
	release_date = dijit.byId("release_date").get('value');
	var a = new Date(release_date);
		mm = a.getMonth()+amount_date+1;
	var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	 if(mm<10){
		 mm = "0"+mm;
	}
	var y = a.getFullYear();
	var epx_date = y + '-'+ mm + '-'+dd ;
	dijit.byId('first_payment').attr('value',epx_date);
}
function printSave(new_stu_id,new_receipt_no){		
	dijit.byId("lbl_schedule").hide();
	//dojo.byId("lb_student_id").innerHTML = dijit.byId("sale_code").get("value");
	dojo.byId("lb_paymentid").innerHTML = dijit.byId("schedule_opt").attr('displayedValue');
	//dojo.byId("lb_receipt").innerHTML = dijit.byId("receipt").get('value');
	dojo.byId("lb_buydate").innerHTML = dijit.byId("date_buy").attr('displayedValue');
	dojo.byId("lb_customer").innerHTML = dijit.byId("member").attr('displayedValue');
	dojo.byId("lb_hourseno").innerHTML = dijit.byId("land_code").attr('displayedValue');
	dojo.byId("lb_price").innerHTML = "$ "+dojo.number.format(dijit.byId("total_sold").get('value'),2);
	dojo.byId("lb_discount").innerHTML = dijit.byId("discount").get('value');
	other_fee = dijit.byId("other_fee").get('value');
	if(isNaN(other_fee)){other_fee=0;}
	dojo.byId("lb_otherfee").innerHTML = "$ "+dojo.number.format(other_fee,2);
	dojo.byId("lb_amount").innerHTML = "$ "+dojo.number.format(dijit.byId("sold_price").get('value'),2);
	dojo.byId("lb_paid").innerHTML = "$ "+dojo.number.format(dijit.byId("deposit").get('value'),2);
	dojo.byId("lb_balance").innerHTML = "$ "+dojo.number.format(dijit.byId("balance").get('value'),2);
	dojo.byId("lb_noted").innerHTML =dijit.byId("note").get('value');
	schedule_opt = dijit.byId("schedule_opt").get("value");
	
	 dojo.byId("lbl_customer").innerHTML = dijit.byId("member").attr('displayedValue');
	if(schedule_opt==1){
		//EXPIRED_DATE
	}
	
	 dijit.byId("terms").show();	
	}
var url_previewloan = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'addschedultest')); ?>';
function addPreviewLoan(){
	old_paid = dijit.byId('paid_before').get('value');
	new_paid = dijit.byId('deposit').get('value');
	if(old_paid > new_paid){
		alert('You can not pay less than old paid amount');
		dijit.byId('deposit').focus();
		return false;
	}
	r=0;
	if(dijit.byId('frm_add_tran').validate()){
		client = dijit.byId('member').get('value');
		if (client=='' || client==-1){
			alert('Please Select Client Name !');
			dijit.byId('customer_code').focus();
			return false;
		}

		dojo.xhrPost({
		    url: url_previewloan,	
			form: dojo.byId("frm_add_tran"),		    
			handleAs:"json", 
			load: function(data) {
				if(data.row_id=='row_id'){//return 1;
					printSave();
					}else{
						  document.getElementsByClassName("overlay")[0].style.display="none";
						  temp='';	
						  fund_title=0;thead='';fund_title=0;
						  temp='<table class="collape tablesorter" style="font-size:13px; width:1000px !important; " id="table">'
						  temp+='<tr style="background:#ccc;"><th><?php echo $tr->translate("NUM");?></th>';
						  temp+='<th><?php echo $tr->translate("ថ្ងៃបង់ប្រាក់");?></th>';
						  temp+='<th><?php echo $tr->translate("ប្រាក់ដើមគ្រា");?></th>';
						  temp+='<th><?php echo $tr->translate("ប្រាក់ដើម");?></th>';
						  temp+='<th><?php echo $tr->translate("ប្រាក់ការ");?></th>';
						  temp+='<th><?php echo $tr->translate("សរុប");?></th>';
						  temp+='<th><?php echo $tr->translate("ប្រាក់ដើមនៅសល់");?></th>';
						  principal_permonth=0;total_interest=0;total_payment_after=0;
						for(i=0;i<data.length;i++){
							principal_permonth=principal_permonth+parseFloat(data[i].principal_permonth);
							total_interest=total_interest+parseFloat(data[i].total_interest);
							total_payment_after=total_payment_after+parseFloat(data[i].total_payment_after);
					      r++;
						  temp+='<tr><td align="center">'+r+'</td>';
						  var myDate = new Date(data[i].date_payment);
						  d = new Date(data[i].date_name);
						  temp+='<td>'+getDayName(d.getDay())+'-'+data[i].date_payments+'</td>';
						  temp+='<td>'+dojo.number.format(data[i].begining_balance,2)+'</td>';
						  temp+='<td>'+dojo.number.format(data[i].principal_permonth,2)+'</td>';
						  temp+='<td>'+dojo.number.format(data[i].total_interest,2)+'</td>';
						  temp+='<td><b>'+dojo.number.format(data[i].total_payment_after,2)+'<b></td>';
						  temp+='<td><b>'+dojo.number.format((data[i].ending_balance),2)+'<b></td>';
						 }
						  temp+='<tr><td align="right" colspan="3" style="border-left:1px solid #fff;border-bottom:1px solid #fff;">&nbsp;សរុប -Total</td>';
						  temp+='<td>'+dojo.number.format(principal_permonth,2)+'</td>';
						  temp+='<td>'+dojo.number.format(total_interest,2)+'</td>';
						  temp+='<td><b>'+dojo.number.format(total_payment_after,2)+'<b></td>';
						  temp+='<td></td>';
						temp+='</table>';
						dojo.byId('t_amountmoneytype').innerHTML = temp;
						dijit.byId("lbl_schedule").show();
					}
				
			},
			error: function(response, ioArgs) {
				alert("Failed while doing the operation: " + ioArgs.xhr.response);
				//document.getElementsByClassName("overlay")[0].style.display="none";
				//alert("You can not preview this loan number!");
			}
	   });
	}
}
function getDayName(day){
	 var weekday = new Array(7);
	    weekday[0] = "អាទិត្យ";
	    weekday[1] = "ច័ន្ទ";
	    weekday[2] = "អង្គារ";
	    weekday[3] = "ពុធ";
	    weekday[4] = "ព្រហ";
	    weekday[5] = "សុក្រ";
	    weekday[6] = "សៅរ៍";
	    return weekday[day];
}
function hideDialog() {		
	dijit.byId("lbl_schedule").hide();
}

function showPopupclient(){
	dijit.byId("frmpop_client").show();
}
var individual_client_url = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insert-client'));?>';
function addNewindividual(){
	if(dijit.byId('addclient').validate()){
	dojo.xhrPost({
		url:individual_client_url,	
		form:dojo.byId('addclient'),
		content:{
			'branch_id':1
			},
		handleAs:"json",
		load: function(response) {
			dijit.byId('frmpop_client').hide();	
			var myNewItem = {					
					id: response.id,
					name: dijit.byId('name_en').get('value')+' - '+dijit.byId('name_kh').get('value'),
			};			
			addDataToSelectbox(dijit.byId('member'), client_store, myNewItem, response.id);
			var myNewItem1 = {					
					id: response.id,
					name: response.client_code,
			};			
			addDataToSelectbox(dijit.byId('customer_code'), client_number_store, myNewItem1, response.id);		
			dijit.byId('addclient').reset();
		},
		error: function(err) {
		}
	});
 }	
}
function printSubmit(){
	 $('#frm_add_tran').submit();
}
function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}
</script>
<style>
.overlay {display: none;position: absolute;width: 100%;height: 100%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .95;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           border: solid 1px #060522;text-align: center;
           background: #fff url("<?php echo $this->baseUrl()?>/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>