<?php 
$frm = $this->frm_search;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title> Other Income</title>
<script>
	dojo.require('dijit.form.Button');
	dojo.require("dijit.form.DateTextBox");
</script>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'loan','controller'=>'income','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
  <table width="100%">
   <tr>  
        <td><?php echo $frm->getElement("adv_search");?></td>
        <td><?php echo $frm->getElement('branch_id');?></td>
   		<td><?php echo $frm->getElement('currency_type');?></td>
   		<td><?php echo $frm->getElement('start_date');?></td>
   		<td><?php echo $frm->getElement('end_date');?></td>
   		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
   </tr>
</table>
</form>
 <?php echo $this->list;?>
