<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();
		$request=Zend_Controller_Front::getInstance()->getRequest();
		$status = $request->getParam('search_status');
		if(empty($status) AND $status==0) $status=-1;
?>

<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("PROVINCE_LIST"));
?>	
<?php $frm =  $this->frm_search;?>
<?php
$url_edit = $this->url(array('module'=>'dailywork','controller'=>'index','action'=>'edit'));
$row_rs = $this->row_rs;
?>
<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage(); ?>
<?php $formFilter =  $this->frm_search;?>
<meta charset="utf-8" />
<form method="post" action="">
		<div class="form-group" style="padding-top: 6px;">
			<label class="control-label col-md-2"><input  dojoType="dijit.form.TextBox"  id="adv_search" name="adv_search" value="<?php echo $this->row['adv_search']?>" placeholder="<?php echo $this->translate("Search");?>" type="text" ></label>
				<label class="control-label col-md-2">
					<input type="submit" value="save_close" name="save_close" label="ស្វែងរក" dojoType="dijit.form.Button" 
												iconClass="dijitEditorIcon dijitEditorIconSave" />
					
				</label>
		</div>		
</form> 
<?php echo $this->list; ?>