<?php 
	  $tr=Application_Form_FrmLanguages::getCurrentlanguage();
	  $home=$this->url(array('module'=>'home','controller'=>'index','action'=>'index'), null, true);
	  $group=$this->url(array('module'=>'group','controller'=>'index','action'=>'index'), null, true);
	  $other=$this->url(array('module'=>'other','controller'=>'index','action'=>'index'), null, true);
	  $old_report=$this->url(array('module'=>'allreport','controller'=>'index','action'=>'index'), null, true);
	  $report=$this->url(array('module'=>'report','controller'=>'index','action'=>'index'), null, true);
	  $loan_view=$this->url(array('module'=>'loan','controller'=>'index','action'=>'index'), null, true);
	  $accounting_view=$this->url(array('module'=>'accounting','controller'=>'index','action'=>'index'), null, true);
	  $teller=$this->url(array('module'=>'tellerandexchange','controller'=>'xchanges','action'=>'index'), null, true);
	  $payroll_view=$this->url(array('module'=>'payroll','controller'=>'index','action'=>'index'), null, true);
	  $callecterall=$this->url(array('module'=>'callecterall','controller'=>'index','action'=>'index'), null, true);
	  $capital=$this->url(array('module'=>'capital','controller'=>'index','action'=>'index'), null, true);
	  $backup=$this->url(array('module'=>'backup','controller'=>'index','action'=>'index'), null, true);
      $user=$this->url(array('module'=>'user','controller'=>'index','action'=>'index'), null, true);
      $acl=$this->url(array('module'=>'rsvacl','controller'=>'index','action'=>'index'), null, true);
      $setting=$this->url(array('module'=>'setting','controller'=>'index','action'=>'index'), null, true);
      $sale = $this->url(array('module'=>'loan','controller'=>'index','action'=>'add'), null, true);
	  
	  $module=Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
      $session_user=new Zend_Session_Namespace('auth');
      $arr_module = $session_user->arr_module;
      $menuleft=array();
      $class='link';
      if(!empty($arr_module)){
      	foreach ($arr_module as $rs){
      		if($rs==$module){$class='current';}else{$class='link';}
      		if($rs=='loan'){
      			$old_module = $rs;
      			$rs="dd";
      			$menuleft[$rs]="<li ><a href='$sale'><span>".$tr->translate(strtoupper("SALE_PROPERTY"))."</span></a></li>";
      			$rs=$old_module;
      		}
      		 
      		$url =$this->url(array('module'=>$rs,'controller'=>'index','action'=>'index'), null, true); ;
      		$menuleft[$rs]="<li class='$class'><a href='$url'><span>".$tr->translate(strtoupper($rs))."</span></a></li>";
      	}
      }
?>  
<div id="menu">
	<ul>
		<?php
	$session_user=new Zend_Session_Namespace('auth');
		$modules_access = $session_user->arr_module;
			foreach($menuleft as $key=>$value){
				$access = array_search($key,$modules_access);
				//if($access!='' OR $access>=0){
					if($module==$value){
						echo str_replace('link', 'current',$value);
					}
					else{
						echo $value;
					}
				//}
			} 
		?>
		<li style="float: right;">
			<a href="" class="langiconen" onclick="changeLange(2);"></a>
		</li>
		<li style="float: right;  border-left: 1px solid #fff; border-right: 1px solid #fff;">
		<a href="" class="langiconkh" onclick="changeLange(1);"></a>
		</li>
	</ul>
</div>
<script>
		
var url_changelang = '<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'changelange'));?> ';
function changeLange(lang){
	dojo.xhrPost({
		url: url_changelang,
	    content :{ 
			    'lange':lang,
		},	
		handleAs:"json",
		load: function(data) {
			location.reload();
		},
		error: function(err) {
			
		}
	});
}
	</script>