	<?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action = $request->getActionName();
	$baseurl  = $this->baseUrl();
	$session_user=new Zend_Session_Namespace('auth');
	$arr_module = $session_user->arr_acl;
	$menu = array();
	$module = '';
	$controller=array();
	$newarray=array();
	if(!empty($arr_module)){
		foreach ($arr_module as $key => $rs){
			if($rs['module']=='report' AND $rs['controller']!='loan'){
				continue;
			}
			$lblcontroller = $rs['label'];
// 			if($rs['controller']=='index' AND $rs['module']=='group' ){
// 				$lblcontroller='CLIENT_INFO';
// 			}
// 			if($rs['controller']=='index' AND $rs['module']=='loan' ){
// 				$lblcontroller='IL_DISBURSE';
// 			}
// 			if($rs['controller']=='index' AND $rs['module']=='other' ){
// 				$lblcontroller='province';
// 			}
// 			if($rs['controller']=='loantype' AND $rs['module']=='other' ){
// 				$lblcontroller='OTHER';
// 			}
// 			if($rs['controller']=='term' AND $rs['module']=='other' ){
// 				$lblcontroller='termcondition';
// 			}
	

			if($module!=$rs['module']){
				$newarray= array($rs['controller']=>'<a href="">'.$tr->translate(strtoupper($lblcontroller)).'</a>');
				$menu[$rs['module']]= $newarray;
				$old_module=$rs['module'];
			}else{
				$newarray= array_merge($newarray,array($rs['controller']=>'<a href="">'.$tr->translate(strtoupper($lblcontroller)).'</a>'));
			    $menu[$rs['module']] = $newarray;
			}
			$module=$rs['module'];
		}
	}
	$arr_param_menu = $menu;
	?>
	
	</div>
	<script>
	function openNav() {
	    document.getElementById("mySidenav").style.width = "175px";
	    $('#mynavclose').css('display','none');
	}
	function closeNav() {
	    document.getElementById("mySidenav").style.width = "0";
	    document.getElementById("mySidenav").style.height = "100%";
	    $('#mynavclose').css('display','block');
	}
	</script>
	<style>
		.sidenav {
		    width: 0;
		   /* position: fixed;*/
		    z-index: 1;
		    top: 0;
		    left: 0;
		    background-color: #fff;
		    overflow-x: hidden;
		    transition: 0.5s;
		}
		.sidenav span.closebtn {
			font-size: 18px;
		    cursor: pointer;
		    display: block;
		    color: #fff;
		    border-bottom: solid 1px #ccc;
		 	text-align: left;
		    background: #000088;
			padding-left: 10px;
		    height: 36px;
            line-height: 38px;
			}
		.sidenav a {
		   padding: 5px 8px 2px 2px;
		    text-decoration: none;
		    font-size: 14px;
		    color: #000000;
		    display: block;
		    transition: 0.3s;
		    border-bottom: solid 1px #ccc;
			border: solid 1px #ccc;
		    margin: 2px 0px;
		    padding: 4px 3px;
		}
    .sidenav table a {
		   padding: 0px;
		    //font-size: 14px;
		    //color: #000000;
		    //transition: 0.3s;
		    border-bottom:none;
			border:none;
		    margin: 0px;
		    padding: 0px;
		}		
		.sidenav a:hover, .offcanvas a:focus, .sidenav a.current-left{
		      color: #000000;
   			 background: #EDF7F8;
		}
		
		</style>