	<?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action = $request->getActionName();
	$baseurl  = $this->baseUrl();
	$session_user=new Zend_Session_Namespace('auth');
	$arr_module = $session_user->arr_acl;
	$menu = array();
	$module = '';
	$controller=array();
	$newarray=array();
	if(!empty($arr_module)){
		foreach ($arr_module as $key => $rs){
			if($rs['module']=='report' AND $rs['controller']!='loan'){
				continue;
			}
			$lblcontroller = $rs['label'];
// 			if($rs['controller']=='index' AND $rs['module']=='group' ){
// 				$lblcontroller='CLIENT_INFO';
// 			}
// 			if($rs['controller']=='index' AND $rs['module']=='loan' ){
// 				$lblcontroller='IL_DISBURSE';
// 			}
// 			if($rs['controller']=='index' AND $rs['module']=='other' ){
// 				$lblcontroller='province';
// 			}
// 			if($rs['controller']=='loantype' AND $rs['module']=='other' ){
// 				$lblcontroller='OTHER';
// 			}
// 			if($rs['controller']=='term' AND $rs['module']=='other' ){
// 				$lblcontroller='termcondition';
// 			}
			if($module!=$rs['module']){
				$newarray= array($rs['controller']=>'<a href="">'.$tr->translate(strtoupper($lblcontroller)).'</a>');
				$menu[$rs['module']]= $newarray;
				$old_module=$rs['module'];
			}else{
				$newarray= array_merge($newarray,array($rs['controller']=>'<a href="">'.$tr->translate(strtoupper($lblcontroller)).'</a>'));
			    $menu[$rs['module']] = $newarray;
			}
			$module=$rs['module'];
		}
	}
	$arr_param_menu = $menu;
	?>
	<span id ="mynavclose" style="font-size: 22px;cursor: pointer;display: none;background: #000088;text-align: center;color: #fff;border-radius: 4px;" onclick="openNav()">&#9776;</span>
	<div id="mySidenav" class="sidenav" style=" width:185px;">
	<span href="javascript:void(0)"  class="closebtn"  onclick="closeNav()">Hide Left</span>
		<?php 
				if($request->getModuleName()!='default' AND $action!='changepassword' ){
				$dc=new Application_Model_Decorator();					
				$class="current-left";					
				$menu=$dc->getMenuLeft($arr_param_menu[$request->getModuleName()],$request->getControllerName(),$request->getModuleName());
				if($menu) echo $menu;	
}				
			?>
			
			 <div  style="background: #fff;padding: 2px;max-width: 180px;min-height:70px;max-height: 500px;overflow: scroll;" >
	   			<div class="portlet box green" style="">
						<div class="portlet-body flip-scroll">
							<table cellpadding="2" cellpadding="2" border="1" 
							style="border-collapse:collapse;border: 1px solid #ddd;color:#888888;font-size:13px;font-family:'Kh Battambang','Khmer Battambang' !important;" class="table table-bordered table-striped table-condensed flip-content">
							<thead class="flip-content" style="background:#3598dc;color: #eee;">
							<tr height="30px;" style="font-family:'Khmer MEF2'; color: #100505; background: #e6e6e6; font-size: 14px;"><td colspan="9">តារាងអតិថិជនត្រូវបង់</td></tr>
							<tr style="white-space: nowrap;">
								<th> លរ</th>
								<th> ឈ្មោះអតិថិជន</th>
								<th> លេខទូរសព្ទ</th>
								<th> លេខផ្ទះ</th>
								<th class="numeric">ជំពាក់សរុប</th>
								<th class="numeric">ថ្ងៃត្រូវបង់	</th>
								<th class="numeric">យឺត</th>
								<th class="numeric">បង់លើក</th>
								<th class="numeric">ប្រាក់ត្រូវបង់</th>
							</tr>
							</thead>
							<?php 
								$db = new Report_Model_DbTable_DbloanCollect();
								$rs = $db->getCustomerNearlyPayment();
								$num=0;
								$class='';
								if(!empty($rs)){
							?>
							<?php foreach($rs as $key=> $result){
								if($class==''){$class='odd';}else{$class='';}
								?>
								<tr class="hover <?php echo $class;?>" style="white-space: nowrap;">
								<?php $url = $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'add'), null, true)."/id/".$result['sale_id'];?>
									<td align="center"><?php echo $key+1;?></td>
									<td style="white-space: nowrap;"><a href="<?php echo $url;?>"><?php echo $result['client_name'];?></a></td>
									<td class="numeric"><a href="<?php echo $url;?>"><?php echo $result['phone_number'];?></a></td>
									<td class="numeric"><a href="<?php echo $url;?>"><?php echo $result['land_address'].' '.$result['street'];?></a></td>
									<?php  $total_payment = $result['principal_permonthafter']+$result['total_interest_after']+$result['service_charge'];?>
									<td class="numeric"><a href="<?php echo $url;?>"><?php echo number_format($result['begining_balance_after'],2);?></a></td>
									<td class="numeric"><a href="<?php echo $url;?>"><?php echo date("d/m/Y",strtotime($result['date_payment']));?></a></td>
									<?php 
									$datetime1 = new DateTime(date("Y-m-d"));
									$datetime2 = new DateTime(date("Y-m-d",strtotime($result['date_payment'])));
									$interval = $datetime2->diff($datetime1);
								    ?>
									<td class="numeric"><a href="<?php echo $url;?>" style='color:red;'><?php echo @abs($interval->format('%R%a'))."ថ្ងៃ"; ?></a></td>
									<td class="numeric" align="center"><a href="<?php echo $url;?>"><?php echo $result['no_installment'];?></a></td>
									<td class="numeric"><a href="<?php echo $url;?>"><?php echo number_format($total_payment,2);?></a></td>
								</tr>
							<?php }
							}?>
							<tr><td colspan="9">សរុបទាំងអស់:<span style="color:red;"><?php echo count($rs);?> នាក់</span></td></tr>
						</table>
						</div>
					</div>
   				</div>
	</div>
	<script>
	function openNav() {
	    document.getElementById("mySidenav").style.width = "175px";
	    $('#mynavclose').css('display','none');
	}
	function closeNav() {
	    document.getElementById("mySidenav").style.width = "0";
	    document.getElementById("mySidenav").style.height = "100%";
	    $('#mynavclose').css('display','block');
	}
	</script>
	<style>
		.sidenav {
		    width: 0;
		   /* position: fixed;*/
		    z-index: 1;
		    top: 0;
		    left: 0;
		    background-color: #fff;
		    overflow-x: hidden;
		    transition: 0.5s;
		}
		.sidenav span.closebtn {
			font-size: 18px;
		    cursor: pointer;
		    display: block;
		    color: #fff;
		    border-bottom: solid 1px #ccc;
		 	text-align: left;
		    background: #000088;
			padding-left: 10px;
		    height: 36px;
            line-height: 38px;
			}
		.sidenav a {
		   padding: 5px 8px 2px 2px;
		    text-decoration: none;
		    font-size: 14px;
		    color: #000000;
		    display: block;
		    transition: 0.3s;
		    border-bottom: solid 1px #ccc;
			border: solid 1px #ccc;
		    margin: 2px 0px;
		    padding: 4px 3px;
		}
    .sidenav table a {
		   padding: 0px;
		    //font-size: 14px;
		    //color: #000000;
		    //transition: 0.3s;
		    border-bottom:none;
			border:none;
		    margin: 0px;
		    padding: 0px;
		}		
		.sidenav a:hover, .offcanvas a:focus, .sidenav a.current-left{
		      color: #000000;
   			 background: #EDF7F8;
		}
		
		</style>