<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore");  
</script>
<script type="text/javascript">  
var district_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var commune_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
		dijit.byId('province_name').attr('value',<?php echo $this->result['province_name'];?>);
		 
		new dijit.form.FilteringSelect({
		store: district_store,
		autoComplete: true,          
		required: false,		           
		name: "district_name",
		id: "district_name",
		searchAttr: "name",
		class: 'fullside',
		value:"<?php echo $this->result['district_name'];?>",
		missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
			onChange: function() {
					filterCommune();
		    }
		}, "district_name");
		
		new dijit.form.FilteringSelect({
		store: commune_store,
		autoComplete: true,
		required: false,		           
		name: "commune_name",
		id: "commune_name",
		searchAttr: "name",
		class: 'fullside',
		value:"<?php echo $this->result['commune_name'];?>",
		missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
			onChange: function() {
	        }
		}, "commune_name");
		filterDistrict();
		filterCommune();
});
url_getdistrict = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'get-district'));?>';
function filterDistrict(){
	pro_id = dijit.byId('province_name').get('value');
	if(pro_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getdistrict,	
		content:{ 
			'pro_id': pro_id
		},
		handleAs:"json",
		load: function(data) {	
			district_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('district_name').set('store', district_store);
		    dijit.byId('district_name').attr('value','<?php echo $this->result['district_name'];?>');
		},
		error: function(err) {
			alert(err);
		}
	});	
}
url_getcommune = '<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'get-commune'));?>';
function filterCommune(){
	distict_id = dijit.byId('district_name').get('value');
	if(distict_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getcommune,	
		content:{ 
			'district_id': distict_id
		},
		handleAs:"json",
		load: function(data) {	
			commune_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('commune_name').set('store', commune_store);
		    dijit.byId('commune_name').attr('value','<?php echo $this->result['commune_name'];?>');
		},
		error: function(err) {
			alert(err);
		}
	});
}
</script>
<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("VILLAGE_LIST"));
$frm = $this->frm_village;
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   <table>
   		<tr>
		   	<td><?php echo $frm->getElement("adv_search");?></td>
		   	<td><?php  echo $frm->getElement('province_name');?></td>
		   	<td><input id="district_name" ></td>
		   	<td><input id="commune_name" ></td>
		    <td><?php echo $frm->getElement('search_status');?></td>
		    <td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
   	   </tr>
   </table>
</form>
<?php echo $this->list;?>
