<?php $frm = $this->frm_search;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();

?>
<meta charset="utf-8">
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<style>
.hover:hover{background: #ccc;}
img.view{height: 85px !important;}
</style>
<title><?php echo $tr->translate("RECEIPT");?></title>
 <form method="post">
<div style=" width:29cm;min-height:23cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
			<style>
				.fontbig{
					font-size: 16px;	
				}
				.fonttel{
					font-size: 18px;	
				}
				.pleft{
					width: 110px;	
				}

				.label{ font-size: 22px;}
				.value{ font:16px 'Khmer OS Battambang';border: 1px solid #000; height: 30px; padding: 0 2px;width: 100%;margin-right:5px; display: block;
						line-height: 30px;
					    text-align: center;
						}
				.values{ border: 1px solid #000; height: 30px; padding: 0 10px;display: block;
						line-height: 30px;}
				.h{}
				.print tr td{
					padding:2px 2px; 
				}
			   .khmerbold{font:14px 'Khmer OS Battambang';}
			   .khmer{font:14px 'Khmer OS Battambang';}
			   .one{white-space:nowrap;}
			   .h{ margin-top: -10px;}
			</style>
			<?php for($i=0; $i<2; $i++){ ?>			
			<table width="100%" style="white-space: nowrap;font-size:14px;  padding:10px 10px 0px 5px;margin-top: -15px;" class="print" cellspacing="0"  cellpadding="0" >
				<tr>
					<td colspan="6">
						<table width="100%" style="font-family:'Khmer MEF2';white-space:nowrap;">
							<tr>
								<td width="25%">
									<img class="view" style="width:100%;height:55px;" src="<?php echo $this->baseUrl().'/images/bppt_logo.png'?>">
								</td>					
								<td width="50%" style="font:18px 'Kh Muol';" valign="top" align="center"><u><strong style=" font-family: Arial Black;font-family:'Khmer MEF2';">បង្កាន់ដៃទទួលប្រាក់</strong></u>
									<div style="line-height:10px;"><strong style="font-size: 18px;">OFFICIAL RECEIPT</strong></div>
								</td>
								<td width="25%">
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<table style="width:100%;white-space: nowrap;font-size:16px;padding:-10px 10px 0px 5px; margin-top: -30px;margin-bottom:10px;font-family: 'Khmer OS Battambang';" class="print" cellspacing="3px"  cellpadding="0" >
				<tr height="1px">
					<td width="10%" ></td>
					<td width="30%" ></td>
					<td width="15%" ></td>
					<td width="17%" ></td>
					<td width="10%" ></td>
					<td width="18%" ></td>
				</tr>
				<!-- <tr style="white-space: nowrap;">
				    <td colspan="5"></td>
					<td align="right"><strong><label id="lb_receipt1" ></label></strong></td>
				</tr>
				
				<tr style="white-space: nowrap;">
				    <td   >លេខកូដលក់</td>
				    <td  ><strong><label id="lb_student_id1" class="value"><?php //echo $this->rs['sale_number'];?></label></strong></td>
				  
					<td   >&nbsp;&nbsp;&nbsp;តម្លៃលក់</td>
                    <td colspan="3" ><strong><label id="lb_price1" class="value"></label></strong></td>
				</tr>
				
				<tr style="white-space: nowrap;">
				
				    <td  >ឈ្មោះ​អតិថិជន </td>
				    <td ><strong><label id="lb_customer1" class="value"><?php //echo $this->rs['name_kh'];?></label></strong></td>
					
					<td  >​&nbsp;&nbsp;&nbsp;បញ្ចុះតម្លៃ</td>
				    <td><strong><label id="lb_discount1" class="value"></label></strong></td>
				    
					<td  >&nbsp;&nbsp;តម្លៃផ្សេងៗ</td>
				    <td><strong><label id="lb_otherfee1" class="value"></label></strong></td>
                    
                </tr>
				<tr style="white-space: nowrap;">
				
					<td  >លេខផ្ទះ</td>
                    <td><strong><label id="lb_hourseno1" class="value"><?php //echo $this->rs['land_address']; if(!empty($this->rs['street'])){echo ' , '.$this->rs['street']; }?></label></strong></td>
					
					
				    <td  >&nbsp;&nbsp;&nbsp;ប្រាក់ត្រូវបង់</td>
                    <td colspan="3"><strong><label id="lb_amount1" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
				
					<td   width="10%">ប្រភេទបង់</td>
				    <td width="40%"><strong><label id="lb_paymentid1" class="value"></label></strong></td>
					
					<td  >&nbsp;&nbsp;&nbsp;ប្រាក់បានបង់</td>
				    <td colspan="3"><strong><label id="lb_paid1" class="value"></label></strong></td>
				</tr>

				<tr>
					<td  >សែក</td>
					<td ><strong><label id="lb_moneynote1" class="value"></label></strong></td>
					
					
					<td  >&nbsp;&nbsp;&nbsp;ប្រាក់នៅសល់</td>
					<td colspan="3"><strong><label id="lb_balance1" class="value"></label></strong></td>
					
				</tr>
				<tr style="white-space: nowrap;">
				
					<td  >សម្គាល់</td>
				    <td ><strong style="white-space: nowrap;"><label style="white-space: nowrap;" id="lb_noted1" class="value"></label></strong></td>
					
					<td  >&nbsp;&nbsp;&nbsp;ថ្ងៃលក់</td>
				    <td colspan="3"><strong><label id="lb_buydate1" class="value"></label></strong></td>
				</tr>-->
				
				<tr style="white-space: nowrap;font-size: 14px;margin-top: -10px;" >
				    <td colspan="5"></td>
					<td align="right"><strong><label><?php echo $this->rs['receipt_no'];?></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
				    <td  >លេខកូដលក់</td>
				    <td  ><strong><label class="value"><?php echo $this->rs['sale_number'];?></label></strong></td>
					<td  >&nbsp;&nbsp;ប្រាក់ដើមត្រូវបង់</td>
                    <td  ><strong><label  class="value"><?php echo  number_format($this->rs['total_principal_permonth'],2)." $";?></label></strong></td>
					<td>&nbsp;បង់លើកទី</td>
					<td><strong><label id="lbl_paid_date1" class="value"><?php //echo date("d-M-Y",strtotime($this->rs['date_input']));?></label></strong></td>
				
				</tr>
				<tr style="white-space: nowrap;">
				    <td >ឈ្មោះ​អតិថិជន </td>
				    <td ><strong><label class="value"><?php echo $this->rs['name_kh'];echo !empty($this->rs['hname_kh'])?" /".$this->rs['hname_kh']:"";?></label></strong></td>
					<td >​&nbsp;&nbsp;បញ្ចុះតម្លៃ</td>
				    <td colspan="3"><strong><label id="lb_discount1" class="value"><?php echo number_format($this->rs['total_discount'],2)." $";?></label></strong></td>
                </tr>
				<tr style="white-space: nowrap;">
					<td >លេខផ្ទះ</td>
                    <td><strong><label class="value"><?php echo $this->rs['land_address']; if(!empty($this->rs['street'])){echo ' , '.$this->rs['street']; } echo ' '.$this->rs['property_type'];?></label></strong></td>
				   <td >&nbsp;&nbsp;ប្រាក់បង់បន្ថែម</td>
					<td colspan="3"><strong><label  class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td  width="10%">តំលៃផ្ទះ</td>
				    <td width="40%"><strong><label id="lblpropertyprice1" class="value"><?php echo  number_format($this->rs['price_sold'],2)." $";?></label></strong></td>
					<td >&nbsp;&nbsp;ប្រាក់ត្រូវបង់</td>
                    <td colspan="3"><strong><label id="lbl_total_payment1" class="value"><?php echo  number_format($this->rs['total_principal_permonth'],2)." $";?></label></strong></td>
				</tr>
				<tr>
					<td >ប្រាក់បានបង់សរុប</td>
					<td ><strong><label id="lbl_total_paid1" class="value"><?php echo  number_format(($this->rs['price_sold']-($this->rs['outstanding']-$this->rs['recieve_amount'])),2)." $";?></label></strong></td>
					<td>&nbsp;&nbsp;ប្រាក់បានបង់</td>
				    <td colspan="3"><strong><label  class="value" style="font-weight:700; font-family: Arial,Helvetica,sans-serif;"><?php echo number_format($this->rs['recieve_amount'],2)." $";?></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td >ប្រាក់នៅសល់</td>
				    <td ><strong style="white-space: nowrap;"><label style="white-space: nowrap;" class="value"><?php echo  number_format(($this->rs['outstanding']-$this->rs['recieve_amount']),2)." $";?></label></strong></td>
					<td >&nbsp;&nbsp;ថ្ងៃត្រូវបង់</td>
				    <td><strong><label id="lb_buydate1" class="value"><?php echo date("d-M-Y",strtotime($this->rs['date_pay']));?></label></strong></td>
					<td>&nbsp;ថ្ងៃទទួល</td>
					<td><strong><label id="lbl_paid_date1" class="value"><?php echo date("d-M-Y",strtotime($this->rs['date_input']));?></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td >សម្គាល់</td>
				    <td ><strong style="white-space: nowrap;"><label style="white-space: nowrap;" id="lb_noted1" class="value"></label></strong></td>
					<td >&nbsp;&nbsp;សែក</td>
					<td colspan="3"><strong><label id="lb_cheque1" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;" height="35px;">
					<td colspan="6">
						<table width="100%" border="0" style="font-size:14px;line-height: 18px;">
							<tr>
								<td width="30%">
									&nbsp;
								</td>
								
								<td align="center" width="40%">
									ស្នាមមេដៃអ្នកប្រគល់
								</td>
									
								<td align="center" width="30%">
									ស្នាមមេដៃអ្នកទទួល
								</td>
							</tr>
							<tr>
								<td colspan="3">
									&nbsp;
								</td>
							</tr>
							<tr>
								<td colspan="3">
									&nbsp;
								</td>
							</tr>
							<tr>
								<td width="30%">
									&nbsp;
								</td>
								
								<td align="center" width="40%">
									<strong><label id="lbl_customer1"><?php echo $this->rs['name_kh'];echo (empty($this->rs['hname_kh'])?"":"/".$this->rs['hname_kh']); ?></label></strong>
								</td>
									
								<td align="center" width="30%">
									<strong>
										<?php 
										   $session_user=new Zend_Session_Namespace('auth');
										   $last_name=$session_user->last_name;
										   $username = $session_user->first_name;
										   echo $last_name." ".$username;
										?>
									</strong>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				
				<tr style="line-height: 20px;font-size: 11px;">
					<td valign="top" >
						<span style="text-decoration:underline;font-size: 14px;">សំគាល់ ៖</span>
					</td>
					<td colspan="5">
						<span style="font-size: 13px;"><?php echo $this->data['comment'];?></span><br />
						<span style="white-space: pre-line;font-size: 13px;"><?php echo $this->data['comment1'];?></span><br />
					</td>
				</tr>
				
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="6" style="border-top: 2px solid rgba(255, 235, 59, 0.88)">
						
					</td>
				</tr>
				
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="6" >
						<table width="100%" style="font-family: 'Khmer OS Battambang'; font-size:13px;line-height: 10px;margin-top: -10px; margin-bottom:10px;white-space:nowrap;"> 
							<tr>
								<td width="22%">
									<img style="width:70%;height: 25px;" src="<?php echo $this->baseUrl().'/images/bppt_letter.png'?>">
								</td>
								<td width="40%">
									<span style=""><?php echo $this->data['website'];?></span>
								</td>
								<td width="40%" align="right">
									<span style="font-family: 'Khmer OS Battambang';"><?php echo $this->data['email_client'];?></span>
								</td>
							</tr>
							<tr style="white-space:nowrap;">
								<td colspan="2">
									<?php echo $this->data['footer_branch'];?>
								</td>
								<td width="40%" align="right">
									<span style=""><?php echo $this->data['tel-client'];?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<?php if($i==0){?>
				<tr>
					<td colspan="6" style="border-top:2px dashed #000;" >
						
					</td>
				</tr>
				<?php }?>
			</table>
			<?php } ?>
		</div>
	</div>
</div>
</div>