<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_search;
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<style>
.hover:hover{background: #ccc;}
</style>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPORT_WATER_OF_VILLAGE");?></title>
<form name="frm_rptstaff" action="<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-of-month-village')); ?>" dojoType="dijit.form.Form" method="post">
	<table style="width:28cm; margin: 0 auto;">
		<tr>  
	        <td><?php echo $frm->getElement("adv_search");?></td>
	        <td><?php echo $frm->getElement('village_name'); ?></td>
	   		<td><?php echo $frm->getElement('start_date');?></td>
	   		<td><?php echo $frm->getElement('end_date');?></td>
	   		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
	   </tr>
	</table>
 </form> 
<div style=" width:28cm;min-height:22cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
	<table style="font-family: 'Khmer OS Content'; width:100%;">
	
		<tr>
    		<td align="center">
    	 		<div id="divPrint">
    	 			<style>
						.style{
							line-height: 20px;font-size: 12px !important;
							font-family: 'Khmer OS Battambang';
						}
						th{padding: 5px;}
					</style>
        			<table width="100%" style="font-family:'Khmer OS Battambang';" style="margin:0; padding:0;border:none;" >
			        	<tr>
			                <td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
			                <td width="60%" valign="top">
			                 <h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("WATER_STATION_PDAO");?></label></h2>
			                </td>
			                <td width="20%"></td>
			             </tr>
			             <tr>
			             	<td width="20%">&nbsp;</td>
			                <td width="60%" valign="top">
			                <h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("PHONE_NUMBER");?> :<?php echo ("016 885 866/ 015 777 262");?></label></h2>
			                <p style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("បញ្ជីប្រចាំខែ");?>: <?php echo date("D-d-m-Y",strtotime($this->list_end_date));?></p>
			                </td>
			                <td width="20%"></td>
			             </tr>
			           	<tr>
			            	<td colspan="3" id="exportExcel">
			            			<table width="100%" border="1" style="border-collapse:collapse; border:1px solid #000; " cellspacing="0">
						               <?php $all=$this->rows;?>
						                <tr style="padding:0px 1px;white-space: nowrap; text-align: center;background-color: #ADC7E4;">
						                 	<td width="5%"​​><?php echo $tr->translate("No");?></td>
						                 	<td width=""​​><?php echo $tr->translate("Name");?></td>               
						                    <td width=""​​><?php echo $tr->translate("VILLAGE");?></td>
						                   ​​	<td width=""​​><?php echo $tr->translate("phone");?></td>
						                    <td width=""><?php echo $tr->translate("OLD_CONTER");?></td>
						                    <td width=""><?php echo $tr->translate("NEW_CONTER");?></td>
						                    <td width=""><?php echo $tr->translate("ចំនួនប្រើប្រាស់");?></td>
						                    <td width=""><?php echo $tr->translate("តម្លៃរាយ");?></td>
						                    <td width=""><?php echo $tr->translate("ប្រាក់សរុប");?></td>

						                 </tr>  
						                   <?php 
						                   	$totaluse=0; $totalmoney=0;$no=1;$Amountuse=0;$Amountmoney=0;
						                   $Amountprice=0;
						                   		foreach  ($all as $rows) 
						                   
						             		{
						             			$totaluse=$rows['end_use']-$rows['stat_use'];
						             			$totalmoney=$totaluse*$rows['price'];
						             			$Amountuse+=$totaluse;
						             			$Amountmoney+=$totalmoney;
						             			$Amountprice+=$rows['price'];
						             	 	?> 
						                <tr  class="style" align="center" style="padding:0px 2px;white-space: nowrap;">  
						                    <td width=""​​><?php echo $no;?><br><?php //echo $tr->translate("PDAO");?></td>
						                    <td width=""><?php echo $rows['name_kh'];?></td>
						                    <td width=""><?php echo $rows['village_namekh'];?></td>
						                    <td width=""><?php echo $rows['phone'];  ?></td>	
						                    <td width=""><?php echo $rows['stat_use'];?></td>	       
						                    <td width=""><?php echo $rows['end_use'];?></td>
						                    <td width=""><?php echo $totaluse;?></td>
						                    <td width=""​​><?php echo $rows['price'];?></td>
						                    <td width=""><?php echo $totalmoney;?></td>
						                </tr>  
										  <?php  $no++;}?>        
						               
						                  <tr  class="style" align="center" style="padding:0px 2px;white-space: nowrap;">  
						                    <td width=""​​><?php echo 'Total';?><br><?php //echo $tr->translate("PDAO");?></td>
						                    <td width=""><?php //echo $rows['total_water'];?></td>
						                    <td width=""><?php //echo $rows['total_price'];?></td>
						                    <td width=""><?php //echo $totaldepebefor; ?></td>	
						                    <td width=""><?php //echo $rows['totalpaid'];?></td>	       
						                    <td width=""><?php //echo $debemoney;?></td>
						                    <td width=""><?php echo $Amountuse;?></td>
						                    <td width=""​​><?php echo $Amountprice;?></td>
						                    <td width=""><?php echo $Amountmoney;?></td>
						                </tr>  
						                
					            </table>
			            	</td>
			            	
			            </tr>
            			
            	</table>
            </div>
    	</td>
    </tr>
    
	</table>
		<br />
		   
</div>

