<?php $filter = $this->frm_search;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<style>
.hover:hover{background: #ccc;}</style>
<meta charset="utf-8">
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<title><?php echo $tr->translate("LOAN_DISBURSE_BY_CO");?></title>
<form method="post">
	<table style="font-family: 'Khmer OS Content'; margin: 0 auto;width:28.6cm;" >
		<tr>
			<td><?php echo $filter->getElement('adv_search');?></td>
			<td><?php echo $filter->getElement('co_id');?></td>
			<td><?php echo $filter->getElement('member');?></td>
		</tr>
		<tr>
			<td><?php echo $filter->getElement('start_date');?></td>
			<td><?php echo $filter->getElement('end_date');?></td>
			<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
		</tr>
	</table>
	</form>
<style>
.style{
	line-height: 20px;font-size: 10px !important;
	font-family: 'Khmer OS Battambang';
}
ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold; list-style-type: none;}
td ul li{list-style: none; }
</style>
<div style="clear: both;"></div>
<div style=" width:28cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm;">
<div id="divPrint" style="width: 100%;">
<table style="font-family: 'Khmer OS Content'; width:100%;">
	<tr>
    	<td align="center">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                		<ul>
                			<li style="list-style:none; text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_TITLE");?></li>
                			<li style="list-style:none;text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("LOAN_DISBURSE_BY_CO");?></li>
                			<li style="list-style:none;text-align:center; font-size:13px;"><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));?></li>
                		</ul>
                    </td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%">
                			<tr class='style'>
                				<td class="style" style="font-size: 10px;">
                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
                				</td>
                				<td width="65%"></td>
                			</tr>
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    <tr>
    	<td id="exportExcel" >
            <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:10px;" width="100%" cellspacing="0">
                   <?php  
                   
                    $co_id=''; $deposit=0;$num=1;$all_total_r=0;
                    $sold_amount = 0;$sold_deposit=0;
	               if(!empty($this->loanrelease_list)) foreach($this->loanrelease_list as $key =>$row){
               ?>
               <?php 
	             $sold_amount = $sold_amount+$row["price"];
	             $sold_deposit=$sold_deposit+$row["deposit"];
               ?>
                <?php 
                if($co_id!=$row['staff_id']){
                	$num=1;
                ?>
                <?php if($key>0){?>
                <tr>
                	<td style="background: #8494B5;" class="style" colspan="4">&nbsp;<?php echo $tr->translate("TOTAL");?>&nbsp;</td>
                </tr>
	            <tr bgcolor="#ccc" class="style" align="center" style="floafont-weight:bold; line-height: 14px; font-size:10px; padding:5px 0px;">
	                    <td style="padding:5px 0px;" colspan="2">&nbsp;​<?php echo $tr->translate("TOTAL_AMOUNT");?>&nbsp;</td>
	                    <td style="padding:5px 0px;" colspan="2">&nbsp;<?php echo $tr->translate("TOTAL_DEPOSIT");?>&nbsp;</td>
	            </tr>
                <tr class="style" style="font-weight:bold; line-height: 24px;">
                    <td colspan="2">&nbsp;<?php echo number_format($all_total_r,2);?>&nbsp;</td>
                    <td colspan="2">&nbsp;<?php echo number_format($deposit,2);?>&nbsp;</td>
                </tr>
                </table>
                    <br />
                <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:10px;" width="100%" cellspacing="0">
                <?php 
                } 
	                $all_total_r=0;
	                $deposit=0;
                ?>
             <?php ?>
                <tr>
                	<td colspan="15" class="style" style="background:#8494B5;">&nbsp;<span style="text-align:center;"><?php //echo $tr->translate("CO_NAME");?> </span><?php  echo $row['co_code'].' , '.$row['co_name'].' - '.$row['co_name_en'].' '//.($row['sex']=1?'ភេទ ប្រុស':'ភេទ  ស្រី'); ?></td>
                </tr>
                 <tr bgcolor="#ccc" align="center" class="style" style="font-weight:bold; line-height: 18px; font-size:10px;white-space:nowrap;">
                   <td>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
                   <td>&nbsp;<?php echo $tr->translate("LOAN_NO");?>&nbsp;</td>
                   <td>&nbsp;<?php echo $tr->translate("LAND_ADDRESS");?>&nbsp;</td>
                   <td>&nbsp;<?php echo $tr->translate("CLIENT_NUM");?>&nbsp;</td>
                   <td>&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?>&nbsp;</td>
                   <td>&nbsp;<?php echo $tr->translate("LOAN_AMOUNT");?>&nbsp;</td>
                   <td><?php echo $tr->translate("Price Before Dic");?></td>
                   <td><?php echo $tr->translate("Disc");?>%</td>
                   <td>&nbsp;<?php echo $tr->translate("DEPOSIT");?>&nbsp;</td>
                   <td>&nbsp;<?php echo $tr->translate("BALANCE");?>&nbsp;</td>
                   <td>&nbsp;<?php echo $tr->translate("INTEREST_RATE");?>&nbsp;</td>
                   <td>&nbsp;<?php echo $tr->translate("LOAN_PERIOD");?>&nbsp;</td>
                   <td>&nbsp;<?php echo $tr->translate("RELEASED_DATE");?>&nbsp;</td>
                   <td>&nbsp;<?php echo $tr->translate("LIFE_LOAN");?>&nbsp;</td>
                   <td>&nbsp;<?php echo $tr->translate("COMMISSION");?>&nbsp;%&nbsp;</td>
                </tr>
                <?php 
                }
	                $co_id = $row['staff_id'];
	                $all_total_r=$all_total_r+$row["price"];
	                $deposit=$deposit+$row["deposit"];
                ?>
					<tr align="center" class="hover">
						<td>&nbsp;<?php echo $num; $num++;?>&nbsp;</td>
						<td align="left">&nbsp;<?php echo $row['land_code']; ?>&nbsp;</td>
						<td align="left">&nbsp;<?php echo $row['land_address']; ?>&nbsp;</td>
						<td align="left">&nbsp;<?php echo $row['client_number']; ?>&nbsp;</td>
						<td align="left">&nbsp;<?php echo $row['client_name']; ?>&nbsp;</td>
						<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo number_format($row['org_price'],2); ?>&nbsp;</td>
						<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo number_format($row['discount'],2); ?>%&nbsp;</td>
						<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo number_format($row['price'],2); ?>&nbsp;</td>
						<td>&nbsp;<?php echo number_format($row['deposit'],2);?>&nbsp;</td>
						<td>&nbsp;<?php echo number_format($row['balance'],2);?>&nbsp;</td>
						<td >&nbsp;<?php echo number_format($row['interest_rate'],2); ?>&nbsp;</td>
						<td>&nbsp;<?php echo $row['amount_month'];?>&nbsp;</td>
						<td style="white-space:nowrap;" >&nbsp;<?php echo date('d/m/Y',strtotime($row['date_buy']));?>&nbsp;</td>
						<td style="white-space:nowrap;" >&nbsp;<?php echo date('d/m/Y',strtotime($row['end_date']));?>&nbsp;</td>
						<td>&nbsp;<?php echo $row['commission'];?>&nbsp;</td>
					</tr>
				<?php }?>
            	 <tr>
                	<td  style="background: #8494B5;" colspan="4">&nbsp;<?php echo $tr->translate("TOTAL");?>&nbsp;</td>
                </tr>
                 <tr bgcolor="#ccc" class="style" align="center" style="floafont-weight:bold; line-height: 14px; font-size:10px; padding:5px 0px;">
	                    <td style="padding:5px 0px;" colspan="2">&nbsp;​<?php echo $tr->translate("TOTAL_AMOUNT");?>&nbsp;</td>
	                    <td style="padding:5px 0px;" >&nbsp;<?php echo $tr->translate("TOTAL_DEPOSIT");?>&nbsp;</td>
	            		<td style="padding:5px 0px;" >&nbsp;<?php echo $tr->translate("Balance");?>&nbsp;</td>
	            </tr>
                <tr class="style" style="font-weight:bold; line-height: 24px;">
                    <td colspan="2">&nbsp;<?php echo number_format($all_total_r,2);?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format($deposit,2);?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format($all_total_r-$deposit,2);?>&nbsp;</td>
                </tr>
                 
              </table>
             <div style="border:1px dashed #000;margin:10px 0px; "><strong>Total Sold</strong></div>
              <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:10px;" width="100%" cellspacing="0">
              <tr bgcolor="#ccc" class="style" align="center" style="floafont-weight:bold; line-height: 14px; font-size:10px; padding:5px 0px;">
	                    <td style="padding:5px 0px;" colspan="2">&nbsp;​<?php echo $tr->translate("TOTAL_AMOUNT");?>&nbsp;</td>
	                    <td style="padding:5px 0px;">&nbsp;<?php echo $tr->translate("TOTAL_DEPOSIT");?>&nbsp;</td>
	            		<td style="padding:5px 0px;" >&nbsp;<?php echo $tr->translate("Balance");?>&nbsp;</td>
	            </tr>
                <tr class="style" style="font-weight:bold; line-height: 24px;">
                    <td colspan="2">&nbsp;<?php echo number_format($sold_amount,2);?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format($sold_deposit,2);?>&nbsp;</td>
                    <td>&nbsp;<?php echo number_format($sold_amount-$sold_deposit,2);?>&nbsp;</td>
                </tr>
             </table>
    	</td>
    </tr>
     	<tr><td>
               <table align="center" width="100%">
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>
        </td>
       </tr>       
</table>
</div>
</div>
