<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_search;
$opt = array(1=>"បង់ធម្មតា",2=>"បង់មុន",3=>"បង់រំលោះប្រាក់ដើម",4=>"បង់ផ្តាច់");
?>
<title><?php echo $tr->translate("RPT_CLIENT_PAYMENT");?></title>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
<form method="post">
<table style="font-family: 'Khmer OS Content'; margin: 0 auto;width:28.6cm;" >
	<tr>
   			<td><?php echo $frm->getElement("adv_search");?></td>
   			<td><?php echo $frm->getElement('branch_id');?></td>   			
   			<td><?php echo $frm->getElement('client_name');?></td>
   			<td><?php echo $frm->getElement('co_id');?></td>
   		</tr>
   		<tr>
   			<td><?php echo $frm->getElement('start_date');?></td>
   			<td><?php echo $frm->getElement('end_date');?></td>
   			<td><?php echo $frm->getElement('status');?></td>   			
   			<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
   	</tr>
</table>
</form>
<div style="width:100%; margin:0 auto;">
<div style=" width:28cm;min-height:22cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
<div id="divPrint">
<style type="text/css">
.style{
	line-height: 20px;font-size: 10px !important;
	font-family: 'Khmer OS Battambang';
}
.style1:hover{ background: #ccc; }
table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
</style>
<table width="100%">
	<tr>
    	<td align="center" valign="top">
        	<table width="100%" style="font-family: 'Khmer OS Battambang';"style="margin:0;padding:0;">
            	<tr>
                	<td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="80px"></td>
                	<td width="60%" valign="top">
                		<ul>
                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_TITLE");?></li>
                			<li style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("RPT_CLIENT_PAYMENT");?></li>
                			<li style="text-align:center; font-size:13px;"><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));?></li>
                		</ul>
                   </td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
                		<table width="100%" cellpadding="0" cellspacing="0">
                			<tr class='style'>
                				<td class="style" style="font-size: 7px;">
                					<?php echo $tr->translate("ADDRESS_COMPANY");?>
									<br /><?php echo $tr->translate("TEL_COMPANY");?>
                				</td>
                				<td width="65%"></td>
                			</tr>
		                </table>
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    <tr>
    	<td>
            <table id="exportExcel" width="100%" border="1" style="border-collapse:collapse; border:1px solid #000; " cellspacing="0">
	                <tr bgcolor="#ccc" class="style" align="center" style="padding:0px 2px;white-space: nowrap;">
	                    <th rowspan="2"><?php echo $tr->translate("NUM");?></th>
	                    <th rowspan="2"><?php echo $tr->translate("BRANCH_NAME");?></th>
	                    <th rowspan="2"><?php echo $tr->translate("LOAN_NO");?></th>	  
	                    <th rowspan="2"><?php echo $tr->translate("CLIENT_NUM");?></th>                  
	                    <th rowspan="2"><?php echo $tr->translate("CUSTOMER_NAME");?></th>
	                    <th rowspan="2"><?php echo $tr->translate("CO_NAME");?></th>
	                    <th colspan="5"><?php echo $tr->translate("TOTAL_PAYMENT");?></th>    
	                    <th rowspan="2" style="white-space:nowrap; border-right:3px double black; "><?php echo $tr->translate("PAY_DATE");?></th>
	                    <th rowspan="2"><?php echo $tr->translate("INPUT_DATE");?></th>
	                    <th rowspan="2"><?php echo $tr->translate("RECIEPT_NO");?></th>
	                    <th rowspan="2"><?php echo $tr->translate("PAYMENT_OPTION");?></th>
	                    <!-- <th rowspan="2"><?php //echo $tr->translate("BALANCE");?></th>-->
	                </tr>
	                <tr class="style" style="white-space: nowrap;">
	                	<th><?php echo $tr->translate("PRINCIPLE");?></th>                   
	                    <th><?php echo $tr->translate("INTEREST");?></th>
	                    <th><?php echo $tr->translate("PENALIZE AMOUNT");?></th>
	                    <th><?php echo $tr->translate("SERVICE CHARGE");?></th>	                    
	                    <th><?php echo $tr->translate("TOTAL");?></th>
	                </tr>
                <?php $amt_r1 = 0; $amn_r2 = 0; $amn_r3 = 0;$amt_r4 = 0;$amn_r5 = 0;
                	  $amt_d1 = 0;$amt_d2 = 0;$amt_d3 = 0;$amt_d4 = 0;$amt_d5 = 0;
                	 $amn_b1 = 0; $amn_b2 = 0; $amn_b3 = 0; $amn_b4 = 0;$amn_b5 = 0;
                	 $i=1;$oldloan_number='';
                	 //$total_penilize_amount_r=0;$total_penilize_amount_d=0;$total_penilize_amount_b=0;
                	 $total_d=0;$total_b=0;$total_r=0;
                ?>
                <?php $is_set =0; if(!empty($this->loantotalcollect_list)) foreach ($this->loantotalcollect_list as $index => $rs){ ?>
                
               <?php 
               $interest=0;
               	if($rs["payment_option"]==4){
               		
// 					if($oldloan_number!=$rs['loan_number'] AND $is_set!=1){
						$principle= $rs["principle_amount"];
						$total_pay = $rs["payment"];
						$interest= $rs["interest"];
						$recieve = $rs["amount_recieve"];
						$penelize = $rs["penelize"];
						$service_charge =$rs["service"];
						$is_set=1;
// 					}
				}else{
						$is_set=0;
	               		$service_charge = $rs["service_charge"];
	               		$interest = $rs["total_interest"];
	               		$principle = $rs["total_principal_permonth"];
	               		$penelize = $rs["penelize"];
	               		$recieve = $rs["recieve_amount"];
	               		$total_pay = $rs["total_payment"];
               		}
               		$oldloan_number = $rs['loan_number'];
               		$new_service = $recieve-$service_charge;
               		if($new_service>=0){
						$service = $service_charge;
						$new_penelize = $new_service - $penelize;
						if($new_penelize>=0){
							$penelize_amount =  $penelize;
							$new_interest = $new_penelize - $interest;
							if($new_interest>=0){
								$interest_amount = $interest;
								$new_printciple = $new_interest - $principle;
								if($new_printciple>=0){
									$principle_amount = $principle;
// 									exit();
								}else{
									$principle_amount = abs($new_interest);
// 									echo  $principle_amount;
								}
							}else{
								$interest = abs($new_penelize);
								$principle_amount=0;
								
							}
						}else{
							$penelize_amount = abs($new_service);
							$interest =0;
							$principle_amount=0;
							
						}
					}else{
						$service = abs($new_service);
						$penelize_amount = 0;
						$interest =0;
						$principle_amount=0;
					}
               ?>
               <?php 
//                		if($rs["payment_option"]==4){
// 						$principle_amount = $principle_amount + $principle;
// 						$interest_amount = $interest_amount + $interest;
// 						$penelize_amount= $penelize_amount+$penelize;
// 						$service = $service+$service_charge;
// 					}
               ?>
               <?php 
		               if($rs['currency_type']==1){
		               		$amt_r1 = $amt_r1+$principle_amount;
		               		$amn_r2 = $amn_r2+$interest_amount;
		               		$amn_r3 = $amn_r3+$penelize_amount;
		               		$amn_r5 = $amn_r5+$service;
		               		$total_r=$amt_r1+$amn_r2+$amn_r3+$amn_r5;
		               }elseif($rs['currency_type']==2){
							$amt_d1 = $amt_d1+$principle_amount;
							$amt_d2 = $amt_d2+$interest_amount;
							$amt_d3 = $amt_d3+$penelize_amount;
							$amt_d5 = $amt_d5+$service;
							$total_d=$amt_d1+$amt_d2+$amt_d3+$amt_d5;
		               }else{
		               		$amn_b1 = $amn_b1+$principle_amount;
							$amn_b2 = $amn_b2+$interest_amount;
							$amn_b3 = $amn_b3+$penelize_amount;
							
							$amn_b5 = $amn_b5+$service;
							$total_b=$amn_b1+$amn_b2+$amn_b3+$amn_b5;
		               }
               ?>
                <tr class="style style1" style="font-family: 'Khmer OS Content'; white-space:nowrap; ">
               		<td style="text-align: center;">&nbsp;<?php echo $i++; ?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["branch_name"];?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["loan_number"];?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["client_number"];?>&nbsp;</td>                 		
               		<td>&nbsp;<?php echo $rs["client_name"];?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["co_name"];?>&nbsp;</td>
               		<td align="center" style="font:bolder 11px Arial;">&nbsp;<?php echo number_format($principle_amount,2).' '.$rs['currency_typeshow'];?>&nbsp;</td>               		
               		<td align="center" style="font:bolder 11px Arial;">&nbsp;<?php echo number_format($interest_amount,2).' '.$rs['currency_typeshow'];?>&nbsp;</td>
               		<td align="center" style="font:bolder 11px Arial;">&nbsp;<?php echo number_format($penelize_amount,2).' '.$rs['currency_typeshow'];?>&nbsp;</td>
               		<td align="center" style="font:bolder 11px Arial;">&nbsp;<?php echo number_format($service,2).' '.$rs['currency_typeshow'];?>&nbsp;</td>
               		<td style="font:bolder 11px Arial;">&nbsp;<?php echo number_format($recieve,2).' '.$rs['currency_typeshow'];?>&nbsp;</td>
               		<!-- <td align="center" style="font:bolder 11px Arial;">&nbsp;<?php //echo number_format($rs["total_payment"],2).' '.$rs['currency_typeshow'];;?>&nbsp;</td> -->
               		<td style="white-space:nowrap; border-right:3px double black; ">&nbsp;<?php echo date("d-M-Y",strtotime($rs["date_payment"]));?>&nbsp;</td>
               		<td style="white-space:nowrap; ">&nbsp;<?php echo date("d-M-Y",strtotime($rs["date_input"]));?>&nbsp;</td>
               		<td>&nbsp;<?php echo $rs["receipt_no"];?>&nbsp;</td>
               		<td style="font-site:9px; <?php if($rs["payment_option"]==4){echo " background:#ccc";} ?>" align="center" >&nbsp;<?php echo @$opt[$rs["payment_option"]];?>&nbsp;</td>
               		<!--<td style="font:bolder 11px Arial;">&nbsp;<?php //$balance=($rs["recieve_amount"]-$rs["recieve_amount"])-$rs["total_payment"]; if($balance<0){echo '('.abs($balance).')';}else {echo $balance=0;};echo $rs['currency_typeshow'];?>&nbsp;</td>-->
                </tr>
                <?php }?>
            </table>
            <br />
             <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:9px;" width="100%" cellspacing="0">
                 <tr bgcolor="#ccc" class="style" style="font-weight:bold; line-height: 24px; text-align: center; font-size:9px;font-family: 'Khmer OS Content';">
                    <td><?php echo $tr->translate("CURRENT_TYPE");?></td>
                    <th><?php echo $tr->translate("PRINCIPAL");?></th>                    
                    <th><?php echo $tr->translate("TOTAL_INTEREST");?></th>
                    <th><?php echo $tr->translate("TOTAL_PENILIZE_AMOUNT");?></th>
                    <th><?php echo $tr->translate("TOTAL_SERVICE_CHARGE");?></th>
                    <th><?php echo $tr->translate("TOTAL");?></th>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:9px; font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d5,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo $total_d;?>&nbsp;</td>
                </tr>
                 <tr class="style" style=" line-height: 24px; font-size:9px;font-family: 'Khmer OS Content';">
                    <td>&nbsp;<?php echo $tr->translate("REILS");?></td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amt_r1,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_r2,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_r3,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo number_format($amn_r5,2);?>&nbsp;</td>
                    <td>&nbsp;&nbsp;<?php echo $total_r;?>&nbsp;</td>
                </tr>
                 <tr class="style" style="line-height: 24px; font-size:9px;font-family: 'Khmer OS Content';">
                   <td>&nbsp;<?php echo $tr->translate("BATH");?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b1,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b2,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b3,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo number_format($amn_b5,2);?>&nbsp;</td>
                   <td>&nbsp;&nbsp;<?php echo $total_b;?>&nbsp;</td>
                </tr>
              </table>
              <br />
               <table align="center" width="100%">
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>
    	</td>
    </tr>
</table>
</div>
</div>
</div>