<?php $tran = $this->tran_schedule;
$client = $this->client;
$filter = $this->form_filter;
$dayin_khmer = $this->day_inkhmer;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();

?>
<title><?php echo $tr->translate('REPORT WEEK');?></title>
<style>
td p{ margin-top:0px !important;}
</style>
<div style=" width:21cm; margin:0 auto; border: 1px dotted #ccc; padding: 0 40px;">
	<div id="divPrint">
	<style type="text/css">
	.style{
		line-height: 20px;font-size: 11px;
		font-family: 'Khmer OS Battambang';
	}
	.font_bold{
		font-family:'Khmer MEF2';
		font-size: 14px;
		
	}
	td p{ margin-top:-12px;}
	</style>
	<table style="font-family: 'Khmer OS Content'; width:100%;"  >
		<tr>
	    	<td align="center">
	        	<table width="100%" style="font-family:khmer;margin:0 auto;padding:0px; border:none;">
	            	<tr>
	                	<td width="30%" style="border-bottom: 1px solid #000;"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px">
	                		<p style="font-family: 'Khmer OS Battambang'; font-size:9px;margin-top:4px; line-height:15px;"><?php //echo $client['branch_name'];?> 	<?php echo $this->data['brand_adress'];?>
								<br /><?php //echo $this->data['phone_brand'];?></p>
	                	</td>
	                	<td width="47%" valign="top">
	                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer OS Muol'"><label><?php echo $tr->translate("BRAND_TITLE");?><?php //echo $this->data['brand_title'];?></label></h2>
	                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><?php //echo $tr->translate('rpt-paymentschedule');?> <?php //echo ($client['loan_type']==1)?$tr->translate('RPT_ILLOAN'):$tr->translate('RPT_GROULOAN') ;?></h2>
	                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"> <?php echo $tr->translate('RPT_ILLOAN');?></h2>
	                	</td>
	                    <td ></td>
	                </tr>
	                <?php $db = new Application_Model_DbTable_DbGlobal();
	                	  $row = $db->getClientByType(null,$client['client_id'],1);
	                ?> 
	                <tr>
	                	<td colspan="3">
	                		<table width="100%" style="margin-top:10px;">
			                	<tr class='style'>
				                   <td width="35%">
				                	    <p><b><?php echo $tr->translate('CUSTOMER_NAME');?></b>: <?php echo $client['client_name_kh'] ;?> </p>
				                	    <p> <?php echo "<strong>". $tr->translate('CLIENT_NO')."</strong> : ".$client['client_number']?></p>
				                		<p><b><?php echo $tr->translate("ADDRESS");?></b>:<?php echo $row['village_name'];?> ,<?php echo $row['commune_name'];?> <br /><?php echo $row['district_name'];?> ,  <?php echo $row['province_en_name'];?>
				                		<p><?php echo $tr->translate("TEL");?>  : <?php echo $client['tel'];?></p>  
				                		</td>
				                    <td valign="top" style="" width="33%">
				                        <!--<p><?php //echo $tr->translate("LOAN_AMOUNT");?>  : <?php //echo number_format($client['price_sold']-$client['other_fee'],2);?> $</p>
				                    	<p><?php //echo $tr->translate("Discount");?> : <b><?php //echo $client['discount_percent']."% +".number_format($client['discount_amount'],2);?> $</b></p>
				                    	<p><?php //echo $tr->translate("OTHER_FEE");?>  : <?php //echo number_format($client['other_fee'],2);?></p>
				                    	<p><?php //echo $tr->translate("TOTAL_AMOUNT");?>  : <?php //echo number_format($client['price_sold'],2);?></p>
				                    	<p><?php //echo $tr->translate("PAID");?>  : <?php //echo number_format($client['paid_amount'],2);?></p>
				                    	<p><?php //echo $tr->translate("BALANCE");?>  : <strong><?php //echo number_format($client['balance'],2);?></strong></p> -->
				                     <p><?php echo $tr->translate("HOUSE");?> : <b><?php echo $client['land_address'].",".$client['stree'];?></b></p>
				                	 <p><?php echo $tr->translate("ចំនួនប្រាក់ត្រូវរំលស់");?>  : <?php echo number_format($client['price_sold']-$client['total_installamount'],2);?> $</p>
				                     <p><?php echo $tr->translate("INTEREST_RATE");?> : <?php echo $client['interest_rate'];?>&nbsp;%</p>
									 <p><?php echo $tr->translate("TERM_BORROWINYEAR");?> : <?php echo ($client['total_duration']);?>&nbsp;ឆ្នាំ</p>
				     	             <!-- <p><?php //echo $tr->translate("TERM_BORROW");?> : <?php //echo $client['total_duration']*12;?>&nbsp;ខែ</p> -->
				                     
				                    </td>
				                     <td valign="top">
				                     <p><?php echo $tr->translate("RELEASED_DATE");?> : <?php echo date('d-M-Y',strtotime($client['buy_date']));?> </p>
				                     <p><?php echo $tr->translate("ថ្ងៃបង់រំលស់ដំបូង");?> : <?php echo date('d-M-Y',strtotime($client['first_payment'])); ?></p>
				                     <p><?php echo $tr->translate("ថ្ងៃបញ្ចប់");?> : <?php echo date('d-M-Y',strtotime($client['end_line'])); ?></p>
				                    </td>
				                </tr>
			                </table>
			              </td>
			           </tr>   
	            </table>
	        </td>
	    </tr>
	    <tr>
	    	<td>
	            <table id="exportExcel" border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%">
	                 <tr class="style" align="center" style="font-weight:bold; line-height: 20px;">
	                    <td rowspan="2"><?php echo $tr->translate("NUM");?></td>
	                    <td rowspan="2"><?php echo $tr->translate("DAY_PAYMENT");?></td>
	                    <!-- <td>ចំនួនថ្ងៃ</td> -->
	                    <td rowspan="2"><?php echo $tr->translate("PRINCIPLE");?></td>
	                    <td rowspan="2"><?php echo $tr->translate("ប្រាក់បង់បន្ថែម");?></td>
	                    <td colspan="3"><?php echo $tr->translate("AMOUNT");?></td>
	                    <td rowspan="2"><?php echo $tr->translate("OS");?></td>
	                    <td rowspan="2"><?php echo $tr->translate("Cumulative Interest");?></td>
	                </tr>
	                <tr class="style" align="center" style="font-weight:bold; line-height: 20px;">
	                    <!--<td>ចំនួនថ្ងៃ</td>-->
	                    <td>ប្រាក់ដើម</td>
	                    <td><?php echo $tr->translate("TOTAL_INTEREST");?></td>
	                    <td><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
	                </tr>
	               <?php $set=1; if(!empty($tran)) foreach($tran as $key =>$row){?>
	               	<?php if($set==1 AND $row['is_rescheule']==1){?>
	               	<tr align="center" style="font-weight:bold; height: 20px;" class="style">
	               		<td colspan="9" style="background: #d3d3ff">ចេញតារាងកាលវិភាគថ្មី</td>
	               	</tr>
	               	<?php $set=0; } ?>
	               	<tr align="center" style="font-weight:bold; height: 20px;" class="style">
	                    <td ><?php echo ($key+1<10)?"0":"";echo $key+1;?></td>
	                    <?php $str_day = date('D',strtotime($row['date_payment']));
	                    	$day_as_khmer = $dayin_khmer[$str_day];
	                    ?>
	                    <!--<td align="right">&nbsp;<?php //echo $day_as_khmer.'-'.$str_day; ?>&nbsp;&nbsp;&nbsp;</td> -->
	                    <td align="center"><?php echo date('d-M-Y',strtotime($row['date_payment']));?></td>
	                    <td><?php echo str_replace('.00', '', number_format($row['begining_balance'],2));?></td>
	                    <td align="center">&nbsp;-<?php  ?>&nbsp;&nbsp;&nbsp;</td>
	                    <td><?php echo str_replace('.00', '', number_format($row['principal_permonth'],2));?></td>
	                    <td><?php echo str_replace('.00', '', number_format($row['total_interest'],2));?></td>
	                    <td ><?php echo str_replace('.00', '', number_format($row['total_payment'],2)); ?></td>
	                    <?php 
	                   		$remain = $row['ending_balance'];
	                    ?>
	                    <td><?php echo number_format($remain,(!strrpos($remain,"."))? 0 : 2);?></td>
	                    <td><?php echo str_replace('.00', '', number_format($row['cum_interest'],2)); ?></td>
	                </tr>
	               <?php }
	               	if(!empty($record))for($record = $key;$record<11;$record++){
	               ?>
	               		<tr>
	               			<td>&nbsp;</td>
	               			<td></td>
	               			<td></td>
	               			<td></td>
	               			<td></td>
	               			<td></td>
	               			<td></td>
	               			<td></td>
	               		</tr>
	               <?php }?>
	            </table>
	            <table width="100%" cellpadding="3">
	            	<tr class="font_bold" style="height:25px;">
	            		<td align="center" valign="bottom" style="font-family:'Khmer OS Muol'"><?php echo $tr->translate('ACCOUNTING_SIGN');?></td>
	            		<td align="center" valign="bottom"></td> 
	            		<td align="center" valign="bottom" style="font-family:'Khmer OS Muol'"><?php echo $tr->translate('BORROWER');?></td>
	            	</tr>
	            	<tr class="font_bold">
	            		<td align="center" height="80px" valign="bottom"><?php echo $client['user_name'];?></td>
	            		<td align="center"  valign="bottom">
	            			<?php //echo ($client['displayby']==1)?$client['co_khname']:$client['co_enname'] ;?></td>
	            		<td align="center" height="75px" valign="bottom">
	            		<?php echo $client['client_name_kh'] ;?>
	            			<?php //echo ($client['displayclient']==1)? $client['client_name_kh']: $client['client_name_en'] ;?></td>
	            	</tr>
	            </table>
	    	</td>
	    </tr>
	</table>
	</div>
</div>