<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_search;
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<style>
.hover:hover{background: #ccc;}
</style>
<meta charset="utf-8">
<title><?php echo $tr->translate("BILLING_CLIENT");?></title>
<form name="frm_rptstaff" action="<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-water-month')); ?>" dojoType="dijit.form.Form" method="post">
	<table style="width:28cm; margin: 0 auto;">
		<tr>  
	        <td><?php echo $frm->getElement("adv_search");?></td>
	        <td><?php echo $frm->getElement('village_name');?></td>
	   		<td><?php echo $frm->getElement('client_name');?></td>
	   		<td><?php echo $frm->getElement('start_date');?></td>
	   		<td><?php echo $frm->getElement('end_date');?></td>
	   		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
	   </tr>
	</table>
 </form> 
<div style=" width:28cm;min-height:22cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
<?php $all=$this->rows;?>

 <?php
 //print_r($all);exit();
 $total_water=0; $total_payment=0;
 	foreach ($all as $rows)

 		
 		//$total_water=$rows['end_use']-$rows['stat_use'];
 		//$total_payment=$total_water*$rows['price'];
 {?> 
 
          
	<table style="font-family: 'Khmer OS Content'; width:100%;"  >
		<tr>
    		<td align="center">
    	 		<div id="divPrint">
    	 			<style>
						.style{
							line-height: 15px;font-size: 12px !important;
							font-family: 'Khmer OS Battambang';
						}
						th{padding: 1px;}
					</style>
        			<table width="100%" style="font-family:'Khmer OS Battambang';" style="margin:0; padding:0;border:none;" >
			        	<tr>
			                <td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="70px"></td>
			                <td width="75%" valign="top">
			                 <h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'">
			                 	<label><?php echo $tr->translate("WATER_STATION_PDAO");?></label>
			                 	  <h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("PHONE_NUMBER");?></label>:<?php echo ("016 885 866/ 015 777 262");?></h2>
			                <p style="text-align:center; font-size:14px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BILLING");?></p>
			                 </h2>
			                </td>
			                <td width="5%"></td>
			             </tr>

			             <tr>
			             	<td colspan="3">
			             		<table width="100%" style=" font-size: 12px;"  >
			             			<tr>
			             				<td width="25%"style="  font-weight: bold" ><?php echo $tr->translate("CUSTOMER_NAME");?> : </td>
			             				<td width="25%" ><?php echo $rows['name_kh']; ?></td>
			             				<td width="25%"style="  font-weight: bold" ><?php echo $tr->translate("CODE");?> :</td>
			             				<td width="25%"><?php echo $rows['client_num'];?></td>
			             			</tr>
									<tr>
										<td width="25%"style="  font-weight: bold" ><?php echo $tr->translate("START_DATE");?></td>
										<td width="25%"><?php echo $rows['date_start']?></td>
										<td width="25%"style="  font-weight: bold" ><?php echo $tr->translate("PHONE_NUMBER");?>:</td>
										<td width="25%"><?php echo $rows['phone'];?></td>
									</tr>
									<tr>
										<td width="25%"style="  font-weight: bold" ><?php echo $tr->translate("END_DATE");?></td>
										<td width="25%"><?php echo $rows['deadline']?></td>
										<td width="25%"style="  font-weight: bold" ><?php echo $tr->translate("ADDRESS");?></td>
										<td width="25%"><?php echo $rows['village_namekh']?></td>
									</tr>

			             		</table>
			             	</td>
			                
			             </tr>
            
			           	<tr>
			            	<td colspan="3" id="exportExcel">
			            			<table width="100%" border="1" style="border-collapse:collapse;  border:1px solid #b5b5b5; font-size: 12px; co " cellspacing="0">
						                <tr bgcolor="#c1d0f3"  class="style" align="center" style="padding:0px 1px;white-space: nowrap; height: 30px;">
						                    <td  width="15%" ><?php echo $tr->translate("OLD_CONTER");?></td>
						                    <td width="15%" ><?php echo $tr->translate("NEW_CONTER");?></td>
						                    <td width="15%" ><?php echo $tr->translate("TOTAL_USED_WATER");?>(M3)</td>	       
						                    <td width="25%"><?php echo $tr->translate("UNIT_PRICE");?>(KHR)</td>
						                    <td width="30%" ><?php echo $tr->translate("TOTAL");?>(KHR)</td>	
						                   
						                </tr>

						                <tr style="height: 7px; " >
						                	<td><?php echo $rows['stat_use'];?>m<sup>3</sup></td>
						                	<td><?php echo $rows['end_use'];?>m<sup>3</sup></td>
						                	<td><?php echo $rows['end_use']-$rows['stat_use'];?>m<sup>3</sup></td>
						                	 <td  width="25%" align="center"><?php echo $rows["price"];?></td>
						                	<td>&nbsp;</td>
						                </tr>
						                <tr  style="height: 7px;">
						                	<td colspan="3" rowspan="5" ><?php //echo $rows['stat_use'];?></td>
						                	<td  width="25%" align="center" style="background-color: #c1d0f3"><?php echo $tr->translate("MONEY_DEBTS");?></td>
						                	<td>&nbsp;</td>
						                </tr> 
						                <tr style="height: 7px; ">
						                	<td  width="25%" align="center" ><?php echo $tr->translate("MANTAINENT_CONTER");?></td>
						                	<td><?php echo $rows['maintanance_service']?></td>
						                </tr> 
						                <tr style="height: 7px; ">
						                	<td  width="25%" align="center" style="background-color: #c1d0f3"><?php echo $tr->translate("TOTALY_PAY");?></td>
						                	<td><?php echo $rows['total_price']?></td>
						                </tr> 
						                  <tr style="height: 7px; ">
						                	<td  width="25%" align="center" ><?php echo $tr->translate("DAY_PAY");?></td>
						                	<td><?php echo $rows['create_date']?></td>
						                </tr> 
						                  <tr style="height: 7px; ">
						                	<td  width="25%" align="center" style="background-color: #c1d0f3"><?php echo $tr->translate("TOTALY_PAID");?></td>
						                	<td><?php echo $rows['total_price']+$rows['maintanance_service']?></td>
						                </tr> 
						                
						                
						                <tr style="height:25px; ">
							            	<td colspan="3" style="border-top-style: hidden; border-right-style:hidden;"></td>
							            	<td align="center" colspan="2" style="border-bottom-style: hidden;"><b><?php echo $tr->translate("SIGNATUR_RECIVER");?></b></td>
							            </tr>
						                  <tr style="height:35px; ">
							            	<td colspan="3" style="border-top-style: hidden; border-right-style:hidden;"></td>
							            	<td align="center" colspan="2" >______________________</td>
							            </tr>
						               <tr bgcolor="#c1d0f3" style="padding: 0px; 20px;">
							            	<td colspan="3" align="right" ><?php echo $tr->translate("PLEASE_PAY_BEFOR");?></td>
							            	<td colspan="2" ><?php echo $rows['deadline'];?></td>
							            </tr>
   
					            </table>
			            	</td>
			            	
			            </tr>
			            
			            <tr >
			            <td colspan="5"><hr style="margin: 5px 0px; border-style: none none dotted; "></td>
			            </tr>
			            	<tr>
			            	<td colspan="3" id="exportExcel">
			            			<table width="100%" border="1" style="border-collapse:collapse;  border:1px solid #b5b5b5; font-size: 12px; " cellspacing="0">
						                <tr  class="style" align="center" style="padding:0px 1px;white-space: nowrap; height: 10px;  ">
						                    <td colspan="3" style="border-bottom-style: hidden;"  width="45%"></td>     
						                    <td width="20%" ></td>
						                    <td width="30%"></td>	
						                   
						                </tr>
						                <tr  style="height: 7px; " >
						                	<td colspan="3" rowspan="4" ><?php //echo $rows['stat_use'];?></td>
						                	<td  width="25%" align="center" style="background-color: #c1d0f3"><?php echo $tr->translate("MONNEY_TO_PAY_AMOUNT");?> </td>
						                	<td><?php echo $rows['total_price']+$rows['maintanance_service'] ?></td>
						                </tr> 
						                 
						                <tr style="height: 7px; ">
						                	<td  width="25%" align="center" ><?php echo $tr->translate("DAY_PAYMENT");?> </td>
						                	<td><?php echo $rows['create_date']?></td>
						                </tr> 
						                  <tr style="height: 7px; ">
						                	<td  width="25%" align="center" style="background-color: #c1d0f3"><?php echo $tr->translate("TOTALY_PAID");?> </td>
						                	<td>e</td>
						                </tr> 
						                  <tr style="height: 7px; ">
						                	<td  width="25%" align="center" ><?php echo $tr->translate("THE_AMOUNT_lACKING");?> </td>
						                	<td>&nbsp;</td>
						                </tr> 
						                
						                
						                <tr style="height:25px; ">
							            	<td colspan="3" style="border-top-style: hidden; border-right-style:hidden; " ></td>
							            	<td align="center" colspan="2" style="border-bottom-style: hidden;"><b><?php echo $tr->translate("SIGNATUR_RECIVER");?></b></td>
							            </tr>
						                  <tr style="height:35px; ">
							            	<td colspan="3" style="border-top-style: hidden; border-right-style:hidden; " ></td>
							            	<td align="center" colspan="2" >______________________</td>
							            </tr>
				            	</table>
			            	</td>
			            	
			            </tr>
			          
            	   </table>
           		 </div>
    		</td>
    	</tr>
	</table>
 <?php }?>  
		
</div>

