<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_callteral;
?>
<style>	
.fullside{
	width: 100%;
	height: 30px;
}
</style>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()){
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" class='fullside' >
	<tr>
		<td>
				<fieldset>
					<legend align="center"><strong>ព៌ត័មាន កិច្ចសន្យាខ្ចីប្រាក់</strong></legend>
					<form  id='add_techer' action="/landsystem/trunk/public/group/position/Add" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				/*if(dijit.byId('province').get('value')==''){
					alert('Province required');
					return false;
			    }*/
				return true;
			} else {
				return false;
			}
</script>
<table cellspacing="10" width="90%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset>
					<legend><strong>POSITION_INFO</strong></legend>
					
					<table style="margin: 0 auto; width: 95%;" cellspacing="10">
						<tr>
							<td>POSITION_KH</td>
							<td>
<input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="position_kh" name="position_kh" value="" type="text"></td>
							<td>POSITION_EN</td>
							<td>
<input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="position_en" name="position_en" value="" type="text"></td>
						</tr>
						<tr>
							<td>ការបង្ហាញ</td>
							<td>
<select name="display" id="display" dojoType="dijit.form.FilteringSelect" class="fullside">
    <option value="1" label="ឈ្មោះជាខ្មែរ">ឈ្មោះជាខ្មែរ</option>
    <option value="2" label="NAME_ENGLISH">NAME_ENGLISH</option>
</select></td>
							<td>ស្ថានភាព</td>
							<td>
<select name="status" id="status" dojoType="dijit.form.FilteringSelect" class="fullside">
    <option value="1" label="នៅដំណើរការ">នៅដំណើរការ</option>
    <option value="0" label="ផ្អាកដំណើរការ">ផ្អាកដំណើរការ</option>
</select></td>
						</tr>
					</table>	
					<div style="text-align: center; margin: 10px 0px;"> 
						<input type="hidden" name="exchangefrom" value="2" />
						<input type="hidden" name="inv_no" value="">
						<input type="reset" value="សំអាត" label="សំអាត"dojoType="dijit.form.Button"/>
						<input type="submit" value="save_close" name="save_close" label="រក្សាទុក+បិត" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconSave" />
						<input type="submit" value="save_new" name="save_new" label="រក្សាទុក+ថ្មី" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconSave" />
					</div>	`
		</fieldset>
		</td>
	</tr>
</table>	
</form>
				</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
			<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"
				 iconClass="dijitEditorIcon dijitEditorIconSave"/>
		</td>
	</tr>	
</table>
</form>
<script type="text/javascript">
	dojo.require("dijit.form.Textarea");
</script>