<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('Land Information'));
?>	
<?php  $frm = $this->frm_client;?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.Dialog");
</script>
<form id='add_client' action="<?php echo $this->url(array('module'=>'group','controller'=>'land','action'=>'edit')); ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<table  width="100%" style="margin-top:-5px;">
	<tr>
		<td>
		<fieldset>
					<legend ><strong><?php echo $tr->translate("EDIT_PROPERTY");?></strong></legend>
					<table style="margin: 0 auto; width:100%;" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("BRANCH_NAME")?></td>
							<td><?php echo $frm->getElement('branch_id');?></td>
							<td><?php echo $tr->translate("PROPERTY_CODE")?></td>
							<td><?php echo $frm->getElement('landcode');?></td>
							 <td valign="top"><?php echo $tr->translate("HEAD_TITLE_NO")?></td>
							<td valign="top"><?php  echo $frm->getElement('hardtitle');?></td>
							</tr>
						<tr>
							<td><?php echo $tr->translate("HOUSE_TITLE")?>*</td>
							<td><label id="message" style="color: red;"></label>
							<?php  echo $frm->getElement('land_address');?></td>
							<td><?php echo $tr->translate("STREET")?>*</td>
							<td><?php  echo $frm->getElement('street');?></td>
							<td valign="top"><?php echo $tr->translate("PROPERTY_TYPE")?></td>
							<td valign="top"><input id="property_type" /><?php  //echo $frm->getElement('property_type');?></td>
						</tr>
						<tr>
						   <td><?php echo $tr->translate("LAND_PRICE")?>*</td>
							<td><?php  echo $frm->getElement('land_price');?></td>
							<td><?php echo $tr->translate("HOUSE_PRICE")?>*</td>
							<td><?php  echo $frm->getElement('house_price');?></td>
							<td><?php echo $tr->translate("PRICE")?>*</td>
							<td><?php  echo $frm->getElement('price');?></td>
							
						</tr>
						<tr>
							<td><?php echo $tr->translate("WIDTH")?></td>
							<td><?php  echo $frm->getElement('width');?></td>
							<td><?php echo $tr->translate("HEIGHT")?></td>
							<td><?php  echo $frm->getElement('height');?></td>
							<td><?php echo $tr->translate("SIZE")?></td>
							<td><?php  echo $frm->getElement('size');?></td>
						  
						</tr>
						<tr>
							<td valign="top"><?php echo $tr->translate("FLOOR")?></td>
							<td><?php  echo $frm->getElement('floor');?></td>
							<td valign="top"><?php echo $tr->translate("BEDROOM")?></td>
							<td valign="top"><?php  echo $frm->getElement('bedroom');?></td>
						    <td valign="top"><?php echo $tr->translate("LIVING")?></td>
							<td valign="top"><?php  echo $frm->getElement('living');?></td>
						</tr>
						<tr>
							<td valign="top"><?php echo $tr->translate("DINNER_ROOM")?></td>
							<td><?php  echo $frm->getElement('dinnerroom');?></td>
							<td valign="top"><?php echo $tr->translate("BUIDING_YEAR")?></td>
							<td valign="top"><?php  echo $frm->getElement('buidingyear');?></td>
						    <td valign="top"><?php echo $tr->translate("PARKING_SPACE")?></td>
							<td valign="top"><?php echo $frm->getElement('parkingspace');?></td>
						</tr>
						<tr>
							<td valign="top"><?php echo $tr->translate("STATUS")?></td>
							<td valign="top"><?php  echo $frm->getElement('status');?></td>
							<td valign="top"><?php echo $tr->translate("NOTE")?></td>
							<td><?php  echo $frm->getElement('desc');?></td>
						</tr>
						<tr>
							<td colspan="6" align="center">
							<input type="reset" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" 
								 iconClass="dijitIconClear" /> 
							 <input type="submit" value="SAVE_CLOSE" tabindex="2" label="<?php echo $tr->translate('GO_EDIT');?>" id="save_close" dojoType="dijit.form.Button" name="save_close"
								 iconClass="dijitEditorIcon dijitEditorIconSave" /> 
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<table>
<tr>
</tr>
</table>
<?php echo $this->frmPopupPropertyType;?>
<script type="text/javascript">
var propertyType_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->pro_type));?> );
dojo.ready(function(){
	
	try{
		new dijit.form.FilteringSelect({
			store: propertyType_store,
			autoComplete: true,
			required: false,         
			name: "property_type",
			id: "property_type",
			value: "<?php echo $this->row['property_type'];?>",
			searchAttr: "name",
			class: 'fullside',
				onChange: function() {
					//district = dijit.byId('property_type').get('value');
					showPopupForm();
				}  
			}, "property_type");
	}catch(e){
	}
});

function showPopupForm(){
	property_type = dijit.byId('property_type').get('value');
	if(property_type==''){
		alert('Please Select Property Type');
		dijit.byId('property_type').focus();
		return false;
	}else if(property_type==-1){
		dijit.byId('frm_propertytype').show();
	}
}
url_property = '<?php echo $this->url(array('module'=>'group','controller'=>'propertiestype','action'=>'add-propertytype'));?>';
function addNewPropertytype(){
	if(dijit.byId('frm_propertytype').validate()) {
		dojo.xhrPost({
			url:url_property,	
			form:dojo.byId('form_propertytype'),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data,
					    name: dijit.byId('type_nameen').get('value')
				};		
				addDataToSelectbox(dijit.byId('property_type'), propertyType_store, Itemmake, data);
				dijit.byId('property_type').attr('value',data);	
				dijit.byId('frm_propertytype').reset();
				dijit.byId('frm_propertytype').hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
function CalculatePrice(){
	house_price = dijit.byId('house_price').get('value');
	land_price = dijit.byId('land_price').get('value');
	var price = Number(house_price + land_price);
	dijit.byId('price').attr('value',price);
}
var old_title = '<?php echo $this->row['land_address'];?>';
url_CheckTitle = '<?php echo $this->url(array('module'=>'group','controller'=>'land','action'=>'check-title'));?>';
function checkTitle(){
	title = dijit.byId('land_address').get('value');
	branch_id = dijit.byId('branch_id').get('value');
	dojo.xhrPost({
		url:url_CheckTitle,	
		content:{ 
			'branch_id': branch_id , 'land_address': title
		},
		handleAs:"json",
		load: function(data) {	
			if(title == old_title){
				document.getElementById('message').innerHTML ='';
			}else{
				if(data !== false ){
			   		document.getElementById('message').innerHTML ='This title has been used ready.';
			   		dijit.byId('land_address').focus();
				}else{
					document.getElementById('message').innerHTML ='';
				}
			}
		},
		error: function(err) {
			alert(err);
		}
	});
}
</script>