<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_expense;
// print_r($this->all_category);
?>
<title>Edit Other Expense</title>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
</style>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
 <script>
		//require(["dijit/form/DateTextBox","dijit/form/NumberTextBox"]);
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog"]);
 </script>
 
 
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'expense','action'=>'edit')); ?>" 
	dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
               branch_id = dijit.ById('branch_id').get('value');
			  // if(branch_id==null || branch_id==0){
				//alert("Please Select Project");
				//dijit.byId("branch_id").focus();
				//return false;
         	 // }
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" class='fullside' >
	<tr>
		<td>
			<fieldset>
				<legend><strong>ចំណាយផ្សេងៗ</strong></legend>
				<table cellspacing="10"  width="100%">
					<tr>
					    <td><?php echo $tr->translate("BRANCH_NAME")?></td>
						<td><?php echo $frm->getElement('branch_id');?></td>
						<td><?php echo $tr->translate("Inc.")?></td>
						<td><?php echo $frm->getElement('invoice');?></td>
						 <td><?php echo $tr->translate("EXPENSE_TITLE")?></td>
						<td><?php echo $frm->getElement('title');?></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("CATEGORY")?></td>
						<td><input id="income_category" /></td>
						<td><?php echo $tr->translate("TOTAL_INCOME")?></td>
						<td><?php echo $frm->getElement('total_amount');?></td>
						<td><?php echo $tr->translate("DATE")?></td>
						<td><?php echo $frm->getElement('Date');?></td>
					</tr>
					<tr>
					    <td><?php echo $tr->translate("ប្រភេទ")?></td>
						<td><?php echo $frm->getElement('payment_type');?></td>
						<td><?php echo $tr->translate("CHEQUE")?></td>
						<td><?php echo $frm->getElement('cheque');?></td>
						<td><?php echo $tr->translate("NOTE")?></td>
						<td><?php echo $frm->getElement('Description');?></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("STATUS")?></td>
						<td><?php echo $frm->getElement('Stutas');?></td>
					</tr>
				</table>
			</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
		<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button"
				 iconClass="dijitIconClear"/>
			<input type="submit" label="<?php echo $tr->translate("GO_EDIT");?>" name='saveclose' value='saveclose' dojoType="dijit.form.Button"
				 iconClass="dijitIconDelete"/>
			<input type="button" label="<?php echo $tr->translate("PRINT_SAVE")?>" name='print' value=''print'' dojoType="dijit.form.Button"
				 iconClass="dijitIconNewTask" onClick="printSave('');displayNone();" />
		</td>
	</tr>	
</table>
</form>

<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.CheckBox");

function displayNone(){
	document.getElementById('divPrint1').style.display="none";
}

dojo.ready(function(){
	dijit.byId('income_category').attr('value',<?php echo $this->row['category_id'];?>);
});


var income_category_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->all_category));?> );

new dijit.form.FilteringSelect({
	store: income_category_store,
	autoComplete: true,                        
    id: "income_category",
    name: "income_category",  
   // tabindex: "17",    
    class: 'fullside',  
    placeHolder:"Selected Category", 
    onChange: function() {          
	   	fa_job = dijit.byId('income_category').get('value');
	    if(fa_job==-1){
	   	 dijit.byId("popup_category").show();
	    }
    } 
}, "income_category");

var url_add_category = '<?php echo $this->url(array("module"=>"loan","controller"=>"expense","action"=>"add-category")); ?>';
function addCategory(){
	dojo.xhrPost({
		url:url_add_category,
		form: dojo.byId("frm_category"),
		handleAs:"json",
		load: function(data) {
			var Itemmake = { 
	    		id: data,
		        name: dijit.byId('cate_name').get('value')
		    };
	 		addDataToSelectbox(dijit.byId('income_category'), income_category_store, Itemmake, data);
		    dijit.byId('frm_category').reset();
		    dijit.byId("popup_category").hide();
		},
		error: function(err) {
			alert(err);
		}
	});
}

function getInvoiceNo(condition){
	
}

function printSave(new_invoice_no){
	
	dojo.byId("lb_invoice").innerHTML = dijit.byId("invoice").attr('displayedValue');
	dojo.byId("lb_invoice1").innerHTML = dijit.byId("invoice").attr('displayedValue');
	
	dojo.byId("lb_branch").innerHTML = dijit.byId("branch_id").attr('displayedValue');
	//dojo.byId("lb_customer").innerHTML = dijit.byId("customer").attr('displayedValue');
	dojo.byId("lb_income_category").innerHTML = dijit.byId("income_category").attr('displayedValue');
	dojo.byId("lb_income_title").innerHTML = dijit.byId("title").get('value');
	dojo.byId("lb_total_amount").innerHTML =currencyFormat(dijit.byId("total_amount").get('value'));
	dojo.byId("lb_date").innerHTML = dijit.byId("Date").attr('displayedValue');
	dojo.byId("lb_description").innerHTML = dijit.byId("Description").attr('displayedValue');
	//dojo.byId("lb_customer_name").innerHTML = dijit.byId("customer").attr('displayedValue');
	dojo.byId("lb_cheque").innerHTML = dijit.byId("cheque").attr('displayedValue');


	dojo.byId("lb_branch1").innerHTML = dijit.byId("branch_id").attr('displayedValue');
	//dojo.byId("lb_customer1").innerHTML = dijit.byId("customer").attr('displayedValue');
	dojo.byId("lb_income_category1").innerHTML = dijit.byId("income_category").attr('displayedValue');
	dojo.byId("lb_income_title1").innerHTML = dijit.byId("title").get('value');
	dojo.byId("lb_total_amount1").innerHTML = currencyFormat(dijit.byId("total_amount").get('value'));
	dojo.byId("lb_date1").innerHTML = dijit.byId("Date").attr('displayedValue');
	dojo.byId("lb_description1").innerHTML = dijit.byId("Description").attr('displayedValue');
	//dojo.byId("lb_customer_name1").innerHTML = dijit.byId("customer").attr('displayedValue');
	dojo.byId("lb_cheque1").innerHTML = dijit.byId("cheque").attr('displayedValue');
	
	dijit.byId("print_income").show();
}

function currencyFormat(num) {
    return "$ " + num.toFixed(2).replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1,")
}

function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML + dojo.byId('divPrint1').innerHTML;;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    printSubmit();
    hideDialog();
}
function printSubmit(){
	 $('#frm_add_tran').submit();
}
</script>

<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:30%;" id="popup_category" >
		<form style="background-color: buttonface; width:100%;" id='frm_category' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
				<tr>
					<td>
						<fieldset style="background-color: buttonface;">
						<legend align="center" ><?php echo $tr->translate('ADD_CATEGORY');?></legend><br />
							<table style="margin: 0 auto; width: 100%;  padding:10px;" cellspacing="7" >
								<tr>
									<td><?php echo $tr->translate('NAME_KH');?></td>
									<td>
										<input dojoType="dijit.form.ValidationTextBox"   class="fullside" id="cate_name" name="cate_name" value="" type="text">
									</td>
								</tr>
								<tr>
									<td><?php echo $tr->translate('STATUS');?></td>
									<td>
										<select name="status_j" id="status_j" dojoType="dijit.form.FilteringSelect"   class="fullside">
		    								<option value="1" label="active">Active</option>
		    								<option value="0" label="deactive">Deactive</option>
										</select>
									</td>
									
								</tr>
								<tr>
									<td colspan="4" align="center">
										<input type="button" value="ចាកចេញ" label="Close" id="close" name="close" dojoType="dijit.form.Button" 
										​ ​​iconClass="dijitIconUndo" onclick="hideDialog1();"/>
										<input type="button" value="save" label="SAVE" id="save" name="save" dojoType="dijit.form.Button" 
										 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addCategory();"/>
									</td>
								</tr>
								
							</table>
					</fieldset>
					</td>
				</tr>
			</table>

		</form>
	</div>
</div>


<div class="dijitHidden" style="width: 22cm !important; height: 11cm ; padding: 0px; margin: 0px;">
	<div data-dojo-type="dijit.Dialog" style="width:22cm;" align="center" data-dojo-props="title:'<?php echo $tr->translate("PAYMENT_RECEIPT");?>'" id="print_income" >
		<div id="divPrint" style="width: 21cm !important; height: 13cm ; padding: 0px; margin: 0px;">
			<style>
				.fontbig{
					font-size: 15px;	
				}
				.fonttel{
					font-size: 18px;	
				}
				.pleft{
					width: 110px;	
				}

				.label{ font-weight: bold;font-size: 22px;}
				.value{ font:bold 12px 'Khmer OS Battambang';border: 1px solid rgba(14, 0, 107, 1); height: 24px; width: 100%;margin-right:5px; display: block;
						line-height: 25px;
					    text-align: center;
						}
				.print tr td{
					padding:2px 2px; 
				}
			   .khmerbold{font:bold 12px 'Khmer OS Battambang';}
			   .khmer{font:12px 'Khmer OS Battambang';}
			   .one{white-space:nowrap;}
			   .h{ margin-top: -10px;/*margin-left:4px;*/}
			</style>	
			<table width="100%" style="white-space: nowrap;font-size:12px;margin-top: -10px;" class="print" cellspacing="0"  cellpadding="0" >
				<tr>
					<td colspan="6">
						<table width="100%" style="font-family:'Khmer MEF2';white-space:nowrap;">
							<tr>
								<td width="25%">
									<img style="width:100%;height:61px;" src="<?php echo $this->baseUrl().'/images/bppt_logo.png'?>">
								</td>					
								<td width="50%" style="font:bold 18px 'Kh Muol';" valign="top" align="center"><u><b><strong style=" font-family: Arial Black;font-family:'Khmer MEF2';">បង្កាន់ដៃចំណាយ</strong></b></u>
									<div style="line-height:10px;"><strong style="font-size: 18px;font-weight:bold">OFFICIAL RECEIPT</strong></div>
								</td>
								<td width="25%">
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<table width="100%" style="white-space: nowrap;font-size:12px;margin-top: -20px;" class="print" cellspacing="8px"  cellpadding="0">
				<tr>
					<td width="10%" ></td>
					<td width="37%" ></td>
					<td width="15%" ></td>
					<td width="13%" ></td>
					<td width="10%" ></td>
					<td width="20%" ></td>
				</tr>
				
				
				<tr style="white-space: nowrap;">
				
					<td class="one khmerbold">គម្រោង</td>
                    <td><strong><label id="lb_branch" class="value"></label></strong></td>
					
					
				    <td class="one khmerbold">&nbsp;&nbsp;&nbsp;វិក័យប័ត្រលេខ</td>
                    <td colspan="3"><strong><label id="lb_invoice" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
				
					<td class="one khmerbold">ពណ៌នាចំនាយ</td>
					<td ><strong><label id="lb_income_title" class="value"></label></strong></td>
					
					<td class="one khmerbold">&nbsp;&nbsp;&nbsp;ប្រភេទចំណាយ</td>
				    <td colspan="3"><strong><label id="lb_income_category" class="value"></label></strong></td>
				</tr>

				<tr>
					<td class="one khmerbold">សែក</td>
				    <td ><strong style="white-space: nowrap;"><label style="white-space: nowrap;" id="lb_cheque" class="value"></label></strong></td>
					
					<td class="one khmerbold">&nbsp;&nbsp;&nbsp;ចំណាយសរុប</td>
					<td colspan="3"><strong><label id="lb_total_amount" class="value"></label></strong></td>
					
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold">សម្គាល់</td>
				    <td colspan="1" align="center"><strong style="white-space: nowrap;"><label style="white-space: nowrap;text-align: center; " id="lb_description" class="value"></label></strong></td>
				
					
					<td class="one khmerbold">&nbsp;&nbsp;&nbsp;ថ្ងៃចំណាយ</td>
				    <td colspan="3"><strong><label id="lb_date" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
				    <td class="khmerbold" style="line-height: 14px;"colspan="4"  align="center" >&nbsp;&nbsp;<strong style=" font-family: Arial Black;font-family:'Khmer MEF2';"></strong></td>
				    <td colspan="2" class="khmerbold" style="line-height: 14px;" align="center" ><strong style=" font-family: Arial Black;font-family:'Khmer MEF2';">ស្នាមមេដៃអ្នកទទួល</strong></td>
				</tr>
				<tr style="white-space: nowrap;" height="60px;">
					<td class="one khmerbold" colspan="4" align="center" valign="bottom">
					</td>
				    <td class="one khmerbold" colspan="2" align="center" valign="bottom">&nbsp;
				  			<h4 style="padding-right: 5px ! important;margin-bottom: -10px  !important;">
				              <?php $session_user=new Zend_Session_Namespace('auth');
						           $last_name=$session_user->last_name;
						           $username = $session_user->first_name;
						           echo $last_name." ".$username;?></h4>  
					</td>
				</tr>
				
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="6" valign="top" >
						
					</td>
				</tr>
				
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="6" style="border-top: 2px solid rgba(255, 235, 59, 0.88)">
						
					</td>
				</tr>
				
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="6" >
						<table width="100%" style="font-size:11px;line-height: 12px;margin-top: -5px;font-family: 'Khmer OS Battambang';"> 
							<tr>
								<td width="22%">
									<img style="width:70%;height: 25px;" src="<?php echo $this->baseUrl().'/images/bppt_letter.png'?>">
								</td>
								<td width="40%">
									<span style=""><?php echo $this->data['website'];?></span>
								</td>
								<td width="40%" align="right">
									<span style="font-family: 'Khmer OS Battambang';"><?php echo $this->data['email_client'];?></span>
								</td>
							</tr>
							<tr >
								<td colspan="3">
									<table width="100%" style="white-space:nowrap;font-size:11px;font-family: 'Khmer OS Battambang';">
										<tr>
											<td width="70%" >
												<?php echo $this->data['footer_branch'];?>
											</td>
											<td width="30%" align="right">
												<span style=""><?php echo $this->data['tel-client'];?></span>
											</td>
										</tr>
									</table>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="6">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="6" style="border-top:1px dashed #000;" >
						
					</td>
				</tr>
			</table>
		</div>
		<table>
			<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
			<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
				type="button" onclick="doPrint();">បោះពុម្ភ/Print</button>
		</table>
		
		<div id="divPrint1" style="width: 21cm !important; height: 13cm ; padding: 0px; margin: 0px;">
			<table width="100%" style="white-space: nowrap;font-size:12px;margin-top: 10px;" class="print" cellspacing="0"  cellpadding="0" >
				<tr>
					<td colspan="6">
						<table width="100%" style="font-family:'Khmer MEF2';white-space:nowrap;">
							<tr>
								<td width="25%">
									<img style="width:100%;height:61px;" src="<?php echo $this->baseUrl().'/images/bppt_logo.png'?>">
								</td>					
								<td width="50%" style="font:bold 18px 'Kh Muol';" valign="top" align="center"><u><b><strong style=" font-family: Arial Black;font-family:'Khmer MEF2';">បង្កាន់ដៃចំណាយ</strong></b></u>
									<div style="line-height:10px;"><strong style="font-size: 18px;font-weight:bold">OFFICIAL RECEIPT</strong></div>
								</td>
								<td width="25%">
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<table width="100%" style="white-space: nowrap;font-size:12px;margin-top: -20px;" class="print" cellspacing="8px"  cellpadding="0">
				<tr>
					<td width="10%" ></td>
					<td width="37%" ></td>
					<td width="15%" ></td>
					<td width="13%" ></td>
					<td width="10%" ></td>
					<td width="20%" ></td>
				</tr>
				
				
				<tr style="white-space: nowrap;">
				
					<td class="one khmerbold">សាខា</td>
                    <td><strong><label id="lb_branch1" class="value"></label></strong></td>
					
					
				    <td class="one khmerbold">&nbsp;&nbsp;&nbsp;វិក័យប័ត្រលេខ</td>
                    <td colspan="3"><strong><label id="lb_invoice1" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
				
					<td class="one khmerbold">ពណ៌នាចំនាយ</td>
					<td ><strong><label id="lb_income_title1" class="value"></label></strong></td>
					
					<td class="one khmerbold">&nbsp;&nbsp;&nbsp;ប្រភេទចំណាយ</td>
				    <td colspan="3"><strong><label id="lb_income_category1" class="value"></label></strong></td>
				</tr>

				<tr>
					<td class="one khmerbold">សែក</td>
				    <td ><strong style="white-space: nowrap;"><label style="white-space: nowrap;" id="lb_cheque1" class="value"></label></strong></td>
					
					<td class="one khmerbold">&nbsp;&nbsp;ចំណាយសរុប</td>
					<td colspan="3"><strong><label id="lb_total_amount1" class="value"></label></strong></td>
					
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold">សម្គាល់</td>
				    <td colspan="1" align="center"><strong style="white-space: nowrap;"><label style="white-space: nowrap;text-align: center; " id="lb_description1" class="value"></label></strong></td>
				
					
					<td class="one khmerbold">&nbsp;&nbsp;ថ្ងៃចំណាយ</td>
				    <td colspan="3"><strong><label id="lb_date1" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
				    <td class="khmerbold" style="line-height: 14px;"colspan="4"  align="center" >&nbsp;&nbsp;<strong style=" font-family: Arial Black;font-family:'Khmer MEF2';"></strong></td>
				    <td colspan="2" class="khmerbold" style="line-height: 14px;" align="center" ><strong style=" font-family: Arial Black;font-family:'Khmer MEF2';">ស្នាមមេដៃអ្នកទទួល</strong></td>
				</tr>
				<tr style="white-space: nowrap;" height="60px;">
					<td class="one khmerbold" colspan="4" align="center" valign="bottom">
					</td>
				    <td class="one khmerbold" colspan="2" align="center" valign="bottom">&nbsp;
				  			<h4 style="padding-right: 5px ! important;margin-bottom: -10px  !important;">
				              <?php $session_user=new Zend_Session_Namespace('auth');
						           $last_name=$session_user->last_name;
						           $username = $session_user->first_name;
						           echo $last_name." ".$username;?></h4>  
					</td>
				</tr>
				
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="6" valign="top" >
						
					</td>
				</tr>
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="6" style="border-top: 2px solid rgba(255, 235, 59, 0.88)">
						
					</td>
				</tr>
				
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="6" >
						<table width="100%" style="font-size:11px;line-height: 12px;margin-top: -5px;font-family: 'Khmer OS Battambang';"> 
							<tr>
								<td width="22%">
									<img style="width:70%;height: 25px;" src="<?php echo $this->baseUrl().'/images/bppt_letter.png'?>">
								</td>
								<td width="40%">
									<span style=""><?php echo $this->data['website'];?></span>
									
								</td>
								<td width="40%" align="right">
									<span style="font-family: 'Khmer OS Battambang';"><?php echo $this->data['email_client'];?></span>
								</td>
							</tr>
							<tr >
								<td colspan="3">
									<table width="100%" style="white-space:nowrap;font-size:11px;font-family: 'Khmer OS Battambang';">
										<tr>
											<td width="70%" >
												<?php echo $this->data['footer_branch'];?>
											</td>
											<td width="30%" align="right">
												<span style=""><?php echo $this->data['tel-client'];?></span>
											</td>
										</tr>
									</table>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="6">&nbsp;</td>
				</tr>
			</table>
		</div>
		
	</div>
</div>



