<?php	
	$this->headTitle('Add Sell'); 
	echo $this->headTitle();
	$frm = $this->frm_loan;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<style>
.fullside50{ width:48%;}
</style>
<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>	
	<script src="<?php echo $baseurl;?>/js/help.js"></script>
   <script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog"]);
   </script>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'transferproject','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				branch_id = dijit.byId('branch_id').get('value');
				if (branch_id=='' || branch_id==-1){
					alert('Please Select Branch!');
					dijit.byId('branch_id').focus();
					return false;
				}
				client = dijit.byId('member').get('value');
				if (client=='' || client==-1){
					alert('Please Select Client Name !');
					dijit.byId('member').focus();
					return false;
				}
				
				// old_paid = dijit.byId('paid_before').get('value');
				// new_paid = dijit.byId('deposit').get('value');
				// if(old_paid > new_paid){
					// alert('You can not pay less than old paid amount');
					// dijit.byId('deposit').focus();
					// return false;
				// }
				return true;
			}else {
				return false;
			}
</script>
<table width="100%" style="margin-top:-10px;">
	<tr>
		<td>
				<fieldset>
					<legend><strong><?php echo $tr->translate("INFO_INDILOAN")?></strong></legend>
					<table cellspacing="5"  width="100%" style="margin-top: -10px;">
						<tr>
							<td width="13%"><?php echo $tr->translate("BRANCH_NAME")?></td>
							<td width="25%"><?php echo $frm->getElement('branch_id');?></td>
							<td><?php echo $tr->translate("LOAN_NO")?></td>
							<td><input id='loan_number' /></td>
							<td><?php echo $tr->translate("CUSTOMER_CODE")?></td>
							<td><input id="customer_code" /><input type="hidden" name="identity" id="identity"  value="" >
							</tr>
						<tr>
							<td><?php echo $tr->translate("DATE_BUY")?></td>
							<td><?php echo $frm->getElement('date_buy');?></td>
							<td style="white-space: nowrap;"><?php echo $tr->translate("AGREEMENT_DATE")?></td>
							<td><?php echo $frm->getElement('agreement_date');?></td>
							<td><?php echo $tr->translate("CUSTOMER_NAME")?></td>
							<td><input id="member" /> <?php //echo $frm->getElement('member');?></td>
						</tr>
						<tr style="background: #edf7f8;">
							<td colspan="6" style="border-bottom:1px solid #aac4e6;"><strong><?php echo $tr->translate("PROPERTY_INFORMATION")?></strong></td>
						</tr>
						<tr height="40px">
							<td><?php echo $tr->translate("LAND_CODE")?></td>
							<td><input id="land_code" /><?php //echo $frm->getElement('');?></td>
							<td><?php echo $tr->translate("DESCRIPTION")?></td>
							<td style="height: 50px; border:1px solid #aac4e6; widht:100%; font-size: 13px; color:blue;padding:5px;" colspan="4"><label id="land_information"></label><?php //echo $tr->translate("Address")?></td>
						</tr>
						<tr>
						    <td><?php echo $tr->translate("TOTAL_SOLD")?></td>
							<td><?php echo $frm->getElement('total_sold');?></td>
							<td><?php echo $tr->translate("PAID")?></td>
							<td><?php echo $frm->getElement('paid_before');?></td>
							<td><?php echo $tr->translate("Balance")?></td>
							<td><?php echo $frm->getElement('balance_before');?></td>
						</tr>
						<tr>
							<td colspan="6" style="border-bottom:1px solid #aac4e6;"><strong><?php echo $tr->translate("TRANSFER_PROPERTY_INFORMATION")?></strong></td>
						</tr>
						<tr height="40px">
							<td><?php echo $tr->translate("BRANCH_NAME")?></td>
							<td><?php echo $frm->getElement('to_branch_id');?></td>
							<td><?php echo $tr->translate("TO_LAND_CODE")?></td>
							<td><input id="to_land_code" /><?php //echo $frm->getElement('');?></td>
							<td><?php echo $tr->translate("DESCRIPTION")?></td>
							<td style="widht:200px; font-size: 12px;" colspan="2"><label id="to_land_information"></label><?php //echo $tr->translate("Address")?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("LAND_PRICE")?></td>
							<td><?php echo $frm->getElement('land_price');?></td>
							<td><?php echo $tr->translate("HOUSE_PRICE")?></td>
							<td><?php echo $frm->getElement('house_price');?></td>
							<td><?php echo $tr->translate("TOTAL_SOLD")?></td>
							<td><?php echo $frm->getElement('to_total_sold');?></td>
						</tr>
						<tr style="background: #edf7f8;">
							<td colspan="6" style="border-bottom:1px solid #aac4e6;"><strong><?php echo $tr->translate("PAYMENT_INFORMATION")?></strong></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Discount")?></td>
							<td><?php echo $frm->getElement('discount_percent');?><?php echo $frm->getElement('discount');?></td>
							<td><?php echo $tr->translate("TOTAL_PAYMENT")?></td>
							<td><?php echo $frm->getElement('sold_price');?></td>
							<td><?php echo $tr->translate("Balance")?></td>
							<td><?php echo $frm->getElement('balance');?>
								<?php echo $frm->getElement('other_fee');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("PAYMENT_TYPE")?></td>
							<td><?php echo $frm->getElement('schedule_opt');?></td>
							<td style="color:red;">ប្រាក់រំលស់</td>
							<td><?php //echo $frm->getElement('deposit');?>
							<input dojoType="dijit.form.TextBox" class="fullside" id="deposit" name="deposit" value="" type="hidden">
							<?php //echo $frm->getElement('total_installamount');?>
							<input readonly type="text" class="fullside" dojoType="dijit.form.TextBox" name="for_installamount" id="for_installamount"  value="" >
									<input type="hidden" class="fullside" dojoType="dijit.form.TextBox" name="total_installamount" id="total_installamount"  value="" >
							</td>
						</tr>
						<tr>
						    <td style="white-space: nowrap;"><lable id='lbl_period'><?php echo $tr->translate("TERM_BORROW")?></lable><lable id='lbl_year'><?php echo $tr->translate("YEAR")?></lable></td>
							<td><?php echo $frm->getElement('period');?></td>
							<td><?php echo $tr->translate("INTEREST_RATE")?></td>
							<td><?php echo $frm->getElement('interest_rate');?></td>
							<td><label id="lbl_payment"><?php echo $tr->translate("AMOUNT_FUND_GRAICE_PARIOD")?></label></td>
							<td><?php echo $frm->getElement('fixed_payment');?></td>
						</tr>
						<tr>
							<td><label id="lbl_release"><?php echo $tr->translate("LOAN_RELEASE")?></label></td>
							<td><?php echo $frm->getElement('release_date');?></td>
							<td><?php echo $tr->translate("FIRST_PAYMENT")?></td>
							<td><?php echo $frm->getElement('first_payment');?></td>
							<td><?php echo $tr->translate("LIFE_LOAN")?></td>
							<td><?php echo $frm->getElement('date_line');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("CHEQUE")?></td>
							<td><?php echo $frm->getElement('cheque')?></td>
							
							<td><?php echo $tr->translate("NOTE")?></td>
							<td><?php echo $frm->getElement('note')?></td>
						</tr>
						<tr style="max-height: 300px;">
								<td colspan="6">
									<div  id="showrecord"></div>
									<input type="button" label="<?php echo $tr->translate('ADD_INSTALLMENT');?>" dojoType="dijit.form.Button" 
								 		iconClass="dijitIconEditProperty" onclick="addRow();" />
								</td>
						</tr>
					</table>
				</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
			<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
			<input type="submit" label="<?php echo $tr->translate("SAVECLOSE");?>" name='saveclose' value='saveclose' dojoType="dijit.form.Button" iconClass="dijitIconDelete"/>
			<input type="submit" label="<?php echo $tr->translate("SAVENEW")?>" name='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask"/>
			<input type="button" onclick="addPreviewLoan();" label="<?php echo $tr->translate("PREVIEW")?>" name='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask" />
		</td>
	</tr>	
</table>
<div class="dijitHidden">
<style>
.print tr td{
	padding:5px 2px; 
}
</style>
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'កាលវិភាគត្រូវបង់ប្រាក់'" id="lbl_schedule" style="width:1000px">
	<div id="rpt_print" class="print" style="text-align: center;">
		<div id="t_amountmoneytype" name="t_amountmoneytype">
		</div>
	</div>
</div>
</div>
</form>
<script type="text/javascript">	
var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'get-il-loan-Detail')); ?>';
function getLaonPayment(){
	loan_number = dijit.byId("loan_number").get('value');
		dojo.xhrPost({
		    url: url_submit,
		    content : { 
			    'loan_number':loan_number,
			},	
			handleAs:"json",
			load: function(respone) {
					/*dijit.byId('identity').attr('value',"");
					dijit.byId('priciple_amount').attr('value',0);
					dijit.byId('os_amount').attr('value',0);
					dijit.byId('total_payment').attr('value',0);
					dijit.byId('amount_receive').attr('value',0);
					dijit.byId('discount').attr('value',0);
					dijit.byId('service_charge').attr('value',0);
					dijit.byId('penalize_amount').attr('value',0);
					dijit.byId('total_interest').attr('value',"");
					dijit.byId('amount_return').attr('value',0);
					dijit.byId('payment_term').attr('value',"");
					dijit.byId('currency_type').attr('value',"");*/
				
			},
			error: function(e) {
				//alert(e);
			}
		});
}

function setBranchID(){
	dijit.byId('to_branch_id').attr('value',dijit.byId('branch_id').get('value'));	
}
function checkScheduleOption(){
	dijit.byId('first_payment').set("readOnly",false);
	dijit.byId('period').set("readOnly",false);
	dijit.byId('interest_rate').set("readOnly",false);
	dijit.byId('release_date').set("readOnly",false);
	dijit.byId('date_line').set("readOnly",true);
	method_id = dijit.byId('schedule_opt').get('value');

	amount_principal = dijit.byId('balance').get('value');	
	debt_amount = dijit.byId('period').get('value');

	dojo.byId('lbl_period').innerHTML="<?php echo $tr->translate("TERM_BORROW")?>";
	dojo.byId('lbl_year').innerHTML="<?php echo $tr->translate("YEAR")?>";
	dojo.query("#table_row").append('');
	$('#identity').val('');
	dojo.query("#showrecord").append('');
	title=0;
	no=0;
	
	if(method_id==4){
		calCulateFixedPeriod();		
		}else {
			dijit.byId('fixed_payment').attr('value',0);
			dijit.byId('fixed_payment').set("readOnly",true);
		if(method_id==1){//booking
			dijit.byId('date_line').attr('value','<?php echo date("Y-m-d");?>');
			dijit.byId('release_date').set("readOnly",true);
			dijit.byId('first_payment').set("readOnly",true);
			dijit.byId('date_line').set("readOnly",false);
			dijit.byId('period').set("readOnly",true);
			dijit.byId('period').attr("value",0);
			dijit.byId('interest_rate').attr("value",0);
			dijit.byId('interest_rate').set("readOnly",true);
		}else if(method_id==2){//payoff
			dijit.byId('release_date').set("readOnly",true);
			dijit.byId('first_payment').set("readOnly",true);
			dijit.byId('interest_rate').set("readOnly",true);
			dijit.byId('interest_rate').attr("value",0);
			dijit.byId('period').set("readOnly",true);
			amount_principal = dijit.byId("balance").get("value");
			dijit.byId('deposit').attr("value",0);
			
		}else if(method_id==3){//times
			dojo.byId('lbl_period').innerHTML="<?php echo $tr->translate("TOTAL_INSTALLMENT")?>";
			dojo.byId('lbl_release').innerHTML="<?php echo $tr->translate("START_DATE")?>";
			dojo.byId('lbl_year').innerHTML='<?php echo $tr->translate("MONTH")?>';
			if(isNaN(amount_principal)){amount_principal=0;}if(isNaN(debt_amount)){debt_amount=0;}
			total_collect = amount_principal/debt_amount;
			total_collect = total_collect.toFixed(2);
			if(debt_amount!=0){
				dijit.byId('fixed_payment').attr("value",total_collect);
			}
			if(dijit.byId('interest_rate').get('value')==0){
				dijit.byId('interest_rate').attr("value",0);}
			dijit.byId('interest_rate').set("readOnly",false);
			
		}else if(method_id==5){//times
			dijit.byId('release_date').set("readOnly",true);
			dijit.byId('first_payment').set("readOnly",true);
			if(dijit.byId('interest_rate').get('value')==0 ){
				dijit.byId('interest_rate').attr("value",0);
			}
			dijit.byId('interest_rate').set("readOnly",true);
			dijit.byId('period').set("readOnly",true);
		}
		else if(method_id==6){//times
			
			if(dijit.byId('period').get('value')==12){
				dijit.byId('period').attr('value',12);
			}
			$('#identity').val('');
			dojo.byId('lbl_period').innerHTML="<?php echo $tr->translate("TOTAL_INSTALLMENT")?>";
			dojo.byId('lbl_year').innerHTML='<?php echo $tr->translate("MONTH")?>';
			dojo.byId('lbl_period').innerHTML="<?php echo $tr->translate("TOTAL_INSTALLMENT")?>";
			dojo.byId('lbl_release').innerHTML="<?php echo $tr->translate("START_DATE")?>";
			if(isNaN(amount_principal)){amount_principal=0;}if(isNaN(debt_amount)){debt_amount=0;}
			
			total_collect = amount_principal/debt_amount;
			total_collect = total_collect.toFixed(2);
			if(isNaN(total_collect)){
				total_collect=0;
			}
			dijit.byId('fixed_payment').attr("value",total_collect);
			if(dijit.byId('interest_rate').get('value')==0){
			dijit.byId('interest_rate').attr("value",0);}
			dijit.byId('interest_rate').set("readOnly",false);
		}
	}
}
function calCulateFixedPeriod(){
	var total_paid_install = dijit.byId('total_installamount').get('value');
	if(total_paid_install == 0){
		amount_principal = dijit.byId('balance').get('value');
	}else{
		amount_principal = dijit.byId('balance').get('value')-dijit.byId('total_installamount').get('value');
	}	
	
	dijit.byId('fixed_payment').set('readOnly',false);
	dojo.byId('lbl_payment').innerHTML="<?php echo $tr->translate("AMOUNT_GRAICE_PARIOD")?>";
	debt_term=30;
	collect_term = 1;
	collect_amount = 1;
	collect_term=30;
	debt_amount = dijit.byId('period').get('value')*12;
	
	term = (debt_term*debt_amount)/(collect_term*collect_amount);
	interest_rate=dijit.byId('interest_rate').get('value')/12/(100);//(100/30day)
	if(interest_rate==0){
		amount_payment = parseFloat(amount_principal/debt_amount);
		amount_payment = amount_payment.toFixed(0);
		if(amount_payment=='Infinity' || amount_payment=='NaN'){amount_payment=0;}
	}else{
		top_pow = Math.pow((1+interest_rate),term);
		bellow = Math.pow((1+interest_rate),(term))-1;
		amount_payment = (amount_principal*interest_rate*top_pow)/(bellow);
		
		amount_payment = amount_payment.toFixed(0);
		if(isNaN(amount_payment)){amount_payment=0;
		}
	}	
	dijit.byId('fixed_payment').attr('value',amount_payment);
	dijit.byId('for_installamount').attr('value',amount_principal);
}
function calculateDiscount(){
	total_sold = dijit.byId('to_total_sold').get('value');
	discount = dijit.byId('discount').get('value');
	discount_percent = dijit.byId('discount_percent').get('value');
	other_fee = dijit.byId('other_fee').get('value');
	if(isNaN(other_fee)){
		other_fee=0;
	}if(isNaN(discount)){
		discount=0;
	}
	if(isNaN(discount_percent)){
		discount_percent=0;
	}
	discount_percent = total_sold*discount_percent/100;
	//total_sold = total_sold-discount_percent-discount+other_fee;
	total_sold = total_sold-discount_percent-discount+other_fee;
	dijit.byId('sold_price').attr('value',total_sold);
	Balance();
}
function Balance(){
	price = dijit.byId('to_total_sold').get('value');
	deposit =dijit.byId('deposit').get('value');
	if(isNaN(deposit)){
		deposit=0;
	}
	if(deposit>price){
		alert("Deposit can not biger than price");
		dijit.byId('deposit').focus();
		dijit.byId('deposit').attr('value',price)
		dijit.byId('balance').attr('value',0)
	}else{ 
		schedule_opt = dijit.byId('schedule_opt').get('value');
		if(schedule_opt==2){
			dijit.byId('balance').attr('value',0);
		}else{
			if(schedule_opt==3){
				dijit.byId('for_installamount').attr('value',price-deposit);
			}
		}
		checkScheduleOption();
	}
	sold_price = dijit.byId("sold_price").get("value");
	balance_before= dijit.byId("balance_before").get("value");
	paid_before = dijit.byId("paid_before").get('value');
	dijit.byId('balance').attr('value',sold_price-paid_before);
	
	dijit.byId('for_installamount').attr('value',sold_price-paid_before);
	
}
function filterClient(){
	branch_id = dijit.byId('branch_id').get('value');
	
	getAllPropertyBranch(branch_id);
	//getLoanByBranch();
	//getReceiptByBranch();
	getAllClientByBranch(branch_id);
	getAllClientNumberByBranch(branch_id);
	getAllSaleNumber(branch_id);
}
var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'transferproject','action'=>'getallland')); ?>';
function getAllPropertyBranch(branch_id){//used
	dojo.xhrPost({
		url:url_getland,	
		content:{ 
		    'branch_id':branch_id,
		    'action':1
		},		    
		handleAs:"json",
		load: function(data) {
			property_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('land_code').set('store', property_store);
		},
		error: function(err) {
		}
	});
} 

var url_getland_transfer = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
function getAllPropertyBranchTransfer(){//used
	to_branch_id = dijit.byId('to_branch_id').get('value');
	dojo.xhrPost({
		url:url_getland_transfer,	
		content:{ 
		    'branch_id':to_branch_id,
		},		    
		handleAs:"json",
		load: function(data) {
			property_store_transfer  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('to_land_code').set('store', property_store_transfer);
		},
		error: function(err) {
		}
	});
} 

var url_getclient = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientbybranch')); ?>';
function getAllClientByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclient,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('member').set('store', client_store);
		},
		error: function(err) {
		}
	});
}
var url_getclientnum = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientnumberbybranch')); ?>';
function getAllClientNumberByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclientnum,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_number_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('customer_code').set('store', client_number_store);
		},
		error: function(err) {
		}
	});
}
var url_getloan = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getloannumber')); ?>';
function getLoanByBranch(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_getloan,	
		content:{ 
		    'branch_id':branch_id,
		    'is_group':0
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('sale_code').attr('value',data);
		},
		error: function(err) {
			//alert(err);
		}
	});
}

var url_getreceipt = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'get-receipt-number')); ?>';
function getReceiptByBranch(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_getreceipt,	
		content:{ 
		    'branch_id':branch_id,
		    'is_group':0
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('receipt').attr('value',data);
		},
		error: function(err) {
			//alert(err);
		}
	});
}
    function calCulatorBalance(){
    	//price = dijit.byId('land_price').get('value');
    	deposit =dijit.byId('deposit').get('value');
    	if(isNaN(deposit)){
    		deposit=0;
    	}
    	if(deposit>price){
    		//alert("Deposit can not biger than price ");
    		//dijit.byId('deposit').focus();
    		//dijit.byId('deposit').attr('value',price)
    	}
        dijit.byId('balance').attr('value',price-deposit);
        checkScheduleOption();
    	
    }
    
    function checkValidateDate(){
		return true;
     }
    function setDefaultPaymentAmount(){
    	//amount_principal = dijit.byId('land_price').get('value');
    	debt_term = dijit.byId('pay_every').get('value');
    	debt_amount = dijit.byId('period').get('value');
    	if(debt_term==1){
    		debt_term=1;
    	}else if(debt_term==2){
    		debt_term=7;
    	}
    	else{
    		debt_term=30;
    	}
    	//collect_term = dijit.byId('collect_termtype').get('value');
		collect_amount = 1;
		if(collect_term==1){
			collect_term=1;
    	}else if(collect_term==2){
    		collect_term=7;
    	}
    	else{
    		collect_term=30;
    	}
		
    	term = (debt_term*debt_amount)/(collect_term*collect_amount);

		interest_rate=dijit.byId('interest_rate').get('value')/100;

		top_pow = Math.pow((1+interest_rate),term);
		bellow = Math.pow((1+interest_rate),(term))-1;
		
		amount_payment = (amount_principal*interest_rate*top_pow)/(bellow);
		}
	function hideDialog() {		
		dijit.byId("recript_dialog").hide();
		saveTrans(); 
	}
	function doPrint() {
		//alert(document.getElementById('lbl_mainform'));
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML + dojo.byId('divPrint1').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
		printSubmit();
	    hideDialog();
	}
	function printSubmit(){
		$('#frm_add_tran').submit();
	}
	function displayNone(){
		document.getElementById('divPrint1').style.display="none";
	}
</script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");

var client_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->client_name));?> );
var client_number_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->client_code));?> );
var co_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->co_name));?> );
var property_store  = getDataStorefromJSON('id','name', null );
var property_store_transfer  = getDataStorefromJSON('id','name', null );

require(["dojo/ready"], function(ready){
	 ready(function(){
		setFirstPaymentAndDateLine(3,<?php echo date('d-m-Y');?>,1);
		checkScheduleOption();
	  });
	 
	new dijit.form.FilteringSelect({
			store: property_store,//dojo.data.ObjectStore({objectStore: client_data}),
			autoComplete: true,
			required: false,		           
			name: "land_code",
			id: "land_code",
			searchAttr: "name",
			class: 'fullside',
			required:true,
			onChange: function() {
				land_code = dijit.byId('land_code').get('value');
				if(land_code==-1){
				}else{
					getlandinfo();
				}
		}
	}, "land_code");

	new dijit.form.FilteringSelect({
		store: property_store_transfer,//dojo.data.ObjectStore({objectStore: client_data}),
		autoComplete: true,
		required: false,		           
		name: "to_land_code",
		id: "to_land_code",
		searchAttr: "name",
		class: 'fullside',
		required:true,
		onChange: function() {
			land_code = dijit.byId('to_land_code').get('value');
			if(land_code==-1){
			}else{
				getlandinfotransfer();
			}
	}
}, "to_land_code");
	 
	new dijit.form.FilteringSelect({
	store: client_store,//dojo.data.ObjectStore({objectStore: client_data}),
	autoComplete: true,
	required: false,		           
	name: "member",
	id: "member",
	searchAttr: "name",
	required:true,
	class: 'fullside',
	onChange: function() {
		member = dijit.byId('member').get('value');
		if(member==-1){
			showPopupclient();
		}else{
			dijit.byId('customer_code').attr('value',member);
		}
}
	}, "member");
	
	new dijit.form.FilteringSelect({
	store: client_number_store,//dojo.data.ObjectStore({objectStore: client_number}),
	autoComplete: true,
	           
	required: false,		           
	name: "customer_code",
	id: "customer_code",
	searchAttr: "name",
	class: 'fullside',
	onChange: function() {
		customer_code = dijit.byId('customer_code').get('value');
		if(customer_code==-1){
			showPopupclient();
		}else{
			dijit.byId('member').attr('value',customer_code);
		}
    }
	}, "customer_code");

	new dijit.form.FilteringSelect({
		store: co_store,//dojo.data.ObjectStore({objectStore: client_number}),
		autoComplete: true,            
		required: false,		           
		name: "co_id",
		id: "co_id",
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			co_id = dijit.byId('co_id').get('value');
			if(co_id==-1){
				popupcreditofficer();
			}else{
			}
	    }
		}, "co_id");

	new dijit.form.FilteringSelect({
		store: co_store,//dojo.data.ObjectStore({objectStore: client_number}),
		autoComplete: true,            
		required: false,		           
		name: "loan_number",
		id: "loan_number",
		searchAttr: "name",
		class: 'fullside',
		onChange: function(){
			getInfoByLoanNumber();
	    }
		}, "loan_number");
	 
	});
</script>
<script type="text/javascript">
var url_submiinfo = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getsaleinfo')); ?>';
function getInfoByLoanNumber(){
	loan_id = dijit.byId('loan_number').get('value');
	dojo.xhrPost({
	    url: url_submiinfo,	
	    content : { 
		    'sale_id':loan_id ,
		},	
		handleAs:"json",
		load: function(data) {

			total_principal= data.total_principal;
			
			if(isNaN(total_principal) || total_principal==null){total_principal=0;}
		    paid_amount = data.paid_amount;
			if(isNaN(paid_amount) || paid_amount==null){paid_amount=0;}
			total_principal = parseFloat(total_principal);
			
			dijit.byId('paid_before').attr('value',total_principal);
			
			dijit.byId("member").attr('value',data.client_id);
			dijit.byId('customer_code').set('readOnly',true);
			dijit.byId('land_code').attr('value',data.house_id)
			dijit.byId('member').set('readOnly',true);
			dijit.byId('total_sold').attr('value',data.price_sold);
			dijit.byId('total_sold').set('readOnly',true);
			dijit.byId('date_buy').attr('value',data.buy_date);
			dijit.byId('agreement_date').attr('value',data.agreement_date);
			
			/*dijit.byId("customer_code").attr('value',data.client_id);
			dijit.byId('member').set('readOnly',true);
			dijit.byId('currency_type').attr('value',data.currency_type);
			dijit.byId('currency_type').set('readOnly',true);
			dijit.byId('co_id').attr('value',data.co_id);
			dijit.byId('interest_rate').attr('value',data.interest_rate);
			dijit.byId('zone').attr('value',data.zone_id);
		    dijit.byId('level').attr('value',data.level);
		    dijit.byId('level').set('readOnly',true);
		    dijit.byId('repayment_method').attr('value',data.payment_method);
		    dijit.byId('branch_id').attr('value',data.branch_id);
		    dijit.byId('branch_id').set('readOnly',true);
		    ;
		    dijit.byId('group_id').attr('value',data.group_id);*/
		},
		error: function(err) {
			alert(err);
		}
	});
}
var sale_number_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_getsalenumber = "<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'get-sale-number')); ?>";
function getAllSaleNumber(branch_id){//used
	dojo.xhrPost({
		url:url_getsalenumber,	
		content:{ 
		    'branch_id':dijit.byId('branch_id').get('value')
		},		    
		handleAs:"json",
		load: function(data) {
			sale_number_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('loan_number').set('store',sale_number_store); 
		},
		error: function(err) {
			
		}
	});
}
var url_getlandinfodetail = '<?php echo $this->url(array('module'=>'group','controller'=>'land','action'=>'getlandinfo')); ?>';
function getlandinfo(){
	//dijit.byId('total_sold').attr('value',0);
	dijit.byId('sold_price').attr('value',0);
	dojo.xhrPost({
		url:url_getlandinfodetail,	
		content:{ 
		    'land_id':dijit.byId('land_code').get('value')
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('land_code').set('readOnly',true);
			dijit.byId('paid_before').set('readOnly',true);
			dijit.byId('balance_before').set('readOnly',true);

			//dijit.byId('total_sold').attr('value',data.price);
			dojo.byId('land_information').innerHTML ="លេខសម្គាល់ "+data.land_code+", លេខផ្ទះ/ឡូតិ៏  "+data.land_address+", លេខផ្លូវ  "+data.street+", ប្រភេទ  "+data.property_type+", ទំហំ "+data.land_size+" ម៉ែត្រការ៉េ, បណ្តោយ "+data.height+" ម៉ែត្រ, ទទឹង  "+data.width+" ម៉ែត្រ";
			paid_before = dijit.byId('paid_before').get('value');
			price_sold = dijit.byId("total_sold").get("value");
			dijit.byId('balance_before').attr('value',price_sold-paid_before);
			
			//dijit.byId('deposit').attr('value',data.price);
			
			checkScheduleOption();
			Balance();
			
		},
		error: function(err) {
			alert(err);
		}
	});
}

var url_getlandinfotransferdetail = '<?php echo $this->url(array('module'=>'group','controller'=>'land','action'=>'getlandinfo')); ?>';
function getlandinfotransfer(){
	dojo.xhrPost({
		url:url_getlandinfotransferdetail,	
		content:{ 
		    'land_id':dijit.byId('to_land_code').get('value')
		},		    
		handleAs:"json",
		load: function(data) {
			
			//dojo.byId('to_land_information').innerHTML ="លេខ "+data.land_code+", ឈ្មោះ  "+data.land_address+", ទំហំ "+data.land_size+", បណ្តោយ "+data.height+",ទទឹង  "+data.width;
			
			dijit.byId('land_price').attr('value',data.land_price);
			dijit.byId('house_price').attr('value',data.house_price);
			dijit.byId('to_total_sold').attr('value',data.price);
            tohouseprice = dijit.byId('to_total_sold').get('value');
            if(isNaN(tohouseprice)){tohouseprice=0;}
                
            paid_before = dijit.byId('paid_before').get('value');
            if(isNaN(tohouseprice)){paid_before=0;}
            balance_price = parseFloat(tohouseprice)-parseFloat(paid_before);
			dijit.byId('sold_price').attr('value',data.price);
			//alert(balance_price);//ប្រាក់ត្រូវបង់បន្ទាប់
			dijit.byId('deposit').attr('value',0);
			
			//checkScheduleOption();
			Balance();
			
		},
		error: function(err) {
			alert(err);
		}
	});
}


function clearTextBox(){
	dijit.byId('member').set('value','');
	dijit.byId('total_amount').set('value',0);
}
function getClientInfo(type){
	if(type==1){
		customer_code= dijit.byId('customer_code').get('value');
		dijit.byId('member').attr('value',customer_code);
	}else{
		customer_code= dijit.byId('member').get('value');
		dijit.byId('customer_code').attr('value',customer_code);
	}
}
var url_submitdistrict = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'add-newdistrict')); ?>';
function addNewDistrict(){
		dojo.xhrPost({
	    url: url_submitdistrict,	
		form: dojo.byId("form_district"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_district').reset(); 
			dijit.byId('frm_district').hide();
		},
		error: function(err) {
			alert("Your message could not be sent, please try again!.");
		}
	});
}
var url_submitcommune = '<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'add-newcommune')); ?>';
function addNewCommune(){
		dojo.xhrPost({
	    url: url_submitcommune,	
		form: dojo.byId("form_commune"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_commune').reset(); 
			dijit.byId('frm_commune').hide();
		},
		error: function(err) {
			alert("Your message could not be sent, please try again!.");
		}
	});
}
var url_submitvillage = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'add-newvillage')); ?>';
function addNewVillage(){
		dojo.xhrPost({
	    url: url_submitvillage,	
		form: dojo.byId("form_village"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_village').reset(); 
			dijit.byId('frm_village').hide();
		},
		error: function(err) {
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
</script>
<script>
function checkFirstRecord(){
	var rowId = $('#identity').val();
	if(rowId!=''){
		var rowIDArray = rowId.split(',');
		for(var n = 0; n < rowIDArray.length; n++) {
			total_amountpayment = (dijit.byId('total_payment'+rowIDArray[n]).get('value'));
			if(n==0){ 
				paid = dijit.byId('deposit').get('value');
				if(total_amountpayment<paid){alert("សូមបញ្ជូលប្រាក់ត្រូវបង់ ធំជាងប្រាក់ដែលទទួលបាន! ");dijit.byId('percent'+rowIDArray[n]).focus();return false;}
			}
		}
  }
}
col=0;no=0;title=0;temp='';
function addRow(){
	result = checkFirstRecord();
	if(result==false){return false;}
	payment_method = dijit.byId('schedule_opt').get('value');
	if(payment_method==4){addInstallment();}
	if(payment_method!=6){return false;}
	period = dijit.byId('period').get('value');
	//deposit = dijit.byId("deposit").get("value");
	//if(isNaN(deposit)){
		//deposit = 0;
	//}
	//if(deposit>0){ period = period-1;}
	if(period==0){alert("សូមបញ្ជូលចំនួនដង ត្រូវបង់!");dijit.byId('period').focus();return false;}

	no=0;title=0;temp='';$('#identity').val('');
	dojo.byId("showrecord").innerHTML = '';
	tmp='<table id="table_row" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
	tmp+='<tr id="head-title" class="head-td" style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
	tmp+='</table>';
	dojo.query("#showrecord").append(tmp);
	
	for(i=1;i<=period;i++){
		if(payment_method==6){
			col++;no++;
			template='';
			if(title!=1){    
				temp+='<th><?php echo $tr->translate("DEL");?></th>';
				temp+='<th><?php echo $tr->translate("NUM");?></th>';
				temp+='<th><?php echo $tr->translate("DATE_PAYMENT");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("PERCENT_PAID");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("OS_AMOUNT");?></th>';
				temp+='<th><?php echo $tr->translate("NOTE");?></th>';
				dojo.query("#head-title").append(temp);
				title=1;
				epx_date = '<?php echo date('Y-m-d');?>';
			}else{
				indexs = col-1;
				epx_date = dijit.byId("date_payment"+indexs).get("value");
				var a = new Date(epx_date);
				mm = a.getMonth()+2;
				var dd = a.getDate();
				 if(dd<10){
					 dd = "0"+dd;
				}
				if(mm<10){
					 mm = "0"+mm;
				}
				var y = a.getFullYear();
				var epx_date = y+'-'+ mm + '-'+dd ;
			}
				template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
				template+='<td width="2%" align="center">'+no+'</td>';
				template+="<td><input class='fullside' type='text' constraints="+"{datePattern:'dd/MM/yyyy'}"+" dojoType='dijit.form.DateTextBox' value='"+epx_date+"' id='date_payment"+col+"' name='date_payment"+col+"' /></td>";
				template+='<td><input type="text" onkeyup="calCulateAmount('+col+')" class="fullside" required="true" data-dojo-type="dijit.form.NumberTextBox"  id="percent'+col+'" name="percent'+col+'" /></td>';			
				template+='<td><input class="fullside" onkeyup="calCulateAmount('+col+',2)" type="text" required="true"  dojoType="dijit.form.NumberTextBox" id="total_payment'+col+'" name="total_payment'+col+'" /></td>';			
				template+='<td <input class="fullside" type="text"  name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ"/><label id="subsub"></label></td>';
			tmp='<tr class="hover" style="border-bottom:1px solid #ccc;" id="row'+col+'">';
			tmp+="</tr>";
			dojo.query("#table_row").append(tmp);
		
			if($("#identity").val()!="") {
				var identity = $("#identity").val();
				$("#identity").val(identity+','+col);
			} else {$("#identity").val(col);}
			dojo.html.set(dojo.byId("row"+col),template , {
			     parseContent: true,
			});
		}
	}
	dijit.byId("date_line").attr('value',epx_date);
}
function addInstallment(){
	result = checkFirstRecord();
	if(result==false){return false;}
	payment_method = dijit.byId('schedule_opt').get('value');
	
	period = dijit.byId('period').get('value')*12;
	if(period==0){alert("សូមបញ្ជូលចំនួនដង ត្រូវបង់!");dijit.byId('period').focus();return false;}
	temp='';

	result = checkFirstRecord();
	if(result==false){return false;}
	
		if(payment_method==4){
			col++;no++;
			template='';
			if(title!=1){    
				tmp='<table id="table_row" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
				tmp+='<tr id="head-title" class="head-td" style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
				tmp+='</table>';
				dojo.query("#showrecord").append(tmp);
				
				temp+='<th><?php echo $tr->translate("DEL");?></th>';
				temp+='<th><?php echo $tr->translate("NUM");?></th>';
				temp+='<th><?php echo $tr->translate("DATE_PAYMENT");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("PERCENT_PAID");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("OS_AMOUNT");?></th>';
				temp+='<th><?php echo $tr->translate("NOTE");?></th>';
				dojo.query("#head-title").append(temp);
				title=1;
				epx_date ='<?php echo date('Y-m-d');?>';
			}else{
				indexs = col-1;
				epx_date = dijit.byId("date_payment"+indexs).get("value");
				var a = new Date(epx_date);
				mm = a.getMonth()+2;
				var dd = a.getDate();
				 if(dd<10){
					 dd = "0"+dd;
				}
				if(mm<10){
					 mm = "0"+mm;
				}
				var y = a.getFullYear();
				var epx_date = y+'-'+ mm + '-'+dd ;

				mm_nextmonth = a.getMonth()+3;
				if(mm_nextmonth<10){
					mm_nextmonth = "0"+mm_nextmonth;
				}
				
				var start_date = y + '-'+ mm_nextmonth + '-'+dd ;
				dijit.byId("first_payment").attr('value',start_date);
			}
			    dijit.byId("release_date").attr('value',epx_date);
				template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
				template+='<td width="2%" align="center">'+no+'</td>';
				template+="<td><input class='fullside' type='text' constraints="+"{datePattern:'dd/MM/yyyy'}"+" dojoType='dijit.form.DateTextBox' value='"+epx_date+"' id='date_payment"+col+"' name='date_payment"+col+"' /></td>";
				template+='<td><input onkeyup="calCulateAmount('+col+')" class="fullside" type="text" required="true" data-dojo-type="dijit.form.NumberTextBox" id="percent'+col+'" name="percent'+col+'" /></td>';	//data-dojo-props='+'regExp:"[0-9]{1,2}"'+'		
				template+='<td><input class="fullside" type="text" onkeyup="calCulateAmount('+col+',2)" required="true"  dojoType="dijit.form.NumberTextBox" id="total_payment'+col+'" name="total_payment'+col+'" /></td>';			
				template+='<td <input class="fullside" type="text"  name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ"/><label id="subsub"></label></td>';
			tmp='<tr class="hover" style="border-bottom:1px solid #ccc;" id="row'+col+'">';
			tmp+="</tr>";
			dojo.query("#table_row").append(tmp);
		
			if($("#identity").val()!="") {
				var identity = $("#identity").val();
				$("#identity").val(identity+','+col);
			} else {$("#identity").val(col);}
			dojo.html.set(dojo.byId("row"+col),template , {
			     parseContent: true,
			});
		}
}

function calCulateAmount(index,revers=1){
	balance = dijit.byId('balance').get('value');
	if(revers==1){//% to value
	    percent = dijit.byId('percent'+index).get('value');
	    amount_payment = balance*percent/100;
	    dijit.byId('total_payment'+index).attr('value',amount_payment);
   }else{//value to %
	   amount_payment =  dijit.byId('total_payment'+index).get('value');
	   percent = amount_payment*100/balance;
	   dijit.byId('percent'+index).attr('value',percent);
     }
	calCulateSchedulePayment();
	 if(dijit.byId('percent'+index).get('value')>100){
		 alert("តម្លៃត្រូវបង់មិនអាចធំជាង ១០០ ភាគរយបានទេ !");
		 dijit.byId('percent'+index).focus();
     }
}
function calCulateSchedulePayment(){
	var total_amount=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	if(rowId!=''){
	for(var n = 0; n < rowIDArray.length; n++) {
			total_amountpayment = (dijit.byId('total_payment'+rowIDArray[n]).get('value'));
			if(n==0){ 
			}
			if(isNaN(total_amountpayment)){
				total_amountpayment = 0;
			}
			total_amount = total_amount+ total_amountpayment;
		}
	}
	total_amount = parseFloat(total_amount);
	dijit.byId('total_installamount').attr('value',total_amount);
	calCulateFixedPeriod();
}
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
	if(arrays.length==0){ dijit.byId('total_installamount').attr('value','');}
	calCulateSchedulePayment();
}

function setFirstPaymentAndDateLine(pay_term,date_release,amount_date){
	var a = new Date(date_release);
	mm = a.getMonth()+amount_date+1;
	 var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	 if(mm<10){
		 mm = "0"+mm;
	}
	var y = a.getFullYear()+1;

	var epx_date = y + '-'+ mm + '-'+dd ;
	calCulateEndDate();
	calCulateFirstPayment();
}
function calCulateEndDate(){
	amount_period = 1;
	if(dijit.byId("schedule_opt").get('value')==4){amount_period=12;}
	amount_date = dijit.byId('period').get('value')*amount_period;
	release_date = dijit.byId("first_payment").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
	}else{
		var a = new Date(release_date);
		month = a.getMonth()+amount_date;
		mm = month%12;
		year = parseInt(month/12);
		 var dd = a.getDate();
		 if(dd<10){
			 dd = "0"+dd;
		}
		 if(mm<10){
			 mm = "0"+mm;
		}
		var y = a.getFullYear()+year;
		var epx_date = y + '-'+ mm + '-'+dd ;
        payment_option = dijit.byId('schedule_opt').attr('value');
		if(payment_option==2){
			dijit.byId('date_line').attr('value','<?php echo date("Y-m-d");?>');
		}else{
			dijit.byId('date_line').attr('value',epx_date);	
		}
    }
}
function CalculateDate(){
	pay_term = 1;
	amount_period = 1;
	if(dijit.byId("schedule_opt").get('value')==4){amount_period=12;}
	amount_date = dijit.byId('period').get('value')*amount_period;
	
	release_date = dijit.byId("first_payment").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
	}else{
		setFirstPaymentAndDateLine(pay_term,release_date,amount_date);		
    }
}
function checkReleaseDate(){
	CalculateDate();
}
function getFirstPayment(){
	calCulateFirstPayment();
}
function calCulateFirstPayment(){
	pay_term = 1;
	amount_date = 1;
	method_id = dijit.byId('schedule_opt').get('value');
	addamount=1;
	if(method_id==3 || method_id==4 || schedule_opt==6){
		addamount=0;
	}
	release_date = dijit.byId("release_date").get('value');
	var a = new Date(release_date);
		mm = a.getMonth()+amount_date+addamount;
	var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	 if(mm<10){
		 mm = "0"+mm;
	}
	var y = a.getFullYear();
	var epx_date = y + '-'+ mm + '-'+dd ;
	dijit.byId('first_payment').attr('value',epx_date);
}
var url_previewloan = '<?php echo $this->url(array('module'=>'loan','controller'=>'transferproject','action'=>'addschedultest')); ?>';
function addPreviewLoan(){
	r=0;
	if(dijit.byId('frm_add_tran').validate()){
		client = dijit.byId('member').get('value');
		if (client=='' || client==-1){
			alert('Please Select Client Name !');
			dijit.byId('customer_code').focus();
			return false;
		}

		dojo.xhrPost({
		    url: url_previewloan,	
			form: dojo.byId("frm_add_tran"),		    
			handleAs:"json", 
			load: function(data) {
				if(data.row_id=='row_id'){//return 1;
					
					//printSave();
					}else{
						  document.getElementsByClassName("overlay")[0].style.display="none";
						  temp='';	
						  fund_title=0;thead='';fund_title=0;
						  temp='<table class="collape tablesorter" style="font-size:13px; width:1000px !important; " id="table">'
						  temp+='<tr style="background:#ccc;"><th><?php echo $tr->translate("NUM");?></th>';
						  temp+='<th><?php echo $tr->translate("ថ្ងៃបង់ប្រាក់");?></th>';
						  temp+='<th><?php echo $tr->translate("ប្រាក់ដើមគ្រា");?></th>';
						  temp+='<th><?php echo $tr->translate("ប្រាក់ដើម");?></th>';
						  temp+='<th><?php echo $tr->translate("ប្រាក់ការ");?></th>';
						  temp+='<th><?php echo $tr->translate("សរុប");?></th>';
						  temp+='<th><?php echo $tr->translate("ប្រាក់ដើមនៅសល់");?></th>';
						  principal_permonth=0;total_interest=0;total_payment_after=0;
						for(i=0;i<data.length;i++){
							principal_permonth=principal_permonth+parseFloat(data[i].principal_permonth);
							total_interest=total_interest+parseFloat(data[i].total_interest);
							total_payment_after=total_payment_after+parseFloat(data[i].total_payment_after);
					      r++;
						  temp+='<tr><td align="center">'+r+'</td>';
						  var myDate = new Date(data[i].date_payment);
						  d = new Date(data[i].date_name);
						  temp+='<td>'+getDayName(d.getDay())+'-'+data[i].date_payments+'</td>';
						  temp+='<td>'+dojo.number.format(data[i].begining_balance,2)+'</td>';
						  temp+='<td>'+dojo.number.format(data[i].principal_permonth,2)+'</td>';
						  temp+='<td>'+dojo.number.format(data[i].total_interest,2)+'</td>';
						  temp+='<td><b>'+dojo.number.format(data[i].total_payment_after,2)+'<b></td>';
						  temp+='<td><b>'+dojo.number.format((data[i].ending_balance),2)+'<b></td>';
						 }
						  temp+='<tr><td align="right" colspan="3" style="border-left:1px solid #fff;border-bottom:1px solid #fff;">&nbsp;សរុប -Total</td>';
						  temp+='<td>'+dojo.number.format(principal_permonth,2)+'</td>';
						  temp+='<td>'+dojo.number.format(total_interest,2)+'</td>';
						  temp+='<td><b>'+dojo.number.format(total_payment_after,2)+'<b></td>';
						  temp+='<td></td>';
						temp+='</table>';
						dojo.byId('t_amountmoneytype').innerHTML = temp;
						dijit.byId("lbl_schedule").show();
					}
				
			},
			error: function(response, ioArgs) {
				alert("Failed while doing the operation: " + ioArgs.xhr.response);
				//document.getElementsByClassName("overlay")[0].style.display="none";
				//alert("You can not preview this loan number!");
			}
	   });
	}
}
function getDayName(day){
	 var weekday = new Array(7);
	    weekday[0] = "អាទិត្យ";
	    weekday[1] = "ច័ន្ទ";
	    weekday[2] = "អង្គារ";
	    weekday[3] = "ពុធ";
	    weekday[4] = "ព្រហ";
	    weekday[5] = "សុក្រ";
	    weekday[6] = "សៅរ៍";
	    return weekday[day];
}
function hideDialog() {		
	dijit.byId("lbl_schedule").hide();
}

function showPopupclient(){
	dijit.byId("frmpop_client").show();
}
var individual_client_url = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insert-client'));?>';
function addNewindividual(){
	if(dijit.byId('addclient').validate()){
	dojo.xhrPost({
		url:individual_client_url,	
		form:dojo.byId('addclient'),
		content:{
			'branch_id':1
			},
		handleAs:"json",
		load: function(response) {
			dijit.byId('frmpop_client').hide();	
			var myNewItem = {					
					id: response.id,
					name: dijit.byId('name_en').get('value')+' - '+dijit.byId('name_kh').get('value'),
			};			
			addDataToSelectbox(dijit.byId('member'), client_store, myNewItem, response.id);
			var myNewItem1 = {					
					id: response.id,
					name: response.client_code,
			};			
			addDataToSelectbox(dijit.byId('customer_code'), client_number_store, myNewItem1, response.id);		
			dijit.byId('addclient').reset();
		},
		error: function(err) {
		}
	});
 }	
}
function calculateDuration(type=null){
	if(type==1){
		var total_paid_install = dijit.byId('total_installamount').get('value');
		if(total_paid_install == 0){
			sold_price = dijit.byId('balance').get('value');
		}else{
			sold_price = dijit.byId('balance').get('value')-dijit.byId('total_installamount').get('value');
		}
		
		interest_rate= dijit.byId('interest_rate').get('value')/12/(100);//(100/30day)
		fixed_payment = dijit.byId('fixed_payment').get('value');
		if(isNaN(interest_rate)){interest_rate=0;}
		pi = (parseFloat(fixed_payment)-(parseFloat(sold_price)*parseFloat(interest_rate)));
		s = parseFloat(fixed_payment);
		top_ii = Math.log(s/pi);
		var duration =  Math.ceil(top_ii / Math.log(1+ parseFloat(interest_rate)));// ROUND UP
		duration = duration/12;
		dijit.byId('period').attr('value',duration);
	}
}
function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}
</script>
<style>
.overlay {display: none;position: absolute;width: 100%;height: 100%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .95;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           border: solid 1px #060522;text-align: center;
           background: #fff url("<?php echo $this->baseUrl()?>/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>