<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("VIEW_LOAN_RESCHEDULE"));
$frm = $this->frm_search;
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'loan','controller'=>'transferproject','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   <table width="100%"​​>
   		<tr>
   			<td><?php echo $frm->getElement("adv_search");?></td>
   			<td><?php echo $frm->getElement("branch_id");?></td>
   			<td><?php echo $frm->getElement("client_name");?></td>
   			<td><?php echo $frm->getElement("repayment_method");?></td>
   			<td><?php echo $frm->getElement('status');?></td>
   			<td><?php echo $frm->getElement('start_date');?></td>
   			<td><?php echo $frm->getElement('end_date');?></td>
   			<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
   			<td colspan="3"></td>
   			
   		</tr>
   </table>
</form>
<?php echo $this->list;?>
