<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_CLIENT'));
?>	
<?php  $frm = $this->frm_client;?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.CheckBox");
dojo.require("dijit.Dialog");
dojo.require("dijit.layout.TabContainer");

</script>
<form id='add_client' action="<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'add')); ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				if(dijit.byId('province').get('value')==0){
					alert('Province required');
					dijit.byId('province').focus();
					return false;
			    }
				return true;
			} else {
				return false;
			}
</script>
<table  width="100%" style="margin-top:-5px;">
	<tr>
		<td style="overflow: scroll;max-width:1100px;overflow-y:hidden;">
				<style>
				.dojoxGridSortNode{
						text-align: center;	
						height: 30px;		
					}
					.dijitTabPaneWrapper , .dijitContentPane,.dijitTabListContainer-top{max-width: 99% !important;}
				</style>
				<div id="mainTabContainer" style="max-width:100%; height: 400px;overflow-y:hidden;" dojoType="dijit.layout.TabContainer" region="center"  >
					<div style="width:100%;overflow-x:hidden;overflow-y:hidden;" dojoType="dijit.layout.ContentPane" title="<?php echo $tr->translate('ADD_CLIENT');?>" selected="true">
						<fieldset>
							<legend><strong><?php echo $tr->translate("ADD_CLIENT");?></strong></legend>
							<table style="margin: 0 auto; width:100%;" cellspacing="10">
								<tr>
									<td><?php echo $tr->translate("BRANCH_NAME")?></td>
									<td><?php echo $frm->getElement('branch_id');?></td>
									<td><?php echo $tr->translate("CLIENT_NO")?></td>
									<td><?php echo $frm->getElement('client_no');?></td>
									<td><?php echo $tr->translate("CUSTOMER_NAME")?></td>
									<td><?php  echo $frm->getElement('name_kh');?></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("SEX")?></td>
									<td><?php  echo $frm->getElement('sex');?></td>
									<td><?php echo $tr->translate("NATIONALITY")?></td>
									<td><?php  echo $frm->getElement('nationality');?></td>
									<td><?php echo $tr->translate("DOCMENT_TYPE")?></td>
									<td><input id="client_d_type" required="true" /></td>
								</tr>
								<tr>
									
									<td><?php echo $tr->translate("NATIONAL_ID")?></td>
									<td><?php  echo $frm->getElement('national_id');?></td>
									<td><?php echo $tr->translate("DOB")?></td>
									<td><?php  echo $frm->getElement('dob_client');?></td>
									<td><?php echo $tr->translate("PHONE")?></td>
									<td><?php  echo $frm->getElement('phone');?></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("EMAIL")?></td>
									<td><?php  echo $frm->getElement('email');?></td>
									<td><?php echo $tr->translate("PROVINCE")?></td>
									<td><?php  echo $frm->getElement('province');?></td>
									<td><?php echo $tr->translate("DISTRICT")?></td>
									<td><input id="district" required="true" ></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("COMMUNE")?></td>
									<td><input id="commune" ></td>
									<td><?php echo $tr->translate("VILLAGE")?></td>
									<td><input id="village" ><?php  //echo $frm->getElement('village');?></td>
									<td><?php echo $tr->translate("STREET_NO")?></td>
									<td><?php  echo $frm->getElement('street');?></td>
								</tr>
								<tr>
									
									<td><?php echo $tr->translate("HOUSE_NO")?></td>
									<td><?php  echo $frm->getElement('house');?></td>
									<td valign="top"><?php echo $tr->translate("STATUS")?></td>
									<td valign="top"><?php  echo $frm->getElement('status');?></td>
									<td valign="top"><?php echo $tr->translate("NOTE")?></td>
									<td><?php  echo $frm->getElement('desc');?></td>
								</tr>
								<tr>
									
									<td><?php echo $tr->translate("PHOTO")?></td>
									<td><?php echo $frm->getElement('photo');?></td>
								</tr>
							</table>
					</fieldset>
				</div>
				<div  dojoType="dijit.layout.ContentPane" style="overflow-x:hidden;overflow-y:hidden;" title="<?php echo $tr->translate('RELEVANT_STAKEHOLDER');?>" selected="false">
						<fieldset>
							<legend><strong><?php echo $tr->translate("RELEVANT_STAKEHOLDER");?></strong></legend>
						<table style="margin: 0 auto; width:100%;" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("JOIN_NAME")?></td>
							<td><?php echo $frm->getElement('hname_kh');?></td>
							<td><?php echo $tr->translate("SEX")?></td>
							<td><?php  echo $frm->getElement('ksex');?></td>
							<td><?php 	echo $tr->translate("DOCMENT_TYPE")?></td>
							<td><input id="join_d_type"/></td> 
						</tr>
						<tr>
							<td><?php 	echo $tr->translate("NATIONAL_ID")?></td>
							<td><?php   echo $frm->getElement('rid_no');?></td> 
							<td><?php 	echo $tr->translate("NATIONALITY")?></td>
							<td><?php   echo $frm->getElement('p_nationality');?></td>
							<td><?php 	echo $tr->translate("PHONE")?></td>
							<td><?php  	echo $frm->getElement('lphone');?></td>
						</tr>
						<tr>
							
							<td><?php 	echo $tr->translate("PROVINCE")?></td>
							<td><?php  	echo $frm->getElement('cprovince');?></td>
							<td><?php 	echo $tr->translate("DISTRICT")?></td>
							<td><input id="adistrict" required="true" ><?php //echo $frm->getElement('adistrict');?></td>
							<td><?php 	echo $tr->translate("COMMUNE")?></td>
							<td><input id="dcommune" ><?php //echo $frm->getElement('dcommune');?></td>		
						</tr>
						<tr>
							<td><?php 	echo $tr->translate("VILLAGE")?></td>
							<td><input id="qvillage" ><?php //echo $frm->getElement('qvillage');?></td>
							<td><?php 	echo $tr->translate("STREET_NO")?></td>
							<td><?php  	echo $frm->getElement('dstreet');?></td>
							<td><?php 	echo $tr->translate("HOUSE_NO")?></td>
							<td><?php  	echo $frm->getElement('ghouse');?></td>
						</tr>
						<tr>
							<td><?php 	echo $tr->translate("JOIN_TYPE")?></td>
							<td><?php  	echo $frm->getElement('join_type');?></td>
							<td><?php 	echo $tr->translate("SPOUSE_NAME")?></td>
							<td><?php  	echo $frm->getElement('arid_no');?></td>
							<td><?php 	echo $tr->translate("SPOUSE_NATION_ID")?></td>
							<td><?php  	echo $frm->getElement('reference_national_id');?></td>
							
						</tr>
						<tr>
							<td><?php 	echo $tr->translate("STATUS")?></td>
							<td><?php  	echo $frm->getElement('istatus');?></td>
							<td><?php 	echo $tr->translate("NOTE")?></td>
							<td><?php 	echo $frm->getElement('edesc');?></td>
						</tr>
					</table>
					</fieldset>
				</div>
			</div>
				<div style="text-align: center;">
				<input type="reset" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" 
								 iconClass="dijitIconClear" /> 
							 <input type="submit" value="SAVE_CLOSE" tabindex="2" label="<?php echo $tr->translate('SAVECLOSE');?>" id="save_close" dojoType="dijit.form.Button" name="save_close"
								 iconClass="dijitEditorIcon dijitEditorIconSave" /> 
							<input type="submit" value="SAVE_NEW" tabindex="1" label="<?php echo $tr->translate('SAVENEW');?>" id="save_new" dojoType="dijit.form.Button" name="save_new"
								 iconClass="dijitEditorIcon dijitEditorIconSave"/> 
			</div>
		</td>
	</tr>
</table>	
</form>
<table>
<tr>
</tr>
</table>
<?php 
echo $this->frm_popup_district;
echo $this->frm_popup_village;
echo $this->frm_popup_comm;
?>
<script type="text/javascript">

var d_datastore  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->clienttype));?> );
var joint_doc_type_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->clienttype));?> );
var district_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var commune_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var village_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var adistrict_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var dcommune_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var qvillage_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );


dojo.ready(function(){
	
	try{
	
	new dijit.form.FilteringSelect({
	store: district_store,
	autoComplete: true,
	required: false,		           
	name: "district",
	id: "district",
	searchAttr: "name",
	class: 'fullside',
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ ស្រុក/ខ័ណ្ឌ!",	
		onChange: function() {
			district = dijit.byId('district').get('value');
			if(district==-1){
				showPopupdistrict();
				}
				filterCommune();
		}  
	}, "district");
	 
	new dijit.form.FilteringSelect({
	store: commune,
	autoComplete: true,
	required: false,		           
	name: "commune",
	id: "commune",
	searchAttr: "name",
	class: 'fullside',
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឃុំ/សង្កាត់",	
		onChange: function() {
			commune = dijit.byId('commune').get('value');
			if(commune==-1){
				showPopupCommune();
			}
			else{
				filterVillage();
			}
  }
	}, "commune");

	 
	new dijit.form.FilteringSelect({
	store: village_store,
	autoComplete: true,
	required: false,		           
	name: "village",
	id: "village",
	searchAttr: "name",
	class: 'fullside',
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះភូមិ!",	
		onChange: function() {
			vill = dijit.byId('village').get('value');
			if(vill==-1){
				showPopupVillage();
			}
		}

	}, "village");

	
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	new dijit.form.FilteringSelect({
		store: d_datastore,//dojo.data.ObjectStore({objectStore: d_data}),
		autoComplete: true,          
		required: false,		           
		name: "client_d_type",
		id: "client_d_type",
		searchAttr: "name",
		value: "0",
		class: 'fullside',
		missingMessage:"អ្នក​ភ្លេច​​ បំពេញប្រភេទឯកសារ !",	
			onChange: function() {
				client_d_type = dijit.byId('client_d_type').get('value');
				if(client_d_type==-1){
					dijit.byId('type').attr('value',1);
					showPopupclientdtype();
				}
			}
		}, "client_d_type");

	new dijit.form.FilteringSelect({
			store: joint_doc_type_store,//dojo.data.ObjectStore({objectStore: d_data}),
			autoComplete: true,          
			required: false,		           
			name: "join_d_type",
			id: "join_d_type",
			searchAttr: "name",
			value: "0",
			class: 'fullside',
			missingMessage:"អ្នក​ភ្លេច​​ បំពេញប្រភេទឯកសារ !",	
			onChange: function() {
				client_d_type = dijit.byId('join_d_type').get('value');
				if(client_d_type==-1){
					dijit.byId('type').attr('value',2);
					showPopupclientdtype();
				}
			}
		}, "join_d_type");

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	// new dijit.form.FilteringSelect({
		// store: d_datastore,//dojo.data.ObjectStore({objectStore: d_data}),
		// autoComplete: true,
		// required: false,		           
		// name: "guarantor_d_type",
		// id: "guarantor_d_type",
		// searchAttr: "name",
		// class: 'fullside',
			// onChange: function() {
				// client_d_type = dijit.byId('guarantor_d_type').get('value');
				// if(client_d_type==-1){
					// doc_type=3;
					// showPopupclientdtype();
				// }
			// }
		// }, "guarantor_d_type");

	new dijit.form.FilteringSelect({
		store: adistrict_store,
		autoComplete: true,
		required: false,		           
		name: "adistrict",
		id: "adistrict",
		searchAttr: "name",
		class: 'fullside',
		missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ ស្រុក/ខ័ណ្ឌ!",	
			onChange: function() {
				district = dijit.byId('adistrict').get('value');
				if(district==-1){
					dshowPopupdistrict();
					}
					dfilterCommune();
			}  
		}, "adistrict");
		 
		new dijit.form.FilteringSelect({
		store: dcommune_store,
		autoComplete: true,
		required: false,		           
		name: "dcommune",
		id: "dcommune",
		searchAttr: "name",
		class: 'fullside',
		missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឃុំ/សង្កាត់",	
			onChange: function() {
				commune = dijit.byId('dcommune').get('value');
				if(commune==-1){
					dshowPopupCommune();
				}
				else{
					dfilterVillage();
				}
	  }
		}, "dcommune");

		 
		new dijit.form.FilteringSelect({
		store: qvillage_store,
		autoComplete: true,
		required: false,		           
		name: "qvillage",
		id: "qvillage",
		searchAttr: "name",
		class: 'fullside',
		missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះភូមិ!",	
			onChange: function() {
				vill = dijit.byId('qvillage').get('value');
				if(vill==-1){
					dshowPopupVillage();
				}
			}
		}, "qvillage");
		getClientNo();
	}catch(e){
		alert(e);
	}
});

url_getdistrict = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'get-district'));?>';
function filterDistrict(){
	pro_id = dijit.byId('province').get('value');
	if(pro_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getdistrict,	
		content:{ 
			'pro_id': pro_id
		},
		handleAs:"json",
		load: function(data) {	
			district_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('district').set('store', district_store);
		},
		error: function(err) {
			alert(err);
		}
	});	
}
url_getcommune = '<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'get-commune'));?>';
function filterCommune(){
	distict_id = dijit.byId('district').get('value');
	if(distict_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getcommune,	
		content:{ 
			'district_id': distict_id
		},
		handleAs:"json",
		load: function(data) {	
			commune_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('commune').set('store', commune_store);
		},
		error: function(err) {
			alert(err);
		}
	});
}
url_getvillage = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'get-allvillage'));?>';
function filterVillage(){
	commune_id = dijit.byId('commune').get('value');
	if(commune_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getvillage,	
		content:{ 
			'commune_id': commune_id
		},
		handleAs:"json",
		load: function(data) {	
			village_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('village').set('store', village_store);
		},
		error: function(err) {
			alert(err);
		}
	});
}
url_getdistrict = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'get-district'));?>';
function dfilterDistrict(){
	cpro_id = dijit.byId('cprovince').get('value');
	if(cpro_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getdistrict,	
		content:{ 
			'pro_id': cpro_id
		},
		handleAs:"json",
		load: function(data) {	
			adistrict_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('adistrict').set('store', adistrict_store);
		},
		error: function(err) {
			alert(err);
		}
	});	
}
url_getcommune = '<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'get-commune'));?>';
function dfilterCommune(){
	adistict_id = dijit.byId('adistrict').get('value');
	if(adistict_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getcommune,	
		content:{ 
			'district_id': adistict_id
		},
		handleAs:"json",
		load: function(data) {	
			dcommune_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('dcommune').set('store', dcommune_store);
		},
		error: function(err) {
			alert(err);
		}
	});
}
url_getvillage = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'get-allvillage'));?>';
function dfilterVillage(){
	dcommune_id = dijit.byId('dcommune').get('value');
	if(dcommune_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getvillage,	
		content:{ 
			'commune_id': dcommune_id
		},
		handleAs:"json",
		load: function(data) {	
			qvillage_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('qvillage').set('store', qvillage_store);
		},
		error: function(err) {
			alert(err);
		}
	});
}
client_village = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'add-village'));?>';
function addVillage(){
	if(dijit.byId('frm_village').validate()) {
		dojo.xhrPost({
			url:client_village,	
			form:dojo.byId('form_village'),
			handleAs:"json",
			load: function(data) {
				labelen = dijit.byId('village_name').get('value');
				labelkh = dijit.byId('village_namekh').get('value');
				var villageItem1 = {					
						id: data,
						name: labelen+' - '+labelkh,
				};			
				addDataToSelectbox(dijit.byId('village'), village_store, villageItem1, data);	
				dijit.byId('frm_village').reset();
				dijit.byId('frm_village').hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
function showPopupVillage(){
	communeid = dijit.byId('commune').get('value');
	if(communeid!=-1){
		province_id = dijit.byId('province').get('value');
		dijit.byId('province_name').attr('value',province_id);
		dijit.byId('province_name').set('readOnly',true);

		district_name=province_id = dijit.byId('district').get('value');
		dijit.byId('district_name').attr('value',district_name);
		dijit.byId('district_name').set('readOnly',true);

		dijit.byId('commune_name').attr('value',communeid);
		dijit.byId('commune_name').set('readOnly',true);
		dijit.byId('frm_village').show();
	}else{
		alert('please select commune first');
		dijit.byId('commune').focus();
	}
}
function showPopupCommune(){
	district = dijit.byId('district').get('value');
	if(district!=-1){
		dijit.byId('district_nameen').attr('value',district);
		dijit.byId('district_nameen').set('readOnly',true);
		dijit.byId('frm_commune').show();
	}else{
		alert('please select district first');
		dijit.byId('district').focus();
	}
}
function showPopupdistrict(){
	province_id = dijit.byId('province').get('value');
	if(province_id!=0){
		dijit.byId('province_names').attr('value',province_id);
		dijit.byId('province_names').set('readOnly',true);
		dijit.byId('frm_district').show();
	}else{
		alert('please select province first');
		dijit.byId('province').focus();
	}
}
function dshowPopupVillage(){
	communeid = dijit.byId('dcommune').get('value');
	if(communeid!=-1){
		province_id = dijit.byId('cprovince').get('value');
		dijit.byId('province_name').attr('value',province_id);
		dijit.byId('province_name').set('readOnly',true);

		district_name=province_id = dijit.byId('adistrict').get('value');
		dijit.byId('district_name').attr('value',district_name);
		dijit.byId('district_name').set('readOnly',true);

		dijit.byId('commune_name').attr('value',communeid);
		dijit.byId('commune_name').set('readOnly',true);
		dijit.byId('frm_village').show();
	}else{
		alert('please select commune first');
		dijit.byId('dcommune').focus();
	}
}
function dshowPopupCommune(){
	district = dijit.byId('adistrict').get('value');
	if(district!=-1){
		dijit.byId('district_nameen').attr('value',district);
		dijit.byId('district_nameen').set('readOnly',true);
		dijit.byId('frm_commune').show();
	}else{
		alert('please select district first');
		dijit.byId('adistrict').focus();
	}
}
function dshowPopupdistrict(){
	province_id = dijit.byId('province').get('value');
	if(province_id!=0){
		dijit.byId('province_names').attr('value',province_id);
		dijit.byId('province_names').set('readOnly',true);
		dijit.byId('frm_district').show();
	}else{
		alert('please select province first');
		dijit.byId('province').focus();
	}
}
var district_url = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insert-district'));?>';
function addNewDistrict(){
	if(dijit.byId('frm_district').validate()) {
		dojo.xhrPost({
			url:district_url,	
			form:dojo.byId('form_district'),
			handleAs:"json",
			load: function(data) {	
				var myNewItem1 = {					
						id: data,
						name: dijit.byId('pop_district_name').get('value')+' - '+dijit.byId('pop_district_namekh').get('value'),
				};			
				addDataToSelectbox(dijit.byId('district'), district_store, myNewItem1, data);	
				dijit.byId('frm_district').reset();
				dijit.byId('frm_district').hide();
			},
			error: function(err) {
				alert(err);
			}
		});	
	}
}
var commune_url = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insertcommune'));?>';
function addNewCommune(){
	if(dijit.byId('frm_commune').validate()) {
		dojo.xhrPost({
			url:commune_url,	
			form:dojo.byId('form_commune'),
			handleAs:"json",
			load: function(data) {	
				communeen = dijit.byId('commune_nameen').get('value');
				communekh = dijit.byId('commune_namekh').get('value');
				var Itemcommune = {					
						id: data,
						name: communeen+' - '+communekh,
				};			
				addDataToSelectbox(dijit.byId('commune'), commune_store, Itemcommune, data);
				dijit.byId('frm_commune').reset();
				dijit.byId('frm_commune').hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
var document_type_url = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insert-document-type'));?>';
function addNewDocumentType(){
	//alert(1);
	type = dijit.byId('type').get('value');
	old_client_doc = dijit.byId('client_d_type').get('value');
	old_join_doc = dijit.byId('join_d_type').get('value');
	
	dojo.xhrPost({
		
		url:document_type_url,	
		form:dojo.byId('frm_client_doc_type'),
		handleAs:"json",
		load: function(data) {	
		
			var myNewItem = {					
				id: data,
				name: dijit.byId('doc_name').get('value')
			};			
			addDataToSelectbox(dijit.byId('client_d_type'), d_datastore, myNewItem, data);	
			addDataToSelectbox(dijit.byId('join_d_type'), joint_doc_type_store, myNewItem, data);				
				 
			dijit.byId('frm_client_doc_type').reset();
			dijit.byId('popup_doc_type').hide();
			if(type == 2){
				dijit.byId('client_d_type').attr('value',old_client_doc);
			}else{
				dijit.byId('join_d_type').attr('value',old_join_doc);
			}
	
		},
		error: function(err) {
			alert(err);
		}
	});	
}
function showPopupclientdtype(){
	dijit.byId('popup_doc_type').show();
}
url_getClientNo = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'get-client-no'));?>';
function getClientNo(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getClientNo,	
		content:{ 
			'branch_id': branch_id
		},
		handleAs:"json",
		load: function(data) {	
		    dijit.byId('client_no').attr('value',data);
		},
		error: function(err) {
			alert(err);
		}
	});
}
function hideDialog1(){
	dijit.byId('popup_doc_type').hide();
}
</script>



<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:30%;" id="popup_doc_type" >
		<form style="background-color: buttonface; width:100%;" id='frm_client_doc_type' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
				<tr>
					<td>
						<fieldset style="background-color: buttonface;">
						<legend align="center" ><?php echo $tr->translate('ADD_DOC_TYPE');?></legend>
							<table style="margin: 0 auto; width: 100%;  padding:10px;" cellspacing="7" >
								<tr>
									<td><?php echo $tr->translate('NAME');?></td>
									<td>
										<input dojoType="dijit.form.ValidationTextBox"   class="fullside" id="doc_name" name="doc_name" value="" type="text">
									</td>
								</tr>
								
								<input type="hidden" name="type"	id="type" dojoType="dijit.form.TextBox" />
								
								<tr>
									<td colspan="4" align="center">
										<input type="button" value="ចាកចេញ" label="Close" id="close" name="close" dojoType="dijit.form.Button" 
										​ ​​iconClass="dijitIconUndo" onclick="hideDialog1();"/>
										<input type="button" value="save" label="SAVE" id="save" name="save" dojoType="dijit.form.Button" 
										 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addNewDocumentType();"/>
									</td>
								</tr>
								
							</table>
					</fieldset>
					</td>
				</tr>
			</table>

		</form>
	</div>
</div>






