<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_CLIENT'));
?>
<?php  $frm = $this->frm_client;?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.CheckBox");
dojo.require("dijit.Dialog");
dojo.require("dijit.layout.TabContainer");
</script>
<form id='add_client' action="<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'add')); ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">
			if(this.validate()) {
				if(dijit.byId('province').get('value')==0){
					alert('Province required');
					dijit.byId('province').focus();
					return false;
			    }
				return true;
			} else {
				return false;
			}
</script>
<table  width="100%" style="margin-top:-5px;">
	<tr>
		<td style="overflow: scroll;max-width:1100px;overflow-y:hidden;">
				<style>
				.dojoxGridSortNode{
						text-align: center;
						height: 30px;
					}
					.dijitTabPaneWrapper , .dijitContentPane,.dijitTabListContainer-top{max-width: 99% !important;}
				</style>
					<div style="width:100%;overflow-x:hidden;overflow-y:hidden;" dojoType="dijit.layout.ContentPane" title="<?php echo $tr->translate('ADD_CLIENT');?>" selected="true">
						<fieldset>
							<legend><strong><?php echo $tr->translate("ADD_CLIENT");?></strong></legend>
							<table style="margin: 0 auto; width:100%;" cellspacing="10">
								<tr>
									<td><?php echo $tr->translate("លេខកូដអតិថិជន")?></td>
									<td><?php  echo $frm->getElement('client_no');?></td>
									<td><?php echo $tr->translate("CUSTOMER_NAME")?></td>
									<td><?php  echo $frm->getElement('name_kh');?></td>
									<td><?php echo $tr->translate("SEX")?></td>
									<td><?php  echo $frm->getElement('sex');?></td>

								</tr>
								<tr>

									<td><?php echo $tr->translate("VILLAGE")?></td>
									<td><?php  echo $frm->getElement('village_1');?></td>

									<td><?php echo $tr->translate("VILLAGE_CODE")?></td>
									<td><?php echo $frm->getElement('village_code');?></td>		<!-- client_no -->
									<td><?php echo $tr->translate("តម្លៃសេវា")?></td>
									<td><?php  echo $frm->getElement('unit_price');?></td>
								</tr>
								<tr>

									<td><?php echo $tr->translate("PHONE")?></td>
									<td><?php  echo $frm->getElement('phone');?></td>
									<td><?php echo $tr->translate("ថ្ងៃចុះឈ្មោះ")?></td>
									<td><?php  echo $frm->getElement('date_cus_start');?>
										

									<td><?php echo $tr->translate("ប្រាក់បង់សេវា")?></td>
								
									<td><?php  echo $frm->getElement('price_service');?></td>

									
								</tr>


								<tr>
									<td valign="top"><?php echo $tr->translate("គីឡូប្រើប្រាស់ដំបូង")?></td>
									<td valign="top"	<input type="text" style="width:110px"  required="true"  name="end_used"  dojoType="dijit.form.ValidationTextBox"/></td>
									</td>
									<td valign="top"><?php echo $tr->translate("តម្លៃក្នុងមួយឯកត្តា")?></td>
									<td><?php  echo $frm->getElement('price_per_use');?><?php  echo $frm->getElement('price_per_use_id');?></td>
									<td><?php echo $tr->translate("ប្រាក់ជំពាក់ថ្លៃសេវា")?></td>
									<td><?php  echo $frm->getElement('total_service');?></td>
								</tr>
								<tr>
									<td valign="top"><?php echo $tr->translate("STATUS")?></td>
									<td valign="top"><?php  echo $frm->getElement('status');?></td>
									<td valign="top"><?php echo $tr->translate("NOTE")?></td>
									<td><?php  echo $frm->getElement('desc');?></td>
								</tr>
							</table>
					</fieldset>
				</div>

				<div style="text-align: center;">
				<input type="reset" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"
								 iconClass="dijitIconClear" />
							 <input type="submit" value="SAVE_CLOSE" tabindex="2" label="<?php echo $tr->translate('SAVECLOSE');?>" id="save_close" dojoType="dijit.form.Button" name="save_close"
								 iconClass="dijitEditorIcon dijitEditorIconSave" />
							<input type="submit" value="SAVE_NEW" tabindex="1" label="<?php echo $tr->translate('SAVENEW');?>" id="save_new" dojoType="dijit.form.Button" name="save_new"
								 iconClass="dijitEditorIcon dijitEditorIconSave"/>
			</div>
		</td>
	</tr>
</table>
</form>
<table>
<tr>
</tr>
</table>
<?php
echo $this->frm_popup_district;
echo $this->frm_popup_village;
echo $this->frm_popup_comm;
?>
<script type="text/javascript">

var d_datastore  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->clienttype));?> );
var joint_doc_type_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->clienttype));?> );
var district_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var commune_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var village_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->villsge));?> );
var adistrict_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var dcommune_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var qvillage_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );


dojo.ready(function(){

	try{

	new dijit.form.FilteringSelect({
	store: district_store,
	autoComplete: true,
	required: false,
	name: "district",
	id: "district",
	searchAttr: "name",
	class: 'fullside',
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ ស្រុក/ខ័ណ្ឌ!",
		onChange: function() {
			district = dijit.byId('district').get('value');
			if(district==-1){
				showPopupdistrict();
				}
				filterCommune();
		}
	}, "district");

	new dijit.form.FilteringSelect({
	store: village_store,
	autoComplete: true,
	required: false,
	name: "village",
	id: "village",
	searchAttr: "name",
	class: 'fullside',
	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះភូមិ!",
		//onChange: function() {
			//vill = dijit.byId('village').get('value');
			//if(vill==-1){
				//showPopupVillage();
			//}
		//}

	}, "village");


///////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	new dijit.form.FilteringSelect({
		store: d_datastore,//dojo.data.ObjectStore({objectStore: d_data}),
		autoComplete: true,
		required: false,
		name: "client_d_type",
		id: "client_d_type",
		searchAttr: "name",
		value: "0",
		class: 'fullside',
		missingMessage:"អ្នក​ភ្លេច​​ បំពេញប្រភេទឯកសារ !",
			onChange: function() {
				client_d_type = dijit.byId('client_d_type').get('value');
				if(client_d_type==-1){
					dijit.byId('type').attr('value',1);
					showPopupclientdtype();
				}
			}
		}, "client_d_type");

	new dijit.form.FilteringSelect({
			store: joint_doc_type_store,//dojo.data.ObjectStore({objectStore: d_data}),
			autoComplete: true,
			required: false,
			name: "join_d_type",
			id: "join_d_type",
			searchAttr: "name",
			value: "0",
			class: 'fullside',
			missingMessage:"អ្នក​ភ្លេច​​ បំពេញប្រភេទឯកសារ !",
			onChange: function() {
				client_d_type = dijit.byId('join_d_type').get('value');
				if(client_d_type==-1){
					dijit.byId('type').attr('value',2);
					showPopupclientdtype();
				}
			}
		}, "join_d_type");

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	// new dijit.form.FilteringSelect({
		// store: d_datastore,//dojo.data.ObjectStore({objectStore: d_data}),
		// autoComplete: true,
		// required: false,
		// name: "guarantor_d_type",
		// id: "guarantor_d_type",
		// searchAttr: "name",
		// class: 'fullside',
			// onChange: function() {
				// client_d_type = dijit.byId('guarantor_d_type').get('value');
				// if(client_d_type==-1){
					// doc_type=3;
					// showPopupclientdtype();
				// }
			// }
		// }, "guarantor_d_type");

	new dijit.form.FilteringSelect({
		store: adistrict_store,
		autoComplete: true,
		required: false,
		name: "adistrict",
		id: "adistrict",
		searchAttr: "name",
		class: 'fullside',
		missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ ស្រុក/ខ័ណ្ឌ!",
			onChange: function() {
				district = dijit.byId('adistrict').get('value');
				if(district==-1){
					dshowPopupdistrict();
					}
					dfilterCommune();
			}
		}, "adistrict");

		new dijit.form.FilteringSelect({
		store: dcommune_store,
		autoComplete: true,
		required: false,
		name: "dcommune",
		id: "dcommune",
		searchAttr: "name",
		class: 'fullside',
		missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឃុំ/សង្កាត់",
			onChange: function() {
				commune = dijit.byId('dcommune').get('value');
				if(commune==-1){
					dshowPopupCommune();
				}
				else{
					dfilterVillage();
				}
	  }
		}, "dcommune");


		new dijit.form.FilteringSelect({
		store: qvillage_store,
		autoComplete: true,
		required: false,
		name: "qvillage",
		id: "qvillage",
		searchAttr: "name",
		class: 'fullside',
		missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះភូមិ!",
			onChange: function() {
				vill = dijit.byId('qvillage').get('value');
				if(vill==-1){
					dshowPopupVillage();
				}
			}
		}, "qvillage");

	}catch(e){
		alert(e);
	}
});

url_getvillagecode = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'get-code-village'));?>';
function getvillagecode(){

	vllage = dijit.byId('village_1').get('value');
	if(vllage==0){
		return false;}
	dojo.xhrPost({
		url:url_getvillagecode,
		content:{
			'vllage': vllage
		},
		handleAs:"json",
		load: function(data) {
		//	alert(data.village_namekh);
			//dijit.byId('client_no').attr('value',data.code);
			//district_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('village_code').set('value',data.code);
		},
		error: function(err) {
			alert(err);
		}
	});
}
function calculate(){
	/*total_service_price=parseFloat(dijit.byId('total_service').get('value'));*/
	unit_price=parseFloat(dijit.byId('unit_price').get('value'));
	pay_service=parseFloat(dijit.byId('price_service').get('value'));
total_service=unit_price-pay_service;


	if(pay_service>unit_price){
		alert('ការបង់ថ្លៃសេវាមិនអាចច្រើនជាងប្រាក់ដែលបានកំណត់ក្នុងប្រព័ន្ធទេ');
		dijit.byId('total_service').attr('value','');
	}else{
		dijit.byId('total_service').attr('value',total_service);
	}
}

function hideDialog1(){
	dijit.byId('popup_doc_type').hide();
}
</script>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:30%;" id="popup_doc_type" >
		<form style="background-color: buttonface; width:100%;" id='frm_client_doc_type' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
				<tr>
					<td>
						<fieldset style="background-color: buttonface;">
						<legend align="center" ><?php echo $tr->translate('ADD_DOC_TYPE');?></legend>
							<table style="margin: 0 auto; width: 100%;  padding:10px;" cellspacing="7" >
								<tr>
									<td><?php echo $tr->translate('NAME');?></td>
									<td>
										<input dojoType="dijit.form.ValidationTextBox"   class="fullside" id="doc_name" name="doc_name" value="" type="text">
									</td>
								</tr>

								<input type="hidden" name="type"	id="type" dojoType="dijit.form.TextBox" />

								<tr>
									<td colspan="4" align="center">
										<input type="button" value="ចាកចេញ" label="Close" id="close" name="close" dojoType="dijit.form.Button"
										​ ​​iconClass="dijitIconUndo" onclick="hideDialog1();"/>
										<input type="button" value="save" label="SAVE" id="save" name="save" dojoType="dijit.form.Button"
										 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addNewDocumentType();"/>
									</td>
								</tr>

							</table>
					</fieldset>
					</td>
				</tr>
			</table>

		</form>
	</div>
</div>






