<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('CLIENT_PROFILE')); 
	echo $this->headTitle(''); 
?>	
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<style>
.b{ font-weight: bold; }
</style>
<script type="text/javascript">
dojo.require("dijit.form.NumberTextBox");
dojo.ready(function(){
	 
}); 
 
</script>
 
		<table width="100%">
		      <tr>
		           <td></td>
			       <td>
						<div class="menureport">
							<ul>
								<li class="preview"><a title="Preview" href="#" onclick="preview();"></a></li>
								<li class="print"><a href="#" title="Print" onclick="doPrint();" ></a></li>
								<li class="excel"><a href="#"  title="Export"  onclick="exportExcel();"></a></li>
							</ul>
						</div>
			      </td>
			</tr>
		   </table>
		<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm; padding: 0.5cm;">
			
			<div id="divPrint">
				<style>
		   			tr.header-line{
		   				font-size: 16px;
					}
		   		</style>
				<table width="100%" style="font-size:12px;font-family:Tahoma,'Khmer OS Battambang';"> 
					<tr>
						<td>
						   <table width="100%" >
						   			<tr>
										<td width="28%" align="left">
											<img style="width:70%;" src="<?php echo $this->baseUrl().'/images/logo.jpg'?>"><br /><br >
										</td>
										<td align="center" width="44%"  >
											<strong style="font-weight:bold;color:#000; font-size: 18px;font-family:Tahoma,'Khmer MEF2';"><?php echo $tr->translate("CLIENT_PROFILE"); ?></strong><br />
										</td>
										<td width="28%" align="right">
										</td>
									</tr>
						   </table>
						   <?php $sex='';
									      if($this->client_list['sex']==1){
									      	$sex=$tr->translate("MALE");
										  }else{
										  	$sex=$tr->translate("FEMALE");
										  }
									?>
					      	<table  cellspacing="5"  style="background:#fff;margin: 0 auto;width: 100%;font-size:12px;font-family:Tahoma,'Khmer OS Battambang';" >
					      		<tr class="header-line">
					     	         <td colspan="6" style="border-bottom:1px solid #ccc;"><strong><?php echo $tr->translate("CLIENT_INFO");?></strong></td>
					     	    </tr>
					      		<tr  >
					      		    <td rowspan="3">
					      		    <?php $image = 'wedding_sister.jpg';
					      		      if(!empty($this->client_list['photo_name'])){$image = $this->client_list['photo_name'];}?>
										 <div style="width:160px; height:140px;padding:3px;"><img style="border:1px solid #ccc; width:120px;height:140px;" src="<?php echo $this->baseUrl();?>/images/<?php echo $image;?>" /></div>
					      		    </td>
					      		      <td style="width:80%; vertical-align: top;" colspan="4">
					      		      
					      		         <table width="100%" style="font-size:12px;font-family: 'Khmer OS Battambang';">
					      		               <tr>
					      		                   <td><?php echo $tr->translate("NAME_KH");?>:</td>
					      		                   <td><label><?php echo $this->client_list['name_kh'];?></label></td>
					      		                   <td><?php echo $tr->translate("NAME_EN");?>:</td>
					      		                   <td><label><?php echo $this->client_list['name_en'];?></label> </td>
					      		               </tr>
					      		               <tr>
					      		               	   <td><?php echo $tr->translate("NATIONALITY");?>:</td>
					      		                   <td><label><?php echo $this->client_list['nationality'];?></label></td>
					      		                   <td> <?php echo $tr->translate("SEX");?>:&nbsp;</td>
					      		                   <td><label><?php echo $sex?></label></td>
					      		               </tr>
					      		               <tr>
					      		                  <td><?php echo $tr->translate("DOCMENT_TYPE");?>:</td>
					      		                  <td><label><?php echo $this->client_list['doc_name'];?></label></td>
					      		                  <td><?php echo $tr->translate("NATIONAL_ID");?>:</td>
					      		                  <td><label><?php echo $this->client_list['nation_id'];?></label></td>
					      		               </tr>
					      		               <tr>
					      		               		<td> <?php echo $tr->translate("DOB");?>:&nbsp; </td>
					      		                  	<td><label><?php echo date("d-M-Y",strtotime($this->client_list['dob']));?></label></td>
					      		               		<td><?php echo $tr->translate("PHONE");?>:&nbsp;</td>
					      		                  	<td><label><?php echo $this->client_list['phone'];?></label></td>
					      		               </tr>
					      		               <tr>
					      		               		<td><?php echo $tr->translate("EMAIL");?>:&nbsp; </td>
					      		               		<td><label><?php echo $this->client_list['email'];?></label></td>
					      		               </tr>
					      		         </table>
									</td>
					      		</tr>
					      		<tr >  </tr>
					      		<tr> </tr>
					      		
					      	</table>
					     	<table width="100%" style="margin:0 auto;font-size:12px;font-family: 'Khmer OS Battambang';" cellspacing="5">
					      		<tr><td></td></tr>
					      		<tr class="header-line">
					      			<td colspan="6"​ style="border-bottom:1px solid #ddd;" class="b"><strong><?php echo $tr->translate("CURRENT_ADDRESS");?></strong></td>
					      		</tr>
					      		<tr>
					      			<td><?php echo $tr->translate("HOUSE");?>:</td>
									<td><label><?php echo $this->client_list['house'];?></label>  </td>
									<td><?php echo $tr->translate("STREET");?>:</td>
									<td><label><?php echo $this->client_list['street'];?></label> </td>
									<td><?php echo $tr->translate("VILLAGE");?>:</td>
									<td><label><?php echo $this->client_list['village_name'];?></label></td>
									
								</tr>
								<tr>								
									<td><?php echo $tr->translate("COMMUNE");?>:</td>
									<td><?php echo $this->client_list['commune_name'];?> </td>
									<td><?php echo $tr->translate("DISTRICT");?>:</td>
									<td><label><?php echo $this->client_list['district_name'];?></label> </td>
									<td><?php echo $tr->translate("PROVINCE");?>:</td>
									<td><label><?php echo $this->client_list['province_en_name'];?></label>
									</td>
								</tr>
					      		<tr class="header-line">
					      			<td colspan="6"​ style="border-bottom:1px solid #ccc;"><strong><?php echo $tr->translate("RELEVANT_STAKEHOLDER");?></strong></td>
					      		</tr>
					      		<?php $plot_sex='';
									      if($this->client_list['ksex']==1){
									      	$plot_sex=$tr->translate("MALE");
										  }else{
										  	$plot_sex=$tr->translate("FEMALE");
										  }
									?>
					      		<tr>
					      			<td><?php echo $tr->translate("NAME_KH");?>:</td>
									<td><label><?php echo $this->client_list['hname_kh'];?></label> </td>
									<td><?php echo $tr->translate("NAME_EN");?>:</td>
									<td><label><?php echo $this->client_list['bname_kh'];?></label> </td>
									<td><?php echo $tr->translate("SEX");?>:</td>
									<td><label><?php echo $plot_sex; ?></label></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("NATIONALITY");?>:</td>
									<td><label><?php echo $this->client_list['p_nationality'];?></label> </td>
									<td><?php echo $tr->translate("DOCMENT_TYPE");?>:</td>
									<td><label><?php echo $this->client_list['join_doc_name'];?></label> </td>
									<td><?php echo $tr->translate("NATIONAL_ID");?>:</td>
									<td><label><?php echo $this->client_list['rid_no'];?></label> </td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("PHONE");?>:</td>
									<td><label><?php echo $this->client_list['lphone'];?></label> </td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("SPOUSE_NAME");?>:</td>
									<td><label><?php echo $this->client_list['arid_no'];?></label> </td>
									<td><?php echo $tr->translate("NATIONAL_ID");?>:</td>
									<td><label><?php echo $this->client_list['refe_nation_id'];?></label> </td>
								</tr>
								<tr><td></td></tr>
					      		<tr class="header-line">
									<td colspan="6" style="border-bottom:1px solid #ccc;" class="b"><strong><?php echo $tr->translate("CURRENT_ADDRESS");?></strong></td>
								</tr>
					      		<tr>
					      			<td><?php echo $tr->translate("HOUSE");?>:</td>
									<td><label><?php echo $this->client_list['ghouse'];?></label>  </td>
									<td><?php echo $tr->translate("STREET");?>:</td>
									<td><label><?php echo $this->client_list['dstreet'];?></label> </td>
									<td><?php echo $tr->translate("VILLAGE");?>:</td>
									<td><label><?php echo $this->client_list['p_village_name'];?></label></td>
									
								</tr>
								<tr>								
									<td><?php echo $tr->translate("COMMUNE");?>:</td>
									<td><?php echo $this->client_list['p_commune_name'];?> </td>
									<td><?php echo $tr->translate("DISTRICT");?>:</td>
									<td><label><?php echo $this->client_list['p_district_name'];?></label> </td>
									<td><?php echo $tr->translate("PROVINCE");?>:</td>
									<td><label><?php echo $this->client_list['p_province_en_name'];?></label></td>
								</tr>
							</table>
		 
					   </td>
					</tr>
					<tr>
						<td align="center">
							<table width="100%">
								<tr>
									<td colspan="3">&nbsp;</td>
								</tr>
								
								<tr >
									<td align="center" width="25%">
										<strong style="font-weight:bold;color:#000; font-size: 12px;font-family:Tahoma,'Khmer MEF2';"><?php echo $tr->translate("VERIFIED_BY"); ?></strong>
									</td>
									<td  width="50%">
										&nbsp;
									</td>
									<td align="center"  width="25%">
										<strong style="font-weight:bold;color:#000; font-size: 12px;font-family:Tahoma,'Khmer MEF2';text-align:right;"><?php echo $tr->translate("PREPARED_BY"); ?></strong>
									</td>
								</tr>
							</table>
							
					   	</td>
					  </tr>
	   </table>
	   </div>
	 </div>
<script type="text/javascript">
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    hideDialog();
}
function preview()
{ 
  var disp_setting="toolbar=no,status=no,resizable=no,location=no,directories=yes,menubar=no,"; 
      disp_setting+="scrollbars=no,width=1200, height=700, left=100, top=25"; 
  var content_vlue = document.getElementById("divPrint").innerHTML; 
  
  var docprint=window.open("","",disp_setting); 
   docprint.document.open(); 
   docprint.document.write('<html><head>'); 
   docprint.document.write('</head><div style=" font-size:16px !important; margin:0px; font-family:Verdana;"><style>table th {font-size:14px !important;} table td{font-size:12px !important;}</style><center>');          
   docprint.document.write(content_vlue);          
   docprint.document.write('</center></div></html>'); 
   docprint.document.close(); 
   docprint.focus(); 
}
function exportExcel(){
	$('#exportExcel').tableExport({type:'excel',escape:'false'});
}
</script>

